### ISSUE TITLE
circleci build => Error: Too long with no output (exceeded 10m0s)

### ISSUE THREAD

**Issue by nick-youngblut** [bioconda/bioconda-recipes#10017]
Running `circleci build` keeps generating the following error:

```
[...]
Attempting to finalize metadata for r-cooccur
Solving environment: ...working... done
Traceback (most recent call last):
  File "/opt/conda/bin/bioconda-utils", line 11, in <module>
    load_entry_point('bioconda-utils==0+untagged.1.g9aa0ef2', 'console_scripts', 'bioconda-utils')()
  File "/opt/conda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 638, in main
    bioconductor_skeleton, pypi_check, clean_cran_skeleton,
  File "/opt/conda/lib/python3.6/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/opt/conda/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/opt/conda/lib/python3.6/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/opt/conda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 413, in build
    lint_args=lint_args,
  File "/opt/conda/lib/python3.6/site-packages/bioconda_utils/build.py", line 407, in build_recipes
    force=force)
  File "/opt/conda/lib/python3.6/site-packages/bioconda_utils/utils.py", line 889, in get_package_paths
    platform, metas = _load_platform_metas(recipe, finalize=True)
  File "/opt/conda/lib/python3.6/site-packages/bioconda_utils/utils.py", line 812, in _load_platform_metas
    return platform, load_all_meta(recipe, config=config, finalize=finalize)
  File "/opt/conda/lib/python3.6/site-packages/bioconda_utils/utils.py", line 172, in load_all_meta
    bypass_env_check=bypass_env_check,
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 51, in render
    bypass_env_check=bypass_env_check):
  File "/opt/conda/lib/python3.6/site-packages/conda_build/metadata.py", line 1970, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/metadata.py", line 699, in finalize_outputs_pass
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/render.py", line 456, in finalize_metadata
    exclude_pattern)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/render.py", line 351, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/render.py", line 324, in _read_upstream_pin_files
    extra_run_specs = get_upstream_pins(m, actions, env)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/render.py", line 306, in get_upstream_pins
    package_subset=linked_packages)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/render.py", line 285, in execute_download_actions
    pfe.execute()
  File "/opt/conda/lib/python3.6/site-packages/conda/core/package_cache_data.py", line 602, in execute
    exceptions.append(exc)
  File "/opt/conda/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/opt/conda/lib/python3.6/site-packages/conda/common/signals.py", line 57, in signal_handler
    signal.signal(sig, previous_handler)
  File "/opt/conda/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
  File "/opt/conda/lib/python3.6/site-packages/conda/__init__.py", line 110, in conda_signal_handler
    raise CondaSignalInterrupt(signum)
conda.exceptions.CondaSignalInterrupt: Signal interrupt SIGTERM
Error: Too long with no output (exceeded 10m0s)
Step timedout
Task failed
```

This seems to happen regardless of the r-package recipe that I'm trying to run `circleci build` on. Any ideas?

```
$ circleci version

circleci version: 0.0.5894-01cdb92
Build Agent version: 0.0.5895-01cdb92
built: 2018-05-29T20:07:10+0000
```

**Comment by dpryan79** [comment]
I assume this can be closed now that you have it in conda-forge.
