### ISSUE TITLE
OSError: [Errno 40] Too many levels of symbolic links

### ISSUE THREAD

**Issue by holmrenser** [bioconda/bioconda-recipes#10095]
I am trying to add a recipe for GeneNoteBook in #10089, but circleci is failing with the following error:

```
Packaging genenotebook
INFO:conda_build.build:Packaging genenotebook
Packaging genenotebook-0.1.0-0
INFO:conda_build.build:Packaging genenotebook-0.1.0-0
number of files: 1
Making absolute symlink bin/genenotebook -> genenotebook relative
Fixing permissions
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 2177, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1571, in build
    built_package = bundlers[output_d.get('type', 'conda')](output_d, m, env, stats)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 950, in bundle_conda
    output['checksums'] = create_info_files(metadata, files, prefix=metadata.config.host_prefix)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 646, in create_info_files
    checksums = create_info_files_json_v1(m, m.config.info_dir, prefix, files, files_with_prefix)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 751, in create_info_files_json_v1
    files_json_files = build_info_files_json_v1(m, prefix, files, files_with_prefix)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 731, in build_info_files_json_v1
    "size_in_bytes": os.path.getsize(path),
  File "/opt/conda/lib/python3.6/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
OSError: [Errno 40] Too many levels of symbolic links: '/opt/conda/conda-bld/genenotebook_1532604121131/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/genenotebook'


11:22:30 BIOCONDA ERROR BUILD FAILED recipes/genenotebook
11:22:31 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
11:22:31 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/genenotebook
Exited with code 1
```

My ```build.sh``` is as follows:

```sh
#!/bin/bash

mkdir -p $PREFIX/bin
ln -s genenotebook ${PREFIX}/bin
```

I see other recipes using a symlink for the main executable as well, so I don't understand why this is failing.

**Comment by dpryan79** [comment]
You can create a link from somewhere under `$PREFIX`, but doing so from the source code directory, which is probably in a symlinked directory anyway, won't work.
