### ISSUE TITLE
bootstrap.py FileNotFoundError: [Errno 2] No such file or directory: 'sorted-r-blacklist'

### ISSUE THREAD

**Issue by holmrenser** [bioconda/bioconda-recipes#10108]
When trying to run bootstrap.py for local testing I get the following error:
```
Traceback (most recent call last):
  File "/tmp/miniconda/miniconda/bin/bioconda-utils", line 11, in <module>
    sys.exit(main())
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 638, in main
    bioconductor_skeleton, pypi_check, clean_cran_skeleton,
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 350, in build
    modified = utils.modified_recipes(git_range, recipe_folder, config)
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/utils.py", line 1077, in modified_recipes
    unblacklisted = newly_unblacklisted(config_file, recipe_folder, orig_git_range)
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/utils.py", line 779, in newly_unblacklisted
    recipe_folder)
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/utils.py", line 946, in get_blacklist
    for i in open(p, encoding='utf8')
FileNotFoundError: [Errno 2] No such file or directory: 'sorted-r-blacklist'
```

I guess this makes sense since currently there is no such file on master?

**Comment by holmrenser** [comment]
Upon adding a sorted-r-blacklist from a previous version of master, ```boost-1.61-migration-blacklist``` and ```perl-unable-to-find-blacklist``` are also missing.

**Comment by holmrenser** [comment]
That seems to have solved it!
