### ISSUE TITLE
Can't build a R package recipe

### ISSUE THREAD

**Issue by apcamargo** [bioconda/bioconda-recipes#10147]
While trying to add a zinbwave recipe into Bioconda ([here's the PR](https://github.com/bioconda/bioconda-recipes/pull/10142)) I've faced a bug during the building of another recipe (r-softimpute) that I wrote in the same PR:

```
01:45:50 BIOCONDA INFO Generating DAG
01:45:50 BIOCONDA INFO Inspected 0 of 2 recipes
01:45:50 BIOCONDA INFO Building and testing 2 recipes in total
01:45:50 BIOCONDA INFO Recipes to build: 
bioconductor-zinbwave
r-softimpute
01:45:50 BIOCONDA INFO Building and testing subdag 1 of 1 (2 recipes)
01:45:52 BIOCONDA INFO Determining expected packages
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
Adding in variants from internal_defaults
Adding in variants from /opt/conda/conda_build_config.yaml
Adding in variants from /opt/conda/lib/python3.6/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
Attempting to finalize metadata for r-softimpute
Solving environment: ...working... done
Solving environment: ...working... done
Solving environment: ...working... done
01:47:01 BIOCONDA INFO Linting recipe
01:47:02 BIOCONDA INFO BUILD START recipes/r-softimpute
..01:49:20 BIOCONDA ERROR COMMAND FAILED: /opt/conda/bin/conda build --no-anaconda-upload --channel bioconda --channel conda-forge --channel defaults -e /opt/conda/conda_build_config.yaml -m /opt/conda/lib/python3.6/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml recipes/r-softimpute/meta.yaml
01:49:20 BIOCONDA ERROR STDOUT+STDERR:
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /opt/conda/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /opt/conda/conda_build_config.yaml
Adding in variants from /opt/conda/lib/python3.6/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /opt/conda/lib/python3.6/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
Attempting to finalize metadata for r-softimpute
INFO:conda_build.metadata:Attempting to finalize metadata for r-softimpute
Solving environment: ...working... done
Solving environment: ...working... done
Solving environment: ...working... done
BUILD START: ['r-softimpute-1.4-r341ha44fe06_0.tar.bz2']
Solving environment: ...working... done

## Package Plan ##

  environment location: /opt/conda/conda-bld/r-softimpute_1533001623036/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_


The following NEW packages will be INSTALLED:

    blas:             1.1-openblas          conda-forge
    bzip2:            1.0.6-h470a237_2      conda-forge
    ca-certificates:  2018.4.16-0           conda-forge
    cairo:            1.14.12-he56eebe_3    conda-forge
    curl:             7.61.0-h93b3f91_1     conda-forge
    fontconfig:       2.13.0-h0c61d53_4     conda-forge
    freetype:         2.8.1-hfa320df_1      conda-forge
    gettext:          0.19.8.1-0            conda-forge
    glib:             2.55.0-h464dc38_2     conda-forge
    graphite2:        1.3.11-hfc679d8_0     conda-forge
    gsl:              2.2.1-blas_openblas_4 conda-forge [blas_openblas]
    harfbuzz:         1.8.4-h2bb21d5_0      conda-forge
    icu:              58.2-hfc679d8_0       conda-forge
    jpeg:             9c-h470a237_0         conda-forge
    krb5:             1.14.6-0              conda-forge
    libffi:           3.2.1-3               conda-forge
    libgcc:           7.2.0-h69d50b8_2      defaults   
    libgcc-ng:        7.2.0-hdf63c60_3      defaults   
    libgfortran:      3.0.0-1               defaults   
    libiconv:         1.15-h470a237_1       conda-forge
    libpng:           1.6.35-ha92aebf_0     conda-forge
    libssh2:          1.8.0-h5b517e9_2      conda-forge
    libstdcxx-ng:     7.2.0-hdf63c60_3      defaults   
    libtiff:          4.0.9-he6b73bb_1      conda-forge
    libuuid:          1.0.3-1               conda-forge
    libxcb:           1.13-h470a237_2       conda-forge
    libxml2:          2.9.8-h422b904_2      conda-forge
    ncurses:          6.1-hfc679d8_1        conda-forge
    openblas:         0.2.20-8              conda-forge
    openssl:          1.0.2o-h470a237_1     conda-forge
    pango:            1.40.14-h9105a7a_2    conda-forge
    pcre:             8.41-h470a237_2       conda-forge
    pixman:           0.34.0-2              conda-forge
    pthread-stubs:    0.4-h470a237_1        conda-forge
    r-base:           3.4.1-h4fe35fd_8      conda-forge
    r-lattice:        0.20_34-r3.4.1_0      conda-forge
    r-matrix:         1.2_14-r3.4.1_0       conda-forge
    readline:         7.0-haf1bffa_1        conda-forge
    tk:               8.6.8-0               conda-forge
    xorg-kbproto:     1.0.7-h470a237_2      conda-forge
    xorg-libice:      1.0.9-h470a237_4      conda-forge
    xorg-libsm:       1.2.2-h470a237_5      conda-forge
    xorg-libx11:      1.6.5-h470a237_2      conda-forge
    xorg-libxau:      1.0.8-h470a237_6      conda-forge
    xorg-libxdmcp:    1.1.2-h470a237_7      conda-forge
    xorg-libxext:     1.3.3-h470a237_4      conda-forge
    xorg-libxrender:  0.9.10-h470a237_2     conda-forge
    xorg-libxt:       1.1.5-h470a237_2      conda-forge
    xorg-renderproto: 0.11.1-h470a237_2     conda-forge
    xorg-xextproto:   7.3.0-h470a237_2      conda-forge
    xorg-xproto:      7.0.31-h470a237_7     conda-forge
    xz:               5.2.4-h470a237_0      conda-forge
    zlib:             1.2.11-h470a237_3     conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Solving environment: ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /opt/conda/conda-bld/r-softimpute_1533001623036/_build_env


The following NEW packages will be INSTALLED:

    toolchain:               2.1.6-0 conda-forge
    toolchain_c_linux-64:    2.1.6-0 conda-forge
    toolchain_fort_linux-64: 2.1.6-0 conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Source cache directory is: /opt/conda/conda-bld/src_cache
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 2177, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1350, in build
    try_download(m, no_download_source=False, raise_error=True)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/render.py", line 549, in try_download
    source.provide(metadata)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/source.py", line 623, in provide
    timeout=metadata.config.timeout, locking=metadata.config.locking)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/source.py", line 133, in unpack
    src_path, unhashed_fn = download_to_cache(cache_folder, recipe_path, source_dict)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/source.py", line 45, in download_to_cache
    unhashed_fn = fn = source_dict['fn'] if 'fn' in source_dict else basename(source_dict['url'])
  File "/opt/conda/lib/python3.6/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not list


01:49:20 BIOCONDA ERROR BUILD FAILED recipes/r-softimpute
01:49:21 BIOCONDA INFO BUILD SKIP: skipping recipes/bioconductor-zinbwave because it depends on ['recipes/r-softimpute'] which had a failed build.
01:49:21 BIOCONDA ERROR BUILD SUMMARY: of 2 recipes, 1 failed and 1 were skipped. Details of recipes and environments follow.
01:49:21 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/r-softimpute
01:49:21 BIOCONDA ERROR BUILD SUMMARY: SKIPPED recipe bioconductor-zinbwave due to failed dependencies ['recipes/r-softimpute']
Error: Exited with code 1
Step failed
Task failed
```

I couln't find out how to resolve this. I've tryed both the CircleCI and the Bootstrap methods.

**Comment by rvalieris** [comment]
fixed by https://github.com/bioconda/bioconda-utils/pull/324
