### ISSUE TITLE
quast: "distribution was not found"

### ISSUE THREAD

**Issue by nick-youngblut** [bioconda/bioconda-recipes#10201]
@alexeigurevich & @mbargull it appears that quast 4.6.3 is installing as a py2 build ("py27pl526h3727419_2") into a py3 environment. This results in the error:

```
$ quast.py -h
Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/llmga/.snakemake/conda/ebda739f/bin/metaquast.py", line 4, in <module>
    __import__('pkg_resources').run_script('quast==4.6.3', 'metaquast.py')
  File "/ebio/abt3_projects/software/dev/llmga/.snakemake/conda/ebda739f/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/ebio/abt3_projects/software/dev/llmga/.snakemake/conda/ebda739f/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/ebio/abt3_projects/software/dev/llmga/.snakemake/conda/ebda739f/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/ebio/abt3_projects/software/dev/llmga/.snakemake/conda/ebda739f/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/ebio/abt3_projects/software/dev/llmga/.snakemake/conda/ebda739f/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/ebio/abt3_projects/software/dev/llmga/.snakemake/conda/ebda739f/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'quast==4.6.3' distribution was not found and is required by the application
```

Running `conda install python=2.7` fixes the error. 

My conda environment:

```
# Name                    Version                   Build  Channel
blast                     2.5.0                h3727419_3    bioconda
boost                     1.66.0                   py36_1    conda-forge
boost-cpp                 1.66.0                        1    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
expat                     2.2.5                hfc679d8_1    conda-forge
fontconfig                2.12.6                        0    conda-forge
freetype                  2.8.1                         0    conda-forge
gettext                   0.19.8.1                      0    conda-forge
glib                      2.55.0                        0    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         1    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
intel-openmp              2018.0.3                      0
joblib                    0.12                       py_0    conda-forge
jpeg                      9c                   h470a237_0    conda-forge
kiwisolver                1.0.1                    py36_1    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc                    7.2.0                h69d50b8_2
libgcc-ng                 7.2.0                hdf63c60_3
libgfortran-ng            7.2.0                hdf63c60_3
libiconv                  1.15                 h470a237_1    conda-forge
libpng                    1.6.34               ha92aebf_1    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3
libxcb                    1.13                 h470a237_0    conda-forge
libxml2                   2.9.8                h422b904_1    conda-forge
matplotlib                2.2.2                    py36_1    conda-forge
mkl                       2018.0.3                      1
mkl_fft                   1.0.2                    py36_0    conda-forge
mkl_random                1.0.1                    py36_0    conda-forge
ncurses                   5.9                          10    conda-forge
numpy                     1.14.2           py36hdbf6ddf_1
openjdk                   8.0.121                       1
openssl                   1.0.2o                        0    conda-forge
pcre                      8.41                          1    conda-forge
perl                      5.26.2               h470a237_0    conda-forge
pip                       9.0.3                    py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyqt                      5.6.0                    py36_5    conda-forge
python                    3.6.5                         1    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.5                     py_0    conda-forge
qt                        5.6.2                         7    conda-forge
quast                     4.6.3           py27pl526h3727419_2    bioconda
readline                  7.0                           0    conda-forge
setuptools                39.2.0                   py36_0    conda-forge
simplejson                3.8.1                    py36_0    bioconda
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
sqlite                    3.20.1                        2    conda-forge
tk                        8.6.7                         0    conda-forge
tornado                   5.0.2                    py36_0    conda-forge
wheel                     0.31.0                   py36_0    conda-forge
xorg-libxau               1.0.8                h470a237_4    conda-forge
xorg-libxdmcp             1.1.2                h470a237_4    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

**Comment by nick-youngblut** [comment]
This problem doesn't occur with `quast=5.0.0`, so I consider this issue closed.

**Comment by vpuller** [comment]
The problem does occur with quast=5.0.0, which for some reason looks for quast==4.6.3

Traceback (most recent call last):
  File "/home/vadim/anaconda3/bin/quast.py", line 4, in <module>
    __import__('pkg_resources').run_script('quast==4.6.3', 'quast.py')
  File "/home/vadim/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3086, in <module>
    @_call_aside
  File "/home/vadim/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/home/vadim/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3099, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/vadim/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/home/vadim/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/vadim/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'quast==4.6.3' distribution was not found and is required by the application
