### ISSUE TITLE
Error installing transabyss

### ISSUE THREAD

**Issue by readmanchiu** [bioconda/bioconda-recipes#10299]
Hi,

I tried to install `transabyss` and got the following error:
```
(ta) [rchiu@rchiu04 Desktop]$ conda install transabyss
Fetching package metadata ......
WARNING: The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/bionconda

It is possible you have given conda an invalid channel. Please double-check
your conda configuration using `conda config --show`.

If the requested url is in fact a valid conda channel, please request that the
channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json
.............
Solving package specifications: .

Package plan for installation in environment /home/rchiu/anaconda2/envs/ta:

The following NEW packages will be INSTALLED:

    abyss:           1.5.2-boost1.61_2      bioconda   
    blat:            36-0                   bioconda   
    bowtie2:         2.3.4.1-py27pl5.22.0_0 bioconda   
    ca-certificates: 2018.4.16-0            conda-forge
    certifi:         2018.4.16-py27_0       conda-forge
    curl:            7.60.0-0               conda-forge
    gmp:             6.1.2-0                conda-forge
    icu:             58.2-0                 conda-forge
    igraph:          0.7.1-4                conda-forge
    krb5:            1.14.6-0               conda-forge
    libiconv:        1.14-4                 conda-forge
    libpng:          1.6.34-0               conda-forge
    libssh2:         1.8.0-2                conda-forge
    libxml2:         2.9.5-1                conda-forge
    make:            4.2.1-0                conda-forge
    ncurses:         5.9-10                 conda-forge
    openssl:         1.0.2o-0               conda-forge
    pip:             18.0-py27_1            conda-forge
    python:          2.7.15-0               conda-forge
    python-igraph:   0.7.1.post6-py27_2     conda-forge
    readline:        7.0-0                  conda-forge
    samtools:        1.3.1-5                bioconda   
    setuptools:      40.0.0-py27_1          conda-forge
    sqlite:          3.20.1-2               conda-forge
    tbb:             2018_20171205-0        conda-forge
    tk:              8.6.8-0                conda-forge
    transabyss:      1.5.5-py27_3           bioconda   
    wheel:           0.31.1-py27_1          conda-forge
    xz:              5.2.3-0                conda-forge

Proceed ([y]/n)? y

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : 1.21.3
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /home/rchiu/anaconda2  (writable)
    default environment : /home/rchiu/anaconda2/envs/ta
       envs directories : /home/rchiu/anaconda2/envs
                          /home/rchiu/.conda/envs
          package cache : /home/rchiu/anaconda2/pkgs
                          /home/rchiu/.conda/pkgs
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/bionconda/linux-64
                          https://conda.anaconda.org/bionconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/dranew/linux-64
                          https://conda.anaconda.org/dranew/noarch
            config file : /home/rchiu/.condarc
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/2.7.12 Linux/3.10.0-693.5.2.el7.x86_64 CentOS Linux/7.4.1708 glibc/2.17
                UID:GID : 528:577



`$ /home/rchiu/anaconda2/envs/ta/bin/conda install transabyss`




    Traceback (most recent call last):
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 825, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/core/link.py", line 123, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/core/link.py", line 123, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 88, in read_package_info
        paths_data = read_paths_json(extracted_package_directory)
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 150, in read_paths_json
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 581, in box
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 581, in <genexpr>
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 150, in <genexpr>
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    ValidationError: Value for sha256 cannot be None.
```
Thanks

**Comment by corburn** [comment]
```
WARNING: The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/bionconda
```

bionconda => bioconda

**Comment by readmanchiu** [comment]
I got rid of the wrongly spelled channel name from my `.condarc` file, but still got the error:
```
(ta) [rchiu@rchiu04 Spanki-master]$ conda install transabyss=1.5.4
Fetching package metadata .................
Solving package specifications: .
Warning: >10 possible package resolutions (only showing differing packages):
  - conda-forge::gmp-6.1.2-0, conda-forge::icu-58.2-0, conda-forge::libssh2-1.8.0-2, conda-forge::make-4.2.1-0
  - conda-forge::gmp-6.1.2-0, conda-forge::icu-58.2-0, conda-forge::libssh2-1.8.0-2, conda-forge::make-4.2.1-h470a237_0
  - conda-forge::gmp-6.1.2-0, conda-forge::icu-58.2-hfc679d8_0, conda-forge::libssh2-1.8.0-2, conda-forge::make-4.2.1-0
  - conda-forge::gmp-6.1.2-0, conda-forge::icu-58.2-hfc679d8_0, conda-forge::libssh2-1.8.0-2, conda-forge::make-4.2.1-h470a237_0
  - conda-forge::gmp-6.1.2-hfc679d8_0, conda-forge::icu-58.2-hfc679d8_0, conda-forge::libssh2-1.8.0-2, conda-forge::make-4.2.1-0
  - conda-forge::gmp-6.1.2-hfc679d8_0, conda-forge::icu-58.2-hfc679d8_0, conda-forge::libssh2-1.8.0-2, conda-forge::make-4.2.1-h470a237_0
  - conda-forge::gmp-6.1.2-hfc679d8_0, conda-forge::icu-58.2-0, conda-forge::libssh2-1.8.0-2, conda-forge::make-4.2.1-0
  - conda-forge::gmp-6.1.2-hfc679d8_0, conda-forge::icu-58.2-0, conda-forge::libssh2-1.8.0-2, conda-forge::make-4.2.1-h470a237_0
  - conda-forge::gmp-6.1.2-hfc679d8_0, conda-forge::icu-58.2-0, conda-forge::libssh2-1.8.0-h5b517e9_2, conda-forge::make-4.2.1-0
  - conda-forge::gmp-6.1.2-0, conda-forge::icu-58.2-0, conda-forge::libssh2-1.8.0-h5b517e9_2, conda-forge::make-4.2.1-0
  ... and others

Package plan for installation in environment /home/rchiu/anaconda2/envs/ta:

The following NEW packages will be INSTALLED:

    abyss:            1.5.2-boost1.61_5          bioconda   
    blat:             36-0                       bioconda   
    bowtie2:          2.3.4.2-py27h2d50403_0     bioconda   
    ca-certificates:  2018.4.16-0                conda-forge
    cairo:            1.14.12-he6fea26_5         conda-forge
    certifi:          2018.8.13-py27_0           conda-forge
    curl:             7.61.0-h93b3f91_1          conda-forge
    fontconfig:       2.13.0-h65d0f4c_5          conda-forge
    freetype:         2.9.1-h6debe1e_0           conda-forge
    gettext:          0.19.8.1-0                 conda-forge
    glib:             2.55.0-h464dc38_2          conda-forge
    gmp:              6.1.2-0                    conda-forge
    icu:              58.2-0                     conda-forge
    igraph:           0.7.1-hcc8e21d_5           conda-forge
    krb5:             1.14.6-0                   conda-forge
    libffi:           3.2.1-hfc679d8_4           conda-forge
    libgfortran:      3.0.0-1                    conda-forge
    libgfortran-ng:   7.2.0-hdf63c60_3           conda-forge
    libiconv:         1.15-h470a237_2            conda-forge
    libpng:           1.6.35-ha92aebf_0          conda-forge
    libssh2:          1.8.0-2                    conda-forge
    libstdcxx-ng:     7.2.0-hdf63c60_3           conda-forge
    libuuid:          2.32.1-h470a237_0          conda-forge
    libxcb:           1.13-h470a237_2            conda-forge
    libxml2:          2.9.8-h422b904_3           conda-forge
    make:             4.2.1-0                    conda-forge
    mpi:              1.0-openmpi                conda-forge
    ncurses:          6.1-hfc679d8_1             conda-forge
    openmpi:          3.1.0-h26a2512_3           conda-forge
    openssl:          1.0.2o-h470a237_1          conda-forge
    pcre:             8.41-h470a237_2            conda-forge
    pip:              18.0-py27_1                conda-forge
    pixman:           0.34.0-2                   conda-forge
    pthread-stubs:    0.4-h470a237_1             conda-forge
    pycairo:          1.17.1-py27h4d1f301_0      conda-forge
    python:           2.7.15-h9fef7bc_0          conda-forge
    python-igraph:    0.7.1.post6-py27h470a237_5 conda-forge
    readline:         7.0-haf1bffa_1             conda-forge
    samtools:         1.3.1-5                    bioconda   
    setuptools:       40.0.0-py27_1              conda-forge
    sqlite:           3.24.0-h2f33b56_0          conda-forge
    tk:               8.6.8-0                    conda-forge
    transabyss:       1.5.4-py27_1               bioconda   
    wheel:            0.31.1-py27_1              conda-forge
    xorg-kbproto:     1.0.7-h470a237_2           conda-forge
    xorg-libice:      1.0.9-h470a237_4           conda-forge
    xorg-libsm:       1.2.2-h8c8a85c_6           conda-forge
    xorg-libx11:      1.6.5-h470a237_2           conda-forge
    xorg-libxau:      1.0.8-h470a237_6           conda-forge
    xorg-libxdmcp:    1.1.2-h470a237_7           conda-forge
    xorg-libxext:     1.3.3-h470a237_4           conda-forge
    xorg-libxrender:  0.9.10-h470a237_2          conda-forge
    xorg-renderproto: 0.11.1-h470a237_2          conda-forge
    xorg-xextproto:   7.3.0-h470a237_2           conda-forge
    xorg-xproto:      7.0.31-h470a237_7          conda-forge
    xz:               5.2.4-h470a237_1           conda-forge

Proceed ([y]/n)? y

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : 1.21.3
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /home/rchiu/anaconda2  (writable)
    default environment : /home/rchiu/anaconda2/envs/ta
       envs directories : /home/rchiu/anaconda2/envs
                          /home/rchiu/.conda/envs
          package cache : /home/rchiu/anaconda2/pkgs
                          /home/rchiu/.conda/pkgs
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/dranew/linux-64
                          https://conda.anaconda.org/dranew/noarch
            config file : /home/rchiu/.condarc
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/2.7.12 Linux/3.10.0-693.5.2.el7.x86_64 CentOS Linux/7.4.1708 glibc/2.17
                UID:GID : 528:577



`$ /home/rchiu/anaconda2/envs/ta/bin/conda install transabyss=1.5.4`




    Traceback (most recent call last):
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 825, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/core/link.py", line 123, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/core/link.py", line 123, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 88, in read_package_info
        paths_data = read_paths_json(extracted_package_directory)
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 150, in read_paths_json
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 581, in box
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 581, in <genexpr>
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 150, in <genexpr>
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/rchiu/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    ValidationError: Value for sha256 cannot be None.
```
