### ISSUE TITLE
Circleci linting fails

### ISSUE THREAD

**Issue by abretaud** [bioconda/bioconda-recipes#10954]
Maybe someone is already working on it, but it looks like all recent lint jobs have failed with this error:

```
Successfully installed bioconda-utils-0.14.4
The update_index function has changed to index all subdirs at once.  You're pointing it at a single subdir.  Please update your code to point it at the channel root, rather than a subdir.
WARNING:conda_build.index:The update_index function has changed to index all subdirs at once.  You're pointing it at a single subdir.  Please update your code to point it at the channel root, rather than a subdir.
Traceback (most recent call last):
  File "/home/circleci/project/miniconda/bin/conda-index", line 11, in <module>
    sys.exit(main())
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/conda_build/cli/main_index.py", line 71, in main
    return execute(sys.argv[1:])
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/conda_build/cli/main_index.py", line 67, in execute
    verbose=args.verbose, progress=args.progress)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/conda_build/api.py", line 388, in update_index
    patch_generator=patch_generator, threads=threads, verbose=verbose, progress=progress)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/conda_build/index.py", line 268, in update_index
    return update_index(base_path, check_md5=check_md5, channel_name=channel_name, threads=threads, verbose=verbose)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/conda_build/index.py", line 270, in update_index
    patch_generator=patch_generator, verbose=verbose, progress=progress)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/conda_build/index.py", line 744, in index
    detected_subdirs = set(subdir for subdir in os.listdir(self.channel_root)
FileNotFoundError: [Errno 2] No such file or directory: '/home/circleci/project/miniconda/conda-bld'
Exited with code 1
```

**Comment by PauAndrio** [comment]
Same problem here:
`Successfully installed bioconda-utils-0.14.4
The update_index function has changed to index all subdirs at once.  You're pointing it at a single subdir.  Please update your code to point it at the channel root, rather than a subdir.
WARNING:conda_build.index:The update_index function has changed to index all subdirs at once.  You're pointing it at a single subdir.  Please update your code to point it at the channel root, rather than a subdir.
Traceback (most recent call last):
  File "/home/circleci/project/miniconda/bin/conda-index", line 11, in <module>
    sys.exit(main())
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/conda_build/cli/main_index.py", line 71, in main
    return execute(sys.argv[1:])
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/conda_build/cli/main_index.py", line 67, in execute
    verbose=args.verbose, progress=args.progress)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/conda_build/api.py", line 388, in update_index
    patch_generator=patch_generator, threads=threads, verbose=verbose, progress=progress)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/conda_build/index.py", line 268, in update_index
    return update_index(base_path, check_md5=check_md5, channel_name=channel_name, threads=threads, verbose=verbose)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/conda_build/index.py", line 270, in update_index
    patch_generator=patch_generator, verbose=verbose, progress=progress)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/conda_build/index.py", line 744, in index
    detected_subdirs = set(subdir for subdir in os.listdir(self.channel_root)
FileNotFoundError: [Errno 2] No such file or directory: '/home/circleci/project/miniconda/conda-bld'
Exited with code 1`

**Comment by abretaud** [comment]
Looks like it's fixed with #10957?

**Comment by mbargull** [comment]
Yes, @abretaud is right. Please merge `master` into your branches. I'm a in between doing other stuff and thus didn't yet write up on this and look into which PRs/issues are affected.

**Comment by jerowe** [comment]
I just ran into this issue. You are all awesome.
