### ISSUE TITLE
Fail to run DeepVaraint 0.6.1 of Bioconda on Centos7

### ISSUE THREAD

**Issue by ssm0808** [bioconda/bioconda-recipes#11150]
Hi, I want to install and run DeepVaraint 0.6.1 recipes of bioconda channel on Centos7. It's succeeful to conda install deepvariant on Centos7. There are not error have raised when deepvairnat install through conda of miniconda. But I wrote a script to run deepvariant recipe of bioconda. I can't run it succeefully. Is it availabel to run deepvariant recipe on Centos7?
run deepvaraint script (just run dv_make_examples.py):
```
OUTPUT_DIR="/home/simon/deepvariant_test/quickstart_test/quickstart-testdata/output-bioconda"
#EXAMPLES="${OUTPUT_DIR}/${prefix}.examples.tfrecord@${N_SHARDS}.gz"
CALL_VARIANTS_OUTPUT="${OUTPUT_DIR}/${prefix}.cvo.tfrecord.gz"
OUTPUT_VCF="${OUTPUT_DIR}/${prefix}.model.ckpt.output.vcf.gz"
LOG_DIR="${OUTPUT_DIR}/logs"
mkdir -p "${OUTPUT_DIR}"
mkdir -p "${LOG_DIR}"
echo 'Run make_examples'
( time python /home/simon/miniconda2/envs/testdeepvariant/bin/dv_make_examples.py \
       --cores=2 \
       --sample="NA12878" \
       --ref=/home/simon/deepvariant_test/quickstart_test/quickstart-testdata/ucsc.hg19.chr20.unittest.fasta \
       --reads=/home/simon/deepvariant_test/quickstart_test/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam \
       --regions="chr20:10,000,000-10,010,000" \
       --logdir="${LOG_DIR}" \
       --examples="${OUTPUT_DIR}"
) >"${LOG_DIR}/make_examples.log" 2>&1
```

It throws an error:
```
TypeError: __new__() got an unexpected keyword argument 'serialized_options'
```
Is the version of protocol incompatible with tensorflow? When I enter $ protoc --version, it throws libprotoc 3.6.0 on the terminal.
Thank you.

**Comment by chapmanb** [comment]
Thanks for this report and sorry about the issues. DeepVariant is locked to particular versions of tensorflow and protobuf. I updated the deepvariant bioconda package to 0.7.0 which needs tensorflow 1.9 and protobuf 3.4, both of which are pinned in the run dependencies. Would updating to that version in a clean conda environment work for your needs? Hope this gets it working for you.

**Comment by ssm0808** [comment]
Thank you for your work. I know you have updated the deepvariant bioconda package to 0.7.0 version. And I have installed the 0.7.0 version of the deepvariant bioconda package on the clean conda environment of Ubuntu 16.04. It can run normally. But I installed the 0.7.0 version of the deepvariant bioconda package with the same way on CentOS 7. There is an error: 
```
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_27Vmk5/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 41, in <module>
    from deepvariant import pileup_image
  File "/tmp/Bazel.runfiles_27Vmk5/runfiles/com_google_deepvariant/deepvariant/pileup_image.py", line 42, in <module>
    from third_party.nucleus.util import ranges
  File "/tmp/Bazel.runfiles_27Vmk5/runfiles/com_google_deepvariant/third_party/nucleus/util/ranges.py", line 42, in <module>
    from third_party.nucleus.io import bed
  File "/tmp/Bazel.runfiles_27Vmk5/runfiles/com_google_deepvariant/third_party/nucleus/io/bed.py", line 79, in <module>
    from third_party.nucleus.io.python import bed_reader
ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /tmp/Bazel.runfiles_27Vmk5/runfiles/com_google_deepvariant/third_party/nucleus/io/python/../../../../_solib_k8/libexternal_Shtslib_Slibhtslib.so)
parallel: This job failed:
/home/simon/miniconda2/envs/testdeepvariant/bin/python /home/simon/miniconda2/envs/testdeepvariant/share/deepvariant-0.7.0-0/binaries/DeepVariant/0.7.0/DeepVariant-0.7.0+cl-208818123/make_examples.zip --mode calling --ref /home/simon/Documents/quickstart_test/quickstart-testdata/ucsc.hg19.chr20.unittest.fasta --reads /home/simon/Documents/quickstart_test/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam --regions chr20:10,000,000-10,010,000 --examples /home/simon/Documents/quickstart_test/quickstart-testdata/output-bioconda/NA12878.tfrecord@2.gz --task 1
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_PEXlEA/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 41, in <module>
    from deepvariant import pileup_image
  File "/tmp/Bazel.runfiles_PEXlEA/runfiles/com_google_deepvariant/deepvariant/pileup_image.py", line 42, in <module>
    from third_party.nucleus.util import ranges
  File "/tmp/Bazel.runfiles_PEXlEA/runfiles/com_google_deepvariant/third_party/nucleus/util/ranges.py", line 42, in <module>
    from third_party.nucleus.io import bed
  File "/tmp/Bazel.runfiles_PEXlEA/runfiles/com_google_deepvariant/third_party/nucleus/io/bed.py", line 79, in <module>
    from third_party.nucleus.io.python import bed_reader
ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /tmp/Bazel.runfiles_PEXlEA/runfiles/com_google_deepvariant/third_party/nucleus/io/python/../../../../_solib_k8/libexternal_Shtslib_Slibhtslib.so)
```
Actually, the key issue was whether the deepvariant bioconda can run on CentOS system. If it can run on CentOS, which CetOS version was require? I can run the deepvariant bioconda on Ubuntu 16.04.
Thank you

**Comment by chapmanb** [comment]
Simon;
Sorry about the glibc problems. Unfortunately I'm not yet able to build DeepVariant in the conda environment, so use their pre-compiled binaries which require glibc 2.23 or better. CentOS 7 still ships with 2.17 by default so unfortunately can't run directly there.

I've tried to address the build issue, but unfortunately got stuck with build system (bazel) on conda and am not sure how to move this forward right now. This thread has all the discussion:

https://github.com/google/deepvariant/issues/29

It would be worth opening a separate issue on the DeepVariant repo and letting them know CentOS 7 support would be useful for you, and hopefully we can help make this available with help from their team. Sorry about not having it working right now and hope this helps explain the situation.
