### ISSUE TITLE
CI test-linux failing due to "failed to import any qt binding"

### ISSUE THREAD

**Issue by nh3** [bioconda/bioconda-recipes#11420]
Hi all,

I have been trying to submit a recipe #11413 (scanpy-scripts) that depends on #11371 (scanpy). While #11413 passed CI linting and local build test (on mac os), it somehow failed the CI test on linux. It built successfully but failed in runtime when importing scanpy. Looks like matplotlib failing to import binding for qt is the cause. Strangely, #11371 passed the test ("import scanpy"). I am unable to set up a testing environment for linux. Could someone kindly advice what might be the cause?

Many thanks,
Ni

```
10:06:58 BIOCONDA INFO BUILD START recipes/scanpy-scripts
...
10:10:38 BIOCONDA INFO BUILD SUCCESS scanpy-scripts-0.0.1-0.tar.bz2
10:10:38 BIOCONDA INFO TEST START via mulled-build recipes/scanpy-scripts
The update_index function has changed to index all subdirs at once.  You're pointing it at a single subdir.  Please update your code to point it at the channel root, rather than a subdir.
WARNING:conda_build.index:The update_index function has changed to index all subdirs at once.  You're pointing it at a single subdir.  Please update your code to point it at the channel root, rather than a subdir.
The update_index function has changed to index all subdirs at once.  You're pointing it at a single subdir.  Please update your code to point it at the channel root, rather than a subdir.
WARNING:conda_build.index:The update_index function has changed to index all subdirs at once.  You're pointing it at a single subdir.  Please update your code to point it at the channel root, rather than a subdir.
......10:16:41 BIOCONDA ERROR COMMAND FAILED: mulled-build build-and-test scanpy-scripts=0.0.1--0 -n biocontainers --test scanpy-read-10x.py --help && scanpy-filter-cells.py --help && scanpy-filter-genes.py --help && scanpy-normalise-data.py --help && scanpy-find-variable-genes.py --help && scanpy-scale-data.py --help && scanpy-run-pca.py --help && scanpy-neighbours.py --help && scanpy-run-umap.py --help && scanpy-run-tsne.py --help && scanpy-find-cluster.py --help && scanpy-find-markers.py --help && which scanpy-scripts-post-install-tests.sh --channels conda-forge,file:///home/circleci/project/miniconda/conda-bld,bioconda,defaults --involucro-path /home/circleci/project/miniconda/bin/involucro
10:16:41 BIOCONDA ERROR STDOUT+STDERR:
/home/circleci/project/miniconda/bin/involucro -v=2 -f /home/circleci/project/miniconda/lib/python3.6/site-packages/galaxy/tools/deps/mulled/invfile.lua -set CHANNELS='conda-forge,file:///home/circleci/project/miniconda/conda-bld,bioconda,defaults' -set TARGETS='scanpy-scripts=0.0.1=0' -set REPO='quay.io/biocontainers/scanpy-scripts:0.0.1--0' -set BINDS='build/dist:/usr/local/,/home/circleci/project/miniconda/conda-bld:/home/circleci/project/miniconda/conda-bld' -set CONDA_IMAGE='continuumio/miniconda3:4.3.27' -set TEST='scanpy-read-10x.py --help && scanpy-filter-cells.py --help && scanpy-filter-genes.py --help && scanpy-normalise-data.py --help && scanpy-find-variable-genes.py --help && scanpy-scale-data.py --help && scanpy-run-pca.py --help && scanpy-neighbours.py --help && scanpy-run-umap.py --help && scanpy-run-tsne.py --help && scanpy-find-cluster.py --help && scanpy-find-markers.py --help && which scanpy-scripts-post-install-tests.sh' build-and-test
.Passing program arguments as a string may be a security hazard if combined with untrusted input
[Oct 19 10:10:41] DEBU Run file [/home/circleci/project/miniconda/lib/python3.6/site-packages/galaxy/tools/deps/mulled/invfile.lua]
[Oct 19 10:10:41] INFO Invoke Task [build]
[Oct 19 10:10:41] STEP Run image [continuumio/miniconda3:4.3.27] with command [[rm -rf /data/dist]]
[Oct 19 10:10:41] DEBU Creating container [step-32469642ca]
[Oct 19 10:10:41] DEBU Image [continuumio/miniconda3:4.3.27] not present, pulling it
[Oct 19 10:10:41] DEBU Pull Image [continuumio/miniconda3:4.3.27]
[Oct 19 10:10:56] DEBU Created container [77c0d25c317a step-32469642ca], starting it
[Oct 19 10:10:56] DEBU Container [77c0d25c317a step-32469642ca] started, waiting for completion
[Oct 19 10:10:56] DEBU Container [77c0d25c317a step-32469642ca] completed with exit code [0] as expected
[Oct 19 10:10:56] DEBU Container [77c0d25c317a step-32469642ca] removed
[Oct 19 10:10:56] STEP Run image [continuumio/miniconda3:4.3.27] with command [[/bin/sh -c conda install  -c conda-forge -c file:///home/circleci/project/miniconda/conda-bld -c bioconda -c defaults  scanpy-scripts=0.0.1=0 -p /usr/local --copy --yes --quiet]]
[Oct 19 10:10:56] DEBU Creating container [step-7b4660b64c]
[Oct 19 10:10:56] DEBU Created container [ee1e259c55aa step-7b4660b64c], starting it
[Oct 19 10:10:57] DEBU Container [ee1e259c55aa step-7b4660b64c] started, waiting for completion
[Oct 19 10:11:22] SOUT 
[Oct 19 10:11:34] SOUT 
[Oct 19 10:11:34] SOUT Package plan for installation in environment /usr/local:
[Oct 19 10:11:34] SOUT 
[Oct 19 10:11:34] SOUT The following NEW packages will be INSTALLED:
[Oct 19 10:11:34] SOUT 
[Oct 19 10:11:34] SOUT anndata:          0.6.10-py_0                bioconda
[Oct 19 10:11:34] SOUT blas:             1.0-mkl
[Oct 19 10:11:34] SOUT blosc:            1.14.4-hfc679d8_0          conda-forge
[Oct 19 10:11:34] SOUT bzip2:            1.0.6-h470a237_2           conda-forge
[Oct 19 10:11:34] SOUT ca-certificates:  2018.10.15-ha4d7672_0      conda-forge
[Oct 19 10:11:34] SOUT cairo:            1.14.12-h276e583_5         conda-forge
[Oct 19 10:11:34] SOUT certifi:          2018.10.15-py36_1000       conda-forge
[Oct 19 10:11:34] SOUT cycler:           0.10.0-py_1                conda-forge
[Oct 19 10:11:34] SOUT dbus:             1.13.0-h3a4f0e9_0          conda-forge
[Oct 19 10:11:34] SOUT decorator:        4.3.0-py_0                 conda-forge
[Oct 19 10:11:34] SOUT expat:            2.2.5-hfc679d8_2           conda-forge
[Oct 19 10:11:34] SOUT fontconfig:       2.13.1-h65d0f4c_0          conda-forge
[Oct 19 10:11:34] SOUT freetype:         2.9.1-h6debe1e_4           conda-forge
[Oct 19 10:11:34] SOUT gettext:          0.19.8.1-h5e8e0c9_1        conda-forge
[Oct 19 10:11:34] SOUT glib:             2.56.2-h464dc38_0          conda-forge
[Oct 19 10:11:34] SOUT gmp:              6.1.2-hfc679d8_0           conda-forge
[Oct 19 10:11:34] SOUT gst-plugins-base: 1.12.5-hde13a9d_0          conda-forge
[Oct 19 10:11:34] SOUT gstreamer:        1.12.5-h5856ed1_0          conda-forge
[Oct 19 10:11:34] SOUT h5py:             2.8.0-py36h7eb728f_3       conda-forge
[Oct 19 10:11:34] SOUT hdf5:             1.10.2-hc401514_2          conda-forge
[Oct 19 10:11:34] SOUT icu:              58.2-hfc679d8_0            conda-forge
[Oct 19 10:11:34] SOUT igraph:           0.7.1-hcc8e21d_5           conda-forge
[Oct 19 10:11:34] SOUT intel-openmp:     2019.0-118
[Oct 19 10:11:34] SOUT jpeg:             9c-h470a237_1              conda-forge
[Oct 19 10:11:34] SOUT kiwisolver:       1.0.1-py36h2d50403_2       conda-forge
[Oct 19 10:11:34] SOUT libffi:           3.2.1-hfc679d8_5           conda-forge
[Oct 19 10:11:34] SOUT libgcc-ng:        7.2.0-hdf63c60_3           conda-forge
[Oct 19 10:11:34] SOUT libgfortran:      3.0.0-1                    conda-forge
[Oct 19 10:11:34] SOUT libgfortran-ng:   7.2.0-hdf63c60_3           conda-forge
[Oct 19 10:11:34] SOUT libiconv:         1.15-h470a237_3            conda-forge
[Oct 19 10:11:34] SOUT libpng:           1.6.35-ha92aebf_2          conda-forge
[Oct 19 10:11:34] SOUT libstdcxx-ng:     7.2.0-hdf63c60_3           conda-forge
[Oct 19 10:11:34] SOUT libuuid:          2.32.1-h470a237_2          conda-forge
[Oct 19 10:11:34] SOUT libxcb:           1.13-h470a237_2            conda-forge
[Oct 19 10:11:34] SOUT libxml2:          2.9.8-h422b904_5           conda-forge
[Oct 19 10:11:34] SOUT llvmlite:         0.25.0-py36hd28b015_1      conda-forge
[Oct 19 10:11:34] SOUT louvain:          0.6.1-py36hfc679d8_1       conda-forge
[Oct 19 10:11:34] SOUT lzo:              2.10-h470a237_0            conda-forge
[Oct 19 10:11:34] SOUT matplotlib:       2.2.3-py36h8e2386c_0       conda-forge
[Oct 19 10:11:34] SOUT mkl:              2019.0-118
[Oct 19 10:11:34] SOUT mkl_fft:          1.0.6-py36_0               conda-forge
[Oct 19 10:11:34] SOUT mkl_random:       1.0.1-py36_0               conda-forge
[Oct 19 10:11:34] SOUT natsort:          5.4.0-py_0                 conda-forge
[Oct 19 10:11:34] SOUT ncurses:          6.1-hfc679d8_1             conda-forge
[Oct 19 10:11:34] SOUT networkx:         2.2-py_1                   conda-forge
[Oct 19 10:11:34] SOUT numba:            0.40.0-py36hf8a1672_0      conda-forge
[Oct 19 10:11:34] SOUT numexpr:          2.6.8-py36hf8a1672_0       conda-forge
[Oct 19 10:11:34] SOUT numpy:            1.15.0-py36h1b885b7_0
[Oct 19 10:11:34] SOUT numpy-base:       1.15.0-py36h3dfced4_0
[Oct 19 10:11:34] SOUT openssl:          1.0.2p-h470a237_1          conda-forge
[Oct 19 10:11:34] SOUT pandas:           0.23.4-py36hf8a1672_0      conda-forge
[Oct 19 10:11:34] SOUT patsy:            0.5.0-py_1                 conda-forge
[Oct 19 10:11:34] SOUT pcre:             8.41-hfc679d8_3            conda-forge
[Oct 19 10:11:34] SOUT pip:              18.1-py36_1000             conda-forge
[Oct 19 10:11:34] SOUT pixman:           0.34.0-h470a237_3          conda-forge
[Oct 19 10:11:34] SOUT pthread-stubs:    0.4-h470a237_1             conda-forge
[Oct 19 10:11:34] SOUT pycairo:          1.17.1-py36h4d1f301_0      conda-forge
[Oct 19 10:11:34] SOUT pyparsing:        2.2.2-py_0                 conda-forge
[Oct 19 10:11:34] SOUT pyqt:             5.6.0-py36h8210e8a_7       conda-forge
[Oct 19 10:11:34] SOUT pytables:         3.4.4-py36h4f72b40_1       conda-forge
[Oct 19 10:11:34] SOUT python:           3.6.6-h5001a0f_3           conda-forge
[Oct 19 10:11:34] SOUT python-dateutil:  2.7.3-py_0                 conda-forge
[Oct 19 10:11:34] SOUT python-igraph:    0.7.1.post6-py36h470a237_5 conda-forge
[Oct 19 10:11:34] SOUT pytz:             2018.5-py_0                conda-forge
[Oct 19 10:11:34] SOUT qt:               5.6.2-hf70d934_9           conda-forge
[Oct 19 10:11:34] SOUT readline:         7.0-haf1bffa_1             conda-forge
[Oct 19 10:11:34] SOUT scanpy:           1.3.2-py36_0               bioconda
[Oct 19 10:11:34] SOUT scanpy-scripts:   0.0.1-0                    file:///home/circleci/project/miniconda/conda-bld
[Oct 19 10:11:34] SOUT scikit-learn:     0.19.1-py36hedc7406_0
[Oct 19 10:11:34] SOUT scipy:            1.1.0-py36hc49cb51_0
[Oct 19 10:11:34] SOUT seaborn:          0.9.0-py_0                 conda-forge
[Oct 19 10:11:34] SOUT setuptools:       40.4.3-py36_0              conda-forge
[Oct 19 10:11:34] SOUT sip:              4.18.1-py36hfc679d8_0      conda-forge
[Oct 19 10:11:34] SOUT six:              1.11.0-py36_1001           conda-forge
[Oct 19 10:11:34] SOUT sqlite:           3.25.2-hb1c47c0_0          conda-forge
[Oct 19 10:11:34] SOUT statsmodels:      0.9.0-py36h7eb728f_0       conda-forge
[Oct 19 10:11:34] SOUT tk:               8.6.8-ha92aebf_0           conda-forge
[Oct 19 10:11:34] SOUT tornado:          5.1.1-py36h470a237_0       conda-forge
[Oct 19 10:11:34] SOUT wheel:            0.32.1-py36_0              conda-forge
[Oct 19 10:11:34] SOUT xorg-kbproto:     1.0.7-h470a237_2           conda-forge
[Oct 19 10:11:34] SOUT xorg-libice:      1.0.9-h470a237_4           conda-forge
....[Oct 19 10:14:56] SOUT xorg-libsm:       1.2.3-h8c8a85c_0           conda-forge
[Oct 19 10:14:56] SOUT xorg-libx11:      1.6.6-h470a237_0           conda-forge
[Oct 19 10:14:56] SOUT xorg-libxau:      1.0.8-h470a237_6           conda-forge
[Oct 19 10:14:56] SOUT xorg-libxdmcp:    1.1.2-h470a237_7           conda-forge
[Oct 19 10:14:56] SOUT xorg-libxext:     1.3.3-h470a237_4           conda-forge
[Oct 19 10:14:56] SOUT xorg-libxrender:  0.9.10-h470a237_2          conda-forge
[Oct 19 10:14:56] SOUT xorg-renderproto: 0.11.1-h470a237_2          conda-forge
[Oct 19 10:14:56] SOUT xorg-xextproto:   7.3.0-h470a237_2           conda-forge
[Oct 19 10:14:56] SOUT xorg-xproto:      7.0.31-h470a237_7          conda-forge
[Oct 19 10:14:56] SOUT xz:               5.2.4-h470a237_1           conda-forge
[Oct 19 10:14:56] SOUT zlib:             1.2.11-h470a237_3          conda-forge
[Oct 19 10:14:56] SOUT 
[Oct 19 10:14:56] DEBU Container [ee1e259c55aa step-7b4660b64c] completed with exit code [0] as expected
[Oct 19 10:14:58] DEBU Container [ee1e259c55aa step-7b4660b64c] removed
[Oct 19 10:14:58] STEP Wrap [build/dist] as [quay.io/biocontainers/scanpy-scripts:0.0.1--0]
[Oct 19 10:14:58] DEBU Creating container [step-09578a0906]
[Oct 19 10:14:58] DEBU Image [bgruening/busybox-bash:0.1] not present, pulling it
[Oct 19 10:14:58] DEBU Pull Image [bgruening/busybox-bash:0.1]
[Oct 19 10:15:17] DEBU Packing succeeded
.[Oct 19 10:16:04] INFO Invoke Task [singularity]
[Oct 19 10:16:04] WARN Invoked Stepless Task [singularity]
[Oct 19 10:16:04] INFO Invoke Task [cleanup]
[Oct 19 10:16:04] STEP Run image [continuumio/miniconda3:4.3.27] with command [[rm -rf /data/dist]]
[Oct 19 10:16:04] DEBU Creating container [step-d1d95fa773]
[Oct 19 10:16:04] DEBU Created container [7da982f4022a step-d1d95fa773], starting it
[Oct 19 10:16:04] DEBU Container [7da982f4022a step-d1d95fa773] started, waiting for completion
[Oct 19 10:16:06] DEBU Container [7da982f4022a step-d1d95fa773] completed with exit code [0] as expected
[Oct 19 10:16:06] DEBU Container [7da982f4022a step-d1d95fa773] removed
[Oct 19 10:16:06] INFO Invoke Task [test]
[Oct 19 10:16:06] STEP Run image [quay.io/biocontainers/scanpy-scripts:0.0.1--0] with command [[scanpy-read-10x.py --help && scanpy-filter-cells.py --help && scanpy-filter-genes.py --help && scanpy-normalise-data.py --help && scanpy-find-variable-genes.py --help && scanpy-scale-data.py --help && scanpy-run-pca.py --help && scanpy-neighbours.py --help && scanpy-run-umap.py --help && scanpy-run-tsne.py --help && scanpy-find-cluster.py --help && scanpy-find-markers.py --help && which scanpy-scripts-post-install-tests.sh]]
[Oct 19 10:16:06] DEBU Creating container [step-4bdf41e915]
[Oct 19 10:16:06] DEBU Created container [bd765688049c step-4bdf41e915], starting it
[Oct 19 10:16:06] DEBU Container [bd765688049c step-4bdf41e915] started, waiting for completion
[Oct 19 10:16:07] SOUT font search path ['/usr/local/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf', '/usr/local/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/afm', '/usr/local/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts']
[Oct 19 10:16:07] SOUT generated new fontManager
[Oct 19 10:16:08] SERR /usr/local/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[Oct 19 10:16:08] SERR return f(*args, **kwds)
[Oct 19 10:16:08] SERR /usr/local/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[Oct 19 10:16:08] SERR return f(*args, **kwds)
[Oct 19 10:16:08] SERR /usr/local/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[Oct 19 10:16:08] SERR return f(*args, **kwds)
[Oct 19 10:16:08] SERR Traceback (most recent call last):
[Oct 19 10:16:08] SERR File "/usr/local/bin/scanpy-read-10x.py", line 8, in <module>
[Oct 19 10:16:08] SERR from scanpy_wrapper_utils import ScanpyArgParser, write_output_object
[Oct 19 10:16:08] SERR File "/usr/local/bin/scanpy_wrapper_utils.py", line 15, in <module>
[Oct 19 10:16:08] SERR import scanpy.api as sc
[Oct 19 10:16:08] SERR File "/usr/local/lib/python3.6/site-packages/scanpy/api/__init__.py", line 10, in <module>
[Oct 19 10:16:08] SERR from . import pl
[Oct 19 10:16:08] SERR File "/usr/local/lib/python3.6/site-packages/scanpy/api/pl.py", line 1, in <module>
[Oct 19 10:16:08] SERR from ..plotting.anndata import scatter, violin, ranking, clustermap, stacked_violin, heatmap, dotplot, matrixplot
[Oct 19 10:16:08] SERR File "/usr/local/lib/python3.6/site-packages/scanpy/plotting/anndata.py", line 8, in <module>
[Oct 19 10:16:08] SERR from matplotlib import pyplot as pl
[Oct 19 10:16:08] SERR File "/usr/local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
[Oct 19 10:16:08] SERR _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
[Oct 19 10:16:08] SERR File "/usr/local/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
[Oct 19 10:16:08] SERR [backend_name], 0)
[Oct 19 10:16:08] SERR File "/usr/local/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
[Oct 19 10:16:08] SERR from .backend_qt5 import (
[Oct 19 10:16:08] SERR File "/usr/local/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 19, in <module>
[Oct 19 10:16:08] SERR import matplotlib.backends.qt_editor.figureoptions as figureoptions
[Oct 19 10:16:08] SERR File "/usr/local/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
[Oct 19 10:16:08] SERR import matplotlib.backends.qt_editor.formlayout as formlayout
[Oct 19 10:16:08] SERR File "/usr/local/lib/python3.6/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 54, in <module>
[Oct 19 10:16:08] SERR from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
[Oct 19 10:16:08] SERR File "/usr/local/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 158, in <module>
[Oct 19 10:16:08] SERR raise ImportError("Failed to import any qt binding")
[Oct 19 10:16:08] SERR ImportError: Failed to import any qt binding
[Oct 19 10:16:08] ERRO Task processing failed: Unexpected exit code [1] of container [bd765688049c step-4bdf41e915], container preserved

10:16:41 BIOCONDA ERROR TEST FAILED: recipes/scanpy-scripts
10:16:43 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
10:16:43 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/scanpy-scripts
Exited with code 1
```

**Comment by nh3** [comment]
Apparently just adding more dependencies solves the problem. In this case `matplotlib>=3.0` is the quick fix. Though it remains to be seen which package could further help to bring down this version requirement to 2.2 which is the same that scanpy requires.
