### ISSUE TITLE
Lint failed, but cannot understand the error message `Mixing dicts with non-Series...`

### ISSUE THREAD

**Issue by zhanxw** [bioconda/bioconda-recipes#12403]
My recipe `rvtests` failed the CI in the linting step (https://circleci.com/gh/bioconda/bioconda-recipes/35426). 
The meta.yaml looks valid, but the error message confused me, as I don't know where I used dicts or non-Series.

```
#!/bin/bash -eo pipefail
bioconda-utils lint recipes config.yml \
--loglevel debug --full-report \
--git-range master HEAD
Traceback (most recent call last):
  File "/home/circleci/project/miniconda/bin/bioconda-utils", line 11, in <module>
    sys.exit(main())
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 657, in main
    bioconductor_skeleton, pypi_check, clean_cran_skeleton,
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 228, in lint
    df = linting.channel_dataframe(cache=cache)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/linting.py", line 123, in channel_dataframe
    x = pd.DataFrame(repo)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/pandas/core/frame.py", line 330, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/pandas/core/frame.py", line 461, in _init_dict
    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/pandas/core/frame.py", line 6163, in _arrays_to_mgr
    index = extract_index(arrays)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/pandas/core/frame.py", line 6214, in extract_index
    raise ValueError('Mixing dicts with non-Series may lead to '
ValueError: Mixing dicts with non-Series may lead to ambiguous ordering.
Exited with code 1
```

**Comment by epruesse** [comment]
Looks like a bug in bioconda-utils. Which PR is this?

**Comment by zhanxw** [comment]
I have not created a pull request for this branch. Do you want me to create one?

**Comment by zhanxw** [comment]
Just created a PR.

**Comment by zhanxw** [comment]
It is a temporary issue as described in https://github.com/bioconda/bioconda-recipes/pull/12410#issuecomment-442689776, and it is not related to bioconda-utils.

**Comment by zhanxw** [comment]
More discussions are here: bioconda/bioconda-utils#360
