### ISSUE TITLE
cannot find -lpthread -lm  and et al

### ISSUE THREAD

**Issue by zhanxw** [bioconda/bioconda-recipes#12401]
My recipe (rvtests: https://github.com/bioconda/bioconda-recipes/compare/rvtests) failed to compile at the last step. Although I specified the prefixed library path, ld failed. At the end I enclosed relevant error messages.  Are there any additional `-L` options I need to pass to `gcc` in order to use pthread, math and rt libraries?

```
...
mkdir -p /opt/conda/conda-bld/rvtests_1543391504358/work/executable

g++ -o /opt/conda/conda-bld/rvtests_1543391504358/work/executable/rvtest Main.o DataConsolidator.o ModelFitter.o TabixUtil.o ModelManager.o ModelParser.o Model.o GenotypeExtractor.o VCFGenotypeExtractor.o BGenGenotypeExtractor.o KGGGenotypeExtractor.o DataLoader.o GenotypeCounter.o SingleDummy.o -O2 -DNDEBUG -D__STDC_LIMIT_MACROS -std=c++0x -Wall -Wno-unused-function -fopenmp -DGIT_VERSION="\"Unknown\"" -D_USE_KNETFILE -static -L/opt/conda/conda-bld/rvtests_1543391504358/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib /opt/conda/conda-bld/rvtests_1543391504358/work/regression/lib-regression.a /opt/conda/conda-bld/rvtests_1543391504358/work/libVcf/lib-vcf.a /opt/conda/conda-bld/rvtests_1543391504358/work/libBgen/lib-bgen.a /opt/conda/conda-bld/rvtests_1543391504358/work/base/lib-base.a /opt/conda/conda-bld/rvtests_1543391504358/work/libsrc/lib-goncalo.a /opt/conda/conda-bld/rvtests_1543391504358/work/third/samtools/bcftools/libbcf.a /opt/conda/conda-bld/rvtests_1543391504358/work/third/samtools/libbam.a /opt/conda/conda-bld/rvtests_1543391504358/work/third/tabix/libtabix.a /opt/conda/conda-bld/rvtests_1543391504358/work/third/pcre/lib/libpcreposix.a /opt/conda/conda-bld/rvtests_1543391504358/work/third/pcre/lib/libpcre.a /opt/conda/conda-bld/rvtests_1543391504358/work/third/gsl/lib/libgsl.a /opt/conda/conda-bld/rvtests_1543391504358/work/third/zlib/libz.a /opt/conda/conda-bld/rvtests_1543391504358/work/third/bzip2/libbz2.a /opt/conda/conda-bld/rvtests_1543391504358/work/third/nlopt/lib/libnlopt.a /opt/conda/conda-bld/rvtests_1543391504358/work/third/sqlite/lib/libsqlite3.a /opt/conda/conda-bld/rvtests_1543391504358/work/third/zstd/lib/libzstd.a  -lm -lpthread

/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: cannot find -lpthread

/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: cannot find -lm

/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: cannot find -lrt

/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: cannot find -lpthread

/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: cannot find -lc

collect2: error: ld returned 1 exit status

make[1]: *** [/opt/conda/conda-bld/rvtests_1543391504358/work/executable/rvtest] Error 1

make[1]: Leaving directory `/opt/conda/conda-bld/rvtests_1543391504358/work/src'

make: *** [release] Error 2

Traceback (most recent call last):

  File "/opt/conda/bin/conda-build", line 11, in <module>

    sys.exit(main())

  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 438, in main

    execute(sys.argv[1:])

  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 429, in execute

    verify=args.verify)

  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 201, in build

    notest=notest, need_source_download=need_source_download, variants=variants)

  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 2204, in build_tree

    notest=notest,

  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1445, in build

    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)

  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 313, in check_call_env

    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)

  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 293, in _func_defaulting_env_to_os_environ

    raise subprocess.CalledProcessError(proc.returncode, _args)

subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/opt/conda/conda-bld/rvtests_1543391504358/work/conda_build.sh']' returned non-zero exit status 2.



07:57:00 BIOCONDA ERROR BUILD FAILED recipes/rvtests
07:57:01 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
07:57:01 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/rvtests
Exited with code 1
```

**Comment by zhanxw** [comment]
I found a temporary solution: remove the '-static' flag.
