### ISSUE TITLE
test-macos failed

### ISSUE THREAD

**Issue by zhanxw** [bioconda/bioconda-recipes#12440]
The error messages cannot help me to locate the problem.
Is there a way to get more error messages? 

```
...
Downloading source to cache: v2.0.6_72f4419d5d.tar.gz
Downloading https://github.com/zhanxw/rvtests/archive/v2.0.6.tar.gz
Success
Extracting download
source tree in: /Users/distiller/project/miniconda/conda-bld/rvtests_1543556260687/work
Traceback (most recent call last):
  File "/Users/distiller/project/miniconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 438, in main
    execute(sys.argv[1:])
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 429, in execute
    verify=args.verify)
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/api.py", line 201, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 2204, in build_tree
    notest=notest,
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/build.py", line 1445, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/utils.py", line 313, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/utils.py", line 293, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/Users/distiller/project/miniconda/conda-bld/rvtests_1543556260687/work/conda_build.sh']' returned non-zero exit status 1.


21:38:47 BIOCONDA ERROR BUILD FAILED recipes/rvtests
21:38:51 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
21:38:51 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/rvtests
Exited with code 1
```

**Comment by zhanxw** [comment]
It looks like the problem is related to sed, as sed in Mac works differently than sed in Linux.
