### ISSUE TITLE
Install of pysamstats results in ValueError: pysam.libchtslib.HTSFile has the wrong size

### ISSUE THREAD

**Issue by lparsons** [bioconda/bioconda-recipes#12466]
`conda create -n pysamstats pysamstats`

```
Traceback (most recent call last):
  File "/Genomics/grid/users/lparsons/miniconda3/envs/pysamstats/bin/pysamstats", line 10, in <module>
    import pysamstats
  File "/Genomics/grid/users/lparsons/miniconda3/envs/pysamstats/lib/python3.6/site-packages/pysamstats/__init__.py", line 8, in <module>
    from .pileup import *
  File "/Genomics/grid/users/lparsons/miniconda3/envs/pysamstats/lib/python3.6/site-packages/pysamstats/pileup.py", line 6, in <module>
    import pysamstats.opt as opt
  File "libchtslib.pxd", line 2590, in init pysamstats.opt
ValueError: pysam.libchtslib.HTSFile has the wrong size, try recompiling. Expected 88, got 80
```

```
# packages in environment at /Genomics/grid/users/lparsons/miniconda3/envs/pysamstats:
#
# Name                    Version                   Build  Channel
bcftools                  1.9                  h4da6232_0    bioconda
blas                      1.1                    openblas    conda-forge
blosc                     1.14.4               hfc679d8_0    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
curl                      7.62.0               h74213dd_0    conda-forge
hdf5                      1.10.3               hc401514_2    conda-forge
htslib                    1.9                  hc238db4_4    bioconda
krb5                      1.16.2               hbb41f41_0    conda-forge
libcurl                   7.62.0               hbdb9355_0    conda-forge
libdeflate                1.0                  h470a237_0    bioconda
libedit                   3.1.20170329         haf1bffa_1    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libgfortran               3.0.0                         1    conda-forge
libssh2                   1.8.0                h5b517e9_3    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
lzo                       2.10                 h470a237_0    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
numexpr                   2.6.8            py36hf8a1672_0    conda-forge
numpy                     1.15.1          py36_blas_openblashd3ea46f_0    conda-forge
openblas                  0.2.20                        8    conda-forge
openssl                   1.0.2p               h470a237_1    conda-forge
pip                       18.1                  py36_1000    conda-forge
pysam                     0.15.1           py36h0380709_0    bioconda
pysamstats                1.0.1            py36ha92aebf_2    bioconda
pytables                  3.4.4            py36h2392372_1    conda-forge
python                    3.6.7                h5001a0f_1    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
samtools                  1.9                  h8ee4bcc_1    bioconda
setuptools                40.6.2                   py36_0    conda-forge
six                       1.11.0                py36_1001    conda-forge
sqlite                    3.26.0               hb1c47c0_0    conda-forge
tk                        8.6.9                ha92aebf_0    conda-forge
wheel                     0.32.3                   py36_0    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

**Comment by dpryan79** [comment]
Yes, pysam is made for a particular htslib release, I assumed that pinning was already done!

**Comment by lparsons** [comment]
Just checked this myself. These errors have been plaguing me for some time. Any help in tracking them down would be appreciated, but at the moment, I'm pretty stumped.

**Comment by dpryan79** [comment]
I suspect this is a weird numpy version problem. For whatever it's worth I get exactly the same error as you do :(

**Comment by lparsons** [comment]
I wonder what is requiring numpy? I'm wondering if this is actually an issue with stuff in conda-forge?

**Comment by dpryan79** [comment]
You could `bioconda-utils build` that locally and then `conda install` the resulting tarball. That'd allow testing at least.

**Comment by lparsons** [comment]
Hmmm.... Although, this calls for `pysam 0.11.2.2` and I'm not *sure* that version has a pinned htslib dependency... Also, woudn't and updated build work (at least in theory) since the problem was the build was against an old version of htslib/numpy and the run is against a new one?

**Comment by dpryan79** [comment]
You might also look at pytables, since it requires numpy.

**Comment by dpryan79** [comment]
These days that shouldn't do anything. The `conda_build_config.yaml` sets `htslib` to 1.9 currently.
