### ISSUE TITLE
About rMATs in conda

### ISSUE THREAD

**Issue by zhaosq2016** [bioconda/bioconda-recipes#12782]
**Hi
There is some wrong about rMATs in conda. I could find the reason. Can you help me?
The error like this:**

Average number of exons per transcript excluding one-exon tx is 5.579424
Average number of gene per geneGroup is 109.917857
Done processing each gene from dictionary to compile AS events
Found 17348 exon skipping events
Found 2103 exon MX events
Found 16447 alt SS events
There are 9702 alt 3 SS events and 6745 alt 5 SS events.
Found 16824 RI events

Running the statistical part.
Traceback (most recent call last):
  File "/home/miniconda2/bin/rmats.py", line 308, in <module>
    main()
  File "/home/miniconda2/bin/rmats.py", line 289, in main
    run_stat(jc_it % ('SE'), args.tstat, 'JC', 'SE', args.cstat, args.od, args.tmp, args.stat)
  File "/home/miniconda2/bin/rmats.py", line 254, in run_stat
    call(map(str, [rmats_c, '-i', istat, '-t', tstat, '-o', ostat % ('P-V'), '-c', cstat,]), stdout=FNULL)
  File "/home/miniconda2/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/home/miniconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/home/miniconda2/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by bgruening** [comment]
How have you installed rMATs and how did you run it? This could be an missing dependency.

**Comment by fgypas** [comment]
Hi 

I get a similar error. I did the following:

Installation:
```bash
conda create -n rmats -c bioconda rmats=4.0.2
source activate rmats
```

Command:
```bash
rmats.py \
--gtf path/to/gtf \
--b1 path/to/replicateA_samples.tsv \
--b2 path/to/replicateB_samples.tsv \
-t single \
--readLength 51 \
--nthread 16 \
--od path/to/output/directory
```

Error:
```
Running the statistical part.
Traceback (most recent call last):
  File "/abs/path/to/soft/miniconda3/envs/rmats/bin/rmats.py", line 308, in <module>
    main()
  File "/abs/path/to/soft/miniconda3/envs/rmats/bin/rmats.py", line 289, in main
    run_stat(jc_it % ('SE'), args.tstat, 'JC', 'SE', args.cstat, args.od, args.tmp, args.stat)
  File "/abs/path/to/soft/miniconda3/envs/rmats/bin/rmats.py", line 254, in run_stat
    call(map(str, [rmats_c, '-i', istat, '-t', tstat, '-o', ostat % ('P-V'), '-c', cstat,]), stdout=FNULL)
  File "/abs/path/to/soft/miniconda3/envs/rmats/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/abs/path/to/soft/miniconda3/envs/rmats/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/abs/path/to/soft/miniconda3/envs/rmats/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by shihaoshen** [comment]
There is an issue of where rMATS searches for its component in the conda environment. As a temporary solution, you can copy the rMATS directory into the conda bin, when you are in the conda environment.

cp -r $CONDA_PREFIX/rMATS/* $CONDA_PREFIX/bin/

**Comment by dpryan79** [comment]
This is simply due to there being a symlink in `bin` that's ignored by the python script. I'll push a fix shortly.

**Comment by dpryan79** [comment]
@fgypas @zhaosq2016 Please try the updated package. If it doesn't work then let me know and we can reopen this issue.
