### ISSUE TITLE
bootstrap.py fails: AttributeError: type object 'tqdm' has no attribute '_lock'

### ISSUE THREAD

**Issue by rababerladuseladim** [bioconda/bioconda-recipes#12988]
I execute bootstrap.py as specified in the 'contribute a recipe' manual. Building fails with the following Stacktrace.

```
Traceback (most recent call last):
  File "/tmp/miniconda/miniconda/bin/bioconda-utils", line 11, in <module>
    sys.exit(main())
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 696, in main
    bioconductor_skeleton, clean_cran_skeleton, autobump
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 358, in build
    modified = utils.modified_recipes(git_range, recipe_folder, config)
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/utils.py", line 1022, in modified_recipes
    unblacklisted = newly_unblacklisted(config_file, recipe_folder, orig_git_range)
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/utils.py", line 739, in newly_unblacklisted
    logger.info('Recipes newly unblacklisted:\n%s', '\n'.join(list(results)))
  File "/tmp/miniconda/miniconda/lib/python3.6/logging/__init__.py", line 1308, in info
    self._log(INFO, msg, args, **kwargs)
  File "/tmp/miniconda/miniconda/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/tmp/miniconda/miniconda/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/tmp/miniconda/miniconda/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/tmp/miniconda/miniconda/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/utils.py", line 44, in emit
    _tqdm.tqdm.write(self.format(record))
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/tqdm/_tqdm.py", line 525, in write
    with cls.external_write_mode(file=file, nolock=nolock):
  File "/tmp/miniconda/miniconda/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/tqdm/_tqdm.py", line 540, in external_write_mode
    cls._lock.acquire()
AttributeError: type object 'tqdm' has no attribute '_lock'
```

**Comment by bgruening** [comment]
Can you provide us the command which you have run? Was it just `./boostrap.py`?

**Comment by rababerladuseladim** [comment]
I ran 
bioconda-utils build recipes config.yml --git-range master
after changing the build number in recipes/rnaz/

by the way: doing this in a workshop @jfallmann @bernt-matthias

**Comment by bgruening** [comment]
I see, so nothing works in this workshop ... Oo. Sorry about that.
I can not even run ./boostrap atm as I get an anaconda server error. Narf!

**Comment by jfallmann** [comment]
@bgruening Isn't that what workshops are there for ;)

**Comment by bgruening** [comment]
I'm sure you and @bernt-matthias can manage this, I'm just sorry for @rababerladuseladim :)
I promise usually everything works ;)

**Comment by lonsbio** [comment]
Confirm same error on a fresh VM

**Comment by lonsbio** [comment]
@bgruening  `tqdm` might need to be pinned, `conda install tqdm==4.28.1` rescued my fresh install but I'm not across the entire bioconda setup to know of all the consequences

**Comment by jfallmann** [comment]
Same here, @lonsbio 's fix is working for me too

**Comment by bernt-matthias** [comment]
Who would like to open a PR :) ?

**Comment by bgruening** [comment]
@lonsbio awesome thanks!

**Comment by bgruening** [comment]
See https://github.com/bioconda/bioconda-utils/pull/384

**Comment by bgruening** [comment]
@rababerladuseladim can you try again, it should be fixed. Thanks.
