### ISSUE TITLE
conda-forge-pinning dependency issue when executing circleci

### ISSUE THREAD

**Issue by CarlosHorro** [bioconda/bioconda-recipes#13114]
Hi all,

Long after last time I managed this tools, I wanted to create and test a new bioconda package, so I wanted to execute circleci, but there seems to be some dependency problem with conda-forge-pinning v2018.11.27 package which I am not able to solve :
```

./bootstrap.py /tmp/miniconda

....

PackagesNotFoundError: The following packages are not available from current channels:

  - conda-forge-pinning==2018.11.27

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/gaiar/linux-64
  - https://conda.anaconda.org/gaiar/noarch
  - https://conda.anaconda.org/msarahan/linux-64
  - https://conda.anaconda.org/msarahan/noarch
  - file:///home/parallels/conda-channel-local/linux-64
  - file:///home/parallels/conda-channel-local/noarch
  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Traceback (most recent call last):
  File "./bootstrap.py", line 110, in <module>
    sp.check_call(['.circleci/setup.sh'], env=env)
  File "/home/parallels/anaconda2/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['.circleci/setup.sh']' returned non-zero exit status 1

```

I have tried to add all repositories where this package is supposed to be, even installing it locally on my own local channel, but it still fails... 

```

conda search conda-forge-pinning -c file:///home/parallels/conda-channel-local
Loading channels: done
# Name                  Version           Build  Channel             
conda-forge-pinning      2017.11.28      h61ef92c_0  conda-channel-local 
conda-forge-pinning      2017.11.28      h61ef92c_0  msarahan            
conda-forge-pinning      2018.05.07               0  gaiar               
conda-forge-pinning      2018.07.24               0  gaiar               
conda-forge-pinning      2019.01.15               1  conda-forge         
conda-forge-pinning      2019.01.16               0  conda-forge  

```

Does anyone know about this issue, please?

**Comment by dpryan79** [comment]
This should now be resolved, the issue was due to conda-forge removing the `main` label from that build of `conda-forge-pinning`. We've since updated the channels that are used on circleci.
