### ISSUE TITLE
moFF: Python version error

### ISSUE THREAD

**Issue by CarlosHorro** [bioconda/bioconda-recipes#13540]
Hi,

I am using moFF with Galaxy via Conda and, when executing it, I receive this error:

```
Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/home/parallels/GitHub/galaxy/database/dependencies/_conda/envs/__moff@1.2.1/bin/moff.py", line 20, in <module>
    import pymzml
  File "/home/parallels/GitHub/galaxy/database/dependencies/_conda/envs/__moff@1.2.1/lib/python2.7/site-packages/pymzml/__init__.py", line 24, in <module>
    raise RuntimeError('pymzML requires Python 3.4 or later.')
RuntimeError: pymzML requires Python 3.4 or later.

```

It seems that pymzML requires Python 3.4 or later to work properly, but the recipe does not enforce that and it seems it just uses Python version used by default in the system (Python 2.7 in my case), so I am thinking on opening a PR with that modification for moFF recipe:
#13541

Greetings,
Carlos

**Comment by bgruening** [comment]
@CarlosHorro we should probably also fix pymzML https://github.com/bioconda/bioconda-recipes/pull/13543
