### ISSUE TITLE
post-link script not working as expected/intended

### ISSUE THREAD

**Issue by mbhall88** [bioconda/bioconda-recipes#13784]
The [post-link script for the mykrobe recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/mykrobe/post-link.sh) is intended to download some data which is used by the program as a panel for drug resistance prediction at runtime.  
However, when running the bioconda recipe version of mykrobe it seems unable to see this data
```
INFO:mykrobe.cmds.amr:Running AMR prediction with panels data/panels/tb-species-170421.fasta.gz, data/panels/tb-hunt-probe-set-jan-03-2019.fasta.gz
Traceback (most recent call last):
  File "/usr/local/bin/mykrobe", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/mykrobe/cli.py", line 8, in main
    args.func(parser, args)
  File "/usr/local/lib/python3.7/site-packages/mykrobe/parser.py", line 40, in run_subtool
    run(parser, args)
  File "/usr/local/lib/python3.7/site-packages/mykrobe/cmds/amr.py", line 256, in run
    cp.run()
  File "/usr/local/lib/python3.7/site-packages/mykrobe/typing/typer/genotyper.py", line 73, in run
    self._run_cortex()
  File "/usr/local/lib/python3.7/site-packages/mykrobe/typing/typer/genotyper.py", line 90, in _run_cortex
    self.mc_cortex_runner.run()
  File "/usr/local/lib/python3.7/site-packages/mykrobe/cortex/mccortex.py", line 183, in run
    self._check_panels()
  File "/usr/local/lib/python3.7/site-packages/mykrobe/cortex/mccortex.py", line 195, in _check_panels
    panel.filepath)
ValueError: Could not find a panel at /usr/local/lib/python3.7/site-packages/mykrobe/data/panels/tb-species-170421.fasta.gz.
```
Have a misinterpreted what the post-link script does or made an error somewhere?

**Comment by nsoranzo** [comment]
xref. https://github.com/bioconda/bioconda-recipes/issues/13846

**Comment by mbhall88** [comment]
@nsoranzo I'm not sure it's the same problem? The post-link script runs fine, it's just that the files don't seem to be where I expect them to be at runtime.

**Comment by nsoranzo** [comment]
@mbhall88 I still don't understand what's causing these issues, so I can't tell if they have the same origin. But they both involve the post-link scripts, so I've added the xref for your information.

**Comment by KyleL1998** [comment]
@mbhall88 I've submitted a fix that hopefully corrects this problem.

**Comment by mbhall88** [comment]
@KyleL1998 that has fixed the problem. Thanks very much!  

This fixes https://github.com/Mykrobe-tools/mykrobe/issues/46
