### ISSUE TITLE
rseqc genebody coverage doesn't work

### ISSUE THREAD

**Issue by jfreimer** [bioconda/bioconda-recipes#1393]
rseqc installed via bioconda errors while running geneBody_coverage.py. It fails with the following error:

`[jfreimer@h1 scripts]$ geneBody_coverage.py
Traceback (most recent call last):
  File "/N/u/jfreimer/Mason/miniconda/bin/geneBody_coverage.py", line 4, in <module>
    import pkg_resources
  File "/N/u/jfreimer/Mason/miniconda/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 2675, in <module>
    add_activation_listener(lambda dist: dist.activate())
  File "/N/u/jfreimer/Mason/miniconda/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 662, in subscribe
    callback(dist)
  File "/N/u/jfreimer/Mason/miniconda/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 2675, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/N/u/jfreimer/Mason/miniconda/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 2177, in activate
    self.insert_on(path)
  File "/N/u/jfreimer/Mason/miniconda/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 2278, in insert_on
    "with distribute. Found one at %s" % str(self.location))
ValueError: A 0.7-series setuptools cannot be installed with distribute. Found one at /gpfs/home/j/f/jfreimer/Mason/miniconda/lib/python2.7/site-packages/setuptools-20.7.0-py2.7.egg`

**Comment by jfreimer** [comment]
Requires the distribute package to be installed separately for it to work.
