### ISSUE TITLE
Error with click, Python 3 & missing UTF-8 locale

### ISSUE THREAD

**Issue by simonvh** [bioconda/bioconda-recipes#14086]
I get the following error (for full details see [here](https://circleci.com/gh/bioconda/bioconda-recipes/48034)):

```
[Mar 19 11:45:24] DEBU Creating container [step-54cc080860]
[Mar 19 11:45:24] DEBU Created container [6ad88087a20b step-54cc080860], starting it
[Mar 19 11:45:24] DEBU Container [6ad88087a20b step-54cc080860] started, waiting for completion
[Mar 19 11:45:24] SERR /usr/local/lib/python3.6/site-packages/norns-0.1.2-py2.7.egg/norns/cfg.py:72: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
[Mar 19 11:45:24] SERR Traceback (most recent call last):
[Mar 19 11:45:24] SERR File "/usr/local/bin/genomepy", line 11, in <module>
[Mar 19 11:45:24] SERR load_entry_point('genomepy==0.5.4', 'console_scripts', 'genomepy')()
[Mar 19 11:45:24] SERR File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
[Mar 19 11:45:24] SERR return self.main(*args, **kwargs)
[Mar 19 11:45:24] SERR File "/usr/local/lib/python3.6/site-packages/click/core.py", line 696, in main
[Mar 19 11:45:24] SERR _verify_python3_env()
[Mar 19 11:45:24] SERR File "/usr/local/lib/python3.6/site-packages/click/_unicodefun.py", line 124, in _verify_python3_env
[Mar 19 11:45:24] SERR ' mitigation steps.' + extra
[Mar 19 11:45:24] SERR RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/en/7.x/python3/ for mitigation steps.
[Mar 19 11:45:24] SERR 
[Mar 19 11:45:24] SERR Additional information: on this system no suitable UTF-8
[Mar 19 11:45:24] SERR locales were discovered.  This most likely requires resolving
[Mar 19 11:45:24] SERR by reconfiguring the locale system.
[Mar 19 11:45:25] ERRO Task processing failed: Unexpected exit code [1] of container [6ad88087a20b step-54cc080860], container preserved
```

However, in `meta.yaml`  I [have the following lines](https://github.com/simonvh/bioconda-recipes/blob/79fd891620848c793d22569d8261d6be42f20184/recipes/genomepy/meta.yaml#L52-L56):

```
extra:
  container:
    # click requires a unicode locale when used with Python 3
    # extended-base generates en_US.UTF-8 locale and sets LC_ALL, LANG properly
    extended-base: true  # [py3k]
```

This used to work, what am I doing wrong? @bgruening any idea?

**Comment by simonvh** [comment]
Looks like this issue bioconda/bioconda-utils#70 @epruesse

**Comment by simonvh** [comment]
Update: I restarted the the CircleCI check and then it runs fine (at least the Linux build does).
