### ISSUE TITLE
Persistant problems with hap.py installation // Tried Miniconda, docker and wget too 

### ISSUE THREAD

**Issue by achimmiri** [bioconda/bioconda-recipes#14486]
```
(HAPPY) anusha@Precision-7920-Tower:~$ hap.py /home/anusha/TESTBEN/NA12878.vcf.gz /home/anusha/TESTBEN/PRO001B.vcf.gz -f /home/anusha/gatk-4.0.4.0/ussd-ftp.illumina.com/2017-1.0/hg38/small_variants/ConfidentRegions.bed.gz -o benchmarking-output -r /data/human_ref/hg38/genome/genome.fa  --no-leftshift --no-decompose --gender=none --engine=vcfeval --threads 8
2019-04-16 18:15:56,575 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2019-04-16 18:15:56,575 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
[I] Total VCF records:         4167900
[I] Non-reference VCF records: 4167900
[W] overlapping records at chr1:55075666 for sample 0
[W] Variants that overlap on the reference allele: 33
[I] Total VCF records:         85994
[I] Non-reference VCF records: 84788
2019-04-16 18:17:01,268 WARNING  Creating template for vcfeval. You can speed this up by supplying a SDF template that corresponds to /data/human_ref/hg38/genome/genome.fa
2019-04-16 18:18:36,763 ERROR    [stderr] regex_error
2019-04-16 18:18:36,808 ERROR    Command 'quantify /tmp/hap.py.result.Ixh7yg.vcf.gz -o benchmarking-output.roc.tsv -r /data/human_ref/hg38/genome/genome.fa --threads 8 --output-vtc 0 --output-rocs 1 --type ga4gh --qq QUAL --roc-delta 0.500000 --clean-info 1 --fix-chr-regions 0 -v benchmarking-output.vcf.gz -R 'CONF_VARS:/tmp/tmpqXFzwQ.bed' -R 'CONF:/home/anusha/gatk-4.0.4.0/ussd-ftp.illumina.com/2017-1.0/hg38/small_variants/ConfidentRegions.bed.gz' --roc-regions '*'' returned non-zero exit status 1
2019-04-16 18:18:36,809 ERROR    Traceback (most recent call last):
2019-04-16 18:18:36,809 ERROR      File "/home/anusha/miniconda3/envs/HAPPY/bin/hap.py", line 511, in <module>
2019-04-16 18:18:36,809 ERROR        main()
2019-04-16 18:18:36,809 ERROR      File "/home/anusha/miniconda3/envs/HAPPY/bin/hap.py", line 496, in main
2019-04-16 18:18:36,809 ERROR        qfy.quantify(args)
2019-04-16 18:18:36,809 ERROR      File "/home/anusha/miniconda3/envs/HAPPY/bin/qfy.py", line 129, in quantify
2019-04-16 18:18:36,809 ERROR        strat_fixchr=args.strat_fixchr)
2019-04-16 18:18:36,809 ERROR      File "/home/anusha/miniconda3/envs/HAPPY/lib/python27/Haplo/quantify.py", line 177, in run_quantify
2019-04-16 18:18:36,809 ERROR        subprocess.check_call(run_str, shell=True, stdout=tfo, stderr=tfe)
2019-04-16 18:18:36,809 ERROR      File "/home/anusha/miniconda3/envs/HAPPY/lib/python2.7/subprocess.py", line 186, in check_call
2019-04-16 18:18:36,809 ERROR        raise CalledProcessError(retcode, cmd)
2019-04-16 18:18:36,810 ERROR    CalledProcessError: Command 'quantify /tmp/hap.py.result.Ixh7yg.vcf.gz -o benchmarking-output.roc.tsv -r /data/human_ref/hg38/genome/genome.fa --threads 8 --output-vtc 0 --output-rocs 1 --type ga4gh --qq QUAL --roc-delta 0.500000 --clean-info 1 --fix-chr-regions 0 -v benchmarking-output.vcf.gz -R 'CONF_VARS:/tmp/tmpqXFzwQ.bed' -R 'CONF:/home/anusha/gatk-4.0.4.0/ussd-ftp.illumina.com/2017-1.0/hg38/small_variants/ConfidentRegions.bed.gz' --roc-regions '*'' returned non-zero exit status 1
```

with docker 

```
sudo docker run -it --memory=20g -v pwd:/data pkrusche/hap.py /opt/hap.py/bin/hap.py /data/NA12878.vcf.gz /data/PRO001B.vcf.gz -o /data/test1 -r /data/genome.fa -f /data/ConfidentRegions.bed.gz --no-leftshift --no-decompose --gender=none --engine=vcfeval
[sudo] password for anusha: 
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
2019-04-16 10:27:49,884 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2019-04-16 10:27:49,890 WARNING  No reference file found at default locations. You can set the environment variable 'HGREF' or 'HG19' to point to a suitable Fasta file.
2019-04-16 10:27:50,024 ERROR    FP/confident call region bed file does not exist.
2019-04-16 10:27:50,024 ERROR    Traceback (most recent call last):
2019-04-16 10:27:50,024 ERROR      File "/opt/hap.py/bin/hap.py", line 508, in <module>
2019-04-16 10:27:50,024 ERROR        main()
2019-04-16 10:27:50,024 ERROR      File "/opt/hap.py/bin/hap.py", line 198, in main
2019-04-16 10:27:50,024 ERROR        raise Exception("FP/confident call region bed file does not exist.")
2019-04-16 10:27:50,024 ERROR    Exception: FP/confident call region bed file does not exist.
```

**Comment by dpryan79** [comment]
These look like issues with `hap.py` itself, please report it to its authors.

**Comment by epruesse** [comment]
Sorry @achimmiri - this does look like a problem with hap.py. Perhaps if you open an issue over there, someone can help you: https://github.com/Illumina/hap.py/issues
