### ISSUE TITLE
About Python error.

### ISSUE THREAD

**Issue by sdabral05** [bioconda/bioconda-recipes#15335]
Hi , 
i am using rmats 4.0.2 so far i come to this position that i getting results with statistical values but on terminal it shows error.
Can you explain me this ,why this error is coming and what is the solution for this . Is this error will make effect on my results??

```
> (rmats) harn@harn-Precision-T7600:VL_3.19/rMATS.4.0.2/rMATS-turbo-Linux-UCS4$ rmats.py --b1 b1.txt --b2 b2.txt --gtf VL_3.19/run/Homo_sapiens.GRCh38.96.gtf --od L_3.19/run/rmats/test_3 -t paired --tstat 8 
There are 58884 distinct gene ID in the gtf file
There are 208527 distinct transcript ID in the gtf file
There are 36201 one-transcript genes in the gtf file
There are 1279073 exons in the gtf file
There are 25059 one-exon transcripts in the gtf file
There are 22419 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 3.541319
Average number of exons per transcript is 6.133848
Average number of exons per transcript excluding one-exon tx is 6.835056
Average number of gene per geneGroup is 8.052529

==========
Done processing each gene from dictionary to compile AS events
Found 57340 exon skipping events
Found 5305 exon MX events
Found 15413 alt SS events
There are 9435 alt 3 SS events and 5978 alt 5 SS events.
Found 6410 RI events
==========

Running the statistical part.
**Traceback (most recent call last):
  File "/home/harn/miniconda2/envs/rmats/rMATS/rMATS_P/inclusion_level.py", line 50, in <module>
    psi2=vec2psi(inc2,skp2,effective_inclusion_length,effective_skipping_length);
  File "/home/harn/miniconda2/envs/rmats/rMATS/rMATS_P/inclusion_level.py", line 30, in vec2psi
    psi.append(str(round(float(inc[i])/inclusion_length/(float(inc[i])/inclusion_length+float(skp[i])/skipping_length),3)));
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/home/harn/miniconda2/envs/rmats/rMATS/rMATS_P/inclusion_level.py", line 50, in <module>
    psi2=vec2psi(inc2,skp2,effective_inclusion_length,effective_skipping_length);
  File "/home/harn/miniconda2/envs/rmats/rMATS/rMATS_P/inclusion_level.py", line 30, in vec2psi
    psi.append(str(round(float(inc[i])/inclusion_length/(float(inc[i])/inclusion_length+float(skp[i])/skipping_length),3)));
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/home/harn/miniconda2/envs/rmats/rMATS/rMATS_P/inclusion_level.py", line 50, in <module>
    psi2=vec2psi(inc2,skp2,effective_inclusion_length,effective_skipping_length);
  File "/home/harn/miniconda2/envs/rmats/rMATS/rMATS_P/inclusion_level.py", line 30, in vec2psi
    psi.append(str(round(float(inc[i])/inclusion_length/(float(inc[i])/inclusion_length+float(skp[i])/skipping_length),3)));
ZeroDivisionError: float division by zero**
The statistical part is done.
Done.
```

**Comment by endrebak** [comment]
This is a library-specific issue. Ask the rmats developers instead.
