### ISSUE TITLE
snpEff with custom .genome file?

### ISSUE THREAD

**Issue by Buuntu** [bioconda/bioconda-recipes#15970]
I can't seem to get snpEff to work with a custom .genome file (not available online).  Even when I edit the config file in my miniconda directory to contain `example.genome: example`, it gives me this error when I run `snpEff build -genbank example`:
```
java.lang.RuntimeException: Property: 'example.genome' not found
	at org.snpeff.interval.Genome.<init>(Genome.java:106)
	at org.snpeff.snpEffect.Config.readGenomeConfig(Config.java:681)
	at org.snpeff.snpEffect.Config.readConfig(Config.java:649)
	at org.snpeff.snpEffect.Config.init(Config.java:480)
	at org.snpeff.snpEffect.Config.<init>(Config.java:117)
	at org.snpeff.SnpEff.loadConfig(SnpEff.java:451)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdBuild.run(SnpEffCmdBuild.java:364)
	at org.snpeff.SnpEff.run(SnpEff.java:1183)
	at org.snpeff.SnpEff.main(SnpEff.java:162)
```

I definitely have a genes.gbk, example.genome, and example.gbk file in the directory.  It would be great if I didn't even have to edit the config file, if that were somehow an option?

**Comment by matthdsm** [comment]
Hi,

This seems like a snpEff specific question. Can you repost this in the [proper repository](https://github.com/pcingola/SnpEff)? The issues here are only for bioconda related questions.

Thanks
M
