### ISSUE TITLE
List of packages with broken pinnings that are currently causing issues

### ISSUE THREAD

**Issue by dpryan79** [bioconda/bioconda-recipes#17212]
Please feel free to add to this, as we're trying to assess how wide-spread the issues are to better determine if we need to start patching metadata.

 - [ ] htslib <1.9 lacked pinning to libdeflate
 - [ ] pysam < 0.15 lacked pinning to libdeflate

**Comment by guillaumecharbonnier** [comment]
Pysam < 0.15 is looking for libcrypto.so.1.0.0 from openssl <1.1 whereas it currently gets libcrypto.so.1.1.1 without explicit openssl requirement.

**Comment by dpryan79** [comment]
Another one where pysam pinnings are causing issues: https://github.com/bioconda/bioconda-recipes/pull/17260

**Comment by dpryan79** [comment]
Another: https://github.com/bioconda/bioconda-recipes/pull/17247

**Comment by dpryan79** [comment]
Here's another one: https://github.com/bioconda/bioconda-recipes/pull/11698

**Comment by dpryan79** [comment]
ariba is getting broken because of this now too :(

**Comment by rpetit3** [comment]
This should be fixed with Ariba and its dependents, now.

After adding the pysam pinnings to Bactopia and Seroba, the latest build of Ariba (bioconda/linux-64::ariba-2.14.3-py36he1b5a44_1) is selected and working.

**Comment by bernt-matthias** [comment]
Maybe another one: https://github.com/bioconda/bioconda-recipes/issues/24264? Was there a solution for the libcrypto problem? I guess in my case its samtools itself and not pysam?

**Comment by rpetit3** [comment]
Looks like checkm-genome is affected by pysam pinning. After bumping pysam version the issue is gone.

```
(base) rpetit@staphopia:~$ conda create -n checkm -c conda-forge -c bioconda checkm-genome
(base) rpetit@staphopia:~$ conda activate checkm
(checkm) rpetit@staphopia:~$ checkm data setRoot /local/home/rpetit/miniconda3/envs/checkm/checkm_data
Traceback (most recent call last):
  File "/local/home/rpetit/miniconda3/envs/checkm/bin/checkm", line 36, in <module>
    from checkm import main
  File "/local/home/rpetit/miniconda3/envs/checkm/lib/python3.6/site-packages/checkm/main.py", line 28, in <module>
    from checkm.resultsParser import ResultsParser
  File "/local/home/rpetit/miniconda3/envs/checkm/lib/python3.6/site-packages/checkm/resultsParser.py", line 34, in <module>
    from checkm.coverage import Coverage
  File "/local/home/rpetit/miniconda3/envs/checkm/lib/python3.6/site-packages/checkm/coverage.py", line 30, in <module>
    import pysam
  File "/local/home/rpetit/miniconda3/envs/checkm/lib/python3.6/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
(checkm) rpetit@staphopia:~$ conda env export | grep "pysam"
  - pysam=0.14.1=py36hae42fb6_1
(checkm) rpetit@staphopia:~$ conda update -y -c conda-forge -c bioconda pysam
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.9.2

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /local/home/rpetit/miniconda3/envs/checkm

  added / updated specs:
    - pysam


The following packages will be REMOVED:

  bcftools-1.8-h4da6232_3
  htslib-1.7-0
  libgcc-7.2.0-h69d50b8_2
  samtools-1.7-1

The following packages will be UPDATED:

  pysam                               0.14.1-py36hae42fb6_1 --> 0.15.3-py36hda2845c_1

The following packages will be SUPERSEDED by a higher-priority channel:

  libdeflate         conda-forge::libdeflate-1.7-h36c2ea0_0 --> bioconda::libdeflate-1.0-h14c3975_1


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(checkm) rpetit@staphopia:~$ checkm data setRoot /local/home/rpetit/miniconda3/envs/checkm/checkm_data
[2020-12-17 16:25:35] INFO: CheckM v1.1.3
[2020-12-17 16:25:35] INFO: checkm data setRoot /local/home/rpetit/miniconda3/envs/checkm/checkm_data
[2020-12-17 16:25:35] INFO: [CheckM - data] Check for database updates. [setRoot]

Path [/local/home/rpetit/miniconda3/envs/checkm/checkm_data] exists and you have permission to write to this folder.
(re) creating manifest file (please be patient).

Path [/local/home/rpetit/miniconda3/envs/checkm/checkm_data] exists and you have permission to write to this folder.
(re) creating manifest file (please be patient).

**Comment by jmarshall** [comment]
Conda-forge updated its libdeflate to 1.7 on November 12th, a few days after e.g. htslib-1.11_hxyz_1 had been built using the then-current libdeflate-1.6. Plain `conda create -n tmp samtools` etc selected the expected htslib-1.11 / samtools-1.11 for that few days, but returned to giving outdated older versions on Nov 12th — presumably as the newly-released libdeflate-1.7 pushed the 1.6 builds out of Conda-forge's _current_repodata.json_. This is the current cause of #25567 for htslib/samtools/bcftools. (Me, I know how to work around this by forcing the use of _repodata.json_ instead. I have a different question…)

What is the current Bioconda pinning policy for libdeflate? I notice that [wiggletools-1.2.7](https://anaconda.org/bioconda/wiggletools/files) was built a couple of days ago (while libdeflate-1.7 has been the current latest version available in conda-forge) and has been built to use libdeflate-1.6.

Thus it appears that libdeflate is currently pinned to 1.6. Is this right? And if so, where is it specified?
I couldn't see any trace of libdeflate in [conda-forge-pinning](https://github.com/conda-forge/conda-forge-pinning-feedstock)'s _conda_build_config.yaml_ or in _bioconda_utils-conda_build_config.yaml_.

**Comment by mbhall88** [comment]
I guess it is probably expected given the htslib problem mentioned in the original comment, but I am also getting this problem with bcftools. I get version 1.9 when not specifying a version pin.

**Comment by jmarshall** [comment]
Yes, once the problem is resolved for htslib (coming soon) it will automatically resolve itself for samtools and bcftools as well.

Thanks to hints from @dpryan79, I now understand what's going on with wiggletools and the like: because wiggletools build-depends on htslib, while building it the pinned htslib build is pulled in which at present pulls in libdeflate-1.6. So libdeflate is not officially pinned for Bioconda, but this explains why it looks like it is for packages that depend on both htslib and libdeflate (which they shouldn't).

Libdeflate was pinned in the distant past, but this was removed in bioconda/bioconda-utils#610. That PR and commit don't explain why the pinning was removed — but I suspect it's because, of 16 bioconda packages that list libdeflate as a dependency, only a couple (htslib, staden_io_lib, possibly one or two others) actually ought to depend directly on libdeflate. So it's not pinned because it doesn't really need to be.
