### ISSUE TITLE
taxtastic package missed some dependancies

### ISSUE THREAD

**Issue by blinard-BIOINFO** [bioconda/bioconda-recipes#17346]
### Briefly:

**Package "taxtastic":** Current recipe installs the package without errors but running the software throws errors related to missing python modules.

**System**: ubuntu 18.04, linux 64 bits.

**Solution found**: 2 modules are in conda cloud and should be added to the recipe but 2 python libraries have to be installed via pip.
Does it make sense to install those via pip in the recipe or should the sqlalchemy dependency be reworked at conda level ?

### Details:

Conda installation: 
```
$ conda install taxtastic

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /auto/linard/miniconda3

  added / updated specs:
    - taxtastic


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.17.2               |   py37h95a1406_0         5.2 MB  conda-forge
    sqlalchemy-1.3.8           |   py37h516909a_0         1.7 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         7.0 MB

The following NEW packages will be INSTALLED:

  biopython          conda-forge/linux-64::biopython-1.74-py37h516909a_0
  decorator          conda-forge/noarch::decorator-4.4.0-py_0
  libblas            conda-forge/linux-64::libblas-3.8.0-12_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-12_openblas
  liblapack          conda-forge/linux-64::liblapack-3.8.0-12_openblas
  libopenblas        conda-forge/linux-64::libopenblas-0.3.7-h6e990d7_1
  numpy              conda-forge/linux-64::numpy-1.17.2-py37h95a1406_0
  sqlalchemy         conda-forge/linux-64::sqlalchemy-1.3.8-py37h516909a_0
  taxtastic          bioconda/noarch::taxtastic-0.8.11-py_0
  xlrd               conda-forge/noarch::xlrd-1.2.0-py_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
sqlalchemy-1.3.8     | 1.7 MB    | ############################################################################################################################################ | 100% 
numpy-1.17.2         | 5.2 MB    | ############################################################################################################################################ | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```
Trying to run the command and error throw:
```
$ taxit

Traceback (most recent call last):
  File "/auto/linard/miniconda3/bin/taxit", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/auto/linard/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/auto/linard/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/auto/linard/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/auto/linard/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/auto/linard/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/auto/linard/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The '**psycopg2-binary>=2.7.3.1**' distribution was not found and is required by taxtastic
```
In fact, psycopg2-binary is part of a pip package which is not included in the postgress packages available in conda. It seems some package merging in psycopg library resulted to many issues in software depending on it some time ago ..
But it is not the only dependency that is missing, it seems fastalite too is not available in conda ?

Anyway, a solution is to manually install the following pip packages and missing conda dependancies:

```
$ pip install psycopg2-binary          (not in conda cloud)
$ pip install fastalite                        (not in conda cloud)
$ conda install PyYAML                  (not in the recipe)
$ conda install jinja2                       (not in the recipe)
```
Then it works as intended :
```
$ taxit create
usage: taxit create [-h] [-c] -P PATH [-a NAME] [-d TEXT] -l LOCUS
                    [-r VERSION] [-f FILE] [-i file] [-m FILE] [-p FILE]
                    [-R FILE] [-s FILE] [-S FILE] [-t FILE] [-T FILE]
                    [--stats-type {PhyML,FastTree,RAxML}]
                    [--frequency-type {empirical,model}] [--no-reroot]
                    [--rppr RPPR]
taxit create: error: the following arguments are required: -P/--package-name, -l/--locus
```

**Comment by bgruening** [comment]
@blinard-BIOINFO can you add those deps to the recipe? `fastalite` could be a new package.

> Does it make sense to install those via pip in the recipe or should the sqlalchemy dependencies to psycopg2 be reworked at a higher level ?

reworked :)

**Comment by druvus** [comment]
Adding fastalite in PR #17829
