### ISSUE TITLE
Broken anndata recipe

### ISSUE THREAD

**Issue by astrovsky01** [bioconda/bioconda-recipes#18176]
The current anndata build does not resolve all dependencies. When importing in python inside a test environment, it gives the error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alexanderostrovsky/anaconda3/envs/my_env_name/lib/python3.6/site-packages/anndata/__init__.py", line 1, in <module>
    from .base import AnnData
  File "/Users/alexanderostrovsky/anaconda3/envs/my_env_name/lib/python3.6/site-packages/anndata/base.py", line 21, in <module>
    from scipy.sparse.sputils import IndexMixin
ImportError: cannot import name 'IndexMixin'
```

Environment creation included the following packages:
```anndata=0.6.19 scanpy=1.4 loompy=2.0.17```

**Comment by flying-sheep** [comment]
Well, anndata is in conda-forge, so IDK why it needs to be here too …

**Comment by astrovsky01** [comment]
My bad
