### ISSUE TITLE
Remote not found error

### ISSUE THREAD

**Issue by Midnighter** [bioconda/bioconda-recipes#19462]
I'm on a Ubuntu system and I have circleci and docker installed from snap. Until two days ago I was able to test my new recipe locally following the description at https://bioconda.github.io/contributor/building-locally.html#using-the-circle-ci-client

Since yesterday, when I run `circleci build`, I get the following error:

```
11:00:09 BIOCONDA DEBUG get_recipes(recipes, package='['*']'): *
11:00:09 BIOCONDA INFO Considering total of 6947 recipes.
11:00:09 GIT DEBUG Popen(['git', 'remote', 'get-url', '--all', 'origin'], cwd=/root/project, universal_newlines=False, shell=None, istream=None)
11:00:09 BIOCONDA ERROR Dropping into debugger
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 71, in wrapper
    func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 345, in do_lint
    recipes = get_recipes(config, recipe_folder, packages, git_range)
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 168, in get_recipes
    changed_recipes = get_recipes_to_build(git_range, recipe_folder)
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 151, in get_recipes_to_build
    repo = BiocondaRepo(recipe_folder)
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/githandler.py", line 503, in __init__
    super().__init__(repo, dry_run, home, fork, allow_dirty)
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/githandler.py", line 83, in __init__
    self.home_remote = self.get_remote(home)
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/githandler.py", line 143, in get_remote
    raise KeyError(f"No remote matching '{desc}' found")
KeyError: "No remote matching 'bioconda/bioconda-recipes' found"
Traceback (most recent call last):
  File "/opt/conda/bin/bioconda-utils", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 947, in main
    bioconductor_skeleton, clean_cran_skeleton, autobump, bot
  File "/opt/conda/lib/python3.7/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/opt/conda/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/opt/conda/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "<boltons.funcutils.FunctionBuilder-3>", line 8, in do_lint
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 130, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-2>", line 8, in do_lint
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 59, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-1>", line 8, in do_lint
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 71, in wrapper
    func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 345, in do_lint
    recipes = get_recipes(config, recipe_folder, packages, git_range)
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 168, in get_recipes
    changed_recipes = get_recipes_to_build(git_range, recipe_folder)
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 151, in get_recipes_to_build
    repo = BiocondaRepo(recipe_folder)
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/githandler.py", line 503, in __init__
    super().__init__(repo, dry_run, home, fork, allow_dirty)
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/githandler.py", line 83, in __init__
    self.home_remote = self.get_remote(home)
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/githandler.py", line 143, in get_remote
    raise KeyError(f"No remote matching '{desc}' found")
KeyError: "No remote matching 'bioconda/bioconda-recipes' found"
```

I do have a working internet connection but maybe something got messed up in the docker setup?

**Comment by Midnighter** [comment]
I'm not sure what changed. I merged the latest master state into my local branches and suddenly things work again.

**Comment by Juke34** [comment]
I'm on OSX and I have the same error. I never succeeded to make it work. 
```
jacda119@IMB-02Z82USLVDL:bioconda-recipes $ circleci build
Docker image digest: sha256:977842e3959c019b4acb1d88470e58b8e55daa106df7ace3f1df4aa3603fb554
====>> Spin up Environment
Build-agent version 1.0.19967-a88e0eef (2019-11-19T21:38:28+0000)
Docker Engine Version: 19.03.5
Kernel Version: Linux 5d31d8dd27d8 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 Linux
Starting container bioconda/bioconda-utils-build-env
  using image bioconda/bioconda-utils-build-env@sha256:c85477c6f41096267f50b42dad6f9eeec5064fdacbd77303c658856d1c0f3d56

Using build environment variables
  BASH_ENV=/tmp/.bash_env-localbuild-1579292064
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=repeatmodeler
  CIRCLE_BUILD_NUM=
  CIRCLE_JOB=build
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_REPOSITORY_URL=https://github.com/Juke34/bioconda-recipes.git
  CIRCLE_SHA1=9c1826f13f8fa089e4d23247a42f96032f8a098d
  CIRCLE_SHELL_ENV=/tmp/.bash_env-localbuild-1579292064
  CIRCLE_WORKING_DIRECTORY=~/project


The redacted variables listed above will be masked in run step output

====>> Checkout code
  #!/bin/bash -eo pipefail
mkdir -p /root/project && cd /tmp/_circleci_local_build_repo && git ls-files | tar -T - -c | tar -x -C /root/project && cp -a /tmp/_circleci_local_build_repo/.git /root/project
====>> Setup ssh
  #!/bin/bash -eo pipefail
mkdir -p ~/.ssh
ssh-keyscan -H github.com >> ~/.ssh/known_hosts

# github.com SSH-2.0-babeld-3e94cba4
====>> echo ". /opt/conda/etc/profile.d/conda.sh" >> $BASH_ENV
  #!/bin/bash -eo pipefail
echo ". /opt/conda/etc/profile.d/conda.sh" >> $BASH_ENV
====>> echo "conda activate" >> $BASH_ENV
  #!/bin/bash -eo pipefail
echo "conda activate" >> $BASH_ENV
====>> Download common definitions
  #!/bin/bash -eo pipefail
curl -s https://raw.githubusercontent.com/bioconda/bioconda-common/master/common.sh > .circleci/common.sh

====>> Setup bioconda-utils
  #!/bin/bash -eo pipefail
.circleci/setup.sh
remote: Enumerating objects: 4, done.        
remote: Counting objects: 100% (4/4), done.        
remote: Compressing objects: 100% (4/4), done.        
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0        
Unpacking objects: 100% (4/4), done.
From https://github.com/bioconda/bioconda-recipes
 * [new branch]          master     -> __upstream__2av6olUFYF/master
bioconda-utils is /opt/conda/bin/bioconda-utils
====>> Linting
  #!/bin/bash -eo pipefail
bioconda-utils lint recipes config.yml \
--loglevel debug --full-report \
--git-range master HEAD

20:15:01 BIOCONDA DEBUG get_recipes(recipes, package='['*']'): *
20:15:02 BIOCONDA INFO Considering total of 6993 recipes.
20:15:02 GIT DEBUG Popen(['git', 'remote', 'get-url', '--all', 'origin'], cwd=/root/project, universal_newlines=False, shell=None, istream=None)
20:15:02 BIOCONDA ERROR Dropping into debugger
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 71, in wrapper
    func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 345, in do_lint
    recipes = get_recipes(config, recipe_folder, packages, git_range)
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 168, in get_recipes
    changed_recipes = get_recipes_to_build(git_range, recipe_folder)
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 151, in get_recipes_to_build
    repo = BiocondaRepo(recipe_folder)
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/githandler.py", line 503, in __init__
    super().__init__(repo, dry_run, home, fork, allow_dirty)
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/githandler.py", line 83, in __init__
    self.home_remote = self.get_remote(home)
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/githandler.py", line 143, in get_remote
    raise KeyError(f"No remote matching '{desc}' found")
KeyError: "No remote matching 'bioconda/bioconda-recipes' found"
Traceback (most recent call last):
  File "/opt/conda/bin/bioconda-utils", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 947, in main
    bioconductor_skeleton, clean_cran_skeleton, autobump, bot
  File "/opt/conda/lib/python3.7/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/opt/conda/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/opt/conda/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "<boltons.funcutils.FunctionBuilder-3>", line 8, in do_lint
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 130, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-2>", line 8, in do_lint
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 59, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-1>", line 8, in do_lint
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 71, in wrapper
    func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 345, in do_lint
    recipes = get_recipes(config, recipe_folder, packages, git_range)
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 168, in get_recipes
    changed_recipes = get_recipes_to_build(git_range, recipe_folder)
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 151, in get_recipes_to_build
    repo = BiocondaRepo(recipe_folder)
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/githandler.py", line 503, in __init__
    super().__init__(repo, dry_run, home, fork, allow_dirty)
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/githandler.py", line 83, in __init__
    self.home_remote = self.get_remote(home)
  File "/opt/conda/lib/python3.7/site-packages/bioconda_utils/githandler.py", line 143, in get_remote
    raise KeyError(f"No remote matching '{desc}' found")
KeyError: "No remote matching 'bioconda/bioconda-recipes' found"
Error: Exited with code 1
Step failed
Error: runner failed (exited with 101)
Task failed
Error: task failed
```

Any idea was could be wrong?

**Comment by Juke34** [comment]
My local repo was linked to my fork of bioconda-recipes, changing it by the original repo fixed it for me:
`git remote set-url origin https://github.com/bioconda/bioconda-recipes.git`

**Comment by Midnighter** [comment]
This should be added to the [contribution guidelines](https://bioconda.github.io/contributor/setup.html) since the documentation suggests the normal upstream remote name but then the script assumes origin to be that.
