### ISSUE TITLE
Build of rapidnj fails with "make g++: Command not found"

### ISSUE THREAD

**Issue by wholtz** [bioconda/bioconda-recipes#19479]
A log snippet from the CI pipeline:

```
21:17:01 BIOCONDA INFO (OUT) INFO: activate-gxx_linux-64.sh made the following environmental changes:
21:17:01 BIOCONDA INFO (OUT) +CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/rapidnj-2.3.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
21:17:01 BIOCONDA INFO (OUT) +CXX=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-c++
21:17:01 BIOCONDA INFO (OUT) +DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/rapidnj-2.3.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
21:17:01 BIOCONDA INFO (OUT) +GXX=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-g++
21:17:01 BIOCONDA INFO (OUT) g++ -Wall   -O3 -msse2 -Isrc/distanceCalculation -Isrc/ -c -oobj/main.o src/main.cpp
21:17:01 BIOCONDA INFO (OUT) make: g++: Command not found
21:17:01 BIOCONDA INFO (OUT) make: *** [obj/main.o] Error 127 
21:17:03 BIOCONDA INFO (OUT) Traceback (most recent call last):
21:17:03 BIOCONDA INFO (OUT)   File "/opt/conda/bin/conda-build", line 11, in <module>
21:17:03 BIOCONDA INFO (OUT)     sys.exit(main())
21:17:03 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 445, in main
21:17:03 BIOCONDA INFO (OUT)     execute(sys.argv[1:])
21:17:03 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 436, in execute
21:17:03 BIOCONDA INFO (OUT)     verify=args.verify, variants=args.variants)
21:17:03 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
21:17:03 BIOCONDA INFO (OUT)     notest=notest, need_source_download=need_source_download, variants=variants)
21:17:03 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2343, in build_tree
21:17:03 BIOCONDA INFO (OUT)     notest=notest,
21:17:03 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1491, in build
21:17:03 BIOCONDA INFO (OUT)     cwd=src_dir, stats=build_stats)
21:17:03 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 397, in check_call_env
21:17:03 BIOCONDA INFO (OUT)     return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
21:17:03 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 377, in _func_defaulting_env_to_os_environ
21:17:03 BIOCONDA INFO (OUT)     raise subprocess.CalledProcessError(proc.returncode, _args)
21:17:03 BIOCONDA INFO (OUT) subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/opt/conda/conda-bld/rapidnj_1577222150619/work/conda_build.sh']' returned non-zero exit status 2.  
21:17:05 BIOCONDA ERROR COMMAND FAILED (exited with 1): docker run -t --net host --rm -v /tmp/tmp6pc5jmbp/build_script.bash:/opt/build_script.bash -v /home/circleci/project/miniconda/conda-bld/:/opt/host-conda-bld -v /home/circleci/project/recipes/rapidnj:/opt/recipe -e LANG=en_US.UTF-8 -e HOST_USER_ID=1001 bioconda/bioconda-utils-build-env:latest /bin/bash /opt/build_script.bash  
21:17:05 BIOCONDA ERROR BUILD FAILED recipes/rapidnj    
```

**Comment by suhrig** [comment]
I'm having the same issue with the auto-generated pull request #19539, although the `meta.yaml` file specifies `compiler('cxx')`. Let me know when you find a solution. Thanks.

**Comment by dpryan79** [comment]
@suhrig It's a matter of injecting compilers. I've updated the PR.
