### ISSUE TITLE
Docker tests: `conda-build: error: the following arguments are required: RECIPE_PATH`

### ISSUE THREAD

**Issue by endrebak** [bioconda/bioconda-recipes#2109]
I am trying to run the docker tests on OS X, but they fail with `conda-build: error: the following arguments are required: RECIPE_PATH`.

I ran this command:

```bash
docker run -v /Users/labsenter/havpryd/code/bioconda-recipes:/bioconda-recipes \
 bioconda/bioconda-builder --packages bioepic --env-matrix /bioconda-recipes/scripts/env_matrix.yml
```

Is it okay if I add my software packages without running the docker tests? It won't break any builds as no-one is using them yet. And it seems like if I try to test another, already included, package, I get the same error messages. 

This is the full log of messages:

```bash
labsenter@ans-180249 ~/h/c/bioconda-recipes> docker run -v (pwd):/bioconda-recipes bioconda/bioconda-builder --packages bioepic --env-matrix /bioconda-recipes/scripts/env_matrix.yml
Collecting git+https://github.com/conda/conda-build.git@1.20.3
  Cloning https://github.com/conda/conda-build.git (to 1.20.3) to /tmp/pip-_otgvhsk-build
  Requirement already satisfied (use --upgrade to upgrade): conda-build==1.20.3 from git+https://github.com/conda/conda-build.git@1.20.3 in /anaconda/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): conda in /anaconda/lib/python3.5/site-packages (from conda-build==1.20.3)
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ldd (GNU libc) 2.5
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
usage: conda-build [-h] [-V] [-n] [--output] [--python PYTHON_VER]
                   [--perl PERL_VER] [--numpy NUMPY_VER] [--R R_VER]
                   [--lua LUA_VER] [--check] [--no-anaconda-upload]
                   [--no-include-recipe] [-s] [-t] [--no-test] [-b] [-p]
                   [--skip-existing] [--keep-old-work] [-q] [--token TOKEN]
                   [--user USER] [-c CHANNEL] [--override-channels]
                   RECIPE_PATH [RECIPE_PATH ...]
conda-build: error: the following arguments are required: RECIPE_PATH

E
======================================================================
ERROR: Failure: SystemExit (1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/anaconda/lib/python3.5/site-packages/nose/loader.py", line 252, in generate
    for test in g():
  File "/bioconda-recipes/scripts/build-packages.py", line 144, in test_recipes
    recipes = list(filter_recipes(recipes, env_matrix))
  File "/bioconda-recipes/scripts/build-packages.py", line 125, in filter_recipes
    exit(1)
  File "/anaconda/lib/python3.5/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1

----------------------------------------------------------------------
Ran 1 test in 0.504s

FAILED (errors=1)
```

**Comment by endrebak** [comment]
Added #2111

**Comment by daler** [comment]
Does it work if you add a `$` in front of `(pwd)`?

**Comment by endrebak** [comment]
Thanks for your reply.

I am using the fish shell, so `$` does not work :) 

I should have explained that I also tried this command in bash. My bad. I am using stable docker for OS X. 

The bash command I tried:

```
bash-3.2$ pwd
/Users/labsenter/havpryd/code/bioconda-recipes
bash-3.2$ docker run -v `pwd`:/bioconda-recipes bioconda/bioconda-builder --packages your_package --env-matrix /bioconda-recipes/scripts/env_matrix.yml
```

**Comment by WenzhengC** [comment]
i have the same Problem, did you solve the Problem already?
