### ISSUE TITLE
umi_tools not working after conda update

### ISSUE THREAD

**Issue by matthdsm** [bioconda/bioconda-recipes#2150]
Hi,

recently I've submitted the `umi_tools` recipe to bioconda. Everything seemed to work fine up until I updated conda to the latest version. When I try to run the tools I get the following error

```
Traceback (most recent call last):
  File "/Users/matdsmet/miniconda2/bin/umi_tools", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Users/matdsmet/miniconda2/lib/python2.7/site-packages/setuptools-25.1.6-py2.7.egg/pkg_resources/__init__.py", line 2953, in <module>
  File "/Users/matdsmet/miniconda2/lib/python2.7/site-packages/setuptools-25.1.6-py2.7.egg/pkg_resources/__init__.py", line 2939, in _call_aside
  File "/Users/matdsmet/miniconda2/lib/python2.7/site-packages/setuptools-25.1.6-py2.7.egg/pkg_resources/__init__.py", line 2966, in _initialize_master_working_set
  File "/Users/matdsmet/miniconda2/lib/python2.7/site-packages/setuptools-25.1.6-py2.7.egg/pkg_resources/__init__.py", line 635, in _build_master
  File "/Users/matdsmet/miniconda2/lib/python2.7/site-packages/setuptools-25.1.6-py2.7.egg/pkg_resources/__init__.py", line 943, in require
  File "/Users/matdsmet/miniconda2/lib/python2.7/site-packages/setuptools-25.1.6-py2.7.egg/pkg_resources/__init__.py", line 829, in resolve
pkg_resources.DistributionNotFound: The 'umi-tools==0.2.3' distribution was not found and is required by the application
```
I already tried to `force install` the recipe and conda to resolve any issues.
Anyone have an idea what could be causing this?

`conda list`output:

```
# packages in environment at /Users/matdsmet/miniconda2:
#
bcftools                  1.3.1                         0    bioconda
curl                      7.45.0                        1    bioconda
htslib                    1.3.1                         0    bioconda
pysam                     0.9.1                    py27_0    bioconda
python-dateutil           2.3                      py27_0    bioconda
samtools                  1.3.1                         2    bioconda
umi_tools                 0.2.3                         1    bioconda
conda                     4.1.11                   py27_0  
conda-env                 2.5.2                    py27_0  
cython                    0.24.1                   py27_0  
future                    0.15.2                   py27_0  
mkl                       11.3.3                        0  
numpy                     1.11.1                   py27_0  
openssl                   1.0.2h                        1  
pandas                    0.18.1              np111py27_0  
pip                       8.1.2                    py27_0  
pycosat                   0.6.1                    py27_1  
pycrypto                  2.6.1                    py27_4  
python                    2.7.12                        1  
pytz                      2016.6.1                 py27_0  
pyyaml                    3.11                     py27_4  
libgcc                    4.8.5                         1    r
ncurses                   5.9                           8    r
zlib                      1.2.8                         1    r
readline                  6.2                           2  
requests                  2.10.0                   py27_0  
ruamel_yaml               0.11.14                  py27_0  
setuptools                25.1.6                   py27_0  
six                       1.10.0                   py27_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py27_0  
yaml                      0.1.6                         0  
```

**Comment by bgruening** [comment]
@matthdsm I can not reproduce this error. For me it's installing fine. Please make sure you have `-c bioconda` specified and that you wrote `umi_tools` and not `umi-tools`, like in your error message: ``The 'umi-tools==0.2.3' distribution

**Comment by matthdsm** [comment]
Hi Björn, 
Yeah, installing is not an issue, and the test seems to work, I only get the error message when I actually try to run the program. I've tried it in our default conda env, in a clean vagrant box and on a OSX system, all with the same result. It's weird. I also had an older conda installed on a different location, en there it seemed to work properly.

**Comment by bgruening** [comment]
This is strange! Works for me. Which conda version are you using?
```
bag@bag ~/projects/code/docker/docker-galaxy-stable
 % umi_tools --help

umi_tools.py - Tools for UMI analyses
===============================================

:Author: Tom Smith & Ian Sudbury, CGAT
:Release: $Id$
:Date: |today|
:Tags: Genomics UMI

There are two tools: extract & dedup

To get help on a specific tool, type:

    umi_tools <tool> --help

To use a specific tool, type::

    umi_tools <tool> [tool options] [tool arguments]


```

**Comment by matthdsm** [comment]
Currently we're on conda 4.1.11, which is the latest version I presume. I think the last version it worked on was 4.0.5, but that was actually by accident, as that was a forgotten conda installation which took precedence in `$PATH`

It's a bummer I can't get it to work, I'd like to test my galaxy wrapper

**Comment by bgruening** [comment]
@matthdsm how do you run these tools. I can not reproduce.

**Comment by matthdsm** [comment]
what exactly do you mean by "how do you run these tools"?
I install the recipe using `conda install -c bioconda umi_tools`, after which I just call the executable with the `umi_tools --help`command.

output:
```
[galaxy] matdsmet:~ $ umi_tools --help                                                                                                              [8:39:58]
Traceback (most recent call last):
  File "/Shared/Software/bin/umi_tools", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Shared/Software/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py", line 2927, in <module>
  File "/Shared/Software/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py", line 2913, in _call_aside
  File "/Shared/Software/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
  File "/Shared/Software/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py", line 635, in _build_master
  File "/Shared/Software/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py", line 943, in require
  File "/Shared/Software/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py", line 829, in resolve
pkg_resources.DistributionNotFound: The 'umi-tools==0.2.3' distribution was not found and is required by the application
```

**Comment by Frank1219** [comment]
I met the same problem. I have never saw a practical method to solve it, who can tell me ? thanks so much~
