### ISSUE TITLE
Directory '.' is not installable.

### ISSUE THREAD

**Issue by iquasere** [bioconda/bioconda-recipes#22056]
Greetings!

I am trying to commit my first tool to Bioconda, but have bumped into a problem. I have already made a [pull request](https://github.com/bioconda/bioconda-recipes/pull/22022), but it failed what I think are the installation checks to Linux and MacOS. When I try to validate the installation locally with ```bioconda-utils build --docker --mulled-test --git-range master```, I get
```
09:23:10 BIOCONDA INFO (OUT) ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
09:23:10 BIOCONDA INFO (OUT) Exception information:
09:23:10 BIOCONDA INFO (OUT) Traceback (most recent call last):
09:23:10 BIOCONDA INFO (OUT)   File "$PREFIX/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
09:23:10 BIOCONDA INFO (OUT)     status = self.run(options, args)
09:23:10 BIOCONDA INFO (OUT)   File "$PREFIX/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
09:23:10 BIOCONDA INFO (OUT)     return func(self, options, args)
09:23:10 BIOCONDA INFO (OUT)   File "$PREFIX/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 302, in run
09:23:10 BIOCONDA INFO (OUT)     check_supported_wheels=not options.target_dir,
09:23:10 BIOCONDA INFO (OUT)   File "$PREFIX/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 323, in get_requirements
09:23:10 BIOCONDA INFO (OUT)     use_pep517=options.use_pep517,
09:23:10 BIOCONDA INFO (OUT)   File "$PREFIX/lib/python3.6/site-packages/pip/_internal/req/constructors.py", line 396, in install_req_from_line
09:23:10 BIOCONDA INFO (OUT)     parts = parse_req_from_line(name, line_source)
09:23:10 BIOCONDA INFO (OUT)   File "$PREFIX/lib/python3.6/site-packages/pip/_internal/req/constructors.py", line 325, in parse_req_from_line
09:23:10 BIOCONDA INFO (OUT)     url = _get_url_from_path(p, name)
09:23:10 BIOCONDA INFO (OUT)   File "$PREFIX/lib/python3.6/site-packages/pip/_internal/req/constructors.py", line 281, in _get_url_from_path
09:23:10 BIOCONDA INFO (OUT)     "nor 'pyproject.toml' found.".format(**locals())
09:23:10 BIOCONDA INFO (OUT) pip._internal.exceptions.InstallationError: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
09:23:10 BIOCONDA INFO (OUT) Removed build tracker: '/tmp/pip-req-tracker-r3495pw7'
09:23:11 BIOCONDA INFO (OUT) Traceback (most recent call last):
09:23:11 BIOCONDA INFO (OUT)   File "/opt/conda/bin/conda-build", line 11, in <module>
09:23:11 BIOCONDA INFO (OUT)     sys.exit(main())
09:23:11 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 474, in main
09:23:11 BIOCONDA INFO (OUT)     execute(sys.argv[1:])
09:23:11 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 465, in execute
09:23:11 BIOCONDA INFO (OUT)     verify=args.verify, variants=args.variants)
09:23:11 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
09:23:11 BIOCONDA INFO (OUT)     notest=notest, need_source_download=need_source_download, variants=variants)
09:23:11 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2864, in build_tree
09:23:11 BIOCONDA INFO (OUT)     notest=notest,
09:23:11 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1995, in build
09:23:11 BIOCONDA INFO (OUT)     cwd=src_dir, stats=build_stats)
09:23:11 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 404, in check_call_env
09:23:11 BIOCONDA INFO (OUT)     return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
09:23:11 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 384, in _func_defaulting_env_to_os_environ
09:23:11 BIOCONDA INFO (OUT)     raise subprocess.CalledProcessError(proc.returncode, _args)
09:23:11 BIOCONDA INFO (OUT) subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/recognizer_1589188745727/work/conda_build.sh']' returned non-zero exit status 1.
09:23:15 BIOCONDA ERROR COMMAND FAILED (exited with 1): docker run -t --net host --rm -v /tmp/tmpagx3k475/build_script.bash:/opt/build_script.bash -v /tmp/miniconda/miniconda/conda-bld/:/opt/host-conda-bld -v /mnt/HDDStorage/jsequeira/conda_recognizer/bioconda-recipes/recipes/recognizer:/opt/recipe -e LANG=en_US.UTF-8 -e HOST_USER_ID=1000 bioconda/bioconda-utils-build-env:latest /bin/bash /opt/build_script.bash
```
The long version
```
09:15:04 BIOCONDA INFO Considering total of 7210 recipes.
09:15:04 BIOCONDA INFO Constraining to 1 git modified recipes (ognizer).
09:15:05 BIOCONDA INFO Processing 1 recipes (ognizer).
09:15:05 BIOCONDA INFO Generating DAG
Loading Recipes: 100%|███████████████████████████████| 1/1 [00:00<00:00, 46.18it/s]09:15:05 BIOCONDA INFO 1 recipes to build and test:
recognizer
09:15:05 BIOCONDA INFO Determining expected packages for recipes/recognizer
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
09:15:05 CONDA_BUILD WARNING Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
09:15:05 CONDA_BUILD WARNING No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
09:15:05 CONDA_BUILD INFO Adding in variants from internal_defaults
Adding in variants from /tmp/miniconda/miniconda/conda_build_config.yaml
09:15:05 CONDA_BUILD INFO Adding in variants from /tmp/miniconda/miniconda/conda_build_config.yaml
Adding in variants from /tmp/miniconda/miniconda/lib/python3.7/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
09:15:05 CONDA_BUILD INFO Adding in variants from /tmp/miniconda/miniconda/lib/python3.7/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
defaults/noarch: 1.45MB [00:00, 15.3MB/s]                 | 0/9 [00:00<?, ?files/s]
bioconda/linux: 17.1MB [00:00, 18.1MB/s]          | 1/9 [00:00<00:02,  3.36files/s]
defaults/osx: 17.8MB [00:01, 9.96MB/s]            | 2/9 [00:01<00:05,  1.40files/s]
defaults/linux: 19.7MB [00:02, 8.15MB/s]          | 3/9 [00:02<00:04,  1.44files/s]
conda-forge/noarch: 16.7MB [00:02, 5.85MB/s]      | 4/9 [00:03<00:03,  1.46files/s]
bioconda/osx: 14.3MB [00:01, 8.85MB/s]            | 5/9 [00:04<00:02,  1.35files/s]
bioconda/noarch: 10.1MB [00:00, 13.9MB/s]         | 6/9 [00:04<00:02,  1.33files/s]
conda-forge/linux: 65.2MB [00:05, 12.5MB/s]       | 7/9 [00:05<00:01,  1.43files/s]
conda-forge/osx: 62.9MB [00:03, 20.1MB/s]█████▍   | 8/9 [00:09<00:01,  1.74s/files]
Downloading: 100%|████████████████████████████████| 9/9 [02:17<00:00, 15.26s/files]
Attempting to finalize metadata for recognizer
09:17:24 CONDA_BUILD INFO Attempting to finalize metadata for recognizer
Collecting package metadata: ...working... done
Solving environment: ...working... done
Collecting package metadata: ...working... done
Solving environment: ...working... done
09:19:02 BIOCONDA INFO BUILD START recipes/recognizer
09:19:03 BIOCONDA INFO (COMMAND) docker run -t --net host --rm -v /tmp/tmpagx3k475/build_script.bash:/opt/build_script.bash -v /tmp/miniconda/miniconda/conda-bld/:/opt/host-conda-bld -v /mnt/HDDStorage/jsequeira/conda_recognizer/bioconda-recipes/recipes/recognizer:/opt/recipe -e LANG=en_US.UTF-8 -e HOST_USER_ID=1000 bioconda/bioconda-utils-build-env:latest /bin/bash /opt/build_script.bash
09:19:05 BIOCONDA INFO (OUT) /opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py:376: UserWarning: RECIPE_PATH received is a file. File: /opt/recipe/meta.yaml
09:19:05 BIOCONDA INFO (OUT) It should be a path to a folder.
09:19:05 BIOCONDA INFO (OUT) Forcing conda-build to use the recipe file.
09:19:05 BIOCONDA INFO (OUT)   UserWarning
09:19:05 BIOCONDA INFO (OUT) No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
09:19:05 BIOCONDA INFO (OUT) WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
09:19:05 BIOCONDA INFO (OUT) Adding in variants from internal_defaults
09:19:05 BIOCONDA INFO (OUT) INFO:conda_build.variants:Adding in variants from internal_defaults
09:19:05 BIOCONDA INFO (OUT) Adding in variants from /opt/host-conda-bld/conda_build_config_0_-e_conda_build_config.yaml09:19:05 BIOCONDA INFO (OUT) INFO:conda_build.variants:Adding in variants from /opt/host-conda-bld/conda_build_config_0_-e_conda_build_config.yaml
09:19:05 BIOCONDA INFO (OUT) Adding in variants from /opt/host-conda-bld/conda_build_config_1_-e_bioconda_utils-conda_build_config.yaml
09:19:05 BIOCONDA INFO (OUT) INFO:conda_build.variants:Adding in variants from /opt/host-conda-bld/conda_build_config_1_-e_bioconda_utils-conda_build_config.yaml
09:19:06 BIOCONDA INFO (OUT) Attempting to finalize metadata for recognizer
09:19:06 BIOCONDA INFO (OUT) INFO:conda_build.metadata:Attempting to finalize metadata for recognizer
.09:20:23 BIOCONDA INFO (OUT) Collecting package metadata: ...working... done
09:20:31 BIOCONDA INFO (OUT) Solving environment: ...working... done
.09:21:14 BIOCONDA INFO (OUT) Collecting package metadata: ...working... done
09:21:28 BIOCONDA INFO (OUT) Solving environment: ...working... done
09:21:28 BIOCONDA INFO (OUT) BUILD START: ['recognizer-1.2.1-pyh9f0ad1d_0.tar.bz2']
09:21:38 BIOCONDA INFO (OUT) Collecting package metadata: ...working... done
09:21:53 BIOCONDA INFO (OUT) Solving environment: ...working... done
09:21:53 BIOCONDA INFO (OUT)
09:21:53 BIOCONDA INFO (OUT) ## Package Plan ##
09:21:53 BIOCONDA INFO (OUT)
09:21:53 BIOCONDA INFO (OUT)   environment location: /opt/conda/conda-bld/recognizer_1589188745727/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
09:21:53 BIOCONDA INFO (OUT)
09:21:53 BIOCONDA INFO (OUT)
09:21:53 BIOCONDA INFO (OUT) The following NEW packages will be INSTALLED:
09:21:53 BIOCONDA INFO (OUT)
09:21:53 BIOCONDA INFO (OUT)     _libgcc_mutex:          0.1-conda_forge              conda-forge
09:21:53 BIOCONDA INFO (OUT)     _openmp_mutex:          4.5-0_gnu                    conda-forge
09:21:53 BIOCONDA INFO (OUT)     brotlipy:               0.7.0-py36h8c4c3a4_1000      conda-forge
09:21:53 BIOCONDA INFO (OUT)     ca-certificates:        2020.4.5.1-hecc5488_0        conda-forge
09:21:53 BIOCONDA INFO (OUT)     certifi:                2020.4.5.1-py36h9f0ad1d_0    conda-forge
09:21:53 BIOCONDA INFO (OUT)     cffi:                   1.14.0-py36hd463f26_0        conda-forge
09:21:53 BIOCONDA INFO (OUT)     chardet:                3.0.4-py36h9f0ad1d_1006      conda-forge
09:21:53 BIOCONDA INFO (OUT)     conda:                  4.8.3-py36h9f0ad1d_1         conda-forge
09:21:53 BIOCONDA INFO (OUT)     conda-package-handling: 1.6.0-py36h8c4c3a4_2         conda-forge
09:21:53 BIOCONDA INFO (OUT)     cryptography:           2.9.2-py36h45558ae_0         conda-forge
09:21:53 BIOCONDA INFO (OUT)     idna:                   2.9-py_1                     conda-forge
09:21:53 BIOCONDA INFO (OUT)     ld_impl_linux-64:       2.34-h53a641e_0              conda-forge
09:21:53 BIOCONDA INFO (OUT)     libffi:                 3.2.1-he1b5a44_1007          conda-forge
09:21:53 BIOCONDA INFO (OUT)     libgcc-ng:              9.2.0-h24d8f2e_2             conda-forge
09:21:53 BIOCONDA INFO (OUT)     libgomp:                9.2.0-h24d8f2e_2             conda-forge
09:21:53 BIOCONDA INFO (OUT)     libstdcxx-ng:           9.2.0-hdf63c60_2             conda-forge
09:21:53 BIOCONDA INFO (OUT)     ncurses:                6.1-hf484d3e_1002            conda-forge
09:21:53 BIOCONDA INFO (OUT)     openssl:                1.1.1g-h516909a_0            conda-forge
09:21:53 BIOCONDA INFO (OUT)     pip:                    20.1-pyh9f0ad1d_0            conda-forge
09:21:53 BIOCONDA INFO (OUT)     pycosat:                0.6.3-py36h8c4c3a4_1004      conda-forge
09:21:53 BIOCONDA INFO (OUT)     pycparser:              2.20-py_0                    conda-forge
09:21:53 BIOCONDA INFO (OUT)     pyopenssl:              19.1.0-py_1                  conda-forge
09:21:53 BIOCONDA INFO (OUT)     pysocks:                1.7.1-py36h9f0ad1d_1         conda-forge
09:21:53 BIOCONDA INFO (OUT)     python:                 3.6.10-h8356626_1011_cpython conda-forge
09:21:53 BIOCONDA INFO (OUT)     python_abi:             3.6-1_cp36m                  conda-forge
09:21:53 BIOCONDA INFO (OUT)     readline:               8.0-hf8c457e_0               conda-forge
09:21:53 BIOCONDA INFO (OUT)     requests:               2.23.0-pyh8c360ce_2          conda-forge
09:21:53 BIOCONDA INFO (OUT)     ruamel_yaml:            0.15.80-py36h8c4c3a4_1001    conda-forge
09:21:53 BIOCONDA INFO (OUT)     setuptools:             46.1.3-py36h9f0ad1d_0        conda-forge
09:21:53 BIOCONDA INFO (OUT)     six:                    1.14.0-py_1                  conda-forge
09:21:53 BIOCONDA INFO (OUT)     sqlite:                 3.30.1-hcee41ef_0            conda-forge
09:21:53 BIOCONDA INFO (OUT)     tk:                     8.6.10-hed695b0_0            conda-forge
09:21:53 BIOCONDA INFO (OUT)     tqdm:                   4.46.0-pyh9f0ad1d_0          conda-forge
09:21:53 BIOCONDA INFO (OUT)     urllib3:                1.25.9-py_0                  conda-forge
09:21:53 BIOCONDA INFO (OUT)     wheel:                  0.34.2-py_1                  conda-forge
09:21:53 BIOCONDA INFO (OUT)     xz:                     5.2.5-h516909a_0             conda-forge
09:21:53 BIOCONDA INFO (OUT)     yaml:                   0.2.4-h516909a_0             conda-forge
09:21:53 BIOCONDA INFO (OUT)     zlib:                   1.2.11-h516909a_1006         conda-forge
09:21:53 BIOCONDA INFO (OUT)
.09:22:03 BIOCONDA INFO (OUT) Preparing transaction: ...working... done
09:22:06 BIOCONDA INFO (OUT) Verifying transaction: ...working... done
09:22:19 BIOCONDA INFO (OUT) Executing transaction: ...working... done
09:22:29 BIOCONDA INFO (OUT) Collecting package metadata: ...working... done
09:22:59 BIOCONDA INFO (OUT) Solving environment: ...working... done
09:23:00 BIOCONDA INFO (OUT) Source cache directory is: /opt/conda/conda-bld/src_cache
09:23:00 BIOCONDA INFO (OUT) INFO:conda_build.source:Source cache directory is: /opt/conda/conda-bld/src_cache
09:23:00 BIOCONDA INFO (OUT) Downloading source to cache: 1.2.1_581f2acdf9.tar.gz
09:23:00 BIOCONDA INFO (OUT) INFO:conda_build.source:Downloading source to cache: 1.2.1_581f2acdf9.tar.gz
09:23:00 BIOCONDA INFO (OUT) Downloading https://github.com/iquasere/reCOGnizer/archive/1.2.1.tar.gz
09:23:00 BIOCONDA INFO (OUT) INFO:conda_build.source:Downloading https://github.com/iquasere/reCOGnizer/archive/1.2.1.tar.gz
.09:23:08 BIOCONDA INFO (OUT) Success
09:23:08 BIOCONDA INFO (OUT) INFO:conda_build.source:Success
09:23:08 BIOCONDA INFO (OUT) Extracting download
09:23:09 BIOCONDA INFO (OUT) source tree in: /opt/conda/conda-bld/recognizer_1589188745727/work
09:23:09 BIOCONDA INFO (OUT) export PREFIX=/opt/conda/conda-bld/recognizer_1589188745727/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
09:23:09 BIOCONDA INFO (OUT) export BUILD_PREFIX=/opt/conda/conda-bld/recognizer_1589188745727/_build_env
09:23:09 BIOCONDA INFO (OUT) export SRC_DIR=/opt/conda/conda-bld/recognizer_1589188745727/work
09:23:10 BIOCONDA INFO (OUT) Non-user install because user site-packages disabled
09:23:10 BIOCONDA INFO (OUT) Ignoring indexes: https://pypi.org/simple
09:23:10 BIOCONDA INFO (OUT) Created temporary directory: /tmp/pip-ephem-wheel-cache-ou8c25gq
09:23:10 BIOCONDA INFO (OUT) Created temporary directory: /tmp/pip-req-tracker-r3495pw7
09:23:10 BIOCONDA INFO (OUT) Initialized build tracking at /tmp/pip-req-tracker-r3495pw7
09:23:10 BIOCONDA INFO (OUT) Created build tracker: /tmp/pip-req-tracker-r3495pw7
09:23:10 BIOCONDA INFO (OUT) Entered build tracker: /tmp/pip-req-tracker-r3495pw7
09:23:10 BIOCONDA INFO (OUT) Created temporary directory: /tmp/pip-install-k0glsweu
09:23:10 BIOCONDA INFO (OUT) ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
09:23:10 BIOCONDA INFO (OUT) Exception information:
09:23:10 BIOCONDA INFO (OUT) Traceback (most recent call last):
09:23:10 BIOCONDA INFO (OUT)   File "$PREFIX/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
09:23:10 BIOCONDA INFO (OUT)     status = self.run(options, args)
09:23:10 BIOCONDA INFO (OUT)   File "$PREFIX/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
09:23:10 BIOCONDA INFO (OUT)     return func(self, options, args)
09:23:10 BIOCONDA INFO (OUT)   File "$PREFIX/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 302, in run
09:23:10 BIOCONDA INFO (OUT)     check_supported_wheels=not options.target_dir,
09:23:10 BIOCONDA INFO (OUT)   File "$PREFIX/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 323, in get_requirements
09:23:10 BIOCONDA INFO (OUT)     use_pep517=options.use_pep517,
09:23:10 BIOCONDA INFO (OUT)   File "$PREFIX/lib/python3.6/site-packages/pip/_internal/req/constructors.py", line 396, in install_req_from_line
09:23:10 BIOCONDA INFO (OUT)     parts = parse_req_from_line(name, line_source)
09:23:10 BIOCONDA INFO (OUT)   File "$PREFIX/lib/python3.6/site-packages/pip/_internal/req/constructors.py", line 325, in parse_req_from_line
09:23:10 BIOCONDA INFO (OUT)     url = _get_url_from_path(p, name)
09:23:10 BIOCONDA INFO (OUT)   File "$PREFIX/lib/python3.6/site-packages/pip/_internal/req/constructors.py", line 281, in _get_url_from_path
09:23:10 BIOCONDA INFO (OUT)     "nor 'pyproject.toml' found.".format(**locals())
09:23:10 BIOCONDA INFO (OUT) pip._internal.exceptions.InstallationError: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
09:23:10 BIOCONDA INFO (OUT) Removed build tracker: '/tmp/pip-req-tracker-r3495pw7'
09:23:11 BIOCONDA INFO (OUT) Traceback (most recent call last):
09:23:11 BIOCONDA INFO (OUT)   File "/opt/conda/bin/conda-build", line 11, in <module>
09:23:11 BIOCONDA INFO (OUT)     sys.exit(main())
09:23:11 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 474, in main
09:23:11 BIOCONDA INFO (OUT)     execute(sys.argv[1:])
09:23:11 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 465, in execute
09:23:11 BIOCONDA INFO (OUT)     verify=args.verify, variants=args.variants)
09:23:11 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
09:23:11 BIOCONDA INFO (OUT)     notest=notest, need_source_download=need_source_download, variants=variants)
09:23:11 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2864, in build_tree
09:23:11 BIOCONDA INFO (OUT)     notest=notest,
09:23:11 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1995, in build
09:23:11 BIOCONDA INFO (OUT)     cwd=src_dir, stats=build_stats)
09:23:11 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 404, in check_call_env
09:23:11 BIOCONDA INFO (OUT)     return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
09:23:11 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 384, in _func_defaulting_env_to_os_environ
09:23:11 BIOCONDA INFO (OUT)     raise subprocess.CalledProcessError(proc.returncode, _args)
09:23:11 BIOCONDA INFO (OUT) subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/recognizer_1589188745727/work/conda_build.sh']' returned non-zero exit status 1.
09:23:15 BIOCONDA ERROR COMMAND FAILED (exited with 1): docker run -t --net host --rm -v /tmp/tmpagx3k475/build_script.bash:/opt/build_script.bash -v /tmp/miniconda/miniconda/conda-bld/:/opt/host-conda-bld -v /mnt/HDDStorage/jsequeira/conda_recognizer/bioconda-recipes/recipes/recognizer:/opt/recipe -e LANG=en_US.UTF-8 -e HOST_USER_ID=1000 bioconda/bioconda-utils-build-env:latest /bin/bash /opt/build_script.bash

09:23:15 BIOCONDA ERROR BUILD FAILED recipes/recognizer
09:23:15 BIOCONDA INFO (COMMAND) conda build purge
09:23:15 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
09:23:15 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/recognizer
```

**Comment by iquasere** [comment]
Seems this problem was due to not being a python module, so could not install with pip. If anyone else is getting this error, maybe looking into the [pull request](https://github.com/bioconda/bioconda-recipes/pull/22022) can help.
