### ISSUE TITLE
autobump via bioconda-utils

### ISSUE THREAD

**Issue by blinard-BIOINFO** [bioconda/bioconda-recipes#22126]
Hi,

This issue is related to #21073 and the answer of @dpryan79 there.
I'm still trying to understand autobump mechanism to update recipes `rappas` from 1.20 to 1.21 (autobump has never been launched, while I did a new github release monthes ago).

 Sorry to come back to this but I'm stuck with autobumping via bioconda-utils.

First, when following tutorials, I realized that they are not updated anymore.
For instance, https://bioconda.github.io/contributor/updating.html say to use a `bioconda-utils update` command, but the `update` option does not appear anymore in current version of bioconda-utils (install via `conda install bioconda-utils`). 

Then I see via the help of bioconda-utils that there is an `autobump` option. I try to use it but only get some pyton errors:
```
$ bioconda-utils autobump recipes/ config.yml --package rappas
12:02:55 BIOCONDA INFO Hosters loaded: ['FTPHoster', 'GithubRelease', 'GithubTag', 'GithubReleaseAttachment', 'GithubRepoStore', 'Bioconductor', 'CargoPort', 'SourceForge', 'PyPi', 'Bioarchive', 'CPAN', 'CRAN', 'BitBucketTag', 'BitBucketDownload', 'GitlabTag']
12:02:55 BIOCONDA WARNING Selected 1 packages
12:02:55 BIOCONDA INFO Building Recipe DAG
Loading Recipes...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 7222/7222 [00:20<00:00, 346.49it/s]
12:03:17 BIOCONDA INFO Building Recipe DAG: done (4753 nodes, 18345 edges)
12:03:17 BIOCONDA ERROR Dropping into debugger
Traceback (most recent call last):
  File "/media/ben/STOCK/VIRTUAL_ENV/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/cli.py", line 71, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-17>", line 5, in autobump
  File "/media/ben/STOCK/VIRTUAL_ENV/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/cli.py", line 90, in wrapper
    func(*args, **kwargs)
  File "/media/ben/STOCK/VIRTUAL_ENV/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/cli.py", line 823, in autobump
    config_dict, cache_fn=cache and cache + "_dag.pkl")
  File "/media/ben/STOCK/VIRTUAL_ENV/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/autobump.py", line 133, in __init__
    self.dag = graph.filter_recipe_dag(self.dag, packages, exclude)
  File "/media/ben/STOCK/VIRTUAL_ENV/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/graph.py", line 127, in filter_recipe_dag
    and not any(fnmatch(recipe.reldir, p) for p in exclude)):
TypeError: 'NoneType' object is not iterable

```
So my question is: what is the command to autobump via bioconda-utils ?

**Comment by tobiasrausch** [comment]
I have the same problem. I just released a new version of [tracy](https://github.com/gear-genomics/tracy) which is already in [bioconda](http://bioconda.github.io/recipes/tracy/README.html) but the autobump fails with the above error message.

`bioconda-utils autobump recipes/ config.yml --packages tracy --create-pr`

**Comment by dpryan79** [comment]
I always wondered why the bot doesn't run into it and it turns out the answer is that it always runs with `--exclude "bioconductor*"`, since we don't want to autobump those. If you add that that (you can exclude anything, really, even packages that don't exist like "afhjaksdjbavb") then the command will work. This should be an easy fix really, we just have to change a default `None` to `[]`.

You end up needing to add some other options to in order to not run into other apparent problems. So for tracy, the following will work:

```
bioconda-utils autobump --no-check-pinnings --exclude "bioconductor*" --packages tracy
```

That give the message: "tracy has no URL in source 2". There is a git_url there, but we wouldn't want the bot to change that randomly to another sdsl commit and break things, which is why it ends up skipping tracy. 

I'll try to fix needing to exclude stuff this weekend (and also figure out exactly why --no-check-pinnings needs to be added).

**Comment by tobiasrausch** [comment]
Thanks for the explanation, that was beyond my very limited bioconda knowledge but the manual recipe update worked.
