### ISSUE TITLE
Autobump bioconductor-dorothea to 1.0.1

### ISSUE THREAD

**Issue by jperales** [bioconda/bioconda-recipes#24441]
Hi all,
Current recipe for bioconductor-dorothea is outdated (1.0.0). Unfortunately, this leads to an error during installation with `conda`, because the tar files are not found in the sources. This could be solved by updating to the current version: 1.0.1 in BioConductor.

Documentation about how to update a recipe is deprecated (https://bioconda.github.io/contributor/updating.html). But I found along the issues that `autobump` has replaced `update` in `bioconda-utils`. I have tried it my self with `./bootstrap.py`. However it crashes with an error (see below error messages), and I got stacked with no documentation.

Please if anybody could update the recipe for me. I will also invoke the bot in this issue and cross fingers. Thanks!

```
$ bioconda-utils autobump recipes/ config.yml --packages bioconductor-dorothea
17:08:47 BIOCONDA INFO Hosters loaded: ['FTPHoster', 'GithubRelease', 'GithubTag', 'GithubReleaseAttachment', 'GithubRepoStore', 'Bioconductor', 'CargoPort', 'SourceForge', 'PyPi', 'Bioarchive', 'CPAN', 'CRAN', 'BitBucketTag', 'BitBucketDownload', 'GitlabTag']
17:08:47 BIOCONDA WARNING Selected 1 packages
17:08:47 BIOCONDA INFO Building Recipe DAG
17:09:03 BIOCONDA INFO openduck has duplicate key                                                                                                                                                                  
Loading Recipes...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7442/7442 [00:32<00:00, 228.03it/s]
17:09:20 BIOCONDA INFO Building Recipe DAG: done (6514 nodes, 19029 edges)
17:09:20 BIOCONDA ERROR Dropping into debugger
Traceback (most recent call last):
  File "/tmp/miniconda/miniconda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 71, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-17>", line 5, in autobump
  File "/tmp/miniconda/miniconda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 90, in wrapper
    func(*args, **kwargs)
  File "/tmp/miniconda/miniconda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 847, in autobump
    config_dict, cache_fn=cache and cache + "_dag.pkl")
  File "/tmp/miniconda/miniconda/lib/python3.7/site-packages/bioconda_utils/autobump.py", line 133, in __init__
    self.dag = graph.filter_recipe_dag(self.dag, packages, exclude)
  File "/tmp/miniconda/miniconda/lib/python3.7/site-packages/bioconda_utils/graph.py", line 127, in filter_recipe_dag
    and not any(fnmatch(recipe.reldir, p) for p in exclude)):
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/tmp/miniconda/miniconda/bin/bioconda-utils", line 8, in <module>
    sys.exit(main())
  File "/tmp/miniconda/miniconda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 971, in main
    bioconductor_skeleton, clean_cran_skeleton, autobump, bot
  File "/tmp/miniconda/miniconda/lib/python3.7/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/tmp/miniconda/miniconda/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/tmp/miniconda/miniconda/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/tmp/miniconda/miniconda/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "<boltons.funcutils.FunctionBuilder-20>", line 5, in autobump
  File "/tmp/miniconda/miniconda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 130, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-19>", line 5, in autobump
  File "/tmp/miniconda/miniconda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 59, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-18>", line 5, in autobump
  File "/tmp/miniconda/miniconda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 71, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-17>", line 5, in autobump
  File "/tmp/miniconda/miniconda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 90, in wrapper
    func(*args, **kwargs)
  File "/tmp/miniconda/miniconda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 847, in autobump
    config_dict, cache_fn=cache and cache + "_dag.pkl")
  File "/tmp/miniconda/miniconda/lib/python3.7/site-packages/bioconda_utils/autobump.py", line 133, in __init__
    self.dag = graph.filter_recipe_dag(self.dag, packages, exclude)
  File "/tmp/miniconda/miniconda/lib/python3.7/site-packages/bioconda_utils/graph.py", line 127, in filter_recipe_dag
    and not any(fnmatch(recipe.reldir, p) for p in exclude)):
TypeError: 'NoneType' object is not iterable
```

**Comment by jperales** [comment]
@BiocondaBot autobump bioconductor-dorothea

**Comment by jperales** [comment]
The bot did not make it...
Please I would be very thankful if anybody explains to me how to `autobump` the package myself. See first message for the issue. Thanks!

**Comment by jperales** [comment]
solved. It works with the last automatic update of package version
