### ISSUE TITLE
pysam / htslib issue

### ISSUE THREAD

**Issue by simonvh** [bioconda/bioconda-recipes#2519]
@tomkinsc  @lparsons 

There seems to be an issue with the latest version of pysam and/or htslib.

When I try to test a new build of my Python 2.7 module, which depends on pybedtools, I get the following issue:

```
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    from gimmemotifs.tools import *
  File "/anaconda/conda-bld/work/gimmemotifs-master/gimmemotifs/tools.py", line 21, in <module>
    from gimmemotifs.utils import which
  File "/anaconda/conda-bld/work/gimmemotifs-master/gimmemotifs/utils.py", line 23, in <module>
    import pybedtools
  File "/anaconda/envs/_build/lib/python2.7/site-packages/pybedtools/__init__.py", line 12, in <module>
    from . import contrib
  File "/anaconda/envs/_build/lib/python2.7/site-packages/pybedtools/contrib/__init__.py", line 3, in <module>
    from . import venn_maker
  File "/anaconda/envs/_build/lib/python2.7/site-packages/pybedtools/contrib/venn_maker.py", line 12, in <module>
    from pybedtools import helpers
  File "/anaconda/envs/_build/lib/python2.7/site-packages/pybedtools/helpers.py", line 13, in <module>
    import pysam
  File "/anaconda/envs/_build/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by /anaconda/envs/_build/lib/python2.7/site-packages/pysam/../../../libhts.so.1)
``` 

It seems that somewhere in the process a compiled version of htslib is used, one that is not compatible with the Centos 5 glibc. 

The following line in my own `meta.yaml` seems to fix it:
```
    - htslib <1.3.1
``` 

Of course this not ideal :). Any thoughts?

**Comment by kyleabeauchamp** [comment]
Are you using centos 5?  Afaik that is no longer supported.

**Comment by simonvh** [comment]
Ah. Then I'm doing something wrong. Isn't the bionda build box based on
centos 5?

**Comment by kyleabeauchamp** [comment]
Centos 6

**Comment by kyleabeauchamp** [comment]
Changed a month ago or so to use the conda-forge builder

**Comment by simonvh** [comment]
Ah, thanks, I missed that, that explains things. Does that mean that
https://github.com/bioconda/bioconda-recipes/blob/master/README.md is out
of date? Seems to still mention bioconda-builder...

**Comment by daler** [comment]
Thanks @simonvh, I just updated the build info in the readme (#2522).

**Comment by simonvh** [comment]
This indeed fixes the issue, thanks @kyleabeauchamp and @daler!
