### ISSUE TITLE
Conflicts and UnsatisfiableError

### ISSUE THREAD

**Issue by arunhpatil** [bioconda/bioconda-recipes#25190]
Bioconda is working well on Ubuntu 18, I tried installing mirge3 in py36 (worked), py37 (worked), and py38 (**Failed**) as shown below. <br/>
`conda create -n mirge38 python=3.8 `
![image](https://user-images.githubusercontent.com/10003811/98294379-ddf31300-1f7d-11eb-8acd-bfd7a9f7394c.png)

The possible reason for this could be, **Bioconda only supports python 2.7, 3.6 and 3.7. The community is currently working on adding support for python 3.8**

However, one of the users with python 3.7.6 and conda 4.9.1, has a similar issue (mentioned in the image above) and after specifying `conda create -n mirge3 python=3.7` followed by activating mirge3 environment and `conda install -c bioconda mirge3`, a new conflict error follows as shown:
**Note**: all of this was tested in a confined environment. 

![image](https://user-images.githubusercontent.com/10003811/98295024-e009a180-1f7e-11eb-8abb-fa70cef8eaf3.png)

Kindly let me know a recommended fix for this issue. I have successfully installed mirge3 via bioconda in Linux and Max OS.

**Comment by dpryan79** [comment]
`conda create -dn foo python=3.7 mirge3` works fine. There appears to be a dependency that was never rebuilt for python 3.8. You could go through the dependencies and see which can't install in a python 3.8 environment if you need to. These days almost all packages that have python 3 builds will work in a python 3.8 environment.

**Comment by dpryan79** [comment]
This will resolve if one were to loosen the version restrictions within mirge3. It is pinned to an old bowtie version that lacks python 3.8 builds (these are present in the newest version).

**Comment by arunhpatil** [comment]
@dpryan79, thank you. I will modify the yaml file and try again.

**Comment by arunhpatil** [comment]
Hi, I tried to remove the strict bowtie, samtools version, and further removed r-base. I am getting the following error:
```
(mirge38) arun@DESKTOP-H231NS7:~/repositories/bioconda-recipes$ conda config --set unsatisfiable_hints True
(mirge38) arun@DESKTOP-H231NS7:~/repositories/bioconda-recipes$ conda install -y -c bioconda -v mirge3
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working...
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
Traceback (most recent call last):
  File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/cli/install.py", line 261, in install
    unlink_link_transaction = solver.solve_for_transaction(
  File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 275, in solve_final_state
    ssc = self._add_specs(ssc)
  File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 706, in _add_specs
    raise UnsatisfiableError({})
conda.exceptions.UnsatisfiableError:
Did not find conflicting dependencies. If you would like to know which
packages conflict ensure that you have enabled unsatisfiable hints.

conda config --set unsatisfiable_hints True


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
    return getattr(module, func_name)(args, parser)
  File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/cli/main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/cli/install.py", line 308, in install
    raise e
  File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/cli/install.py", line 295, in install
    unlink_link_transaction = solver.solve_for_transaction(
  File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 275, in solve_final_state
    ssc = self._add_specs(ssc)
  File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 704, in _add_specs
    ssc.r.find_conflicts(spec_set)
  File "/home/arun/miniconda3/lib/python3.8/site-packages/conda/resolve.py", line 352, in find_conflicts
    raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)
conda.exceptions.UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

(mirge38) arun@DESKTOP-H231NS7:~/repositories/bioconda-recipes$
```

**Comment by dpryan79** [comment]
Mamba give more coherent error messages:

    Problem: package mirge3-0.0.1-pyh3252c3a_0 requires cutadapt 2.7, but none of the providers can be installed

So either relax the dependency on cutadapt to allow newer versions, or I suppose someone can add a PR to rebuild this older version for newer python versions.

**Comment by arunhpatil** [comment]
Thank you @dpryan79 , I have removed the version specification. I will have to test it though. Thanks for Mamba input, I have installed and got the error message you specified. I have modified the YAML file and sent a PR.
