### ISSUE TITLE
Cutadapt problem

### ISSUE THREAD

**Issue by andreott** [bioconda/bioconda-recipes#26604]
Hi, I discovered a problem with my environment created for Cutadapt (v 2.1, but the same thing happens for v3.2).

When running it will stop working with the error message:

```
Processing reads on 4 cores in single-end mode ...
ERROR: Traceback (most recent call last):
  File "/path_to_conda/miniconda2/envs/cutadapt/lib/python3.8/site-packages/cutadapt/pipeline.py", line 560, in run
    self.send_to_worker(chunk_index, chunk)
  File "/path_to_conda/miniconda2/envs/cutadapt/lib/python3.8/site-packages/xopen/__init__.py", line 141, in __exit__
    self.close()
  File "/path_to_conda/miniconda2/envs/cutadapt/lib/python3.8/site-packages/xopen/__init__.py", line 327, in close
    self._raise_if_error(allow_sigterm=allow_sigterm)
  File "/path_to_conda/miniconda2/envs/cutadapt/lib/python3.8/site-packages/xopen/__init__.py", line 350, in _raise_if_error
    raise OSError("{} (exit code {})".format(message, retcode))
OSError: igzip: Error while decompressing extra concatenatedgzip files on /path_to_fastq/filename.fastq.gz (exit code 1)

ERROR: Traceback (most recent call last):
  File "/path_to_conda/miniconda2/envs/cutadapt/lib/python3.8/site-packages/cutadapt/pipeline.py", line 626, in run
    raise e
OSError: igzip: Error while decompressing extra concatenatedgzip files on /path_to_fastq/filename.fastq.gz (exit code 1)
```

The environment (build with just specifying cutadapt=2.1 as dependency) looks as follows:
```
# packages in environment at /path_to_conda/miniconda2/envs/cutadapt:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py38h578d9bd_1    conda-forge
cutadapt                  2.10             py38h0213d0e_1    bioconda
dnaio                     0.5.0            py38h0213d0e_0    bioconda
isa-l                     2.30.0               h7f98852_1    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
openssl                   1.1.1i               h7f98852_0    conda-forge
pigz                      2.5                  h27826a3_0    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
python                    3.8.6           hffdb5ce_5_cpython    conda-forge
python-isal               0.4.0            py38h497a2fe_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
setuptools                49.6.0           py38h578d9bd_3    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xopen                     1.1.0            py38h578d9bd_1    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
```

For an older environment with the following specs it works:
```
# packages in environment at /path_to_conda/miniconda2/envs/cutadapt_working:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
ca-certificates           2020.11.8            ha878542_0    conda-forge
certifi                   2020.12.5        py38h578d9bd_1    conda-forge
cutadapt                  2.10             py38h0213d0e_1    bioconda
dnaio                     0.4.4            py38h0213d0e_0    bioconda
isa-l                     2.30.0               h36c2ea0_0    conda-forge
ld_impl_linux-64          2.35.1               hed1e6ac_0    conda-forge
libffi                    3.3                  h58526e2_1    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
pigz                      2.3.4                hed695b0_1    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
python                    3.8.6           hffdb5ce_1_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
setuptools                49.6.0           py38h578d9bd_3    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xopen                     1.0.1            py38h578d9bd_1    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
```

The error did not occur for all input files and even for the same input file it occurred at slightly different positions (according to the #processed reads output by cutadapt)

Let me know if you need some additional information!

**Comment by zxl124** [comment]
I had the same problem. I suspected pigz so I tried downgrade it to 2.3.4, but the problem persists.

**Comment by marcelm** [comment]
Hi and thanks for reporting. I don’t monitor issues in the bioconda-recipes repository, so I haven’t seen this report when it was made. Let’s continue the discussion over at marcelm/cutadapt#513 for now.

**Comment by zxl124** [comment]
New build of `isa-l` was made, which has fixed this issue. Please consider closing this issue.

**Comment by marcelm** [comment]
Yes, good point. Credit for the fix goes to @rhpvorderman!
