### ISSUE TITLE
Issues with dependencies when building bcbio_monitor

### ISSUE THREAD

**Issue by guillermo-carrasco** [bioconda/bioconda-recipes#278]
Hi,

I am trying to create a recipe for [bcbio-monitor](https://github.com/guillermo-carrasco/bcbio-nextgen-monitor) and I'm having some troubles with dependencies when building the package:

```
(master) ~/repos_and_code/recipes (master) ~> conda build recipes/bcbio_monitor
Removing old build environment
Removing old work directory
BUILD START: bcbio_monitor-1.0.2-py27_0
Fetching package metadata: ......
Solving package specifications: ........................
The following NEW packages will be INSTALLED:

    ecdsa:        0.13-py27_0
    flask:        0.10.1-py27_1
    freetype:     2.5.5-0
    gevent:       1.0-py27_0
    graphviz:     2.38.0-0
    greenlet:     0.4.9-py27_0
    itsdangerous: 0.24-py27_0
    jinja2:       2.8-py27_0
    libpng:       1.6.17-0
    markupsafe:   0.23-py27_0
    openssl:      1.0.2d-0
    paramiko:     1.15.3-py27_0
    pip:          7.1.2-py27_0
    pycrypto:     2.6.1-py27_0
    python:       2.7.10-2
    pyyaml:       3.11-py27_1
    readline:     6.2-2
    requests:     2.8.1-py27_0
    setuptools:   18.4-py27_0
    sqlite:       3.8.4.1-1
    tk:           8.5.18-0
    werkzeug:     0.11.2-py27_0
    wheel:        0.26.0-py27_1
    yaml:         0.1.6-0
    zlib:         1.2.8-0

Linking packages ...
[      COMPLETE      ]|######################################################################################| 100%
Removing old work directory
Source cache directory is: /Users/guillem/anaconda/conda-bld/src_cache
Found source in cache: bcbio_monitor-1.0.2.tar.gz
Extracting download
Package: bcbio_monitor-1.0.2-py27_0
source tree in: /Users/guillem/anaconda/conda-bld/work/bcbio_monitor-1.0.2
+ /Users/guillem/anaconda/envs/_build/bin/python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to bcbio_monitor.egg-info/requires.txt
writing bcbio_monitor.egg-info/PKG-INFO
writing top-level names to bcbio_monitor.egg-info/top_level.txt
writing dependency_links to bcbio_monitor.egg-info/dependency_links.txt
writing entry points to bcbio_monitor.egg-info/entry_points.txt
reading manifest file 'bcbio_monitor.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'bcbio_monitor.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.5-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/bcbio_monitor
copying bcbio_monitor/__init__.py -> build/lib/bcbio_monitor
creating build/lib/bcbio_monitor/config
copying bcbio_monitor/config/__init__.py -> build/lib/bcbio_monitor/config
creating build/lib/bcbio_monitor/graph
copying bcbio_monitor/graph/__init__.py -> build/lib/bcbio_monitor/graph
creating build/lib/bcbio_monitor/log
copying bcbio_monitor/log/__init__.py -> build/lib/bcbio_monitor/log
creating build/lib/bcbio_monitor/parser
copying bcbio_monitor/parser/__init__.py -> build/lib/bcbio_monitor/parser
creating build/lib/bcbio_monitor/static
copying bcbio_monitor/static/.DS_Store -> build/lib/bcbio_monitor/static
creating build/lib/bcbio_monitor/static/css
copying bcbio_monitor/static/css/bootstrap.min.css -> build/lib/bcbio_monitor/static/css
copying bcbio_monitor/static/css/monitor.css -> build/lib/bcbio_monitor/static/css
creating build/lib/bcbio_monitor/static/ico
copying bcbio_monitor/static/ico/favicon.ico -> build/lib/bcbio_monitor/static/ico
creating build/lib/bcbio_monitor/static/js
copying bcbio_monitor/static/js/moment.js -> build/lib/bcbio_monitor/static/js
copying bcbio_monitor/static/js/monitor.js -> build/lib/bcbio_monitor/static/js
copying bcbio_monitor/static/js/utils.js -> build/lib/bcbio_monitor/static/js
copying bcbio_monitor/static/js/viz.js -> build/lib/bcbio_monitor/static/js
creating build/lib/bcbio_monitor/templates
copying bcbio_monitor/templates/404.html -> build/lib/bcbio_monitor/templates
copying bcbio_monitor/templates/base.html -> build/lib/bcbio_monitor/templates
copying bcbio_monitor/templates/index.html -> build/lib/bcbio_monitor/templates
creating build/bdist.macosx-10.5-x86_64
creating build/bdist.macosx-10.5-x86_64/egg
creating build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor
copying build/lib/bcbio_monitor/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor
creating build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/config
copying build/lib/bcbio_monitor/config/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/config
creating build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/graph
copying build/lib/bcbio_monitor/graph/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/graph
creating build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/log
copying build/lib/bcbio_monitor/log/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/log
creating build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/parser
copying build/lib/bcbio_monitor/parser/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/parser
creating build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/static
copying build/lib/bcbio_monitor/static/.DS_Store -> build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/static
creating build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/static/css
copying build/lib/bcbio_monitor/static/css/bootstrap.min.css -> build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/static/css
copying build/lib/bcbio_monitor/static/css/monitor.css -> build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/static/css
creating build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/static/ico
copying build/lib/bcbio_monitor/static/ico/favicon.ico -> build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/static/ico
creating build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/static/js
copying build/lib/bcbio_monitor/static/js/moment.js -> build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/static/js
copying build/lib/bcbio_monitor/static/js/monitor.js -> build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/static/js
copying build/lib/bcbio_monitor/static/js/utils.js -> build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/static/js
copying build/lib/bcbio_monitor/static/js/viz.js -> build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/static/js
creating build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/templates
copying build/lib/bcbio_monitor/templates/404.html -> build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/templates
copying build/lib/bcbio_monitor/templates/base.html -> build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/templates
copying build/lib/bcbio_monitor/templates/index.html -> build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/templates
byte-compiling build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/config/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/graph/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/log/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/bcbio_monitor/parser/__init__.py to __init__.pyc
creating build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying bcbio_monitor.egg-info/PKG-INFO -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying bcbio_monitor.egg-info/SOURCES.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying bcbio_monitor.egg-info/dependency_links.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying bcbio_monitor.egg-info/entry_points.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying bcbio_monitor.egg-info/requires.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying bcbio_monitor.egg-info/top_level.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying bcbio_monitor.egg-info/zip-safe -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
creating dist
creating 'dist/bcbio_monitor-1.0.2-py2.7.egg' and adding 'build/bdist.macosx-10.5-x86_64/egg' to it
removing 'build/bdist.macosx-10.5-x86_64/egg' (and everything under it)
Processing bcbio_monitor-1.0.2-py2.7.egg
Copying bcbio_monitor-1.0.2-py2.7.egg to /Users/guillem/anaconda/envs/_build/lib/python2.7/site-packages
Adding bcbio-monitor 1.0.2 to easy-install.pth file
Installing bcbio-monitor script to /Users/guillem/anaconda/envs/_build/bin
Installing bcbio_monitor script to /Users/guillem/anaconda/envs/_build/bin

Installed /Users/guillem/anaconda/envs/_build/lib/python2.7/site-packages/bcbio_monitor-1.0.2-py2.7.egg
Processing dependencies for bcbio-monitor==1.0.2
Searching for graphviz
Traceback (most recent call last):
  File "setup.py", line 27, in <module>
    install_requires=install_requires
  File "/Users/guillem/anaconda/envs/_build/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/Users/guillem/anaconda/envs/_build/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Users/guillem/anaconda/envs/_build/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/guillem/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/setuptools/command/install.py", line 67, in run
  File "/Users/guillem/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/setuptools/command/install.py", line 117, in do_egg_install
  File "/Users/guillem/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/setuptools/command/easy_install.py", line 389, in run
  File "/Users/guillem/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/setuptools/command/easy_install.py", line 619, in easy_install
  File "/Users/guillem/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/setuptools/command/easy_install.py", line 670, in install_item
  File "/Users/guillem/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/setuptools/command/easy_install.py", line 718, in process_distribution
  File "/Users/guillem/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/pkg_resources/__init__.py", line 836, in resolve
  File "/Users/guillem/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/pkg_resources/__init__.py", line 1081, in best_match
  File "/Users/guillem/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/pkg_resources/__init__.py", line 1093, in obtain
  File "/Users/guillem/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/setuptools/command/easy_install.py", line 626, in easy_install
  File "/Users/guillem/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/setuptools/package_index.py", line 594, in fetch_distribution
  File "/Users/guillem/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/setuptools/package_index.py", line 431, in find_packages
  File "/Users/guillem/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/setuptools/package_index.py", line 765, in scan_url
  File "/Users/guillem/anaconda/envs/_build/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/setuptools/package_index.py", line 283, in process_url
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/graphviz/r
Command failed: /bin/bash -x -e /Users/guillem/repos_and_code/recipes/recipes/bcbio_monitor/build.sh
```

[Here](https://github.com/guillermo-carrasco/recipes/commit/485477f919b0c00273721ee5e93dc3b967be8134) you can find the code for the recipe. As you can see I already included the dependencies in `meta.yml` and it actually seems to install them, but for some reason its not detecting them when installing the package itself. 

Any help would be really appreciated. 

Thank you very much!

**Comment by daler** [comment]
I think the issue here is that there's a `graphviz` Python package on PyPI (the Python package that's supposed to be a dependency here) and a `graphviz` package in the bioconda channel (which has things like the `dot` program). I think the bioconda one wins. Setuptools then tries to install the missing Python graphviz, but conda disallows setuptools downloading which raises the error.

I think the solution is to create a new bioconda recipe called `py-graphviz` or something that builds the Python graphviz package in the bioconda channel, and list that new `py-graphviz` as the dependency in the `bcbio-monitor` package.

**Comment by guillermo-carrasco** [comment]
@daler thanks for the reply :)

I don't quite understand though, if there is already a package in bioconda channel, and it seems to be fetching it, why is is trying to fetch it from PyPi again?

There is no way to specify in that one or the other should be used?

Thank you again,

**Comment by daler** [comment]
It's a name issue: the `graphviz` package fetched from bioconda happens to be the [C graphviz](http://www.graphviz.org/), but what you really want is the [Python graphviz](https://pypi.python.org/pypi/graphviz). 

The trick is to create a Python `graphviz` recipe in bioconda, but name it differently from the existing C `graphviz` so that you can differentiate between them in your `meta.yaml` based on package name alone.

Ideally, we would be able to specify dependencies in a channel-specific manner inside `meta.yaml`. But the [requirement specs](http://conda.pydata.org/docs/spec.html#build-version-spec) really only talk about version numbers, so I don't think this is possible.

**Comment by guillermo-carrasco** [comment]
Aha, now I get it!

Thanks a lot, I'll create that `pygraphviz` recipe :)
