### ISSUE TITLE
mktemp: failed to create directory via template `XXXXXXXXXX': No space left on device

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#2810]
Hi,
I tried to make a recipe for Falcon_unzip, but it failed with the below error. I have 4 TB free partition where conda is installed and therefore I do not understand the first error `mktemp: failed to create directory via template `XXXXXXXXXX': No space left on device`

```
conda build falcon-unzip
BUILD START: falcon_unzip-052016-0
updating index in: /QRISdata/Q0231/apps/conda-bld/linux-64
updating index in: /QRISdata/Q0231/apps/conda-bld/noarch

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2016.8.31  |                0         163 KB  conda-forge
    gmp-6.1.1                  |                0         727 KB  conda-forge
    ncurses-5.9                |                9         954 KB  conda-forge
    sqlite-3.13.0              |                1         4.9 MB  conda-forge
    tk-8.5.19                  |                0         1.9 MB  conda-forge
    zlib-1.2.8                 |                3          87 KB  conda-forge
    isl-0.12.2                 |                0         1.1 MB  r
    mpfr-3.1.4                 |                1         430 KB  conda-forge
    openssl-1.0.2h             |                2         3.4 MB  conda-forge
    readline-6.2               |                0         713 KB  conda-forge
    cloog-0.18.0               |                0         617 KB  r
    mpc-1.0.3                  |                1          93 KB  conda-forge
    python-2.7.12              |                1        15.5 MB  conda-forge
    certifi-2016.8.31          |           py27_0         219 KB  conda-forge
    gcc-4.8.5                  |                6        64.4 MB
    setuptools-26.1.1          |           py27_0         346 KB  conda-forge
    wheel-0.29.0               |           py27_0          81 KB  conda-forge
    pip-8.1.2                  |           py27_0         1.5 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        97.1 MB

The following NEW packages will be INSTALLED:

    ca-certificates: 2016.8.31-0      conda-forge
    certifi:         2016.8.31-py27_0 conda-forge
    cloog:           0.18.0-0         r          
    gcc:             4.8.5-6                     
    gmp:             6.1.1-0          conda-forge
    isl:             0.12.2-0         r          
    mpc:             1.0.3-1          conda-forge
    mpfr:            3.1.4-1          conda-forge
    ncurses:         5.9-9            conda-forge
    openssl:         1.0.2h-2         conda-forge
    pip:             8.1.2-py27_0     conda-forge
    python:          2.7.12-1         conda-forge
    readline:        6.2-0            conda-forge
    setuptools:      26.1.1-py27_0    conda-forge
    sqlite:          3.13.0-1         conda-forge
    tk:              8.5.19-0         conda-forge
    wheel:           0.29.0-py27_0    conda-forge
    zlib:            1.2.8-3          conda-forge

WARNING:/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/build.pyc:Build prefix failed with prefix length 255
WARNING:/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/build.pyc:Error was: 
WARNING:/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/build.pyc:ERROR: placeholder '/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho' too short in: conda-forge::ncurses-5.9-9

WARNING:/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/build.pyc:One or more of your package dependencies needs to be rebuilt with a longer prefix length.
WARNING:/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/build.pyc:Falling back to legacy prefix length of 80 characters.
WARNING:/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/build.pyc:Your package will not install into prefixes > 80 characters.
updating index in: /QRISdata/Q0231/apps/conda-bld/linux-64
updating index in: /QRISdata/Q0231/apps/conda-bld/noarch

The following NEW packages will be INSTALLED:

    ca-certificates: 2016.8.31-0      conda-forge
    certifi:         2016.8.31-py27_0 conda-forge
    cloog:           0.18.0-0         r          
    gcc:             4.8.5-6                     
    gmp:             6.1.1-0          conda-forge
    isl:             0.12.2-0         r          
    mpc:             1.0.3-1          conda-forge
    mpfr:            3.1.4-1          conda-forge
    ncurses:         5.9-9            conda-forge
    openssl:         1.0.2h-2         conda-forge
    pip:             8.1.2-py27_0     conda-forge
    python:          2.7.12-1         conda-forge
    readline:        6.2-0            conda-forge
    setuptools:      26.1.1-py27_0    conda-forge
    sqlite:          3.13.0-1         conda-forge
    tk:              8.5.19-0         conda-forge
    wheel:           0.29.0-py27_0    conda-forge
    zlib:            1.2.8-3          conda-forge

mktemp: failed to create directory via template `XXXXXXXXXX': No space left on device
rm: cannot remove `': No such file or directory
Cloning into bare repository '/QRISdata/Q0231/apps/conda-bld/git_cache/github.com/PacificBiosciences/FALCON_unzip.git'...
remote: Counting objects: 667, done.
remote: Total 667 (delta 0), reused 0 (delta 0), pack-reused 667
Receiving objects: 100% (667/667), 160.58 KiB | 191 KiB/s, done.
Resolving deltas: 100% (350/350), done.
Cloning into '/QRISdata/Q0231/apps/conda-bld/falcon-unzip_1478230330885/work'...
done.
error: unable to create symlink LICENSE (File name too long)
checkout: u'funzip_052016'
Note: checking out 'funzip_052016'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 21b1df3... (1) avoid infinty loop (2) more robust way removing nodes and (3) cosmetic changes
Submodule 'FALCON' (git@github.com:PacificBiosciences/FALCON.git) registered for path 'FALCON'
Cloning into 'FALCON'...
Warning: Permanently added 'github.com' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
Clone of 'git@github.com:PacificBiosciences/FALCON.git' into submodule path 'FALCON' failed
Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
Error was: 
Command '['/opt/rocks/bin/git', 'submodule', 'update', '--init', '--recursive']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/QRISdata/Q0231/apps/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 242, in main
    execute(sys.argv[1:])
  File "/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 234, in execute
    already_built=None, config=config)
  File "/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/api.py", line 77, in build
    need_source_download=need_source_download, config=config)
  File "/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/build.py", line 1070, in build_tree
    config=recipe_config)
  File "/QRISdata/Q0231/apps/lib/python2.7/site-packages/conda_build/build.py", line 652, in build
    assert not need_source_download, "Source download failed.  Please investigate."
AssertionError: Source download failed.  Please investigate.
```

Hear it the recipe:

```
> vi build.sh 
#!/bin/bash
$PYTHON setup.py clean
$PYTHON setup.py install
```

```
vi meta.yaml 

package:
  name: falcon_unzip
  version: 052016

source:
  git_rev: funzip_052016
  git_url: https://github.com/PacificBiosciences/FALCON_unzip.git

requirements:
  build:
    - python
    - setuptools
    - zlib
    - gcc # [linux]
    - llvm  # [osx]

  run:
    - zlib
    - libgcc  # [linux]

test:
  commands:
    - fc_unzip.py

about:
  home: https://github.com/PacificBiosciences/FALCON_unzip
  license: BSD-3-Clause-License
```

What did I do wrong?

Thank you in advance.

Michal

**Comment by daler** [comment]
I don't get the same error you do, but I do get an error about getting submodules. It looks like this repo has a lot of them

```
...
Unable to checkout 'f5ca2a0bb2a5f939da57cc842e02fc7cbf075407' in submodule path 'FALCON/DALIGNER'
Failed to recurse into submodule path 'FALCON'
```

However in general it's better to use the url for the tarball instead, e.g., 

```yaml
source:
    fn: funzip_052016.tar.gz
    url: https://github.com/PacificBiosciences/FALCON_unzip/archive/funzip_052016.tar.gz
```

Using that tarball fixes the submodule errors, but then I get errors about unlisted dependencies not being installed: it tries to download pysam but pysam is not listed in the meta.yaml requirements.

It looks like you'll have to add more dependencies, but hopefully this will get you on the right track.

**Comment by mictadlo** [comment]
Thank you, it did fix my error, but I got a new one https://github.com/PacificBiosciences/FALCON_unzip/issues/42 .

Furthermore, I added the missing dependecies to meta.yaml
```
requirements:
  build:
    - python
    - pysam
    - networkx
    - setuptools
    - zlib
    - gcc # [linux]
    - llvm  # [osx]

  run:
    - python
    - pysam
    - networkx
    - zlib
    - libgcc  # [linux]
```

**Comment by epruesse** [comment]
inactive
