### ISSUE TITLE
Post-link fails for bioconductor-genomeinfodbdata

### ISSUE THREAD

**Issue by LinkMedicine** [bioconda/bioconda-recipes#28801]
I am new to using conda. I am trying to set up an environment on liunix and I ran into an issue.
（for some reasons ,I have to use tsinghua mirror）

**ERROR conda.core.link:_execute(699): An error occurred while installing package 'https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda::bioconductor-genomeinfodbdata-1.2.6-r41hdfd78af_0'.
Rolling back transaction: done
class: LinkError
message:
post-link script failed for package https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda::bioconductor-genomeinfodbdata-1.2.6-r41hdfd78af_0
location of failed script: /THL4/home/jli02/miniconda3/envs/458/bin/.bioconductor-genomeinfodbdata-post-link.sh**
==> script messages <==

==> script output <==
stdout: ERROR: post-link.sh was unable to download any of the following URLs with the md5sum 284d8e9620b22879410faf66007b3852:
https://bioconductor.org/packages/3.13/data/annotation/src/contrib/GenomeInfoDbData_1.2.6.tar.gz
https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.6.tar.gz
https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.6_src_all.tar.gz
stderr: % Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0curl: (56) Received HTTP code 403 from proxy after CONNECT
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0curl: (56) Received HTTP code 403 from proxy after CONNECT
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0curl: (56) Received HTTP code 403 from proxy after CONNECT

return code: 1

kwargs:
{}

Traceback (most recent call last):
File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in call
return func(*args, **kwargs)
File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/cli/main.py", line 84, in _main
exit_code = do_call(args, p)
File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
return getattr(module, func_name)(args, parser)
File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/cli/main_install.py", line 20, in execute
install(args, parser, 'install')
File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/cli/install.py", line 317, in install
handle_txn(unlink_link_transaction, prefix, args, newenv)
File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/cli/install.py", line 346, in handle_txn
unlink_link_transaction.execute()
File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/core/link.py", line 250, in execute
self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/core/link.py", line 713, in _execute
raise CondaMultiError(tuple(concatv(
conda.CondaMultiErrorclass: LinkError
message:
post-link script failed for package https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda::bioconductor-genomeinfodbdata-1.2.6-r41hdfd78af_0
location of failed script: /THL4/home/jli02/miniconda3/envs/458/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==

==> script output <==
stdout: ERROR: post-link.sh was unable to download any of the following URLs with the md5sum 284d8e9620b22879410faf66007b3852:
https://bioconductor.org/packages/3.13/data/annotation/src/contrib/GenomeInfoDbData_1.2.6.tar.gz
https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.6.tar.gz
https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.6_src_all.tar.gz

stderr: % Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0curl: (56) Received HTTP code 403 from proxy after CONNECT
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0curl: (56) Received HTTP code 403 from proxy after CONNECT
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0curl: (56) Received HTTP code 403 from proxy after CONNECT

return code: 1

kwargs:
{}

: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/THL4/home/jli02/miniconda3/bin/conda", line 13, in
sys.exit(main())
File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/cli/main.py", line 152, in main
return conda_exception_handler(_main, *args, **kwargs)
File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1371, in conda_exception_handler
return_value = exception_handler(func, *args, **kwargs)
File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1082, in call
return self.handle_exception(exc_val, exc_tb)
File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1113, in handle_exception
return self.handle_application_exception(exc_val, exc_tb)
File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1129, in handle_application_exception
self._print_conda_exception(exc_val, exc_tb)
File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1133, in _print_conda_exception
print_conda_exception(exc_val, exc_tb)
File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1056, in print_conda_exception
stderrlog.error("\n%r\n", exc_val)
File "/THL4/home/jli02/miniconda3/lib/python3.9/logging/init.py", line 1471, in error
self._log(ERROR, msg, args, **kwargs)
File "/THL4/home/jli02/miniconda3/lib/python3.9/logging/init.py", line 1585, in _log
self.handle(record)
File "/THL4/home/jli02/miniconda3/lib/python3.9/logging/init.py", line 1594, in handle
if (not self.disabled) and self.filter(record):
File "/THL4/home/jli02/miniconda3/lib/python3.9/logging/init.py", line 802, in filter
result = f.filter(record)
File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/gateways/logging.py", line 60, in filter
record.msg = record.msg % new_args
File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/init.py", line 126, in repr
errs.append(e.repr())
File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/init.py", line 65, in repr
return '%s: %s' % (self.class.name, text_type(self))
File "/THL4/home/jli02/miniconda3/lib/python3.9/site-packages/conda/init.py", line 84, in str
return text_type(self.message % self._kwargs)
ValueError: unsupported format character 'T' (0x54) at index 739

**Comment by dlaehnemann** [comment]
I'm guessing that this was due to the packages being really new up on bioconda. So maybe there was a timing issue where the packages weren't properly up at those respective sites, so couldn't be downloaded. @LinkMedicine Do you still see this issue, or can this issue be closed?

**Comment by ranjanmanishblue** [comment]
I have been same issue installing qiime2 on ubuntu miniconda env. 
the error is:
class: LinkError
message:
post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.4-r40hdfd78af_2
why this error comes?

**Comment by LinkMedicine** [comment]
> I have been same issue installing qiime2 on ubuntu miniconda env. the error is: class: LinkError message: post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.4-r40hdfd78af_2 why this error comes?

well,I solved this problem by downloading the R-packages by myself and upload it into our lab service  installing it with R instruction. The problem happens when  I install some R packages with conda. When u install those packages, conda first download a bash,and run it.If the bash needs to connect to some certain websites that u cant open by your own service,this error will happen.

**Comment by ranjanmanishblue** [comment]
> > I have been same issue installing qiime2 on ubuntu miniconda env. the error is: class: LinkError message: post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.4-r40hdfd78af_2 why this error comes?
> 
> well,I solved this problem by downloading the R-packages by myself and upload it into our lab service installing it with R instruction. The problem happens when I install some R packages with conda. When u install those packages, conda first download a bash,and run it.If the bash needs to connect to some certain websites that u cant open by your own service,this error will happen.

Yes this seems to be the reason, however i just tried to reinstall qiime2 without any proxy settings (removing proxy setting from everywhere on my system including condarc, bash.bashrc, apt.conf etc files) on system and with other internet connections , it worked fine giving no error.

**Comment by neenah13** [comment]
Hello all, I have this issue when installing it on Ubuntu 20.04.4 LTS. However when i install it on my server which is Ubuntu 18.04.6 LTS, it installs PERFECTLY. I don't know if you should use a lower ubuntu version but qiime2 definitely works on it. Thank you. Have a good day!

**Comment by athenasyarifa** [comment]
Hi all, 

I have exactly the same issue. I tried downloading the tar and install it via R while activating my conda environment, but it still doesn't work. I guess because I am trying to install the package via snakemake batch job. Any help would be appreciated. 

I also check that they have a new tar version here: https://www.bioconductor.org/packages/release/data/annotation/src/contrib/GenomeInfoDbData_1.2.14.tar.gz

Cheers, 
Rifa

**Comment by bobermayer** [comment]
in our case this is caused by newer versions of openssl (see https://github.com/bioconda/bioconda-recipes/issues/11485#issuecomment-3275159913)
