### ISSUE TITLE
Medaka 1.4.3: ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found when running "quay.io/biocontainers/medaka:1.4.3--py38h130def0_0" Docker container

### ISSUE THREAD

**Issue by peterk87** [bioconda/bioconda-recipes#29483]
Running Medaka v1.4.3 command `medaka_variant` with the [quay.io/biocontainers/medaka:1.4.3--py38h130def0_0](https://quay.io/repository/biocontainers/medaka?tag=1.4.3--py38h130def0_0&tab=tags) Docker container produces the following error message:

```
  Traceback (most recent call last):
    File "/usr/local/bin/medaka", line 7, in <module>
      from medaka.medaka import main
    File "/usr/local/lib/python3.8/site-packages/medaka/medaka.py", line 9, in <module>
      import medaka.features
    File "/usr/local/lib/python3.8/site-packages/medaka/features.py", line 17, in <module>
      import medaka.labels
    File "/usr/local/lib/python3.8/site-packages/medaka/labels.py", line 15, in <module>
      import medaka.rle
    File "/usr/local/lib/python3.8/site-packages/medaka/rle.py", line 16, in <module>
      import medaka.smolecule
    File "/usr/local/lib/python3.8/site-packages/medaka/smolecule.py", line 10, in <module>
      import mappy
  ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by .../.local/lib/python3.8/site-packages/mappy.cpython-38-x86_64-linux-gnu.so)
```

The container has `libc6_2.28-10_amd64.deb` installed and the following label:

```
glibc: GNU C Library (Debian GLIBC 2.28-10) stable release version 2.28.
```

The `medaka_variant` command works when running with Medaka installed with Conda into a new env.

**Comment by peterk87** [comment]
For some reason, when running Medaka using Docker with Nextflow, it was trying to use a locally installed version of Mappy (`~/.local/lib/python3.8/site-packages/mappy.cpython-38-x86_64-linux-gnu.so`) instead of Mappy in the container. When I removed the locally installed version, `medaka_variant` was able to run without issue.
