### ISSUE TITLE
Problems with Pysam

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#2949]
Hi, 
I tried to create a `conda` package for GenomicConsensus with the following steps:

```
#!/bin/bash

$PYTHON setup.py clean
$PYTHON setup.py install
```

```
> vi recipes/GenomicConsensus/meta.yaml 

package:
  name: python-genomicconsensus
  version: 1.0.0

source:
  git_rev: 1.0.0
  git_url: https://github.com/PacificBiosciences/GenomicConsensus.git

requirements:
  build:
    - python
    - python-consensuscore
    - pysam
    - numpy
    - setuptools
    - zlib
    - gcc # [linux]

  run:
    - python
    - boost
    - numpy
    - zlib
    - libgcc  # [linux]

test:
  commands:
    - fc_unzip.py

about:
  home: https://github.com/PacificBiosciences/
```

```
Unfortunately, I have got this error:

Installed /QRISdata/Q0231/apps/conda-bld/GenomicConsensus_1479177051376/_b_env_placehold_p/lib/python2.7/site-packages/GenomicConsensus-1.0.0-py2.7.egg
Processing dependencies for GenomicConsensus==1.0.0
Searching for pysam==0.8.1
Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    'pysam == 0.8.1'
  File "/QRISdata/Q0231/apps/conda-bld/GenomicConsensus_1479177051376/_b_env_placehold_p/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/QRISdata/Q0231/apps/conda-bld/GenomicConsensus_1479177051376/_b_env_placehold_p/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/QRISdata/Q0231/apps/conda-bld/GenomicConsensus_1479177051376/_b_env_placehold_p/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/QRISdata/Q0231/apps/conda-bld/GenomicConsensus_1479177051376/_b_env_placehold_p/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/QRISdata/Q0231/apps/conda-bld/GenomicConsensus_1479177051376/_b_env_placehold_p/lib/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/QRISdata/Q0231/apps/conda-bld/GenomicConsensus_1479177051376/_b_env_placehold_p/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 410, in run
    self.easy_install(spec, not self.no_deps)
  File "/QRISdata/Q0231/apps/conda-bld/GenomicConsensus_1479177051376/_b_env_placehold_p/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 646, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/QRISdata/Q0231/apps/conda-bld/GenomicConsensus_1479177051376/_b_env_placehold_p/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 697, in install_item
    self.process_distribution(spec, dist, deps)
  File "/QRISdata/Q0231/apps/conda-bld/GenomicConsensus_1479177051376/_b_env_placehold_p/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 742, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/QRISdata/Q0231/apps/conda-bld/GenomicConsensus_1479177051376/_b_env_placehold_p/lib/python2.7/site-packages/pkg_resources/__init__.py", line 850, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/QRISdata/Q0231/apps/conda-bld/GenomicConsensus_1479177051376/_b_env_placehold_p/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1122, in best_match
    return self.obtain(req, installer)
  File "/QRISdata/Q0231/apps/conda-bld/GenomicConsensus_1479177051376/_b_env_placehold_p/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1134, in obtain
    return installer(requirement)
  File "/QRISdata/Q0231/apps/conda-bld/GenomicConsensus_1479177051376/_b_env_placehold_p/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 653, in easy_install
    not self.always_copy, self.local_index
  File "/QRISdata/Q0231/apps/conda-bld/GenomicConsensus_1479177051376/_b_env_placehold_p/lib/python2.7/site-packages/setuptools/package_index.py", line 639, in fetch_distribution
    self.find_packages(requirement)
  File "/QRISdata/Q0231/apps/conda-bld/GenomicConsensus_1479177051376/_b_env_placehold_p/lib/python2.7/site-packages/setuptools/package_index.py", line 480, in find_packages
    self.scan_url(self.index_url + requirement.unsafe_name + '/')
  File "/QRISdata/Q0231/apps/conda-bld/GenomicConsensus_1479177051376/_b_env_placehold_p/lib/python2.7/site-packages/setuptools/package_index.py", line 812, in scan_url
    self.process_url(url, True)
  File "/QRISdata/Q0231/apps/conda-bld/GenomicConsensus_1479177051376/_b_env_placehold_p/lib/python2.7/site-packages/setuptools/package_index.py", line 317, in process_url
    "Be sure to add all dependencies in the meta.yaml  url=%sr" % url)
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/pysam/r
Command failed: /bin/bash -x -e /QRISdata/Q0231/apps/conda-bld/GenomicConsensus_1479177051376/work/conda_build.sh
```

What did I do?

Thank you in advance.

Mic

**Comment by kyleabeauchamp** [comment]
Your setup.py has a hard-coded pysam version requirement but your recipe allows any version.  These two are not compatible.

**Comment by mictadlo** [comment]
Thank you, but now I got:

```
mport: u'pysam'
import: u'pysam.include'
import: u'pysam.include.htslib'
Traceback (most recent call last):
  File "/QRISdata/Q0231/apps/conda-bld/pysam_1479186475267/test_tmp/run_test.py", line 33, in <module>
    import pysam.include.htslib
ImportError: No module named htslib
TESTS FAILED: pysam-0.8.1-py27_0
```

After I did:

1. conda skeleton pypi --version 0.8.1 pysam
2. conda build pysam

What did I do miss ?

Thank you in advance.

Mic

**Comment by druvus** [comment]
I was looking at the setup.py file and I see a mismatch between your listed requirements and the ones in setup.py. 

I would suggest a meta.yaml that looks like this. Seems that the tool is written for py27 so skipping all other python versions. It is also recommended to use an url instead of get_rev.

You need to fix recipes for pbcore and pbcommand before trying to build this. 

```
{% set name = "python-genomicconsensus" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name|lower }}_{{ version }}.tar.gz
  url: https://github.com/PacificBiosciences/GenomicConsensus/archive/1.0.0.tar.gz
  md5: e78170019cae6554fd5c693323e32605

build:
  skip: True # [not py27]

requirements:
  build:
    - python
    - setuptools
    - gcc # [not osx]
    - llvm # [osx]
    - h5py >=2.0.1
    - numpy >=1.6.0
    - python-consensuscore >=1.0.1
    - pbcommand >=0.3.20
    - pbcore >=1.2.9

  run:
    - python
    - libgcc  # [osx]
    - h5py >=2.0.1
    - numpy >=1.6.0
    - python-consensuscore >=1.0.1
    - pbcommand >=0.3.20
    - pbcore >=1.2.9

test:
  commands:
    - fc_unzip.py

about:
  home: https://github.com/PacificBiosciences/GenomicConsensus
  license: BSD-3-Clause
  summary: 'PacBio variant and consensus caller'
```

**Comment by druvus** [comment]
@mictadlo I submitted a pcbore PR #2953

**Comment by druvus** [comment]
@mictadlo here is pbcommand #2963

**Comment by bgruening** [comment]
That's community! Thanks a bunch @druvus!

**Comment by mictadlo** [comment]
Thank you @druvus . How is it possible to use your recipes?

**Comment by druvus** [comment]
I haven't merged them yet. I am a little bit unsure if we should use the `python-` prefix or not. Right now I added it because of `python-consensuscore` also used it. 

python-consensuscore is already in the bioconda channel so I think you need to add the correct channels to your setup. Please read the instructions [here](https://github.com/bioconda/bioconda-recipes#step-2-test-the-recipe).

**Comment by druvus** [comment]
I was going through pacbio tools and only consensuscore use the the python prefix so I dropped it from the new packages and they will be ready soon. Various pacbio tools are on my todo list so I am happy to help.

**Comment by mictadlo** [comment]
Thank you for doing it. `python-consensuscore` exist only 1.0.0. I am also interested in FALCON_unzip, but it apparently will require FALCON 1.8.0 [see](https://github.com/PacificBiosciences/FALCON_unzip/issues/44#issuecomment-259034142)

**Comment by druvus** [comment]
I bumped 'python-consensuscore' and 'pbcommand' yesterday so the needed versions are available now. 

They are strictly asking for pysam==0.8.1 that also needs to be built. It exist a recipe for 0.8.3 but I am not sure it is working. pysam 0.8.3 depends on samtools 1.2 while pysam 0.8.1 depends on samtools 1.1. More info [here](http://pysam.readthedocs.io/en/latest/release.html).

**Comment by mictadlo** [comment]
Thank you for your help. I submitted a [PR](https://github.com/bioconda/bioconda-recipes/pull/3016)
