### ISSUE TITLE
simulate-travis.py failure reporting

### ISSUE THREAD

**Issue by mvdbeek** [bioconda/bioconda-recipes#2977]
I had forgotten to add my current user to the docker group, and simulate-travis.py was failing with exit code 127 (command not found). This took me quite a while to figure out.
I guess it would be helpful to report the stderr of whatever command returns a non-zero exit code.

**Comment by mvdbeek** [comment]
Or another instance, now it's probably lack of online connectivity, because the PROXY env vars are not passed on to docker build:
```
(.venv) marius@bardin-gx:~/src/bioconda-recipes$ BIOCONDA_UTILS_TAG="exit-code-check" ./simulate-travis.py --packages cityhash
+ bioconda-utils build recipes config.yml --docker --loglevel=info --mulled-test --packages cityhash
INFO bioconda_utils.docker_utils:_pull_image(302): BIOCONDA DOCKER: Pulling docker image condaforge/linux-anvil
INFO bioconda_utils.docker_utils:_pull_image(308): BIOCONDA DOCKER: Done pulling image
Traceback (most recent call last):
  File "/home/marius/conda3/bin/bioconda-utils", line 11, in <module>
    load_entry_point('bioconda-utils==0.9.0', 'console_scripts', 'bioconda-utils')()
  File "/home/marius/conda3/lib/python3.5/site-packages/bioconda_utils/cli.py", line 172, in main
    argh.dispatch_commands([build, dag, dependent])
  File "/home/marius/conda3/lib/python3.5/site-packages/argh-0.26.2-py3.5.egg/argh/dispatching.py", line 328, in dispatch_commands
  File "/home/marius/conda3/lib/python3.5/site-packages/argh-0.26.2-py3.5.egg/argh/dispatching.py", line 174, in dispatch
  File "/home/marius/conda3/lib/python3.5/site-packages/argh-0.26.2-py3.5.egg/argh/dispatching.py", line 277, in _execute_command
  File "/home/marius/conda3/lib/python3.5/site-packages/argh-0.26.2-py3.5.egg/argh/dispatching.py", line 260, in _call
  File "/home/marius/conda3/lib/python3.5/site-packages/bioconda_utils/cli.py", line 92, in build
    conda_build_version=conda_build_version,
  File "/home/marius/conda3/lib/python3.5/site-packages/bioconda_utils/docker_utils.py", line 296, in __init__
    self._build_image()
  File "/home/marius/conda3/lib/python3.5/site-packages/bioconda_utils/docker_utils.py", line 339, in _build_image
    p = utils.run(cmd)
  File "/home/marius/conda3/lib/python3.5/site-packages/bioconda_utils/utils.py", line 68, in run
    raise e
  File "/home/marius/conda3/lib/python3.5/site-packages/bioconda_utils/utils.py", line 64, in run
    p = sp.run(cmds, stdout=sp.PIPE, stderr=sp.STDOUT, check=True, env=env)
  File "/home/marius/conda3/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'tmp-bioconda-builder', '/tmp/tmp7h4t2_gw']' returned non-zero exit status 1
Traceback (most recent call last):
  File "./simulate-travis.py", line 150, in <module>
    sp.run(['scripts/travis-run.sh'], env=env, universal_newlines=True, check=True)
  File "/home/marius/conda3/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['scripts/travis-run.sh']' returned non-zero exit status 1
```
I guess the call to subprocess.run should be wrapped in a try except statement, so that docker's stdout and stderr can be reported?

**Comment by daler** [comment]
`simulate-travis.py` is a Python script using subprocess to call the bash script `travis-run.sh` used on travis-ci, which in turn is calling the Python CLI tool `bioconda-utils`, which in turn is calling docker in a subprocess call (!). So the trick is to get the docker call to be more verbose rather than a try/except in simulate-travis. I think [this commit](https://github.com/bioconda/bioconda-utils/pull/35/commits/d05f55b7ca0de26fa660bf053d0fa7eefe58d88c) should do it.

In bioconda-utils I was originally sending all of `/usr/bin/env` over to docker, but that caused lots of subtle issues during testing. So I restricted the env vars. Clearly not a good idea for proxies. I'll expose a way of configuring simulate-travis to specify which additional env vars should be exported to docker.

**Comment by mvdbeek** [comment]
> So the trick is to get the docker call to be more verbose rather than a try/except in simulate-travis. I think this commit should do it.

yep, that looks good.

> So I restricted the env vars. Clearly not a good idea for proxies. I'll expose a way of configuring simulate-travis to specify which additional env vars should be exported to docker.

yeah, I realize this is quite the corner-case, and a bit tricky to get right. I just switched to cloud machines, they're faster anyway. Thanks for working on this!

**Comment by daler** [comment]
I think I'm going to hold off for now on the env-var-to-docker stuff, but please feel free to open a PR on bioconda-utils.
