### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#3088]
Hi,
I tried to update MHAP to the latest version, but I ran into the following problem:

```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mhap-2.1.1                 |                0         728 KB  local

The following NEW packages will be INSTALLED:

    java-jdk: 8.0.92-1 bioconda
    mhap:     2.1.1-0  local   

+ source /QRISdata/Q0231/apps/bin/activate /QRISdata/Q0231/apps/conda-bld/mhap_1480654640827/_t_env
+ /bin/bash -x -e /QRISdata/Q0231/apps/conda-bld/mhap_1480654640827/test_tmp/run_test.sh
+ mhap -h
+ grep -q MHAP:
Exception in thread "main" java.lang.UnsupportedClassVersionError: edu/umd/marbl/mhap/main/MhapMain : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
TESTS FAILED: mhap-2.1.1-0
```

`vi recipes/mhap/build.sh`
```
#!/bin/bash

outdir=$PREFIX/share/$PKG_NAME-$PKG_VERSION-$PKG_BUILDNUM
mkdir -p $outdir
mkdir -p $PREFIX/bin
cd $SRC_DIR
gunzip mhap-2.1.1.jar.gz
cp $SRC_DIR/mhap-2.1.1.jar $outdir/
cp $RECIPE_DIR/mhap $outdir/
chmod +x $outdir/mhap
ln -s $outdir/mhap $PREFIX/bin
```

`vi recipes/mhap/meta.yaml `
```
package:
  name: mhap
  version: "2.1.1"

source:
  fn: mhap-2.1.1.jar.gz
  url: https://github.com/marbl/MHAP/releases/download/v2.1.1/mhap-2.1.1.jar.gz
  md5: fcc79d0b7483d55d3d4d744c860bbceb

build:
  detect_binary_files_with_prefix: True
  number: 0
  skip: False

requirements:
  run:
    - java-jdk

test:
  commands:
    - "mhap -h  | grep -q 'MHAP:'"

about:
  home: https://github.com/marbl/MHAP
  license: Apache License 2.0
  summary: 'MHAP: MinHash Alignment Protocol. A tool for finding overlaps of long-read sequences (such as PacBio or Nanopore) in bioinformatics.'                                                                                                                                                  
```

What did I miss?

Thank you in advance.

Michal

**Comment by bgruening** [comment]
@mictadlo this seems to be a error of this specific program. Can you please ask upstream?
