### ISSUE TITLE
Post-link fails for bioconductor-genomeinfodbdata

### ISSUE THREAD

**Issue by khyox** [bioconda/bioconda-recipes#31349]
I'm experiencing something similar to #13846 and would appreciate if you can try to reproduce it. I eventually tried with a fresh Miniconda installation followed by `conda update conda` and install just the package, but the issue is still there:

```
(base) $ conda install -c bioconda bioconductor-genomeinfodbdata
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /ubiome/conda

  added / updated specs:
    - conda

(...)
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(699): An error occurred while installing package 'bioconda::bioconductor-genomeinfodbdata-1.2.2-r36_0'.
Rolling back transaction: done
class: LinkError
message:
post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.2-r36_0
location of failed script: /ubiome/conda/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: ERROR: post-link.sh was unable to download any of the following URLs with the md5sum 64c8f7158601272355f9686235dcb7e1:
https://bioconductor.org/packages/3.10/data/annotation/src/contrib/GenomeInfoDbData_1.2.2.tar.gz
https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.2.tar.gz
https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.2_src_all.tar.gz

stderr:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:00 --:--:--     0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to bioarchive.galaxyproject.org:443 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:00 --:--:--     0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to depot.galaxyproject.org:443 

return code: 1

kwargs:
{}

Traceback (most recent call last):
  File "/ubiome/conda/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/ubiome/conda/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/ubiome/conda/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
    return getattr(module, func_name)(args, parser)
  File "/ubiome/conda/lib/python3.8/site-packages/conda/cli/main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "/ubiome/conda/lib/python3.8/site-packages/conda/cli/install.py", line 317, in install
    handle_txn(unlink_link_transaction, prefix, args, newenv)
  File "/ubiome/conda/lib/python3.8/site-packages/conda/cli/install.py", line 346, in handle_txn
    unlink_link_transaction.execute()
  File "/ubiome/conda/lib/python3.8/site-packages/conda/core/link.py", line 250, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "/ubiome/conda/lib/python3.8/site-packages/conda/core/link.py", line 713, in _execute
    raise CondaMultiError(tuple(concatv(
conda.CondaMultiErrorclass: LinkError
message:
post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.2-r36_0
location of failed script: /ubiome/conda/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: ERROR: post-link.sh was unable to download any of the following URLs with the md5sum 64c8f7158601272355f9686235dcb7e1:
https://bioconductor.org/packages/3.10/data/annotation/src/contrib/GenomeInfoDbData_1.2.2.tar.gz
https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.2.tar.gz
https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.2_src_all.tar.gz

stderr:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:00 --:--:--     0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to bioarchive.galaxyproject.org:443 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:00 --:--:--     0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to depot.galaxyproject.org:443 

return code: 1

kwargs:
{}

: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ubiome/conda/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/ubiome/conda/lib/python3.8/site-packages/conda/cli/main.py", line 152, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "/ubiome/conda/lib/python3.8/site-packages/conda/exceptions.py", line 1371, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/ubiome/conda/lib/python3.8/site-packages/conda/exceptions.py", line 1082, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/ubiome/conda/lib/python3.8/site-packages/conda/exceptions.py", line 1113, in handle_exception
    return self.handle_application_exception(exc_val, exc_tb)
  File "/ubiome/conda/lib/python3.8/site-packages/conda/exceptions.py", line 1129, in handle_application_exception
    self._print_conda_exception(exc_val, exc_tb)
  File "/ubiome/conda/lib/python3.8/site-packages/conda/exceptions.py", line 1133, in _print_conda_exception
    print_conda_exception(exc_val, exc_tb)
  File "/ubiome/conda/lib/python3.8/site-packages/conda/exceptions.py", line 1056, in print_conda_exception
    stderrlog.error("\n%r\n", exc_val)
  File "/ubiome/conda/lib/python3.8/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/ubiome/conda/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/ubiome/conda/lib/python3.8/logging/__init__.py", line 1598, in handle
    if (not self.disabled) and self.filter(record):
  File "/ubiome/conda/lib/python3.8/logging/__init__.py", line 811, in filter
    result = f.filter(record)
  File "/ubiome/conda/lib/python3.8/site-packages/conda/gateways/logging.py", line 60, in filter
    record.msg = record.msg % new_args
  File "/ubiome/conda/lib/python3.8/site-packages/conda/__init__.py", line 126, in __repr__
    errs.append(e.__repr__())
  File "/ubiome/conda/lib/python3.8/site-packages/conda/__init__.py", line 65, in __repr__
    return '%s: %s' % (self.__class__.__name__, text_type(self))
  File "/ubiome/conda/lib/python3.8/site-packages/conda/__init__.py", line 84, in __str__
    return text_type(self.message % self._kwargs)
ValueError: unsupported format character 'T' (0x54) at index 676
```

I originally run into this issue at the end of a [QIIME installation](https://docs.qiime2.org/2021.8/install/native/), which then breaks. Some further info in case it helps:

```
(base) $ conda info        

     active environment : base
    active env location : /ubiome/conda
            shell level : 1
       user config file : /home/ubiome/.condarc
 populated config files : 
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.8.10.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /ubiome/conda  (writable)
      conda av data dir : /ubiome/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /ubiome/conda/pkgs
                          /ubiome/.conda/pkgs
       envs directories : /ubiome/conda/envs
                          /ubiome/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.8.10 Linux/3.10.0-1160.36.2.1chaos.ch6.x86_64 rhel/7.9 glibc/2.17
                UID:GID : 54738:54738
             netrc file : None
           offline mode : False
```

Thanks!

**Comment by ttbond** [comment]
Exactly the same problem!

**Comment by ranjanmanishblue** [comment]
Same problem
no reply from anyone?

**Comment by bgruening** [comment]
> stdout: ERROR: post-link.sh was unable to download any of the following URLs with the md5sum 64c8f7158601272355f9686235dcb7e1:
https://bioconductor.org/packages/3.10/data/annotation/src/contrib/GenomeInfoDbData_1.2.2.tar.gz
https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.2.tar.gz
https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.2_src_all.tar.gz


Try to download those files and check the checksum. I assume they changed and we need to update the package.

**Comment by ranjanmanishblue** [comment]
https://bioconductor.org/packages/3.10/data/annotation/src/contrib/GenomeInfoDbData_1.2.2.tar.gz
https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.2.tar.gz
https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.2_src_all.tar.gz

https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.2.tar.gz **this link is not working.**

Anyway, even if you got these files what to do with them?

**Comment by khyox** [comment]
Many thanks @bgruening! Is there any timeline for updating the package? Thanks.

**Comment by dlaehnemann** [comment]
> https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.2.tar.gz **this link is not working.**

I guess this explains, why the bioarchive package isn't there:
https://github.com/bioconda/bioconda-recipes/pull/23728#issuecomment-668663952

From what I understand, it would only be archived there, if bioconductor removed it. So this is a mechanism to keep the package usable, even if bioconductor removed it, but it will only kick in upon removal.

**Comment by khyox** [comment]
Thanks @dlaehnemann. From [Home/GenomeInfoDB/1.13.4](https://bioarchive.galaxyproject.org/#/pkg/GenomeInfoDb/1.13.4/) should then the link be updated to [https://bioarchive.galaxyproject.org/GenomeInfoDb_1.13.4.tar.gz](https://bioarchive.galaxyproject.org/GenomeInfoDb_1.13.4.tar.gz) without `Data` in the filename?

**Comment by dlaehnemann** [comment]
Nope, I think these are actually distinct bioconductor packages:
* https://www.bioconductor.org/packages/release/bioc/html/GenomeInfoDb.html
* https://www.bioconductor.org/packages/release/data/annotation/html/GenomeInfoDbData.html

**Comment by khyox** [comment]
Thanks @dlaehnemann! It seems the GenomeInfoDbData package is not available anymore from galaxyproject (https://bioarchive.galaxyproject.org/#/pkg/GenomeInfoDb/ is there but not https://bioarchive.galaxyproject.org/#/pkg/GenomeInfoDbData/). So, resorting to that URL if the download from bioconductor fails doesn't look like a good idea.

**Comment by khyox** [comment]
Hi @neenah13, I was unable to finish the conda QIIME2 installation due to this problem, so I resorted to containers. Since my target platform are HPC systems, I prepared a [singularity](https://github.com/sylabs/singularity) container in May and uploaded it to the sylabs cloud library in case it may be useful to others: https://cloud.sylabs.io/library/khyox/metagen/qiime2-core

**Comment by neenah13** [comment]
Hello all, I have this issue when installing it on Ubuntu 20.04.4 LTS. However when i install it on my server which is Ubuntu  18.04.6 LTS, it installs PERFECTLY. I don't know if you should use a lower ubuntu version but qiime2 definitely works on it. Thank you. Have a good day!
