### ISSUE TITLE
Lint failure in recent pull requests

### ISSUE THREAD

**Issue by bkille** [bioconda/bioconda-recipes#33283]
It looks like a number of recent bioconda PRs have been failing the lint step due to an incompatibility between Jinja2 and Markupsafe. The output is below:
```
Starting: Lint
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.198.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/usr/bin/bash /home/vsts/work/_temp/b2ee24dd-62a9-4f5e-8214-5c8f32884be6.sh
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/bioconda/bin/bioconda-utils", line 6, in <module>
    from bioconda_utils.cli import main
  File "/usr/share/miniconda/envs/bioconda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 28, in <module>
    from . import utils
  File "/usr/share/miniconda/envs/bioconda/lib/python3.7/site-packages/bioconda_utils/utils.py", line 36, in <module>
    import jinja2
  File "/usr/share/miniconda/envs/bioconda/lib/python3.7/site-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/share/miniconda/envs/bioconda/lib/python3.7/site-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/usr/share/miniconda/envs/bioconda/lib/python3.7/site-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/usr/share/miniconda/envs/bioconda/lib/python3.7/site-packages/jinja2/utils.py", line 642, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/share/miniconda/envs/bioconda/lib/python3.7/site-packages/markupsafe/__init__.py)
##[error]Bash exited with code '1'.
Finishing: Lint
```

**Comment by sfchen** [comment]
+1

**Comment by sfchen** [comment]
This issue is blocking a lot of auto-bump version upgrade.

**Comment by pmb59** [comment]
+1

**Comment by marcelm** [comment]
This issue has been addressed by @dpryan79. On Gitter, this is what he said:
> If you made a PR in the last couple days that's failed linting due to some cannot import name 'soft_unicode' from 'markupsafe' error, then please rerun the tests on your PR. I've switched to an updated version of bioconda-utils that doesn't produce that. Please note that our pinnings have slightly changed in the process and I only just now started the migration for that in the bulk branch. Thus, it's possible that some dependencies in bioconda will not yet exist. In such cases please wait a week or so for me to get the migration through and try again. I'll try to manually retrigger some of the affected PRs over time as well.
