### ISSUE TITLE
Missing file 'conda_build_config_0_-e_conda_build_config.yaml'

### ISSUE THREAD

**Issue by mahesh-panchal** [bioconda/bioconda-recipes#34924]
Hi, I'm trying to figure out a missing dependency for the merqury package necessary for the container images, but I don't understand how to build the images 'locally'.

## Problem

Trying to build 'locally' I get the following error.
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/gitpod/miniconda3/envs/bioconda/conda-bld/conda_build_config_0_-e_conda_build_config.yaml'
```

## Steps to reproduce

Make a fork of this repo, and then open in Gitpod, by prefixing the repository with 'https://gitpod.io/#' E.g. https://gitpod.io/#https://github.com/mahesh-panchal/bioconda-recipes/.
Modify the file `https://github.com/mahesh-panchal/bioconda-recipes/tree/master/recipes/merqury/meta.yaml` on line 27 to add the dependency of `  - mscorefonts`
Install the environment for building.
```
cd /workspace
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
# accept license, etc
# install mamba
conda install mamba -n base -c conda-forge
conda init
# open new terminal
# follow instructions here: https://bioconda.github.io/contributor/building-locally.html
mamba create -n bioconda -c conda-forge -c bioconda bioconda-utils
conda activate bioconda
# optional linting
bioconda-utils lint --git-range master
# build and test
bioconda-utils build --docker --mulled-test --git-range master
```
which results in :
```
(bioconda) gitpod /workspace/bioconda-recipes (master) $ bioconda-utils build --docker --mulled-test --git-range master
INFO:bioconda_utils.cli:Considering total of 8362 recipes.
12:21:14 BIOCONDA INFO Considering total of 8362 recipes.
INFO:bioconda_utils.cli:Constraining to 0 git modified recipes.
12:21:14 BIOCONDA INFO Constraining to 0 git modified recipes.
INFO:bioconda_utils.cli:Processing 0 recipes.
12:21:14 BIOCONDA INFO Processing 0 recipes.
Traceback (most recent call last):
  File "/home/gitpod/miniconda3/envs/bioconda/bin/bioconda-utils", line 10, in <module>
    sys.exit(main())
  File "/home/gitpod/miniconda3/envs/bioconda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 971, in main
    bioconductor_skeleton, clean_cran_skeleton, autobump, bot
  File "/home/gitpod/miniconda3/envs/bioconda/lib/python3.7/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/home/gitpod/miniconda3/envs/bioconda/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/gitpod/miniconda3/envs/bioconda/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/gitpod/miniconda3/envs/bioconda/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "<boltons.funcutils.FunctionBuilder-5>", line 2, in build
  File "/home/gitpod/miniconda3/envs/bioconda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 130, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-4>", line 2, in build
  File "/home/gitpod/miniconda3/envs/bioconda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 59, in wrapper
    func(*args, **kwargs)
  File "/home/gitpod/miniconda3/envs/bioconda/lib/python3.7/site-packages/bioconda_utils/cli.py", line 453, in build
    build_image=build_image,
  File "/home/gitpod/miniconda3/envs/bioconda/lib/python3.7/site-packages/bioconda_utils/docker_utils.py", line 300, in __init__
    shutil.copyfile(config_file.path, dst_file)
  File "/home/gitpod/miniconda3/envs/bioconda/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/gitpod/miniconda3/envs/bioconda/conda-bld/conda_build_config_0_-e_conda_build_config.yaml'
```
What have I missed? Is there a better way I can test what's missing in the Biocontainer?

**Comment by Colelyman** [comment]
I am running into this error as well! I'm on Mac OS Monterey 12.1 with mamba 0.19.0 and conda 4.11.0.
