### ISSUE TITLE
GATK4 bioconda recipe missing gcnvkernel

### ISSUE THREAD

**Issue by ryanjameskennedy** [bioconda/bioconda-recipes#35390]
I'm trying to update gatk4's bioconda recipe to include gcnvkernel (a python package required for gatk4's germline cnv caller). However, when adding gcnvkernel to the requirements and introducing an import test, I get build failed errors [bioconda/bioconda-recipes#35164](https://github.com/bioconda/bioconda-recipes/issues/35164). Any help on what I'm doing wrong is appreciated.

**Comment by lecorguille** [comment]
We have the same issue here.

What I naively observe is that gcnvkernel isn't import at all when I try to install gatk4

```
[glecorguille@clust-slurm-client ~]$ conda create -c conda-forge -c bioconda -n gatk4-4.2.6.1-test  gatk4=4.2.6.1
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.1
  latest version: 4.13.0

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /shared/home/glecorguille/.conda/envs/gatk4-4.2.6.1-test

  added / updated specs:
    - gatk4=4.2.6.1


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    setuptools-63.1.0          |  py310hff52083_0         1.4 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         1.4 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_gnu
  alsa-lib           conda-forge/linux-64::alsa-lib-1.2.6.1-h7f98852_0
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h7f98852_4
  ca-certificates    conda-forge/linux-64::ca-certificates-2022.6.15-ha878542_0
  cairo              conda-forge/linux-64::cairo-1.16.0-ha61ee94_1011
  expat              conda-forge/linux-64::expat-2.4.8-h27087fc_0
  font-ttf-dejavu-s~ conda-forge/noarch::font-ttf-dejavu-sans-mono-2.37-hab24e00_0
  font-ttf-inconsol~ conda-forge/noarch::font-ttf-inconsolata-3.000-h77eed37_0
  font-ttf-source-c~ conda-forge/noarch::font-ttf-source-code-pro-2.038-h77eed37_0
  font-ttf-ubuntu    conda-forge/noarch::font-ttf-ubuntu-0.83-hab24e00_0
  fontconfig         conda-forge/linux-64::fontconfig-2.14.0-h8e229c2_0
  fonts-conda-ecosy~ conda-forge/noarch::fonts-conda-ecosystem-1-0
  fonts-conda-forge  conda-forge/noarch::fonts-conda-forge-1-0
  freetype           conda-forge/linux-64::freetype-2.10.4-h0708190_1
  gatk4              bioconda/noarch::gatk4-4.2.6.1-py36hdfd78af_1
  gettext            conda-forge/linux-64::gettext-0.19.8.1-h73d1719_1008
  giflib             conda-forge/linux-64::giflib-5.2.1-h36c2ea0_2
  graphite2          conda-forge/linux-64::graphite2-1.3.13-h58526e2_1001
  harfbuzz           conda-forge/linux-64::harfbuzz-4.4.1-hf9f4e7c_0
  icu                conda-forge/linux-64::icu-70.1-h27087fc_0
  jpeg               conda-forge/linux-64::jpeg-9e-h166bdaf_2
  keyutils           conda-forge/linux-64::keyutils-1.6.1-h166bdaf_0
  krb5               conda-forge/linux-64::krb5-1.19.3-h08a2579_0
  lcms2              conda-forge/linux-64::lcms2-2.12-hddcbb42_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.36.1-hea4e1c9_2
  lerc               conda-forge/linux-64::lerc-3.0-h9c3ff4c_0
  libcups            conda-forge/linux-64::libcups-2.3.3-hf5a7f15_1
  libdeflate         conda-forge/linux-64::libdeflate-1.12-h166bdaf_0
  libedit            conda-forge/linux-64::libedit-3.1.20191231-he28a2e2_2
  libffi             conda-forge/linux-64::libffi-3.4.2-h7f98852_5
  libgcc-ng          conda-forge/linux-64::libgcc-ng-12.1.0-h8d9b700_16
  libglib            conda-forge/linux-64::libglib-2.70.2-h174f98d_4
  libgomp            conda-forge/linux-64::libgomp-12.1.0-h8d9b700_16
  libiconv           conda-forge/linux-64::libiconv-1.16-h516909a_0
  libnsl             conda-forge/linux-64::libnsl-2.0.0-h7f98852_0
  libpng             conda-forge/linux-64::libpng-1.6.37-h21135ba_2
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-12.1.0-ha89aaad_16
  libtiff            conda-forge/linux-64::libtiff-4.4.0-hc85c160_1
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h7f98852_1000
  libwebp-base       conda-forge/linux-64::libwebp-base-1.2.2-h7f98852_1
  libxcb             conda-forge/linux-64::libxcb-1.13-h7f98852_1004
  libzlib            conda-forge/linux-64::libzlib-1.2.12-h166bdaf_1
  lz4-c              conda-forge/linux-64::lz4-c-1.9.3-h9c3ff4c_1
  ncurses            conda-forge/linux-64::ncurses-6.3-h27087fc_1
  openjdk            conda-forge/linux-64::openjdk-11.0.15-hc6918da_0
  openssl            conda-forge/linux-64::openssl-3.0.4-h166bdaf_2
  pcre               conda-forge/linux-64::pcre-8.45-h9c3ff4c_0
  pip                conda-forge/noarch::pip-22.1.2-pyhd8ed1ab_0
  pixman             conda-forge/linux-64::pixman-0.40.0-h36c2ea0_0
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h36c2ea0_1001
  python             conda-forge/linux-64::python-3.10.5-ha86cf86_0_cpython
  python_abi         conda-forge/linux-64::python_abi-3.10-2_cp310
  readline           conda-forge/linux-64::readline-8.1.2-h0f457ee_0
  setuptools         conda-forge/linux-64::setuptools-63.1.0-py310hff52083_0
  sqlite             conda-forge/linux-64::sqlite-3.39.0-h4ff8645_0
  tk                 conda-forge/linux-64::tk-8.6.12-h27826a3_0
  tzdata             conda-forge/noarch::tzdata-2022a-h191b570_0
  wheel              conda-forge/noarch::wheel-0.37.1-pyhd8ed1ab_0
  xorg-fixesproto    conda-forge/linux-64::xorg-fixesproto-5.0-h7f98852_1002
  xorg-inputproto    conda-forge/linux-64::xorg-inputproto-2.3.2-h7f98852_1002
  xorg-kbproto       conda-forge/linux-64::xorg-kbproto-1.0.7-h7f98852_1002
  xorg-libice        conda-forge/linux-64::xorg-libice-1.0.10-h7f98852_0
  xorg-libsm         conda-forge/linux-64::xorg-libsm-1.2.3-hd9c2040_1000
  xorg-libx11        conda-forge/linux-64::xorg-libx11-1.7.2-h7f98852_0
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.9-h7f98852_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.3-h7f98852_0
  xorg-libxext       conda-forge/linux-64::xorg-libxext-1.3.4-h7f98852_1
  xorg-libxfixes     conda-forge/linux-64::xorg-libxfixes-5.0.3-h7f98852_1004
  xorg-libxi         conda-forge/linux-64::xorg-libxi-1.7.10-h7f98852_0
  xorg-libxrender    conda-forge/linux-64::xorg-libxrender-0.9.10-h7f98852_1003
  xorg-libxtst       conda-forge/linux-64::xorg-libxtst-1.2.3-h7f98852_1002
  xorg-recordproto   conda-forge/linux-64::xorg-recordproto-1.14.2-h7f98852_1002
  xorg-renderproto   conda-forge/linux-64::xorg-renderproto-0.11.1-h7f98852_1002
  xorg-xextproto     conda-forge/linux-64::xorg-xextproto-7.3.0-h7f98852_1002
  xorg-xproto        conda-forge/linux-64::xorg-xproto-7.0.31-h7f98852_1007
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_1
  zlib               conda-forge/linux-64::zlib-1.2.12-h166bdaf_1
  zstd               conda-forge/linux-64::zstd-1.5.2-h8a70e8d_2


Proceed ([y]/n)?
```

**Comment by nvnieuwk** [comment]
I got the same issue when trying to run `gatk DetermineGermlineContigPloidy`.
Error message:
```
java.lang.RuntimeException: A required Python package ("gcnvkernel") could not be imported into the Python environment. This tool requires that the GATK Python environment is properly established and activated. Please refer to GATK README.md file for instructions on setting up the GATK Python environment.
        at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.checkPythonEnvironmentForPackage(PythonScriptExecutor.java:228)
        at org.broadinstitute.hellbender.tools.copynumber.DetermineGermlineContigPloidy.onStartup(DetermineGermlineContigPloidy.java:296)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:138)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
Caused by: org.broadinstitute.hellbender.utils.python.PythonScriptExecutorException: 
python exited with 1
Command Line: python -c import gcnvkernel
```
