### ISSUE TITLE
Problems downloading bioconductor packages

### ISSUE THREAD

**Issue by descostesn** [bioconda/bioconda-recipes#37535]
Hi,

I have some problems downloading some bioconductor packages, for instance bioconductor-org.mm.eg.db or bioconductor-org.hs.eg.db. It seems that the URLs are not valid:

```
CreateCondaEnvironmentException:
Could not create conda environment from ./rpackagesrnaseq.yaml:
Command:
mamba env create --quiet --file ".snakemake/conda/838eb2e28660514ce97010c0e6e878d3_.yaml" --prefix ".snakemake/conda/838eb2e28660514ce97010c0e6e878d3_"
Output:
  Package                            Version  Build                Channel                    Size
────────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────────────────────────────

  + _libgcc_mutex                        0.1  conda_forge          conda-forge/linux-64     Cached
 [...]
  + zstd                               1.5.2  h6239696_4           conda-forge/linux-64     Cached

  Summary:

  Install: 223 packages

  Total download: 439kB

────────────────────────────────────────────────────────────────────────────────────────────────────

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
ERROR conda.core.link:_execute(735): An error occurred while installing package 'bioconda::bioconductor-go.db-3.11.4-r40_0'.
Rolling back transaction: ...working... done
class: LinkError
message:
post-link script failed for package bioconda::bioconductor-go.db-3.11.4-r40_0
location of failed script: .snakemake/conda/838eb2e28660514ce97010c0e6e878d3_/bin/.bioconductor-go.db-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: .snakemake/conda/838eb2e28660514ce97010c0e6e878d3_/share/bioconductor-go.db-3.11.4-0/GO.db_3.11.4.tar.gz: FAILED
.snakemake/conda/838eb2e28660514ce97010c0e6e878d3_/share/bioconductor-go.db-3.11.4-0/GO.db_3.11.4.tar.gz: FAILED
.snakemake/conda/838eb2e28660514ce97010c0e6e878d3_/share/bioconductor-go.db-3.11.4-0/GO.db_3.11.4.tar.gz: FAILED
ERROR: post-link.sh was unable to download any of the following URLs with the md5sum cb4322c45d6ee988fdf9ccee242eae1f:
https://bioconductor.org/packages/3.11/data/annotation/src/contrib/GO.db_3.11.4.tar.gz
https://bioarchive.galaxyproject.org/GO.db_3.11.4.tar.gz
https://depot.galaxyproject.org/software/bioconductor-go.db/bioconductor-go.db_3.11.4_src_all.tar.gz

stderr:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   406  100   406    0     0   9902      0 --:--:-- --:--:-- --:--:-- 10150
md5sum: WARNING: 1 computed checksum did NOT match
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   153  100   153    0     0    257      0 --:--:-- --:--:-- --:--:--   257
md5sum: WARNING: 1 computed checksum did NOT match
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   153  100   153    0     0    257      0 --:--:-- --:--:-- --:--:--   257
md5sum: WARNING: 1 computed checksum did NOT match

return code: 1

kwargs:
{}

Traceback (most recent call last):
  File "/g/romebioinfo/miniconda/lib/python3.7/site-packages/conda/exceptions.py", line 1129, in __call__
    return func(*args, **kwargs)
  File "/g/romebioinfo/miniconda/lib/python3.7/site-packages/conda_env/cli/main.py", line 80, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/g/romebioinfo/miniconda/lib/python3.7/site-packages/conda/notices/core.py", line 72, in wrapper
    return_value = func(*args, **kwargs)
  File "/g/romebioinfo/miniconda/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 156, in execute
    result[installer_type] = installer.install(prefix, pkg_specs, args, env)
  File "/g/romebioinfo/miniconda/lib/python3.7/site-packages/mamba/mamba_env.py", line 173, in mamba_install
    handle_txn(conda_transaction, prefix, args, True)
  File "/g/romebioinfo/miniconda/lib/python3.7/site-packages/mamba/linking.py", line 44, in handle_txn
    unlink_link_transaction.execute()
  File "/g/romebioinfo/miniconda/lib/python3.7/site-packages/conda/core/link.py", line 284, in execute
    self._execute(tuple(concat(interleave(self.prefix_action_groups.values()))))
  File "/g/romebioinfo/miniconda/lib/python3.7/site-packages/conda/core/link.py", line 751, in _execute
    rollback_excs,
conda.CondaMultiErrorclass: LinkError
message:
post-link script failed for package bioconda::bioconductor-go.db-3.11.4-r40_0
location of failed script: .snakemake/conda/838eb2e28660514ce97010c0e6e878d3_/bin/.bioconductor-go.db-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: .snakemake/conda/838eb2e28660514ce97010c0e6e878d3_/share/bioconductor-go.db-3.11.4-0/GO.db_3.11.4.tar.gz: FAILED
.snakemake/conda/838eb2e28660514ce97010c0e6e878d3_/share/bioconductor-go.db-3.11.4-0/GO.db_3.11.4.tar.gz: FAILED
.snakemake/conda/838eb2e28660514ce97010c0e6e878d3_/share/bioconductor-go.db-3.11.4-0/GO.db_3.11.4.tar.gz: FAILED
ERROR: post-link.sh was unable to download any of the following URLs with the md5sum cb4322c45d6ee988fdf9ccee242eae1f:
https://bioconductor.org/packages/3.11/data/annotation/src/contrib/GO.db_3.11.4.tar.gz
https://bioarchive.galaxyproject.org/GO.db_3.11.4.tar.gz
https://depot.galaxyproject.org/software/bioconductor-go.db/bioconductor-go.db_3.11.4_src_all.tar.gz

stderr:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   406  100   406    0     0   9902      0 --:--:-- --:--:-- --:--:-- 10150
md5sum: WARNING: 1 computed checksum did NOT match
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   153  100   153    0     0    257      0 --:--:-- --:--:-- --:--:--   257
md5sum: WARNING: 1 computed checksum did NOT match
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   153  100   153    0     0    257      0 --:--:-- --:--:-- --:--:--   257
md5sum: WARNING: 1 computed checksum did NOT match

return code: 1

kwargs:
{}

: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/g/romebioinfo/miniconda/condabin/mamba", line 11, in <module>
    sys.exit(main())
  File "/g/romebioinfo/miniconda/lib/python3.7/site-packages/mamba/mamba.py", line 923, in main
    return mamba_env.main()
  File "/g/romebioinfo/miniconda/lib/python3.7/site-packages/mamba/mamba_env.py", line 196, in main
    return conda_env_main()
  File "/g/romebioinfo/miniconda/lib/python3.7/site-packages/conda_env/cli/main.py", line 91, in main
    return conda_exception_handler(do_call, args, parser)
  File "/g/romebioinfo/miniconda/lib/python3.7/site-packages/conda/exceptions.py", line 1429, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/g/romebioinfo/miniconda/lib/python3.7/site-packages/conda/exceptions.py", line 1132, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/g/romebioinfo/miniconda/lib/python3.7/site-packages/conda/exceptions.py", line 1161, in handle_exception
    return self.handle_application_exception(exc_val, exc_tb)
  File "/g/romebioinfo/miniconda/lib/python3.7/site-packages/conda/exceptions.py", line 1175, in handle_application_exception
    self._print_conda_exception(exc_val, exc_tb)
  File "/g/romebioinfo/miniconda/lib/python3.7/site-packages/conda/exceptions.py", line 1179, in _print_conda_exception
    print_conda_exception(exc_val, exc_tb)
  File "/g/romebioinfo/miniconda/lib/python3.7/site-packages/conda/exceptions.py", line 1106, in print_conda_exception
    stderrlog.error("\n%r\n", exc_val)
  File "/g/romebioinfo/miniconda/lib/python3.7/logging/__init__.py", line 1407, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/g/romebioinfo/miniconda/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/g/romebioinfo/miniconda/lib/python3.7/logging/__init__.py", line 1523, in handle
    if (not self.disabled) and self.filter(record):
  File "/g/romebioinfo/miniconda/lib/python3.7/logging/__init__.py", line 751, in filter
    result = f.filter(record)
  File "/g/romebioinfo/miniconda/lib/python3.7/site-packages/conda/gateways/logging.py", line 50, in filter
    record.msg = record.msg % new_args
  File "/g/romebioinfo/miniconda/lib/python3.7/site-packages/conda/__init__.py", line 107, in __repr__
    errs.append(e.__repr__())
  File "/g/romebioinfo/miniconda/lib/python3.7/site-packages/conda/__init__.py", line 64, in __repr__
    return '%s: %s' % (self.__class__.__name__, str(self))
  File "/g/romebioinfo/miniconda/lib/python3.7/site-packages/conda/__init__.py", line 68, in __str__
    return str(self.message % self._kwargs)
ValueError: unsupported format character 'T' (0x54) at index 1222
```

Is the problem coming from bioconductor?

**Comment by mjsteinbaugh** [comment]
Hi @descostesn I'm taking a look into this today
