### ISSUE TITLE
Some plasmidfinder blast results causing staramr to crash

### ISSUE THREAD

**Issue by apetkau** [bioconda/bioconda-recipes#37597]
# Issue

When running staramr where some plasmidfinder incompatibility factors are detected causes staramr to crash with the following message:

```
2022-10-24 11:47:20 ERROR: Index length not within range, for [rep21_24_rep(CN1_plasmid2)_NC_022227]
Traceback (most recent call last):
  File "/home/CSCScience.ca/apetkau/miniconda3/envs/staramr-0.9.0/bin/staramr", line 68, in <module>
    args.run_command(args)
  File "/home/CSCScience.ca/apetkau/miniconda3/envs/staramr-0.9.0/lib/python3.10/site-packages/staramr/subcommand/Search.py", line 467, in run
...
  File "/home/CSCScience.ca/apetkau/miniconda3/envs/staramr-0.9.0/lib/python3.10/site-packages/staramr/blast/results/plasmidfinder/PlasmidfinderHitHSP.py", line 56, in __init__
    raise Exception("Index length not within range, for [" + self.get_amr_gene_id() + "]")
Exception: Index length not within range, for [rep21_24_rep(CN1_plasmid2)_NC_022227]
```

# Testing

To test this out, please download the following test file:

* [test-plasmid-rep.zip](https://github.com/bioconda/bioconda-recipes/files/9853690/test-plasmid-rep.zip)

Unzip this file and try running the following:

```bash
staramr search -o out test-plasmid-rep.fsa
```

You should receive the above error message.

**Comment by apetkau** [comment]
Woops. This issue was made in the wrong repository (wrong tab open in my browser). Sorry.
