### ISSUE TITLE
conda activate error

### ISSUE THREAD

**Issue by sekhwal** [bioconda/bioconda-recipes#37688]
I created conda environment using conda create -n bioinfo, now trying to activate the environment but it shows following error. Please suggest any solution.

---------

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1129, in __call__
        return func(*args, **kwargs)
      File "/home/anaconda3/lib/python3.9/site-packages/conda/cli/main.py", line 111, in main_sourced
        print(activator.execute(), end="")
      File "/home/anaconda3/lib/python3.9/site-packages/conda/activate.py", line 167, in execute
        return getattr(self, self.command)()
      File "/home/anaconda3/lib/python3.9/site-packages/conda/activate.py", line 141, in activate
        builder_result = self.build_activate(self.env_name_or_prefix)
      File "/home/anaconda3/lib/python3.9/site-packages/conda/activate.py", line 288, in build_activate
        return self._build_activate_stack(env_name_or_prefix, False)
      File "/home/anaconda3/lib/python3.9/site-packages/conda/activate.py", line 357, in _build_activate_stack
        path=self.pathsep_join(self._replace_prefix_in_path(old_conda_prefix, prefix)),
      File "/home/anaconda3/lib/python3.9/site-packages/conda/activate.py", line 592, in _replace_prefix_in_path
        if path_list[last_idx + 1] == library_bin_dir:
    IndexError: list index out of range

`$ /home/anaconda3/bin/conda shell.posix activate bioinfo`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/anaconda3/bin/conda
             CONDA_PREFIX=/home/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/anaconda3/bin/python
               CONDA_ROOT=/home/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/game
                          s:/usr/local/games:/snap/bin:/snap/bin:/home/anaconda3/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/anaconda3
            shell level : 1
       user config file : /home/.condarc
 populated config files : /home/anaconda3/.condarc
          conda version : 22.9.0
    conda-build version : 3.22.0
         python version : 3.9.13.final.0
       virtual packages : __linux=5.15.0=0
                          __glibc=2.35=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/anaconda3  (writable)
      conda av data dir : /home/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/anaconda3/pkgs
                          /home/.conda/pkgs
       envs directories : /home/anaconda3/envs
                          /home/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.9.13 Linux/5.15.0-52-generic ubuntu/22.04.1 glibc/2.35
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

Timeout reached. No report sent.

**Comment by rpetit3** [comment]
Hi @sekhwal 

This looks similar to https://github.com/conda/conda/issues/8565
