### ISSUE TITLE
kmergenie missing readfq

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#37856]
Hi,
running histogram estimation
list of reads:
fastp/1740D-43-06_S0_L001_R1_001.fastp.fastq.gz
fastp/1740D-43-06_S0_L001_R2_001.fastp.fastq.gz
Traceback (most recent call last):
  File "/work/waterhouse_team/miniconda2/envs/kmergenie/bin/kmergenie", line 303, in <module>
    best_k = execute_once(arguments_passed_list, first_pass=first_pass)
  File "/work/waterhouse_team/miniconda2/envs/kmergenie/bin/kmergenie", line 279, in execute_once
    ntcard_wrapper(k_interval)
  File "/work/waterhouse_team/miniconda2/envs/kmergenie/bin/kmergenie", line 221, in ntcard_wrapper
    max_read_length = get_read_length(read_file_list)
  File "/work/waterhouse_team/miniconda2/envs/kmergenie/bin/kmergenie", line 147, in get_read_length
    from readfq import readfq
ModuleNotFoundError: No module named 'readfq'

**Comment by rpetit3** [comment]
Hi @mictadlo 

Thank you for bringing this to our attention. Created a pull request to hopefully get this sorted for you.

Cheers,
Robert

**Comment by mencian** [comment]
Solved in #58057.
