### ISSUE TITLE
An error when running ./simulate-travis.py

### ISSUE THREAD

**Issue by CicoZhang** [bioconda/bioconda-recipes#3890]
I got an error which seems to be relevant to license_family.

```
RuntimeError: about/license_family 'Public-Domain' not allowed. Allowed families are
AGPL, Apache, BSD, GPL, GPL2, GPL3, LGPL, MIT, NONE, Other, PSF,
Proprietary, and Public-Domain.
```
 The whole log is as follows: 
```
$ ./simulate-travis.py
+ bioconda-utils build recipes config.yml --docker --loglevel=info --mulled-test
INFO bioconda_utils.docker_utils:_pull_image(317): BIOCONDA DOCKER: Pulling docker image condaforge/linux-anvil
INFO bioconda_utils.docker_utils:_pull_image(323): BIOCONDA DOCKER: Done pulling image
INFO bioconda_utils.docker_utils:_build_image(363): BIOCONDA DOCKER: Built docker image tag=tmp-bioconda-builder
INFO bioconda_utils.build:build_recipes(233): blacklist: abyss, augustus, bioconductor-bubbletree, bioconductor-cexor, bioconductor-deseq2/1.10.1, bioconductor-diffbind, bioconductor-genelendatabase/1.6.0, bioconductor-iranges/2.4.6, bioconductor-iranges/2.4.7, bioconductor-limma/3.26.7, bioconductor-limma/3.28.2, bioconductor-limma/3.28.6, bioconductor-mmdiff, bioconductor-s4vectors/0.8.7, bioconductor-summarizedexperiment/1.0.2, bioconductor-systempiper, blast/2.2.21, cap-mirseq, denovogear, detonate, dsrc, ensembl-vep, intarna, metaprob, mothur, mysqlclient, nanonet, pbbam, pbdagcon, quake, quast, r-hdrcde, r-knitr, r-ks, r-mutoss, r-phonr, r-rainbow, r-readr, r-sartools/1.2.0, r-spp, rsem, sailfish, salmon, transcomb, triform2
INFO bioconda_utils.build:build_recipes(268): Filtering recipes

Traceback (most recent call last):s/anvio                                           
  File "/home/cico/miniconda3/bin/bioconda-utils", line 11, in <module>
    load_entry_point('bioconda-utils==0.9.0', 'console_scripts', 'bioconda-utils')()
  File "/home/cico/miniconda3/lib/python3.5/site-packages/bioconda_utils/cli.py", line 178, in main
    argh.dispatch_commands([build, dag, dependent])
  File "/home/cico/miniconda3/lib/python3.5/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/home/cico/miniconda3/lib/python3.5/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/cico/miniconda3/lib/python3.5/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/cico/miniconda3/lib/python3.5/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/cico/miniconda3/lib/python3.5/site-packages/bioconda_utils/cli.py", line 110, in build
    disable_travis_env_vars=disable_travis_env_vars,
  File "/home/cico/miniconda3/lib/python3.5/site-packages/bioconda_utils/build.py", line 271, in build_recipes
    recipes, env_matrix, check_channels, force=force)
  File "/home/cico/miniconda3/lib/python3.5/site-packages/bioconda_utils/utils.py", line 537, in filter_recipes
    pkg = built_package_path(recipe, env)
  File "/home/cico/miniconda3/lib/python3.5/site-packages/bioconda_utils/utils.py", line 358, in built_package_path
    path = api.get_output_file_path(recipe, config=config)
  File "/home/cico/miniconda3/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/cico/miniconda3/lib/python3.5/site-packages/bioconda_utils/utils.py", line 44, in temp_env
    yield
  File "/home/cico/miniconda3/lib/python3.5/site-packages/bioconda_utils/utils.py", line 358, in built_package_path
    path = api.get_output_file_path(recipe, config=config)
  File "/home/cico/miniconda3/lib/python3.5/site-packages/conda_build/api.py", line 47, in get_output_file_path
    config=config)
  File "/home/cico/miniconda3/lib/python3.5/site-packages/conda_build/render.py", line 147, in render_recipe
    m = MetaData(recipe_dir, config=config)
  File "/home/cico/miniconda3/lib/python3.5/site-packages/conda_build/metadata.py", line 437, in __init__
    self.parse_again(config=config, permit_undefined_jinja=True)
  File "/home/cico/miniconda3/lib/python3.5/site-packages/conda_build/metadata.py", line 470, in parse_again
    config=config, path=self.meta_path)
  File "/home/cico/miniconda3/lib/python3.5/site-packages/conda_build/metadata.py", line 199, in parse
    ensure_valid_license_family(res)
  File "/home/cico/miniconda3/lib/python3.5/site-packages/conda_build/license_family.py", line 106, in ensure_valid_license_family
    (license_family, comma_join(sorted(allowed_license_families)))))
RuntimeError: about/license_family 'Public-Domain' not allowed. Allowed families are
AGPL, Apache, BSD, GPL, GPL2, GPL3, LGPL, MIT, NONE, Other, PSF,
Proprietary, and Public-Domain.
Traceback (most recent call last):
  File "./simulate-travis.py", line 150, in <module>
    sp.run(['scripts/travis-run.sh'], env=env, universal_newlines=True, check=True)
  File "/home/cico/miniconda3/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['scripts/travis-run.sh']' returned non-zero exit status 1

```

**Comment by roryk** [comment]
I also have this issue.

**Comment by bgruening** [comment]
Fixed in master.

**Comment by roryk** [comment]
Thanks!

**Comment by CicoZhang** [comment]
After pulling the update from upstream, I am confronted with a new error, failing to run simulate-travis.py again.

```
$ ./simulate-travis.py                                          
scripts/travis-run.sh: line 8: TRAVIS_COMMIT_RANGE: unbound variable
Traceback (most recent call last):
  File "./simulate-travis.py", line 150, in <module>
    sp.run(['scripts/travis-run.sh'], env=env, universal_newlines=True, check=True)
  File "/home/cico/miniconda3/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['scripts/travis-run.sh']' returned non-zero exit status 1
```

**Comment by bgruening** [comment]
To late ... @johanneskoester merged new build infrastructure changes and we need to adopt the travis_simulate to it. If you can get the commit from 20h back you should be save.
