### ISSUE TITLE
bd2k-python-lib is mostly empty, bad for toil

### ISSUE THREAD

**Issue by smoe** [bioconda/bioconda-recipes#3895]
Heya,
it just ships
```
$ find miniconda2/pkgs/bd2k-python-lib-1.14a1.dev37-py27_0/
miniconda2/pkgs/bd2k-python-lib-1.14a1.dev37-py27_0/
miniconda2/pkgs/bd2k-python-lib-1.14a1.dev37-py27_0/info
miniconda2/pkgs/bd2k-python-lib-1.14a1.dev37-py27_0/info/recipe
miniconda2/pkgs/bd2k-python-lib-1.14a1.dev37-py27_0/info/recipe/build.sh
miniconda2/pkgs/bd2k-python-lib-1.14a1.dev37-py27_0/info/recipe/meta.yaml
miniconda2/pkgs/bd2k-python-lib-1.14a1.dev37-py27_0/info/recipe/meta.yaml.template
miniconda2/pkgs/bd2k-python-lib-1.14a1.dev37-py27_0/info/index.json
miniconda2/pkgs/bd2k-python-lib-1.14a1.dev37-py27_0/info/about.json
miniconda2/pkgs/bd2k-python-lib-1.14a1.dev37-py27_0/info/files
miniconda2/pkgs/bd2k-python-lib-1.14a1.dev37-py27_0/lib
miniconda2/pkgs/bd2k-python-lib-1.14a1.dev37-py27_0/lib/python2.7
miniconda2/pkgs/bd2k-python-lib-1.14a1.dev37-py27_0/lib/python2.7/site-packages
miniconda2/pkgs/bd2k-python-lib-1.14a1.dev37-py27_0/lib/python2.7/site-packages/bd2k_python_lib-1.14a1.dev37-py2.7.egg
miniconda2/pkgs/bd2k-python-lib-1.14a1.dev37-py27_0/lib/python2.7/site-packages/bd2k_python_lib.pth
```
which maybe because the site-pacakges directory is just called bd2k and as such missed (I remember something like that for my Debian pacakge of it). The consequence is that the example code for toil does not work
```$ python toil-sort-example.py file:jobStore
Traceback (most recent call last):
  File "toil-sort-example.py", line 8, in <module>
    from toil.job import Job
  File "/users/sm718/miniconda2/pkgs/toil-3.6.0-py27_0/lib/python2.7/site-packages/toil/__init__.py", line 23, in <module>
    from bd2k.util import memoize
ImportError: No module named bd2k.util
```
Hmpf.

**Comment by chapmanb** [comment]
Steffen;
The bd2k code is all inside of the `bd2k_python_lib-1.14a1.dev37-py2.7.egg` file, python's annoying binary packaging format. I installed toil in a clean conda environment and can't reproduce the issue:
```
$ bash Miniconda2-latest-Linux-x86_64.sh -b -p env
$ ./env/bin/conda install -c bioconda toil
$ ./env/bin/python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from bd2k.util import memoize
>>>
```
Is it possible something else is going on with your miniconda install that removed bd2k-python-lib?

**Comment by bgruening** [comment]
@smoe if you still have an issue with this, please feel free to reopen.

**Comment by smoe** [comment]
@bgruening, @chapmanb, many thanks to you both. I'll revisit this all while the bcbio runtime dependencies slowly (as in nerve-breaking slowly) approach the main distribution.
