### ISSUE TITLE
Build failure on involucro

### ISSUE THREAD

**Issue by Yikun** [bioconda/bioconda-recipes#40063]
```
18:31:22 BIOCONDA INFO (OUT) source tree in: /opt/conda/conda-bld/involucro_1679740152222/work
18:31:22 BIOCONDA INFO (OUT) export PREFIX=/opt/conda/conda-bld/involucro_1679740152222/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
18:31:22 BIOCONDA INFO (OUT) export BUILD_PREFIX=/opt/conda/conda-bld/involucro_1679740152222/_build_env
18:31:22 BIOCONDA INFO (OUT) export SRC_DIR=/opt/conda/conda-bld/involucro_1679740152222/work
18:31:24 BIOCONDA INFO (OUT) go: go.mod file not found in current directory or any parent directory.
18:31:24 BIOCONDA INFO (OUT)    'go get' is no longer supported outside a module.
18:31:24 BIOCONDA INFO (OUT)    To build and install a command, use 'go install' with a version,
18:31:24 BIOCONDA INFO (OUT)    like 'go install example.com/cmd@latest'
18:31:24 BIOCONDA INFO (OUT)    For more information, see https://golang.org/doc/go-get-install-deprecation
18:31:24 BIOCONDA INFO (OUT)    or run 'go help get' or 'go help install'.
18:31:26 BIOCONDA INFO (OUT) Traceback (most recent call last):
18:31:26 BIOCONDA INFO (OUT)   File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
18:31:26 BIOCONDA INFO (OUT)     sys.exit(main())
18:31:26 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 239, in main
18:31:26 BIOCONDA INFO (OUT)     call_conda_build(action, config)
18:31:26 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 211, in call_conda_build
18:31:26 BIOCONDA INFO (OUT)     result = api.build(
18:31:26 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
18:31:26 BIOCONDA INFO (OUT)     return build_tree(
18:31:26 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 3088, in build_tree
18:31:26 BIOCONDA INFO (OUT)     packages_from_this = build(metadata, stats,
18:31:26 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2211, in build
18:31:26 BIOCONDA INFO (OUT)     utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
18:31:26 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 410, in check_call_env
18:31:26 BIOCONDA INFO (OUT)     return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
18:31:26 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 390, in _func_defaulting_env_to_os_environ
18:31:26 BIOCONDA INFO (OUT)     raise subprocess.CalledProcessError(proc.returncode, _args)
18:31:26 BIOCONDA INFO (OUT) subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/involucro_1679740152222/work/conda_build.sh']' returned non-zero exit status 1.
18:31:33 BIOCONDA ERROR COMMAND FAILED (exited with 1): docker run -t --net host --rm -v /tmp/tmppk5l355f/build_script.bash:/opt/build_script.bash -v /root/yikun/miniconda/envs/bioconda/conda-bld/:/opt/host-conda-bld -v /root/bio/bioconda-recipes/recipes/involucro:/opt/recipe -e LANG=en_US.UTF-8 -e HOST_USER_ID=0 quay.io/bioconda/bioconda-utils-build-env-cos7:aarch64 /bin/bash /opt/build_script.bash

18:31:33 BIOCONDA ERROR BUILD FAILED recipes/involucro
18:31:33 BIOCONDA INFO (COMMAND) conda build purge
18:31:35 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
18:31:35 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/involucro
```

bioconda-utils build --docker --mulled-test --packages involucro  --force

**Comment by Yikun** [comment]
Closed by https://github.com/bioconda/bioconda-recipes/pull/40144

And move to conda-forge: https://github.com/conda-forge/staged-recipes/pull/22518
