### ISSUE TITLE
deepvariant : No module named 'etils'

### ISSUE THREAD

**Issue by BELKHIR** [bioconda/bioconda-recipes#40448]
Hi,
After installing deepvariant 1.5.0 and running the command : dv_make_examples.py -h
I have this message :  
Baseline DeepVariant arguments
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_lmvhvsf_/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 38, in <module>
    from deepvariant import make_examples_core
  File "/tmp/Bazel.runfiles_lmvhvsf_/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 41, in <module>
    from etils import epath
ModuleNotFoundError: No module named 'etils'

It seems that the python version coming with bioconda  deepvariant 1.5.0 is python 3.6.15.

Following this issue (https://github.com/google/etils/issues/199) this version of python is incompatible with etils.

Moreover, the Dokerfile in the deepvariant repo (https://github.com/google/deepvariant/blob/r1.5/Dockerfile) install python version is 3.8.

Any advice ?

**Comment by lixiang117423** [comment]
I have the same issue and did not figure it out.
