### ISSUE TITLE
nglview import broken

### ISSUE THREAD

**Issue by marscher** [bioconda/bioconda-recipes#4087]
introduced in #4065, we now can not import nglview in python anymore:
```
marscher@area51:~/sources/molPX (enable_coverage)$ conda update -c bioconda nglview 
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment /home/marscher/miniconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          502 B
    nglview-0.6.2.2            |                1         5.0 MB  bioconda
    ------------------------------------------------------------
                                           Total:         5.0 MB

The following packages will be UPDATED:

    conda:     4.2.13-py35_0  conda-forge --> 4.3.14-py35_0         
    nglview:   0.6.2.2-py35_0 bioconda    --> 0.6.2.2-1     bioconda

The following packages will be SUPERCEDED by a higher-priority channel:

    conda-env: 2.6.0-0        conda-forge --> 2.6.0-0               

Proceed ([y]/n)? y

Pruning fetched packages from the cache ...
Fetching packages ...
conda-env-2.6. 100% |#####################################################################################################################| Time: 0:00:00 231.33 kB/s
nglview-0.6.2. 100% |#####################################################################################################################| Time: 0:00:03   1.53 MB/s
Extracting packages ...
[      COMPLETE      ]|########################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|########################################################################################################################################| 100%
Linking packages ...
Traceback (most recent call last):###############################################################################                                              |  66%
  File "/home/marscher/miniconda3/bin/jupyter-nbextension", line 11, in <module>
    load_entry_point('notebook', 'console_scripts', 'jupyter-nbextension')()
  File "/home/marscher/miniconda3/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/marscher/miniconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/marscher/miniconda3/lib/python3.5/site-packages/notebook/nbextensions.py", line 969, in start
    super(NBExtensionApp, self).start()
  File "/home/marscher/miniconda3/lib/python3.5/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/home/marscher/miniconda3/lib/python3.5/site-packages/notebook/nbextensions.py", line 745, in start
    self.install_extensions()
  File "/home/marscher/miniconda3/lib/python3.5/site-packages/notebook/nbextensions.py", line 724, in install_extensions
    **kwargs
  File "/home/marscher/miniconda3/lib/python3.5/site-packages/notebook/nbextensions.py", line 225, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/home/marscher/miniconda3/lib/python3.5/site-packages/notebook/nbextensions.py", line 1140, in _get_nbextension_metadata
    m = import_item(module)
  File "/home/marscher/miniconda3/lib/python3.5/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
ImportError: No module named 'nglview'
[      COMPLETE      ]|########################################################################################################################################| 100%
```

ping @hainm

**Comment by marscher** [comment]
this is on Python-3.5, the other versions seem to work

**Comment by marscher** [comment]
cc @gph82

**Comment by hainm** [comment]
Weird. I will have a look tonight.

**Comment by marscher** [comment]
On 09.03.2017 16:56, Hai Nguyen wrote:
> Weird. I will have a look tonight.
I think removing Python as a runtime dependency for a Python package 
(even if it contains javascript :P) is a bad idea.

**Comment by hainm** [comment]
uhm, Python 2.7 is used to build `nglview`, so if you unpack the [tarfile](https://anaconda.org/bioconda/nglview/files), you only see the

`lib/python2.7/site-packages/nglview`. This is why the install does not work with other python versions.

> I think removing Python as a runtime dependency for a Python package
(even if it contains javascript :P) is a bad idea.

I know. But I am not really convinced about current workflow if conda build. If a Python package (e.g: nglview) does not require a specific python version to run, we do not really need to have separate build for it.

In the worse case, I just revert my change here in bioconda. :v:

**Comment by hainm** [comment]
yeah right, I will have a look. thanks.
