### ISSUE TITLE
Problem with pysam and htslib

### ISSUE THREAD

**Issue by jfear** [bioconda/bioconda-recipes#4230]
I am having a problem with pysam and htslib. Here is a minimal example.

```bash
$ cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

$ conda --version
conda 4.3.14

$ conda create -n test -y pysam
$ source activate test
(test) $ python -m pysam

Traceback (most recent call last):
  File "/home/fearjm/miniconda3/envs/test/lib/python3.5/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/fearjm/miniconda3/envs/test/lib/python3.5/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/fearjm/miniconda3/envs/test/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/fearjm/miniconda3/envs/test/lib/python3.5/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libhts.so.1: cannot open shared object file: No such file or directory
```

but if I change the version of htslib then things run as expected:

```bash
(test) $ conda install -y htslib=1.3.1
(test) $ python -m pysam
/home/fearjm/miniconda3/envs/test/bin/python: No module named pysam.__main__; 'pysam' is a package and cannot be directly executed
```

Thanks for any advice.
Justin

**Comment by jfear** [comment]
Being worked on here:

https://github.com/pysam-developers/pysam/issues/413

going a head and closing.
