### ISSUE TITLE
perl 5.26.2 not available for linux64?

### ISSUE THREAD

**Issue by edgardomortiz** [bioconda/bioconda-recipes#42404]
I wonder if somebody could help me with the installation error from:

https://github.com/bioconda/bioconda-recipes/pull/42401

where perl 5.26.2 can't be found

```
The reported errors are:
- Encountered problems while solving:
-   - package perl-bioperl-core-1.007002-pl526_0 requires perl >=5.26.2,<5.26.3.0a0, but none of the providers can be installed
-

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 256, in main
    call_conda_build(action, config)
  File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
    result = api.build(
  File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 180, in build
    return build_tree(
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 3078, in build_tree
    packages_from_this = build(metadata, stats,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2115, in build
    create_build_envs(top_level_pkg, notest)
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 1993, in create_build_envs
    raise e
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 1972, in create_build_envs
    environ.get_install_actions(m.config.test_prefix,
  File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 150, in mamba_get_install_actions
    raise err
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {MatchSpec("perl[version='>=5.26.2,<5.26.3.0a0']"), MatchSpec("perl-bioperl-core==1.007002=pl526_0")}

09:25:46 BIOCONDA ERROR BUILD FAILED recipes/captus
09:25:46 BIOCONDA INFO (COMMAND) conda build purge

⠋ running (0:00:00.00)
09:25:47 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
09:25:47 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/captus
##[error]Bash exited with code '1'.
Finishing: Test
```

Any help is appreciated

Edgardo

**Comment by aliciaaevans** [comment]
Closing this because it looks like it was resolved and subsequent versions of the recipe have been successful.
