### ISSUE TITLE
quiime caused ImportError: No module named PyQt4

### ISSUE THREAD

**Issue by mictadlo** [bioconda/bioconda-recipes#4250]
Hi @bgruening,
```
$ convert_fastaqual_fastq.py -f RSnSeQ_110fruit.fastq -c fastq_to_fastaqual -F
Traceback (most recent call last):
  File "/mnt/apps/miniconda2/bin/convert_fastaqual_fastq.py", line 4, in <module>
    __import__('pkg_resources').run_script('qiime==1.9.1', 'convert_fastaqual_fastq.py')
  File "/mnt/apps/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/mnt/apps/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1499, in run_script
  File "/mnt/apps/miniconda2/lib/python2.7/site-packages/qiime-1.9.1-py2.7.egg-info/scripts/convert_fastaqual_fastq.py", line 14, in <module>
    from qiime.util import make_option, create_dir,\
  File "/mnt/apps/miniconda2/lib/python2.7/site-packages/qiime/util.py", line 49, in <module>
    from skbio.util import remove_files, create_dir
  File "/mnt/apps/miniconda2/lib/python2.7/site-packages/skbio/__init__.py", line 15, in <module>
    import skbio.io
  File "/mnt/apps/miniconda2/lib/python2.7/site-packages/skbio/io/__init__.py", line 309, in <module>
    import_module('skbio.io.clustal')
  File "/mnt/apps/miniconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/mnt/apps/miniconda2/lib/python2.7/site-packages/skbio/io/clustal.py", line 123, in <module>
    from skbio.alignment import Alignment
  File "/mnt/apps/miniconda2/lib/python2.7/site-packages/skbio/alignment/__init__.py", line 230, in <module>
    from ._alignment import Alignment, SequenceCollection, StockholmAlignment
  File "/mnt/apps/miniconda2/lib/python2.7/site-packages/skbio/alignment/_alignment.py", line 21, in <module>
    from skbio.stats.distance import DistanceMatrix
  File "/mnt/apps/miniconda2/lib/python2.7/site-packages/skbio/stats/distance/__init__.py", line 193, in <module>
    from ._base import (DissimilarityMatrixError, DistanceMatrixError,
  File "/mnt/apps/miniconda2/lib/python2.7/site-packages/skbio/stats/distance/_base.py", line 16, in <module>
    import matplotlib.pyplot as plt
  File "/mnt/apps/miniconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/mnt/apps/miniconda2/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/mnt/apps/miniconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import QtCore
  File "/mnt/apps/miniconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 26, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/mnt/apps/miniconda2/lib/python2.7/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/mnt/apps/miniconda2/lib/python2.7/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 56, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/mnt/apps/miniconda2/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 137, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named PyQt4
```

Thank you in advance,

Michal

**Comment by bgruening** [comment]
Let's see if we can reproduce this error with a new test in: https://github.com/bioconda/bioconda-recipes/issues/4250

**Comment by pbordron** [comment]
issue solved by this PR https://github.com/bioconda/bioconda-recipes/pull/4411
