### ISSUE TITLE
Platypus-variant package broken

### ISSUE THREAD

**Issue by holtgrewe** [bioconda/bioconda-recipes#4263]
It looks like the wrong person is used at run time.

Please advise.

```
$ conda install platypus-variant
$ platypus -h
Traceback (most recent call last):
  File ".../platypus-variant-0.8.1-0/Platypus.py", line 9, in <module>
    import runner
  File ".../platypus-variant-0.8.1-0/runner.py", line 9, in <module>
    import variantcaller
  File "htslibWrapper.pxd", line 203, in init variantcaller (variantcaller.c:16971)
ImportError: libhts.so.1: cannot open shared object file: No such file or directory
```

**Comment by bgruening** [comment]
can you add and pin htslib to `htslib >=1.3,<1.4`

**Comment by anopperl** [comment]
hii i have same problem, i have installed all Requirements.

**Comment by bgruening** [comment]
Mh, I can not reproduce this :(

```
conda install platypus-variant
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /home/bag/miniconda2:

The following NEW packages will be INSTALLED:

    bzip2:            1.0.6-1             conda-forge
    curl:             7.54.1-0            conda-forge
    htslib:           1.6-0               bioconda   
    krb5:             1.14.2-0            conda-forge
    libssh2:          1.8.0-1             conda-forge
    platypus-variant: 0.8.1.1-htslib1.6_0 bioconda   
    xz:               5.2.3-0             conda-forge

Proceed ([y]/n)? y

htslib-1.6-0.t 100% |#################################################################################################################################################| Time: 0:00:01 987.87 kB/s
platypus-varia 100% |#################################################################################################################################################| Time: 0:00:08   1.22 MB/s
bag@bag ~/projects/code/galaxy-freiburg/docs
 % platypus -h




Invalid usage: use Platypus as follows:


python Platypus.py continueCalling [Options]
python Platypus.py callVariants [Options]


For a list of possible options for a specific command, type 'python Platypus.py Command -h'
```

**Comment by anopperl** [comment]
hii thanks but i use "https://github.com/andyrimmer/Platypus" for install platypus

**Comment by daler** [comment]
@anopperl just to clarify, this issue is in the bioconda-recipes repository. Bioconda eases the installation of bioinformatics tools, and this sort of error is exactly what bioconda aims to help with. See http://bioconda.github.io/ to get started, and it should then work after using the command `conda install platypus-variant` that @bgruening indicates above.

**Comment by Bioinformative** [comment]
This worked for me
` export C_INCLUDE_PATH=/usr/local/include ; export LIBRARY_PATH=/usr/local/lib ; export LD_LIBRARY_PATH=/usr/local/lib`

**Comment by bgruening** [comment]
I hope this is solved it works for me as it seem. Please reopen if you still have a problem.
