### ISSUE TITLE
gimmemotifs: libhts.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by croth1** [bioconda/bioconda-recipes#4278]
gimmemotifs has to be rebuilt against the latest libhts version.
cc @simonvh 

```
gimme genome genomes hg38
Traceback (most recent call last):
  File "/usr/users/croth1/miniconda/envs/test27/bin/gimme", line 11, in <module>
    from  gimmemotifs import commands
  File "/usr/users/croth1/miniconda/envs/test27/lib/python2.7/site-packages/gimmemotifs/commands/__init__.py", line 8, in <module>
    m =  __import__("{0}.{1}".format(__name__, cmdname), globals(), locals(), [cmdname], -1)
  File "/usr/users/croth1/miniconda/envs/test27/lib/python2.7/site-packages/gimmemotifs/commands/background.py", line 10, in <module>
    import gimmemotifs.background as bg
  File "/usr/users/croth1/miniconda/envs/test27/lib/python2.7/site-packages/gimmemotifs/background.py", line 25, in <module>
    import pybedtools
  File "/usr/users/croth1/miniconda/envs/test27/lib/python2.7/site-packages/pybedtools/__init__.py", line 12, in <module>
    from . import contrib
  File "/usr/users/croth1/miniconda/envs/test27/lib/python2.7/site-packages/pybedtools/contrib/__init__.py", line 3, in <module>
    from . import venn_maker
  File "/usr/users/croth1/miniconda/envs/test27/lib/python2.7/site-packages/pybedtools/contrib/venn_maker.py", line 12, in <module>
    from pybedtools import helpers
  File "/usr/users/croth1/miniconda/envs/test27/lib/python2.7/site-packages/pybedtools/helpers.py", line 13, in <module>
    import pysam
  File "/usr/users/croth1/miniconda/envs/test27/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libhts.so.1: cannot open shared object file: No such file or directory
````

**Comment by croth1** [comment]
also:

```
gimme genome genomes/ hg19
/usr/users/croth1/miniconda/envs/test27/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/usr/users/croth1/miniconda/envs/test27/lib/python2.7/site-packages/sklearn/grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)
Traceback (most recent call last):
  File "/usr/users/croth1/miniconda/envs/test27/bin/gimme", line 11, in <module>
    from  gimmemotifs import commands
  File "/usr/users/croth1/miniconda/envs/test27/lib/python2.7/site-packages/gimmemotifs/commands/__init__.py", line 8, in <module>
    m =  __import__("{0}.{1}".format(__name__, cmdname), globals(), locals(), [cmdname], -1)
  File "/usr/users/croth1/miniconda/envs/test27/lib/python2.7/site-packages/gimmemotifs/commands/moap.py", line 16, in <module>
    from gimmemotifs.more import ( KSMoap, LassoMoap, LightningMoap,
  File "/usr/users/croth1/miniconda/envs/test27/lib/python2.7/site-packages/gimmemotifs/more.py", line 31, in <module>
    import pymc as pm
  File "/usr/users/croth1/miniconda/envs/test27/lib/python2.7/site-packages/pymc/__init__.py", line 30, in <module>
    from .CommonDeterministics import *
  File "/usr/users/croth1/miniconda/envs/test27/lib/python2.7/site-packages/pymc/CommonDeterministics.py", line 21, in <module>
    from .utils import safe_len, stukel_logit, stukel_invlogit, logit, invlogit, value, find_element
  File "/usr/users/croth1/miniconda/envs/test27/lib/python2.7/site-packages/pymc/utils.py", line 14, in <module>
    from . import flib
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory
```

**Comment by simonvh** [comment]
Thanks for the notification. I will look into it. At first glance it looks like issues with some dependencies. Can you try what happens if you update pysam and pymc via conda?

**Comment by croth1** [comment]
it's a fresh installation in a fresh environment. Downgrading to "htslib<1.4" and installing openblas fixed it for now.

**Comment by simonvh** [comment]
That's good to know. When I have some time I will release a conda package for gimmemotifs.

**Comment by bgruening** [comment]
@simonvh I think you need to pin the version in your recipe, this will fix it.

**Comment by simonvh** [comment]
@bgruening will do, thanks!

**Comment by croth1** [comment]
The openblas problem occured due to an outdated installation. With the latest version, I still get the hts mismatch and:
```
Retrieving gene annotation for hg38
Expecting 10 words line 1 of /dev/stdin got 9
cut: write error: Broken pipe
Downloading hg38 genome
Trying to download http://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/chromFa.tar.gz
Trying to download http://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz
Unpacking
Creating index
Traceback (most recent call last):
  File "/usr/users/croth1/miniconda/envs/test27/bin/gimme", line 498, in <module>
    args.func(args)
  File "/usr/users/croth1/miniconda/envs/test27/lib/python2.7/site-packages/gimmemotifs/commands/genome.py", line 22, in genome
    get_genome(args.genomebuild, args.fastadir, args.indexdir)
  File "/usr/users/croth1/miniconda/envs/test27/lib/python2.7/site-packages/gimmemotifs/genome_index.py", line 174, in get_genome
    create_bedtools_fa(index_dir, genome_dir)
  File "/usr/users/croth1/miniconda/envs/test27/lib/python2.7/site-packages/gimmemotifs/genome_index.py", line 59, in create_bedtools_fa
    b.nucleotide_content(fi=os.path.join(index_dir, "genome.fa"))
  File "/usr/users/croth1/miniconda/envs/test27/lib/python2.7/site-packages/pybedtools/bedtool.py", line 778, in decorated
    result = method(self, *args, **kwargs)
  File "/usr/users/croth1/miniconda/envs/test27/lib/python2.7/site-packages/pybedtools/bedtool.py", line 204, in not_implemented_func
    raise NotImplementedError(help_str)
NotImplementedError: "nucBed" does not appear to be installed or on the path, so this method is disabled.  Please install a more recent version of BEDTools and re-import to use this method.
```

**Comment by simonvh** [comment]
Yeah, I noticed that just today too. Apparently, pybedtools won't bring in
bedtools. Installing bedtools will fix that.

**Comment by bgruening** [comment]
@croth1 did it worked for you? Can we close this issue?

**Comment by simonvh** [comment]
@bgruening I had no chance to look into this issue due to amazingly bad wifi while travelling. I will make sure to fix it coming week, and will close this issue when I'm sure it all works.
