### ISSUE TITLE
conda install maxbin2 error

### ISSUE THREAD

**Issue by Quicken-up** [bioconda/bioconda-recipes#4436]
I am trying to install the atlas pipeline following these instructions:
https://github.com/pnnl/atlas
Everything installs fine except maxbin2, which throws the AssertionError shown below. Any advice appreciated.

Current conda install:

             platform : linux-64
        conda version : 3.14.1
  conda-build version : 1.14.1
       python version : 3.4.3.final.0
     requests version : 2.7.0
     root environment : /exports/applications/apps/SL7/anaconda/2.3.0  (read only)
  default environment : /exports/cmvm/eddie/eb/groups/watson_grp/software/myanaconda/atlas_env
     envs directories : /exports/cmvm/eddie/eb/groups/watson_grp/software/myanaconda
        package cache : /exports/cmvm/eddie/eb/groups/watson_grp/software/myanaconda/.pkgs
         channel URLs : https://conda.anaconda.org/bioconda/linux-64/
                        https://conda.anaconda.org/bioconda/noarch/
                        https://conda.anaconda.org/r/linux-64/
                        https://conda.anaconda.org/r/noarch/
                        https://conda.anaconda.org/conda-forge/linux-64/
                        https://conda.anaconda.org/conda-forge/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/<user>/.condarc
    is foreign system : False

conda install maxbin2
Traceback (most recent call last):
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/myanaconda/atlas_env/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/exports/applications/apps/SL7/anaconda/2.3.0/lib/python3.4/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/exports/applications/apps/SL7/anaconda/2.3.0/lib/python3.4/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/exports/applications/apps/SL7/anaconda/2.3.0/lib/python3.4/site-packages/conda/cli/common.py", line 612, in inner
    return func(args, parser)
  File "/exports/applications/apps/SL7/anaconda/2.3.0/lib/python3.4/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/exports/applications/apps/SL7/anaconda/2.3.0/lib/python3.4/site-packages/conda/cli/install.py", line 336, in install
    minimal_hint=args.alt_hint)
  File "/exports/applications/apps/SL7/anaconda/2.3.0/lib/python3.4/site-packages/conda/plan.py", line 397, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "/exports/applications/apps/SL7/anaconda/2.3.0/lib/python3.4/site-packages/conda/resolve.py", line 739, in solve
    minimal_hint=minimal_hint)
  File "/exports/applications/apps/SL7/anaconda/2.3.0/lib/python3.4/site-packages/conda/resolve.py", line 484, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "/exports/applications/apps/SL7/anaconda/2.3.0/lib/python3.4/site-packages/conda/resolve.py", line 342, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: r-base-3.3.1-6.tar.bz2 MatchSpec('icu 54.*')

**Comment by bgruening** [comment]
Do you have a PR for us, so we can check it and see the original travis log?
Thanks!

**Comment by Quicken-up** [comment]
Hello, 
I didn't do any pull request. I just followed the installation instructions on the atlas page I linked.
Best, Rob 


On 14 April 2017 16:43:26 BST, "Björn Grüning" <notifications@github.com> wrote:
>Do you have a PR for us, so we can check it and see the original travis
>log?
>Thanks!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bioconda/bioconda-recipes/issues/4436#issuecomment-294176921

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by brwnj** [comment]
The PR for maxbin2 is https://github.com/bioconda/bioconda-recipes/pull/3726.

**Comment by cbrueffer** [comment]
@Quicken-up does this work now, given the maxbin2 fix that was committed?

**Comment by bgruening** [comment]
This seems to work for me and the package has seen many updates in the meantime. Thanks for the report!
