### ISSUE TITLE
Bioconda's nrpys doesn't install properly

### ISSUE THREAD

**Issue by kblin** [bioconda/bioconda-recipes#44377]
## Steps to reproduce:

1. `mamba create -y -n nrypstest "python=3.9.*"`
2. `mamba activate nrypstest`
3. `mamba install -y nrpys`
4. `python3 -c "import nrpys"`

## Actual result:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'nrpys'
```

## Expected result
No traceback, import succeeds.

**Comment by kblin** [comment]
`nrpys` can be made to work in this env by running `pip install nrpys`, so this must be related to how `nrpys` is packaged for bioconda.

This issue is a blocker for #44373

**Comment by mberacochea** [comment]
Building a version for py 3.9 also seems to be working:
```
$ conda install /<path>/bioconda/conda-bld/noarch/nrpys-0.1.1-py39ha8f3691_2.tar.bz2
$ python -c "import nrpys; from importlib.metadata import version; print(version('nrpys'))"
0.1.1
```

**Comment by yodeng** [comment]
The packages `nrpys-0.1.1-py311ha8f3691_1.tar.bz2` build by python3.11, and it's only compatible with py3.11 version.  but this package is compiled as a `noarch` version in the `meta.yaml`. I think that will lead the `conda solver` always make this version as a priority when solving environment if there is no cleared version (include build version) defined。

```
$ conda create -n test nrpys
...
$ conda list -n test | grep -P "python|nrpys"
nrpys                     0.1.1           py311ha8f3691_1    defaults
python                    3.12.0          hab00c5b_0_cpython    defaults
$ python -c "import nrpys; from importlib.metadata import version; print(version('nrpys'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'nrpys'
```

```
$ conda create -n test nrpys python=3.11
...
$ conda list -n test | grep -P "python|nrpys"
nrpys                     0.1.1           py311ha8f3691_1    defaults
python                    3.11.6          hab00c5b_0_cpython    defaults

$ python -c "import nrpys; from importlib.metadata import version; print(version('nrpys'))"
0.1.1
```

```
$ conda create -n test nrpys python=3.10
...
$ conda list -n test | grep -P "python|nrpys"
nrpys                     0.1.1           py311ha8f3691_1    defaults
python                    3.10.13         hd12c33a_0_cpython    defaults

$ python -c "import nrpys; from importlib.metadata import version; print(version('nrpys'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'nrpys'
```

```
$ conda create -n test "nrpys=0.1.1=py39*"
...
$ conda list -n test | grep -P "python|nrpys"
nrpys                     0.1.1            py39h87d955d_0    defaults
python                    3.9.18          h0755675_0_cpython    defaults
python_abi                3.9                      4_cp39    defaults

$ python -c "import nrpys; from importlib.metadata import version; print(version('nrpys'))"
0.1.1
```

```
$ conda create -n test "nrpys=0.1.1=py310*"
...
$ conda list -n test | grep -P "python|nrpys"
nrpys                     0.1.1           py310h8472f5a_0    defaults
python                    3.10.13         hd12c33a_0_cpython    defaults
python_abi                3.10                    4_cp310    defaults

$ python -c "import nrpys; from importlib.metadata import version; print(version('nrpys'))"
0.1.1
```

**Comment by yodeng** [comment]
These packages:

+ nrpys-0.1.1-py310h8472f5a_0.tar.bz2, build by python3.10,

  url: [https://anaconda.org/bioconda/nrpys/0.1.1/download/noarch/nrpys-0.1.1-py310h8472f5a_0.tar.bz2](https://anaconda.org/bioconda/nrpys/0.1.1/download/noarch/nrpys-0.1.1-py310h8472f5a_0.tar.bz2)

  md5: 314f4b1eb160b342860674caaad70d5b

+ nrpys-0.1.1-py39h87d955d_0.tar.bz2, build by python3.9,

  url: [https://anaconda.org/bioconda/nrpys/0.1.1/download/noarch/nrpys-0.1.1-py39h87d955d_0.tar.bz2](https://anaconda.org/bioconda/nrpys/0.1.1/download/noarch/nrpys-0.1.1-py39h87d955d_0.tar.bz2)

  md5: 8860635c9375f193755fb338d90ab526

+ nrpys-0.1.1-py38h4c6a040_0.tar.bz2, build by python3.8,

  ur: [https://anaconda.org/bioconda/nrpys/0.1.1/download/noarch/nrpys-0.1.1-py38h4c6a040_0.tar.bz2](https://anaconda.org/bioconda/nrpys/0.1.1/download/noarch/nrpys-0.1.1-py38h4c6a040_0.tar.bz2)

  md5: d6c357ce9097a6155476c38f5a24bed9

are built with `pip install -vv -e .` command in the `build.sh` file.  It's the editable mode for `pip install`,  so there are no source codes in the conda package tar file. And after `conda install`, any code of nrpys modules be installed.  When `import nrpys`, `ModuleNotFoundError` raise.

```
$ conda create -n test "nrpys=0.1.1=py310*"
...
$ conda list -n test | grep -P "python|nrpys"
nrpys                     0.1.1           py310h8472f5a_0    bioconda
python                    3.10.13         hd12c33a_0_cpython    conda-forge
python_abi                3.10                    4_cp310    conda-forge

$ python -c "import nrpys; from importlib.metadata import version; print(version('nrpys'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'nrpys'

$ ls $(python -c "import site;print(site.getsitepackages()[0])")/nrpys
ls: cannot access <path>/lib/python3.10/site-packages/nrpys: No such file or directory
```



```
$ conda create -n test "nrpys=0.1.1=py39*"
...
$ conda list -n test | grep -P "python|nrpys"
nrpys                     0.1.1            py39h87d955d_0    bioconda
python                    3.9.18          h0755675_0_cpython    conda-forge
python_abi                3.9                      4_cp39    conda-forge

$ python -c "import nrpys; from importlib.metadata import version; print(version('nrpys'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'nrpys'

$ ls $(python -c "import site;print(site.getsitepackages()[0])")/nrpys
ls: cannot access <path>/lib/python3.9/site-packages/nrpys: No such file or directory
```



```
$ conda create -n test "nrpys=0.1.1=py38*"
...
$ conda list -n test | grep -P "python|nrpys"
nrpys                     0.1.1            py38h4c6a040_0    bioconda
python                    3.8.18          hd12c33a_0_cpython    conda-forge
python_abi                3.8                      4_cp38    conda-forge

$ python -c "import nrpys; from importlib.metadata import version; print(version('nrpys'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'nrpys'

$ ls $(python -c "import site;print(site.getsitepackages()[0])")/nrpys
ls: cannot access <path>/lib/python3.8/site-packages/nrpys: No such file or directory
```

**Comment by mberacochea** [comment]
@yodeng altight, the latest version of the package wasn't buit with the flag `-e` AFAIK.

**Comment by yodeng** [comment]
@mberacochea  yes, the latest version `nrpys-0.1.1-py311ha8f3691_1.tar.bz2` wasn't buit with the flag `-e`. The problem is that version built by py3.11 and only support py3.11, but it was built as a `noarch` version in the `meta.yaml` file,  that will lead the conda solver always consider this version as a compatible dependency when solving environment if there is no clear version  defined.  More comment refer to https://github.com/bioconda/bioconda-recipes/issues/44377#issuecomment-1825111250
