### ISSUE TITLE
ResFinder version needs to be updated

### ISSUE THREAD

**Issue by ryanjameskennedy** [bioconda/bioconda-recipes#45291]
Resfinder is currently sitting on v3.1.11 instead of v4.4.2 which is incompatible with the latest database.

**Comment by ryanjameskennedy** [comment]
Upon attempting to run the test build locally before creation a PR using the following:
```
bioconda-utils build --packages resfinder --mulled-test
```
I got the following error:
```
cp: cannot stat '*.py': No such file or directory
Traceback (most recent call last):
  File "/data/bnf/dev/ryan/miniconda3/envs/bioconda/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/data/bnf/dev/ryan/miniconda3/envs/bioconda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 256, in main
    call_conda_build(action, config)
  File "/data/bnf/dev/ryan/miniconda3/envs/bioconda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
    result = api.build(
  File "/data/bnf/dev/ryan/miniconda3/envs/bioconda/lib/python3.8/site-packages/conda_build/api.py", line 180, in build
    return build_tree(
  File "/data/bnf/dev/ryan/miniconda3/envs/bioconda/lib/python3.8/site-packages/conda_build/build.py", line 3078, in build_tree
    packages_from_this = build(metadata, stats,
  File "/data/bnf/dev/ryan/miniconda3/envs/bioconda/lib/python3.8/site-packages/conda_build/build.py", line 2198, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/data/bnf/dev/ryan/miniconda3/envs/bioconda/lib/python3.8/site-packages/conda_build/utils.py", line 451, in check_call_env
    return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
  File "/data/bnf/dev/ryan/miniconda3/envs/bioconda/lib/python3.8/site-packages/conda_build/utils.py", line 427, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/data/bnf/dev/ryan/miniconda3/envs/bioconda/conda-bld/resfinder_1705654130607/work/conda_build.sh']' returned non-zero exit status 1.
```

**Comment by ryanjameskennedy** [comment]
After adding `pdm` to host requirements I got the following error:
```
ModuleNotFoundError: No module named 'pdm.pep517'
```
