### ISSUE TITLE
Package excluded by strict repo priority

### ISSUE THREAD

**Issue by mark0428** [bioconda/bioconda-recipes#45600]
I encountered this error message when updating my tool to a new version:

```
2024-02-03T21:50:07.3421107Z 21:50:07 [32mBIOCONDA INFO[0m (OUT) [?25hMamba failed to solve:[0m
2024-02-03T21:50:07.3421464Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)  - scikit-learn[0m
2024-02-03T21:50:07.3421772Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)  - keras 2.2.4.*[0m
2024-02-03T21:50:07.3422088Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)  - pandas[0m
2024-02-03T21:50:07.3422373Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)  - h5py <3[0m
2024-02-03T21:50:07.3422681Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)  - biopython[0m
2024-02-03T21:50:07.3423202Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)  - python 3.6.*[0m
2024-02-03T21:50:07.3423536Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)  - tensorflow 1.12.*[0m
2024-02-03T21:50:07.3423833Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)  - numpy <1.17[0m
2024-02-03T21:50:07.3424136Z 21:50:07 [32mBIOCONDA INFO[0m (OUT) [0m
2024-02-03T21:50:07.3424546Z 21:50:07 [32mBIOCONDA INFO[0m (OUT) with channels:[0m
2024-02-03T21:50:07.3425194Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)  - file:///opt/host-conda-bld[0m
2024-02-03T21:50:07.3425477Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)  - conda-forge[0m
2024-02-03T21:50:07.3425742Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)  - bioconda[0m
2024-02-03T21:50:07.3426205Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)  - defaults[0m
2024-02-03T21:50:07.3426468Z 21:50:07 [32mBIOCONDA INFO[0m (OUT) [0m
2024-02-03T21:50:07.3426792Z 21:50:07 [32mBIOCONDA INFO[0m (OUT) The reported errors are:[0m
2024-02-03T21:50:07.3427134Z 21:50:07 [32mBIOCONDA INFO[0m (OUT) - Encountered problems while solving:[0m
2024-02-03T21:50:07.3427611Z 21:50:07 [32mBIOCONDA INFO[0m (OUT) -   - package tensorflow-1.12.0-mkl_py36h69b6ba0_0 is excluded by strict repo priority[0m
2024-02-03T21:50:07.3427942Z 21:50:07 [32mBIOCONDA INFO[0m (OUT) -[0m
2024-02-03T21:50:07.3428286Z 21:50:07 [32mBIOCONDA INFO[0m (OUT) Traceback (most recent call last):[0m
2024-02-03T21:50:07.3428772Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)   File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 141, in mamba_get_install_actions[0m
2024-02-03T21:50:07.7575805Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)     solution = solver.solve_for_action(_specs, prefix)[0m
2024-02-03T21:50:07.7577065Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)   File "/opt/conda/lib/python3.8/site-packages/boa/core/solver.py", line 244, in solve_for_action[0m
2024-02-03T21:50:07.7578023Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)     t = self.solve(specs)[0m
2024-02-03T21:50:07.7578672Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)   File "/opt/conda/lib/python3.8/site-packages/boa/core/solver.py", line 234, in solve[0m
2024-02-03T21:50:07.7579617Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)     raise RuntimeError("Solver could not find solution." + error_string)[0m
2024-02-03T21:50:07.7580966Z 21:50:07 [32mBIOCONDA INFO[0m (OUT) RuntimeError: Solver could not find solution.Mamba failed to solve:[0m
2024-02-03T21:50:07.7581786Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)  - scikit-learn[0m
2024-02-03T21:50:07.7582318Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)  - keras 2.2.4.*[0m
2024-02-03T21:50:07.7583028Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)  - pandas[0m
2024-02-03T21:50:07.7583534Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)  - h5py <3[0m
2024-02-03T21:50:07.7584243Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)  - biopython[0m
2024-02-03T21:50:07.7584756Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)  - python 3.6.*[0m
2024-02-03T21:50:07.7585491Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)  - tensorflow 1.12.*[0m
2024-02-03T21:50:07.7586011Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)  - numpy <1.17[0m
2024-02-03T21:50:07.7586706Z 21:50:07 [32mBIOCONDA INFO[0m (OUT) [0m
2024-02-03T21:50:07.7587208Z 21:50:07 [32mBIOCONDA INFO[0m (OUT) with channels:[0m
2024-02-03T21:50:07.7587952Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)  - file:///opt/host-conda-bld[0m
2024-02-03T21:50:07.7588479Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)  - conda-forge[0m
2024-02-03T21:50:07.7589189Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)  - bioconda[0m
2024-02-03T21:50:07.7589690Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)  - defaults[0m
2024-02-03T21:50:07.7590370Z 21:50:07 [32mBIOCONDA INFO[0m (OUT) [0m
2024-02-03T21:50:07.7590891Z 21:50:07 [32mBIOCONDA INFO[0m (OUT) The reported errors are:[0m
2024-02-03T21:50:07.7591669Z 21:50:07 [32mBIOCONDA INFO[0m (OUT) - Encountered problems while solving:[0m
2024-02-03T21:50:07.7592427Z 21:50:07 [32mBIOCONDA INFO[0m (OUT) -   - package tensorflow-1.12.0-mkl_py36h69b6ba0_0 is excluded by strict repo priority[0m
2024-02-03T21:50:07.7593149Z 21:50:07 [32mBIOCONDA INFO[0m (OUT) -[0m
2024-02-03T21:50:07.7593777Z 21:50:07 [32mBIOCONDA INFO[0m (OUT) [0m
2024-02-03T21:50:07.7594533Z 21:50:07 [32mBIOCONDA INFO[0m (OUT) During handling of the above exception, another exception occurred:[0m
2024-02-03T21:50:07.7595031Z 21:50:07 [32mBIOCONDA INFO[0m (OUT) [0m
2024-02-03T21:50:07.7595740Z 21:50:07 [32mBIOCONDA INFO[0m (OUT) Traceback (most recent call last):[0m
2024-02-03T21:50:07.7596293Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)   File "/opt/conda/bin/conda-mambabuild", line 10, in <module>[0m
2024-02-03T21:50:07.7597019Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)     sys.exit(main())[0m
2024-02-03T21:50:07.7597604Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)   File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 256, in main[0m
2024-02-03T21:50:07.7598380Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)     call_conda_build(action, config)[0m
2024-02-03T21:50:07.7598994Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)   File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build[0m
2024-02-03T21:50:07.7599763Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)     result = api.build([0m
2024-02-03T21:50:07.7600344Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)   File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 180, in build[0m
2024-02-03T21:50:07.7601095Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)     return build_tree([0m
2024-02-03T21:50:07.7601690Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)   File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 3078, in build_tree[0m
2024-02-03T21:50:07.7602681Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)     packages_from_this = build(metadata, stats,[0m
2024-02-03T21:50:07.7603338Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)   File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2115, in build[0m
2024-02-03T21:50:07.7604189Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)     create_build_envs(top_level_pkg, notest)[0m
2024-02-03T21:50:07.7604886Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)   File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 1972, in create_build_envs[0m
2024-02-03T21:50:07.7605751Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)     environ.get_install_actions(m.config.test_prefix,[0m
2024-02-03T21:50:07.7606676Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)   File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 147, in mamba_get_install_actions[0m
2024-02-03T21:50:07.7607607Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)     err = DependencyNeedsBuildingError(packages=[str(x) for x in conflict_packages])[0m
2024-02-03T21:50:07.7608351Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)   File "/opt/conda/lib/python3.8/site-packages/conda_build/exceptions.py", line 79, in __init__[0m
2024-02-03T21:50:07.7609224Z 21:50:07 [32mBIOCONDA INFO[0m (OUT)     raise RuntimeError("failed to parse packages from exception:"[0m
2024-02-03T21:50:07.7609991Z 21:50:07 [32mBIOCONDA INFO[0m (OUT) RuntimeError: failed to parse packages from exception: None[0m
2024-02-03T21:50:07.7611435Z 21:50:07 [31mBIOCONDA ERROR[0m COMMAND FAILED (exited with 1): docker run -t --net host --rm -v /tmp/tmpt3_qrdw7/build_script.bash:/opt/build_script.bash -v /opt/mambaforge/envs/bioconda/conda-bld/:/opt/host-conda-bld -v /home/vsts/work/1/s/recipes/amplify:/opt/recipe -e LANG=C.UTF-8 -e HOST_USER_ID=1001 quay.io/bioconda/bioconda-utils-build-env-cos7:2.11.1 /bin/bash /opt/build_script.bash[0m
2024-02-03T21:50:07.7612044Z 
2024-02-03T21:50:07.7612757Z 21:50:07 [31mBIOCONDA ERROR[0m BUILD FAILED recipes/amplify[0m
2024-02-03T21:50:07.7613276Z 21:50:07 [32mBIOCONDA INFO[0m (COMMAND) conda build purge[0m
2024-02-03T21:50:07.7613792Z 
2024-02-03T21:50:08.9785403Z ⠋[0m running (0:00:00.00)[K
2024-02-03T21:50:08.9786215Z [K21:50:08 [31mBIOCONDA ERROR[0m BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.[0m
2024-02-03T21:50:08.9786827Z 21:50:08 [31mBIOCONDA ERROR[0m BUILD SUMMARY: FAILED recipe recipes/amplify[0m
2024-02-03T21:50:12.0664542Z 
2024-02-03T21:50:12.0790158Z ##[error]Bash exited with code '1'.
2024-02-03T21:50:12.0802077Z ##[section]Finishing: Test
```

It used to be fine for all my older versions... Pull request here https://github.com/bioconda/bioconda-recipes/pull/45596

Thanks in advance!

**Comment by mark0428** [comment]
Finally passed the tests by loosening the tensorflow version constraint to be >=1.10, <1.13. The test process downloaded v1.10, while v1.12 can still be downloaded even with the new version constraint on our own machines when installing the tool.

The might be something unusual with the testing system I guess.
