### ISSUE TITLE
cnv_facets fails to build

### ISSUE THREAD

**Issue by stianlagstad** [bioconda/bioconda-recipes#46927]
cvn_facets is in the blacklist on the current master branch: https://github.com/bioconda/bioconda-recipes/blob/6f666fd2c03adf396a0327a27b6ea14dacba0c55/build-fail-blacklist#L684

I am not able to build the recipe myself either. Here is how it fails on my machine:
```
$ bioconda-utils build recipes --packages cnv_facets
...
13:01:40 BIOCONDA INFO (OUT) > install.packages(c("argparse"), lib= NULL, repos= "https://cran.r-project.org")
13:01:40 BIOCONDA INFO (OUT) >
13:01:40 BIOCONDA INFO (OUT) >
13:01:47 BIOCONDA ERROR COMMAND FAILED (exited with 1): /home/stian/miniconda3/envs/bioconda-build/bin/conda mambabuild --override-channels --no-anaconda-upload -c conda-forge -c bioconda -c defaults -e /home/stian/miniconda3/envs/bioconda-build/conda_build_config.yaml -e /home/stian/miniconda3/envs/bioconda-build/lib/python3.9/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml recipes/cnv_facets/meta.yaml

13:01:47 BIOCONDA ERROR BUILD FAILED recipes/cnv_facets
13:01:47 BIOCONDA INFO (COMMAND) conda build purge
13:01:48 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
13:01:48 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/cnv_facets
```

Trying to execute that command (`/home/stian/miniconda3/envs/bioconda-build/bin/conda mambabuild --override-channels --no-anaconda-upload -c conda-forge -c bioconda -c defaults -e /home/stian/miniconda3/envs/bioconda-build/conda_build_config.yaml -e /home/stian/miniconda3/envs/bioconda-build/lib/python3.9/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml recipes/cnv_facets/meta.yaml`) directly gives more info:
```
...

** testing if installed package keeps a record of temporary installation path
* DONE (argparse)

The downloaded source packages are in
        ‘/tmp/RtmpFu4ldW/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
>
>
Error in makeCluster(nprocs, type = "FORK") :
  could not find function "makeCluster"
Calls: exec_snp_pileup_parallel
Execution halted
Traceback (most recent call last):
  File "/home/stian/miniconda3/envs/bioconda-build/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/home/stian/miniconda3/envs/bioconda-build/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 256, in main
    call_conda_build(action, config)
  File "/home/stian/miniconda3/envs/bioconda-build/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
    result = api.build(
  File "/home/stian/miniconda3/envs/bioconda-build/lib/python3.9/site-packages/conda_build/api.py", line 180, in build
    return build_tree(
  File "/home/stian/miniconda3/envs/bioconda-build/lib/python3.9/site-packages/conda_build/build.py", line 3078, in build_tree
    packages_from_this = build(metadata, stats,
  File "/home/stian/miniconda3/envs/bioconda-build/lib/python3.9/site-packages/conda_build/build.py", line 2198, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/home/stian/miniconda3/envs/bioconda-build/lib/python3.9/site-packages/conda_build/utils.py", line 451, in check_call_env
    return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
  File "/home/stian/miniconda3/envs/bioconda-build/lib/python3.9/site-packages/conda_build/utils.py", line 427, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/stian/miniconda3/envs/bioconda-build/conda-bld/cnv_facets_1712058326761/work/conda_build.sh']' returned non-zero exit status 1.
```

Executing that command (`/home/stian/miniconda3/envs/bioconda-build/conda-bld/cnv_facets_1712058326761/work/conda_build.sh`) directly gives this failure:
```
...
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
>
>
chmod: cannot access 'bin/cnv_facets.R': No such file or directory
```

Any tips on how to resolve this will be greatly appreciated, thanks.

**Comment by martin-g** [comment]
It fails here - https://github.com/bioconda/bioconda-recipes/blob/e9b59e5c80db76a16b4e970249807aad1f58f94e/recipes/cnv_facets/build.sh#L15
You could add `ls -la bin` before that line to list what files are available there. Maybe the name does not match.
