### ISSUE TITLE
make: g++: No such file or directory

### ISSUE THREAD

**Issue by wshuai294** [bioconda/bioconda-recipes#47103]
Hello,

In pull request, I got this error:
```

10:39:56 BIOCONDA INFO (OUT) Success
10:39:56 BIOCONDA INFO (OUT) INFO:conda_build.source:Success
10:39:56 BIOCONDA INFO (OUT) Extracting download
10:39:56 BIOCONDA INFO (OUT) source tree in: /opt/conda/conda-bld/localhgt_1712658969352/work
10:39:56 BIOCONDA INFO (OUT) export PREFIX=/opt/conda/conda-bld/localhgt_1712658969352/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac
10:39:56 BIOCONDA INFO (OUT) export BUILD_PREFIX=/opt/conda/conda-bld/localhgt_1712658969352/_build_env
10:39:56 BIOCONDA INFO (OUT) export SRC_DIR=/opt/conda/conda-bld/localhgt_1712658969352/work
10:39:58 BIOCONDA INFO (OUT) g++  -std=c++11 -pthread   -o scripts/extract_ref ./src/extract_ref_normal_peak.cpp
10:39:58 BIOCONDA INFO (OUT) make: g++: No such file or directory
10:39:58 BIOCONDA INFO (OUT) make: *** [Makefile:6: extract_ref] Error 127
10:39:59 BIOCONDA INFO (OUT) Traceback (most recent call last):
10:39:59 BIOCONDA INFO (OUT)   File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
10:39:59 BIOCONDA INFO (OUT)     sys.exit(main())
10:39:59 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 256, in main
10:39:59 BIOCONDA INFO (OUT)     call_conda_build(action, config)
10:39:59 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
10:39:59 BIOCONDA INFO (OUT)     result = api.build(
10:39:59 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.9/site-packages/conda_build/api.py", line 180, in build
10:39:59 BIOCONDA INFO (OUT)     return build_tree(
10:39:59 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 3078, in build_tree
10:39:59 BIOCONDA INFO (OUT)     packages_from_this = build(metadata, stats,
10:39:59 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 2198, in build
10:39:59 BIOCONDA INFO (OUT)     utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
10:39:59 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.9/site-packages/conda_build/utils.py", line 451, in check_call_env
10:39:59 BIOCONDA INFO (OUT)     return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
10:39:59 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.9/site-packages/conda_build/utils.py", line 427, in _func_defaulting_env_to_os_environ
10:39:59 BIOCONDA INFO (OUT)     raise subprocess.CalledProcessError(proc.returncode, _args)
10:39:59 BIOCONDA INFO (OUT) subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/localhgt_1712658969352/work/conda_build.sh']' returned non-zero exit status 2.
10:40:09 BIOCONDA ERROR COMMAND FAILED (exited with 1): docker run -t --net host --rm -v /tmp/tmp3jk4hpjc/build_script.bash:/opt/build_script.bash -v /opt/mambaforge/envs/bioconda/conda-bld/:/opt/host-conda-bld -v /home/vsts/work/1/s/recipes/localhgt:/opt/recipe -e LANG=C.UTF-8 -e HOST_USER_ID=1001 quay.io/bioconda/bioconda-utils-build-env-cos7:2.14.0 /bin/bash /opt/build_script.bash

10:40:09 BIOCONDA ERROR BUILD FAILED recipes/localhgt
10:40:09 BIOCONDA INFO (COMMAND) conda build purge

⠋ running (0:00:00.00)
10:40:11 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
10:40:11 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/localhgt

##[error]Bash exited with code '1'.
Finishing: Test
```
However, I have indicate the compiling tool in meta.ymal:
```
requirements:
  bulid:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - gcc
```
Could you please help me?

Best,
Shuai Wang

**Comment by martin-g** [comment]
The C compiler is available as `$CC` environment variable and the C++ as `$CXX`.
Could you update your build scripts to use those env vars instead of hardcoding `g++` ?

**Comment by martin-g** [comment]
https://github.com/bioconda/bioconda-recipes/pull/47087/files#r1557494961

**Comment by wshuai294** [comment]
Thank you so much for your quick response. I have revised it as suggested. However, it reports this:
```
/opt/conda/conda-bld/localhgt_1712666700884/work/conda_build.sh: line 18: CXX: unbound variable
```

**Comment by wshuai294** [comment]
Thanks for the help. I solved the issue by refining the formate of `meta.yaml`.
