### ISSUE TITLE
drop 1.3.4 build fails after merging: downloaded artifact not a zip file

### ISSUE THREAD

**Issue by AtaJadidAhari** [bioconda/bioconda-recipes#48129]
Hi,

drop v1.3.4 was merged successfully #48083, but it seems to have [failed the CI](https://github.com/bioconda/bioconda-recipes/runs/25485238480) after merging and is not available for download. 
It fails in `build_and_push_linux` in `Handle merged PR` section with the following error where it seems like it cannot download the artifacts:

> 06:35:57 BIOCONDA INFO Downloading artifact https://artprodsu6weu.artifacts.visualstudio.com/A27bcc0f9-b22c-4418-83d8-514809b37fb2/25074ded-3133-43ca-af80-895ab87b53cb/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2Jpb2NvbmRhL3Byb2plY3RJZC8yNTA3NGRlZC0zMTMzLTQzY2EtYWY4MC04OTVhYjg3YjUzY2IvYnVpbGRJZC81OTc5Ny9hcnRpZmFjdE5hbWUvTGludXhBcnRpZmFjdHM1/content?format=zip.
Traceback (most recent call last):
  File "/opt/mambaforge/envs/bioconda/bin/bioconda-utils", line 8, in <module>
    sys.exit(main())
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/bioconda_utils/cli.py", line 1124, in main
    argh.dispatch_commands([
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/argh/dispatching.py", line 510, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/argh/dispatching.py", line 198, in dispatch
    return run_endpoint_function(
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/argh/dispatching.py", line 269, in run_endpoint_function
    return _process_command_output(lines, output_file, raw_output, always_flush)
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/argh/dispatching.py", line 289, in _process_command_output
    for line in lines:
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/argh/dispatching.py", line 414, in _execute_command
    for line in result:
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/argh/dispatching.py", line 394, in _call
    result = function(*positional_values, **values_by_name)
  File "<boltons.funcutils.FunctionBuilder-7>", line 2, in handle_merged_pr
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/bioconda_utils/cli.py", line 137, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-6>", line 2, in handle_merged_pr
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/bioconda_utils/cli.py", line 66, in wrapper
    func(*args, **kwargs)
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/bioconda_utils/cli.py", line 546, in handle_merged_pr
    res = upload_pr_artifacts(
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/bioconda_utils/artifacts.py", line 58, in upload_pr_artifacts
    zipfile.ZipFile(artifact_path).extractall(tmpdir)
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/zipfile.py", line 1271, in __init__
    self._RealGetContents()
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/zipfile.py", line 1338, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[error]Bash exited with code '1'.

`https://artprodsu6weu.artifacts.visualstudio.com/A27bcc0f9-b22c-4418-83d8-514809b37fb2/25074ded-3133-43ca-af80-895ab87b53cb/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2Jpb2NvbmRhL3Byb2plY3RJZC8yNTA3NGRlZC0zMTMzLTQzY2EtYWY4MC04OTVhYjg3YjUzY2IvYnVpbGRJZC81OTc5Ny9hcnRpZmFjdE5hbWUvTGludXhBcnRpZmFjdHM1/content?format=zip` file exists and can be downloaded, so maybe if we re trigger the run it will be successful this time.

Any idea how this can be fixed? 

Thanks!

**Comment by martin-g** [comment]
I've restarted the CI job - https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=59799&view=logs&j=640a6e15-8786-5119-b5ea-bb1b0ee951f5

**Comment by martin-g** [comment]
I think all went well this time!
Please confirm and close this issue!
