### ISSUE TITLE
`simulate_travis.py` --docker fails with CondaHTTPError/ConnectTimeoutError

### ISSUE THREAD

**Issue by vinjana** [bioconda/bioconda-recipes#5027]
Hi

I am trying to run simulate_travis.py from behind a firewall with internet access through a proxy. The proxy configs work for everything but the container (i.e. also for conda/conda-build). Here the output:

```
$ echo $http_proxy
http://www-int2:80
$ echo $https_proxy 
http://www-int2:80
$ HTTP_PROXY=$http_proxy HTTPS_PROXY=$https_proxy ./simulate-travis.py --docker --loglevel=debug
+ bioconda-utils lint recipes config.yml --git-range master HEAD
12:45:56 BIOCONDA INFO Recipes newly unblacklisted:

12:45:56 BIOCONDA INFO Recipes to consider according to git: recipes/perl-vcftools-vcf/0.840
 recipes/perl-vcftools-vcf
 recipes/vcftools/0.1.11
 recipes/vcftools
12:45:56 BIOCONDA INFO Commit message defines skip lint test missing_hash for recipe recipes/perl-vcftools-vcf
12:45:56 BIOCONDA INFO Commit message defines skip lint test uses_perl_threaded for recipe recipes/perl-vcftools-vcf
+ set +x
+ bioconda-utils build recipes config.yml --loglevel=info --docker --loglevel=debug --git-range master HEAD
12:45:59 BIOCONDA INFO DOCKER: Pulling docker image condaforge/linux-anvil
12:46:01 BIOCONDA DEBUG DOCKER: stdout+stderr:
Using default tag: latest
latest: Pulling from condaforge/linux-anvil
Digest: sha256:39d802ab97ae63512541d704ca446575fb9ce620dc660c9d0d2f3d364228f5bb
Status: Image is up to date for condaforge/linux-anvil:latest

12:46:01 BIOCONDA INFO DOCKER: Done pulling image
12:46:01 BIOCONDA INFO DOCKER: Building image "tmp-bioconda-builder" from /tmp/tmp2oemkogc
12:46:01 BIOCONDA DEBUG Dockerfile:

FROM condaforge/linux-anvil
COPY requirements.txt /tmp/requirements.txt
RUN /opt/conda/bin/conda config --add channels conda-forge
RUN /opt/conda/bin/conda config --add channels defaults
RUN /opt/conda/bin/conda config --add channels r
RUN /opt/conda/bin/conda config --add channels bioconda
RUN /opt/conda/bin/conda install --file /tmp/requirements.txt

..12:47:15 BIOCONDA ERROR COMMAND FAILED: docker build -t tmp-bioconda-builder /tmp/tmp2oemkogc
12:47:15 BIOCONDA ERROR STDOUT+STDERR:
Sending build context to Docker daemon  3.072kB
Step 1/7 : FROM condaforge/linux-anvil
 ---> f038280ec208
Step 2/7 : COPY requirements.txt /tmp/requirements.txt
 ---> Using cache
 ---> a5a3b7c39559
Step 3/7 : RUN /opt/conda/bin/conda config --add channels conda-forge
 ---> Using cache
 ---> 6c801cf6f88a
Step 4/7 : RUN /opt/conda/bin/conda config --add channels defaults
 ---> Using cache
 ---> c508c61a9a46
Step 5/7 : RUN /opt/conda/bin/conda config --add channels r
 ---> Using cache
 ---> e159427eaad7
Step 6/7 : RUN /opt/conda/bin/conda config --add channels bioconda
 ---> Using cache
 ---> 1c600638f307
Step 7/7 : RUN /opt/conda/bin/conda install --file /tmp/requirements.txt
 ---> Running in e29a79dccb54
Fetching package metadata ...
CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/bioconda/linux-64/repodata.json>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /bioconda/linux-64/repodata.json (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2d00458898>, 'Connection to conda.anaconda.org timed out. (connect timeout=9.15)'))",),)


The command '/bin/sh -c /opt/conda/bin/conda install --file /tmp/requirements.txt' returned a non-zero code: 1


12:48:01 BIOCONDA ERROR DOCKER FAILED: Error building docker container tmp-bioconda-builder. 
Traceback (most recent call last):
  File "/data/kensche/work/share/miniconda3/bin/bioconda-utils", line 11, in <module>
    load_entry_point('bioconda-utils', 'console_scripts', 'bioconda-utils')()
  File "/data/kensche/work/code/bioconda-utils/bioconda_utils/cli.py", line 353, in main
    argh.dispatch_commands([build, dag, dependent, lint])
  File "/data/kensche/work/share/miniconda3/lib/python3.5/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/data/kensche/work/share/miniconda3/lib/python3.5/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/data/kensche/work/share/miniconda3/lib/python3.5/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/data/kensche/work/share/miniconda3/lib/python3.5/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/data/kensche/work/code/bioconda-utils/bioconda_utils/cli.py", line 253, in build
    conda_build_version=conda_build_version,
  File "/data/kensche/work/code/bioconda-utils/bioconda_utils/docker_utils.py", line 311, in __init__
    self._build_image()
  File "/data/kensche/work/code/bioconda-utils/bioconda_utils/docker_utils.py", line 361, in _build_image
    raise e
  File "/data/kensche/work/code/bioconda-utils/bioconda_utils/docker_utils.py", line 356, in _build_image
    p = utils.run(cmd)
  File "/data/kensche/work/code/bioconda-utils/bioconda_utils/utils.py", line 127, in run
    raise e
  File "/data/kensche/work/code/bioconda-utils/bioconda_utils/utils.py", line 121, in run
    **kwargs)
  File "/data/kensche/work/share/miniconda3/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker', 'build', '-t', 'tmp-bioconda-builder', '/tmp/tmp2oemkogc']' returned non-zero exit status 1
12:48:01 BIOCONDA ERROR COMMAND FAILED: docker rmi tmp-bioconda-builder
12:48:01 BIOCONDA ERROR STDOUT+STDERR:
Error response from daemon: No such image: tmp-bioconda-builder:latest

Exception ignored in: <bound method RecipeBuilder.__del__ of <bioconda_utils.docker_utils.RecipeBuilder object at 0x7f3422239780>>
Traceback (most recent call last):
  File "/data/kensche/work/code/bioconda-utils/bioconda_utils/docker_utils.py", line 314, in __del__
    self.cleanup()
  File "/data/kensche/work/code/bioconda-utils/bioconda_utils/docker_utils.py", line 429, in cleanup
    utils.run(cmd)
  File "/data/kensche/work/code/bioconda-utils/bioconda_utils/utils.py", line 127, in run
    raise e
  File "/data/kensche/work/code/bioconda-utils/bioconda_utils/utils.py", line 121, in run
    **kwargs)
  File "/data/kensche/work/share/miniconda3/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker', 'rmi', 'tmp-bioconda-builder']' returned non-zero exit status 1
```

I would appreciate your help! Tell me if you need more information.

**Comment by daler** [comment]
Based on https://blog.codeship.com/using-docker-behind-a-proxy, you'll need to make a change to your `/etc/default/docker`, and we can make changes to bioconda-utils to pass through http proxies to the Dockerfile if they're in the environment.

**Comment by daler** [comment]
@vinjana can you try changing the `BIOCONDA_UTILS_TAG` line in `.travis.yml` from `master` to `http-proxy-for-docker`, make the change to your `/etc/default/docker`, and see if it works?

**Comment by vinjana** [comment]
I changed the `.travis.yml` and got the changes in `/etc/default/docker`. Additionally, because I use CentOS 7, our sysadmin added the following to `/etc/systemd/system/docker.service.d/proxy.conf`:
```
[Service]
 Environment="http_proxy=http://www-int2:80"
 Environment="https_proxy=http://www-int2:80"
```
The container still fails with the same error message.

**Comment by vinjana** [comment]
O.k. some updates:

* Conda takes the environment variables ```HTTP_PROXY``` or ```HTTPS_PROXY``` (in all capitals) to use the proxy (see [here](https://conda.io/docs/config.html#configure-conda-for-use-behind-a-proxy-server-proxy-servers)).
* On the two systems in our network that I tested the ```--network``` parameter of ```docker build``` needed to be set to ```host```

So, the command that works is
```
docker build --network=host \
   --build-arg "HTTPS_PROXY=$https_proxy" \
   -t tmp-bioconda-builder \
   /tmp/tmBiocondaDirWithDockerfile
```

For me docker complains ```[Warning] One or more build-args [HTTPS_PROXY] were not consumed```, but that's a untrue as the variable is obviously used. Maybe one could use the ARG dockerfile instruction to get rid of the message.

Maybe this helps to implement some support in bioconda-utils, if desired.

**Comment by daler** [comment]
Great, thanks for the follow-up. I'll work on getting this into bioconda-utils and report back here so you can test further.

**Comment by daler** [comment]
@vinjana can you try that branch again please? I made some fixes, including passing both `http_proxy` and `HTTP_PROXY` through to the docker build, and making sure those vars are set _before_ conda install commnad. We already use `--net host`, so that didn't have to change.

**Comment by vinjana** [comment]
So the 4 proxy variables are set but the `/opt/conda/bin/conda install --file /tmp/requirements.txt` command in the Dockerfile still fails with 

```
Sending build context to Docker daemon  3.072kB
Step 1/10 : FROM condaforge/linux-anvil
 ---> 1362d7115380
Step 2/10 : COPY requirements.txt /tmp/requirements.txt
 ---> Using cache
 ---> 193ec8514dc3
Step 3/10 : ENV http_proxy http://www-int2:80
 ---> Using cache
 ---> 21c4d9061fd6
Step 4/10 : ENV HTTP_PROXY http://www-int2:80
 ---> Using cache
 ---> c40c010ebfd9
Step 5/10 : ENV https_proxy http://www-int2:80
 ---> Using cache
 ---> 4992b22a77e6
Step 6/10 : ENV HTTPS_PROXY http://www-int2:80
 ---> Using cache
 ---> 6974c5bdd6cd
Step 7/10 : RUN /opt/conda/bin/conda config --add channels defaults
 ---> Using cache
 ---> e24b7003ece0
Step 8/10 : RUN /opt/conda/bin/conda config --add channels conda-forge
 ---> Using cache
 ---> 818eb0292e35
Step 9/10 : RUN /opt/conda/bin/conda config --add channels bioconda
 ---> Using cache
 ---> ecfd97c9636d
Step 10/10 : RUN /opt/conda/bin/conda install --file /tmp/requirements.txt
 ---> Running in 7f488d596512
Fetching package metadata ... 
CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/bioconda/linux-64/repodata.json>                                                                                                                                 
Elapsed: None                                                                                                                                                                                                                       

An HTTP error occurred when trying to retrieve this URL.                                                                                                                                                                            
HTTP errors are often intermittent, and a simple retry will get you on your way.                                                                                                                                                    
ProxyError(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /bioconda/linux-64/repodata.json (Caused by ProxyError('Cannot connect to proxy.', timeout('select timed out',)))",),)                                                                                                                                                                                                                               


The command '/bin/sh -c /opt/conda/bin/conda install --file /tmp/requirements.txt' returned a non-zero code: 1
```

I think this is because the call lacks the `--network host` option and should rather be: 

```
docker build --network host -t tmp-bioconda-builder /tmp/tmpy6a4hi6j
```

At least this is how I can get it running.

**Comment by daler** [comment]
Ah, @vinjana thanks for the clarification, sorry I missed that. I'll add the `--network host` option for the build step.

**Comment by daler** [comment]
Can you give it another shot @vinjana?

**Comment by vinjana** [comment]
Great, it works! Thanks!

**Comment by daler** [comment]
Great! I'll merge that PR. Sorry it took a couple of rounds; I didn't have a good way of testing.

**Comment by vinjana** [comment]
No worry. I'm happy that I can now try to reproduce the CI errors in Travis :-P
