### ISSUE TITLE
Start using stdlib('c') in recipes

### ISSUE THREAD

**Issue by isuruf** [bioconda/bioconda-recipes#51185]
conda-forge is using these to be explicit about the sysroot version and bioconda should too.

cc @mbargull

**Comment by martin-g** [comment]
We tried to add it in one of the recipes but it failed to lint: https://github.com/bioconda/bioconda-recipes/pull/51295#discussion_r1796588558
https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=71416&view=logs&j=eb1ca712-fec5-5d93-deb0-40983fe61f2f&t=c9ebc308-e058-58af-a4f4-866fa7649dbb&l=39

CC @mfansler

**Comment by aliciaaevans** [comment]
I am at a conference this week, but I will plan to take a look next week at what needs to be changed in the linting. (But if anyone else wants to submit a PR to bioconda-utils, please feel free.)

**Comment by jakirkham** [comment]
Tried looking at the link Martin included above, but it looks like the log expired. If someone has a fresh copy of the lint error, could you please add it here as a comment. That way we can get a better handle on the issue and how best to proceed

**Comment by mbhall88** [comment]
> Tried looking at the link Martin included above, but it looks like the log expired. If someone has a fresh copy of the lint error, could you please add it here as a comment. That way we can get a better handle on the issue and how best to proceed

Here is one from a recent attempt to use `{{ stdlib('c') }}` in #52356  (CI link https://github.com/bioconda/bioconda-recipes/actions/runs/12009842945/job/33475427794)

```
12:19:06 BIOCONDA ERROR Unexpected exception in lint_one
Traceback (most recent call last):
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/bioconda_utils/lint/__init__.py", line 614, in lint_one
    res = self.check_instances[check].run(recipe, fix)
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/bioconda_utils/lint/__init__.py", line 235, in run
    self.check_recipe(recipe)
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/bioconda_utils/lint/check_syntax.py", line 29, in check_recipe
    has_constraints = constraints.search(spec)
TypeError: expected string or bytes-like object
12:19:06 ASYNCIO DEBUG Using selector: EpollSelector
12:19:35 BIOCONDA DEBUG Found: LintMessage(recipe=Recipe "lrge", check='version_constraints_missing_whitespace', severity=<Severity.ERROR: 30>, title='Check raised an unexpected exception', body='', start_line=0, end_line=0, fname='meta.yaml', canfix=False)
The following problems have been found (visit https://bioconda.github.io/contributor/linting.html for details on the particular lints you get below.):

ERROR: meta.yaml:0: version_constraints_missing_whitespace: Check raised an unexpected exception
```

I took a look at the linting code for this lint in bioconda-utils. Essentially I think I a=have tracked it back to this jinja templating dictionary https://github.com/bioconda/bioconda-utils/blob/6240d31e706b91b4b217ab10305fb84aabd8a147/bioconda_utils/recipe.py#L138-L143

It seems easy enough on the surface to add something like `"stdlib" : lambda x: "stdlib_{x}"` but I don't know what the downstream effects of using that path in the recipe would be for bioconda-utils as a whole?

**Comment by jakirkham** [comment]
Seems the origin of the `compiler` line was effectively doing the same thing: https://github.com/bioconda/bioconda-utils/commit/3cb4b1f0e051d483439900446feef715805ff73e

cc @epruesse (who added `compiler` and would have more insight into the linter code)

**Comment by epruesse** [comment]
Just seeing that ping. Oh my. I can't even remember what I did there. Is this issue still open/current/relevant?

**Comment by jakirkham** [comment]
Probably best to look at PR: https://github.com/bioconda/bioconda-utils/pull/1044

That seems where recent work is occurring

**Comment by epruesse** [comment]
Yes, I think @aliciaaevans's got it now.

**Comment by jakirkham** [comment]
Curious where things stand on this issue at this point?

Noticed at least some recipes are now using `{{ stdlib("c") }}`. For example: https://github.com/bioconda/bioconda-recipes/pull/52941

**Comment by jdblischak** [comment]
Can this Issue be closed now that https://github.com/bioconda/bioconda-utils/pull/1091 was merged?

xref: https://github.com/bioconda/bioconda-utils/pull/1044
