### ISSUE TITLE
Elusive bug

### ISSUE THREAD

**Issue by jmeppley** [bioconda/bioconda-recipes#5120]
I'm tracking down an elusive bug and need some guidance. If I import ete3.Tree, I cannot use python's multiprocessing library. This only happens if I have add conda-forge channel to my conda-env create command and I also have blast installed.

So the broken conda config is:
```
==> ebforge.yml <==
channels:
    - bioconda
    - conda-forge
dependencies:
    - python=3
    - ete3
    - blast
```
The python commands to produce the error are:
```
(/slipstream/home/jmeppley/tmp/Bethanie/ebforge) jmeppley@moleculardb:~/tmp/Bethanie$ python
Python 3.6.1 | packaged by conda-forge | (default, May 23 2017, 14:16:20)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from multiprocessing import Manager
>>> Manager().dict()
<DictProxy object, typeid 'dict' at 0x7fa5a6ee50f0>
>>> from ete3 import Tree
>>> Manager().dict()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/slipstream/home/jmeppley/tmp/Bethanie/ebforge/lib/python3.6/multiprocessing/managers.py", line 665, in temp
    authkey=self._authkey, exposed=exp
  File "/slipstream/home/jmeppley/tmp/Bethanie/ebforge/lib/python3.6/multiprocessing/managers.py", line 731, in __init__
    self._incref()
  File "/slipstream/home/jmeppley/tmp/Bethanie/ebforge/lib/python3.6/multiprocessing/managers.py", line 785, in _incref
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/slipstream/home/jmeppley/tmp/Bethanie/ebforge/lib/python3.6/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/slipstream/home/jmeppley/tmp/Bethanie/ebforge/lib/python3.6/multiprocessing/connection.py", line 732, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/slipstream/home/jmeppley/tmp/Bethanie/ebforge/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/slipstream/home/jmeppley/tmp/Bethanie/ebforge/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/slipstream/home/jmeppley/tmp/Bethanie/ebforge/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
>>>
```
However, the error vanished if I either remove conda-forge from the channels or blast from the packages:

```
==> ebnoforge.yml <==
channels:
    - bioconda
dependencies:
    - python=3
    - ete3
    - blast

==> enoblast.yml <==
channels:
    - bioconda
    - conda-forge
dependencies:
    - python=3
    - ete3
```

The eb1 enviromnet was created using the ebforge definition above. There is no error in the ebnoforge environment. The installed package lists (from `conda env list`) are:

```
# packages in environment at /slipstream/home/jmeppley/tmp/Bethanie/ebforge:
#
blast                     2.6.0               boost1.61_0    bioconda
boost                     1.61.0                   py36_0
ca-certificates           2017.4.17                     0    conda-forge
certifi                   2017.4.17                py36_0    conda-forge
ete3                      3.0.0b35                 py36_1    bioconda
fontconfig                2.12.1                        3    conda-forge
freetype                  2.7                           1    conda-forge
icu                       54.1                          0
libgcc                    5.2.0                         0
libgfortran               3.0.0                         1
libiconv                  1.14                          4    conda-forge
libpng                    1.6.28                        0    conda-forge
libuuid                   1.0.3                         1    conda-forge
libxcb                    1.12                          1    conda-forge
libxml2                   2.9.4                         0
libxslt                   1.1.29                        4    conda-forge
lxml                      3.8.0                    py36_0    conda-forge
mkl                       2017.0.3                      0
ncurses                   5.9                          10    conda-forge
numpy                     1.13.0                   py36_0
openssl                   1.0.2l                        0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
pyqt                      4.11.4                   py36_2    conda-forge
python                    3.6.1                         3    conda-forge
qt                        4.8.7                         3
readline                  6.2                           0    conda-forge
scipy                     0.19.1              np113py36_0
setuptools                33.1.1                   py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.10.0                   py36_1    conda-forge
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.19                        1    conda-forge
wheel                     0.29.0                   py36_0    conda-forge
xorg-kbproto              1.0.7                         1    conda-forge
xorg-libice               1.0.9                         2    conda-forge
xorg-libsm                1.2.2                         2    conda-forge
xorg-libx11               1.6.4                         6    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xorg-libxext              1.3.3                         2    conda-forge
xorg-libxrender           0.9.10                        0    conda-forge
xorg-renderproto          0.11.1                        1    conda-forge
xorg-xextproto            7.3.0                         1    conda-forge
xorg-xproto               7.0.31                        6    conda-forge
xz                        5.2.2                         0    conda-forge
zlib                      1.2.11                        0    conda-forge

# packages in environment at /slipstream/home/jmeppley/tmp/Bethanie/ebnoforge:
#
blast                     2.6.0               boost1.61_0    bioconda
boost                     1.61.0                   py35_0
cairo                     1.14.8                        0
ete3                      3.0.0b35                 py35_0    bioconda
fontconfig                2.12.1                        3
freetype                  2.5.5                         2
glib                      2.50.2                        1
harfbuzz                  0.9.39                        2
icu                       54.1                          0
libffi                    3.2.1                         1
libgcc                    5.2.0                         0
libgfortran               3.0.0                         1
libiconv                  1.14                          0
libpng                    1.6.27                        0
libxml2                   2.9.4                         0
libxslt                   1.1.29                        0
lxml                      3.8.0                    py35_0
mkl                       2017.0.3                      0
numpy                     1.13.0                   py35_0
openssl                   1.0.2l                        0
pango                     1.40.3                        1
pcre                      8.39                          1
pip                       9.0.1                    py35_1
pixman                    0.34.0                        0
pyqt                      4.11.4                   py35_4
python                    3.5.3                         1
qt                        4.8.7                         4
readline                  6.2                           2

# packages in environment at /slipstream/home/jmeppley/tmp/Bethanie/enoblast:
#
ca-certificates           2017.4.17                     0    conda-forge
cairo                     1.14.6                        4    conda-forge
certifi                   2017.4.17                py36_0    conda-forge
ete3                      3.0.0b35                 py36_1    bioconda
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
gettext                   0.19.7                        1    conda-forge
glib                      2.51.4                        0    conda-forge
graphite2                 1.3.9                         0    conda-forge
harfbuzz                  1.4.3                         0    conda-forge
icu                       58.1                          1    conda-forge
jpeg                      9b                            0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc                    5.2.0                         0
libgfortran               3.0.0                         1
libiconv                  1.14                          4    conda-forge
libpng                    1.6.28                        0    conda-forge
libtiff                   4.0.6                         7    conda-forge
libuuid                   1.0.3                         1    conda-forge
libxcb                    1.12                          1    conda-forge
libxml2                   2.9.4                         4    conda-forge
libxslt                   1.1.29                        5    conda-forge
lxml                      3.8.0                    py36_0    conda-forge
mkl                       2017.0.3                      0
ncurses                   5.9                          10    conda-forge
numpy                     1.13.0                   py36_0
openssl                   1.0.2k                        0    conda-forge
pango                     1.40.4                        0    conda-forge
pcre                      8.39                          0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
pixman                    0.34.0                        0    conda-forge
pyqt                      4.11.4                   py36_2    conda-forge
python                    3.6.1                         3    conda-forge
qt                        4.8.7                         7    conda-forge
readline                  6.2                           0    conda-forge
scipy                     0.19.1              np113py36_0
setuptools                33.1.1                   py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.10.0                   py36_1    conda-forge
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.19                        1    conda-forge
wheel                     0.29.0                   py36_0    conda-forge
xorg-kbproto              1.0.7                         1    conda-forge
xorg-libice               1.0.9                         2    conda-forge
xorg-libsm                1.2.2                         2    conda-forge
xorg-libx11               1.6.4                         6    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xorg-libxext              1.3.3                         2    conda-forge
xorg-libxrender           0.9.10                        0    conda-forge
xorg-renderproto          0.11.1                        1    conda-forge
xorg-xextproto            7.3.0                         1    conda-forge
xorg-xproto               7.0.31                        6    conda-forge
xz                        5.2.2                         0    conda-forge
zlib                      1.2.11                        0    conda-forge
```

It happens on both Ubuntu 14.04.5 LTS and Fedora 21.

I think it might be connected to the line "from PyQt4.QtGui import *", but I can't quite pin it down.

**Comment by jmeppley** [comment]
This bug is linked to the version of python. If I force python 3.5, then everything works OK. So for now, I've just limited the Anvi'o package (the whole reason I went down this rabbit hole) to python 3.5.
