### ISSUE TITLE
pysam linked against missing libbz2

### ISSUE THREAD

**Issue by andreas-wilm** [bioconda/bioconda-recipes#5188]
Hi all,

it seems pysam 0.11.2.2-htslib1.5_2 bioconda is linked against a missing libbz2 library:

```
$ conda create -n pysam-bzlinkerr pysam
...
bzip2:      1.0.6-3
pysam:      0.11.2.2-htslib1.5_2 bioconda
python:     2.7.13-0
htslib:     1.5-0                bioconda
samtools:   1.5-0                bioconda
...
$ source activate pysam-bzlinkerr
$ python -c 'import pysam'
...
    from pysam.libchtslib import *
ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory

```

This problem does not happen with pysam=0.11.2.1=py27_0

Andreas

PS:conda version : 4.3.17

**Comment by bgruening** [comment]
I think the problem is that you get bzip2 from the default channel and not from conda-forge, can you please check that conda-forge has a higher priority in your channel list than defaults.

**Comment by andreas-wilm** [comment]
Correct! Sorry. Thank you!

**Comment by fdorri** [comment]
I am having the same issue while the channels priority seems ok.
```
$ conda list
# packages in environment at ... :
#
bcftools                  1.5                           3    bioconda
bzip2                     1.0.6                         3
curl                      7.54.1                        0
htslib                    1.5                           0    bioconda
krb5                      1.13.2                        0
libgcc                    5.2.0                         0
libssh2                   1.8.0                         0
mkl                       11.3.3                        0
numpy                     1.8.1                    py27_0
openssl                   1.0.2l                        0
pip                       9.0.1                    py27_1
pysam                     0.11.2.2            htslib1.5_2    bioconda
python                    2.7.13                        0
readline                  6.2                           2
samtools                  1.5                           0    bioconda
scipy                     0.14.0               np18py27_0
setuptools                27.2.0                   py27_0
sqlite                    3.13.0                        0
tk                        8.5.18                        0
wheel                     0.29.0                   py27_0
xz                        5.2.2                         1
zlib                      1.2.8                         3
```
and 
```
$ cat  ~/.condarc
channels:
  - conda-forge
  - defaults
```


```
 $python2.7
....
>>> import pysam
Traceback (most recent call last):
 .../lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory
```
Any ideas why this is happening?

Thanks,
Fatemeh

**Comment by bgruening** [comment]
Hi! This is how it looks for me:
```
 % conda create -n pysam-bzlinkerr pysam
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /anaconda/envs/pysam-bzlinkerr:

The following NEW packages will be INSTALLED:

    bcftools:        1.5-3                bioconda   
    bzip2:           1.0.6-1              conda-forge
    ca-certificates: 2017.7.27.1-0        conda-forge
    certifi:         2017.7.27.1-py27_0   conda-forge
    curl:            7.54.1-0             conda-forge
    htslib:          1.5-0                bioconda   
    krb5:            1.14.2-0             conda-forge
    libgcc:          5.2.0-0                         
    libssh2:         1.8.0-1              conda-forge
    ncurses:         5.9-10               conda-forge
    openssl:         1.0.2l-0             conda-forge
    pip:             9.0.1-py27_0         conda-forge
    pysam:           0.11.2.2-htslib1.5_2 bioconda   
    python:          2.7.13-1             conda-forge
    readline:        6.2-0                conda-forge
    samtools:        1.5-0                bioconda   
    setuptools:      36.2.2-py27_0        conda-forge
    sqlite:          3.13.0-1             conda-forge
    tk:              8.5.19-2             conda-forge
    wheel:           0.29.0-py27_0        conda-forge
    xz:              5.2.2-0              conda-forge
    zlib:            1.2.11-0             conda-forge

Proceed ([y]/n)? y

zlib-1.2.11-0. 100% |#################################################################################################################################################| Time: 0:00:00 243.09 kB/s
python-2.7.13- 100% |#################################################################################################################################################| Time: 0:00:22 651.48 kB/s
bcftools-1.5-3 100% |#################################################################################################################################################| Time: 0:00:03 711.63 kB/s
certifi-2017.7 100% |#################################################################################################################################################| Time: 0:00:00 582.94 kB/s
htslib-1.5-0.t 100% |#################################################################################################################################################| Time: 0:00:01 696.98 kB/s
samtools-1.5-0 100% |#################################################################################################################################################| Time: 0:00:01 600.82 kB/s
pysam-0.11.2.2 100% |#################################################################################################################################################| Time: 0:00:10 621.01 kB/s
setuptools-36. 100% |#################################################################################################################################################| Time: 0:00:01 443.51 kB/s
wheel-0.29.0-p 100% |#################################################################################################################################################| Time: 0:00:00 335.01 kB/s
pip-9.0.1-py27 100% |#################################################################################################################################################| Time: 0:00:03 452.37 kB/s
#
# To activate this environment, use:
# > source activate pysam-bzlinkerr
#
# To deactivate an active environment, use:
# > source deactivate
#

bag@bag ~/projects/code/docker/docker-jupyter-notebook
 % source activate pysam-bzlinkerr

bag@bag ~/projects/code/docker/docker-jupyter-notebook
 % python
Python 2.7.13 | packaged by conda-forge | (default, May  2 2017, 12:48:11) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
>>> 
bag@bag ~/projects/code/docker/docker-jupyter-notebook
 % conda list
# packages in environment at /anaconda/envs/pysam-bzlinkerr:
#
bcftools                  1.5                           3    bioconda
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2017.7.27.1                   0    conda-forge
certifi                   2017.7.27.1              py27_0    conda-forge
curl                      7.54.1                        0    conda-forge
htslib                    1.5                           0    bioconda
krb5                      1.14.2                        0    conda-forge
libgcc                    5.2.0                         0  
libssh2                   1.8.0                         1    conda-forge
ncurses                   5.9                          10    conda-forge
openssl                   1.0.2l                        0    conda-forge
pip                       9.0.1                    py27_0    conda-forge
pysam                     0.11.2.2            htslib1.5_2    bioconda
python                    2.7.13                        1    conda-forge
readline                  6.2                           0    conda-forge
samtools                  1.5                           0    bioconda
setuptools                36.2.2                   py27_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.19                        2    conda-forge
wheel                     0.29.0                   py27_0    conda-forge
xz                        5.2.2                         0    conda-forge
zlib                      1.2.11                        0    conda-forge

```

You don't have bioconda in your condarc at all and your channel order (from the listing of your envs) really looks not correct :(

**Comment by fdorri** [comment]
Hi!

Thanks for your comment. I tried your commands and I got the following error. Maybe related to the Centos version?

>>> import pysam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "..../bin/miniconda2/envs/pysam-bzlinkerr_2/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by ../bin/miniconda2/envs/pysam-bzlinkerr_2/lib/libhts.so.2)

**Comment by Scelta** [comment]
I've got the same issue and solved it according to andreas-wilm's comment:
```
conda config --add channels conda-forge
conda install -c conda-forge bzip2
```
Make sure to re-install bzip2 after lifting the channel priority and get following list:
```
conda list |grep bzip2
bzip2                     1.0.6                         1    conda-forge
```
