### ISSUE TITLE
Conda environment problems with simulate-travis.py

### ISSUE THREAD

**Issue by brainstorm** [bioconda/bioconda-recipes#5315]
This issue is related to https://github.com/bioconda/bioconda-recipes/issues/3275, but it couldn't solve it. For context, [I'm trying to update ansible with and including shade, an OpenStack library](https://github.com/brainstorm/bioconda-recipes/commits/ansible_openstack).

I installed Miniconda3 as `root` environment, created an environment that has python 2.7.13 in it but `conda.fetch` cannot be found:

```
(py2)$ ./simulate-travis.py
Traceback (most recent call last):
  File "./simulate-travis.py", line 11, in <module>
    import conda.fetch
ImportError: No module named conda.fetch
```

Then in the root environment, other errors pop up:

```
(root)$ ./simulate-travis.py
+ bioconda-utils lint recipes config.yml --git-range master HEAD
17:09:27 BIOCONDA INFO Recipes newly unblacklisted:

17:09:27 BIOCONDA INFO Recipes to consider according to git:
recipes/ansible
 recipes/jsonpatch
 recipes/jsonpatch
 recipes/os-client-config
 recipes/os-client-config
 recipes/shade
 recipes/shade
17:09:28 BIOCONDA INFO Recipes to lint:
recipes/ansible
 recipes/jsonpatch
 recipes/os-client-config
 recipes/shade
+ set +x
+ bioconda-utils build recipes config.yml --loglevel=info --git-range master HEAD
17:09:31 BIOCONDA INFO Recipes newly unblacklisted:

17:09:31 BIOCONDA INFO Recipes modified according to git: shade os-client-config jsonpatch ansible
17:09:31 BIOCONDA INFO blacklist: blast/2.2.21, cap-mirseq, denovogear, detonate, mgkit, mothur/1.36.1, perl-font-afm, r-histonehmm
17:09:31 BIOCONDA INFO Filtering recipes

deprecation warning: this function has been renamed to get_output_file_paths, to reflect that potentially multiple paths are returned.  This function will be removed in the conda-build 4.0 release.
Filtering 1 of 4 (25.0%) recipes/ansible
Traceback (most recent call last):
  File "/Users/romanvg/.miniconda/bin/bioconda-utils", line 11, in <module>
    load_entry_point('bioconda-utils==0.10.0', 'console_scripts', 'bioconda-utils')()
  File "/Users/romanvg/.miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 470, in main
    argh.dispatch_commands([build, dag, dependent, lint, duplicates])
  File "/Users/romanvg/.miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/Users/romanvg/.miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/Users/romanvg/.miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/Users/romanvg/.miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/Users/romanvg/.miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 404, in build
    mulled_upload_target=mulled_upload_target,
  File "/Users/romanvg/.miniconda/lib/python3.6/site-packages/bioconda_utils/build.py", line 266, in build_recipes
    recipes, env_matrix, check_channels, force=force)
  File "/Users/romanvg/.miniconda/lib/python3.6/site-packages/bioconda_utils/utils.py", line 723, in filter_recipes
    if tobuild(recipe, env):
  File "/Users/romanvg/.miniconda/lib/python3.6/site-packages/bioconda_utils/utils.py", line 654, in tobuild
    pkg = os.path.basename(built_package_path(recipe, env))
  File "/Users/romanvg/.miniconda/lib/python3.6/posixpath.py", line 144, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not list
```

How should I proceed to fix this once and for all?

**Comment by daler** [comment]
@brainstorm see https://bioconda.github.io/contribute-a-recipe.html#update-repo-and-requirements:

```
./simulate-travis.py --set-channel-order
./simulate-travis.py --install-requirements
```
bioconda-utils needs py3 and other dependencies; it will take care of building of packages that only run in py2.

**Comment by brainstorm** [comment]
Thanks @daler, but that is not cutting it for me either :_/

```
(py2) romanvgs-MacBook-Air:bioconda-recipes romanvg$ ./simulate-travis.py --set-channel-order
Traceback (most recent call last):
  File "./simulate-travis.py", line 11, in <module>
    import conda.fetch
ImportError: No module named conda.fetch
```
