### ISSUE TITLE
docker build crashes with "flag provided but not defined: --network"

### ISSUE THREAD

**Issue by HenningTimm** [bioconda/bioconda-recipes#5387]
When building a recipe, docker build crashes, since it does not know the `--network` parameter (See [here](https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/docker_utils.py#L404)) which has been added to solve #5027.

```

timm@neuromancer ~/repos/bioconda-recipes $ python simulate-travis.py --package ddrage --force
Using config file /home/timm/.config/bioconda/conf.yml, which has the following contents:
{'CONDARC': '/tmp/miniconda/condarc', 'CONDA_ROOT': '/tmp/miniconda'}
+ bioconda-utils lint recipes config.yml --git-range master HEAD
17:57:51 BIOCONDA WARNING git version (1.9.1) is < 2.0. Running git diff using shell=True. Please consider upgrading git
17:57:51 BIOCONDA INFO Recipes newly unblacklisted:

17:57:51 BIOCONDA INFO No recipe modified according to git, exiting.
+ set +x
+ bioconda-utils build recipes config.yml --docker --mulled-test --loglevel=info --package ddrage --force --git-range master HEAD
17:57:54 BIOCONDA INFO DOCKER: Pulling docker image condaforge/linux-anvil
17:57:56 BIOCONDA INFO DOCKER: Done pulling image
17:57:56 BIOCONDA INFO DOCKER: Building image "tmp-bioconda-builder" from /tmp/tmpcy6_orok
.17:57:56 BIOCONDA ERROR COMMAND FAILED: docker build --network host -t tmp-bioconda-builder /tmp/tmpcy6_orok
17:57:56 BIOCONDA ERROR STDOUT+STDERR:
flag provided but not defined: --network
See 'docker build --help'.


17:58:56 BIOCONDA ERROR DOCKER FAILED: Error building docker container tmp-bioconda-builder. 
Traceback (most recent call last):
  File "/tmp/miniconda/bin/bioconda-utils", line 11, in <module>
    load_entry_point('bioconda-utils==0.10.0', 'console_scripts', 'bioconda-utils')()
  File "/tmp/miniconda/lib/python3.5/site-packages/bioconda_utils/cli.py", line 475, in main
    argh.dispatch_commands([build, dag, dependent, lint, duplicates])
  File "/tmp/miniconda/lib/python3.5/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/tmp/miniconda/lib/python3.5/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/tmp/miniconda/lib/python3.5/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/tmp/miniconda/lib/python3.5/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/tmp/miniconda/lib/python3.5/site-packages/bioconda_utils/cli.py", line 395, in build
    keep_image=keep_image,
  File "/tmp/miniconda/lib/python3.5/site-packages/bioconda_utils/docker_utils.py", line 361, in __init__
    self._build_image()
  File "/tmp/miniconda/lib/python3.5/site-packages/bioconda_utils/docker_utils.py", line 415, in _build_image
    raise e
  File "/tmp/miniconda/lib/python3.5/site-packages/bioconda_utils/docker_utils.py", line 410, in _build_image
    p = utils.run(cmd)
  File "/tmp/miniconda/lib/python3.5/site-packages/bioconda_utils/utils.py", line 191, in run
    raise e
  File "/tmp/miniconda/lib/python3.5/site-packages/bioconda_utils/utils.py", line 185, in run
    **kwargs)
  File "/tmp/miniconda/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker', 'build', '--network', 'host', '-t', 'tmp-bioconda-builder', '/tmp/tmpcy6_orok']' returned non-zero exit status 2
17:58:56 BIOCONDA ERROR COMMAND FAILED: docker rmi tmp-bioconda-builder
17:58:56 BIOCONDA ERROR STDOUT+STDERR:
Error response from daemon: No such image: tmp-bioconda-builder
time="2017-07-31T17:58:56+02:00" level=fatal msg="Error: failed to remove one or more images" 

Exception ignored in: <bound method RecipeBuilder.__del__ of <bioconda_utils.docker_utils.RecipeBuilder object at 0x7f98424be978>>
Traceback (most recent call last):
  File "/tmp/miniconda/lib/python3.5/site-packages/bioconda_utils/docker_utils.py", line 365, in __del__
    self.cleanup()
  File "/tmp/miniconda/lib/python3.5/site-packages/bioconda_utils/docker_utils.py", line 488, in cleanup
    utils.run(cmd)
  File "/tmp/miniconda/lib/python3.5/site-packages/bioconda_utils/utils.py", line 191, in run
    raise e
  File "/tmp/miniconda/lib/python3.5/site-packages/bioconda_utils/utils.py", line 185, in run
    **kwargs)
  File "/tmp/miniconda/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker', 'rmi', 'tmp-bioconda-builder']' returned non-zero exit status 1
```

I am using docker version 1.6.2 build 7c8fca2.
When showing the help message for docker build, the network flag is not listed for me:

```
timm@neuromancer ~/repos/bioconda-recipes $ docker build --help
Usage: docker build [OPTIONS] PATH | URL | -

Build a new image from the source code at PATH

  -c, --cpu-shares=0    CPU shares (relative weight)
  --cpuset-cpus=        CPUs in which to allow execution (0-3, 0,1)
  -f, --file=           Name of the Dockerfile (Default is 'PATH/Dockerfile')
  --force-rm=false      Always remove intermediate containers
  --help=false          Print usage
  -m, --memory=         Memory limit
  --memory-swap=        Total memory (memory + swap), '-1' to disable swap
  --no-cache=false      Do not use cache when building the image
  --pull=false          Always attempt to pull a newer version of the image
  -q, --quiet=false     Suppress the verbose output generated by the containers
  --rm=true             Remove intermediate containers after a successful build
  -t, --tag=            Repository name (and optionally a tag) for the image
```

Can this be a problem with my docker version? I find no other mentions of this problem. Am I doing something completely wrong here?

**Comment by daler** [comment]
@HenningTimm looks like a docker version issue: `--network` was added to docker in version 1.13 ([release notes](https://docs.docker.com/release-notes/docker-engine/)). Are you able to upgrade docker? We could do a version check before adding the `--network` argument, which, as far as I know, is used in proxy situations. If you needed to use a proxy, you would have to upgrade docker.

**Comment by HenningTimm** [comment]
@daler I used the docker version from the ubuntu 14.04 package sources, so there might be other people with this problem. On 16.04 this could also be a problem, since right now only version 1.12.0 is available.
If this it a lot of work, I can just install from another source; the ubuntu version is quite old anyway. But maybe not everyone has this option.

I am not too familiar with the inner workings of bioconda-utils and docker, but would this be enough to fix the problem?
```python
import subprocess as sp
import re

# Check if the installed version of docker supports the --network flag (requires version >= 1.13.0)
# Parse output of `docker --version` since the format of
#  `docker version` is not consistent between different docker versions
s = sp.check_output(["docker", "--version"])
p = re.compile("\d+\.\d+\.\d+")  # three groups of at least on digit separated by dots
version_string = re.search(p, s).group(0)
if tuple(int(i) for i in version_string.split(".")) >= (1,13,0):
    cmd = [
            'docker', 'build',

            # xref #5027
            '--network', 'host',
            '-t', self.tag,
            build_dir
    ]
else:
    # Network flag was added in 1.13.0, do not add it for lower versions. xref #5387
    cmd = [
            'docker', 'build',

            '-t', self.tag,
            build_dir
    ]
```

**Comment by daler** [comment]
@HenningTimm thanks, that helps a lot. Tracking down the different version strings across different docker versions and being able to reliably detect is the annoying part. I'm not sure there's a good way to write a test for this, other than temporarily installing a different version of docker. But if it works locally for you on an earlier version then that should be good enough for now.

A PR would be great. Also, not sure but it may be more straightforward to use `distutils.version.LooseVersion`.
