### ISSUE TITLE
Updating BEDOPS recipe for new version fails tests

### ISSUE THREAD

**Issue by alexpreynolds** [bioconda/bioconda-recipes#5503]
I attempted to update the version number of a recipe for BEDOPS (along with the sha256 signature and URL), and the recipe does not seem to pass tests:

```
$ bash -c 'echo $BASH_VERSION'
3.2.57(1)-release
install
432.72s$ scripts/travis-setup.sh
+[[ bedops-v2p4p27 != \m\a\s\t\e\r ]]
+[[ bedops-v2p4p27 != \b\u\l\k ]]
+[[ false == \f\a\l\s\e ]]
+[[ alexpreynolds/bioconda-recipes == \b\i\o\c\o\n\d\a\/\b\i\o\c\o\n\d\a\-\r\e\c\i\p\e\s ]]
+for dir in . recipes
+'[' -e ./meta.yaml ']'
+for dir in . recipes
+'[' -e recipes/meta.yaml ']'
+++dirname scripts/travis-setup.sh
++cd scripts
++pwd
+SCRIPT_DIR=/Users/travis/build/alexpreynolds/bioconda-recipes/scripts
+pip install pyyaml
Collecting pyyaml
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 2.8MB/s 
Building wheels for collected packages: pyyaml
  Running setup.py bdist_wheel for pyyaml ... done
  Stored in directory: /Users/travis/Library/Caches/pip/wheels/2c/f7/79/13f3a12cd723892437c0cfbde1230ab4d82947ff7b3839a4fc
Successfully built pyyaml
Installing collected packages: pyyaml
Successfully installed pyyaml-3.12
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
+sudo mkdir /anaconda
+sudo chown -R travis /anaconda
+/Users/travis/build/alexpreynolds/bioconda-recipes/scripts/../simulate-travis.py --bootstrap /anaconda --overwrite
PREFIX=/anaconda
installing: python-3.5.2-0 ...
installing: conda-env-2.6.0-0 ...
installing: openssl-1.0.2j-0 ...
installing: pycosat-0.6.1-py35_1 ...
installing: readline-6.2-2 ...
installing: requests-2.11.1-py35_0 ...
installing: ruamel_yaml-0.11.14-py35_0 ...
installing: sqlite-3.13.0-0 ...
installing: tk-8.5.18-0 ...
installing: xz-5.2.2-0 ...
installing: yaml-0.1.6-0 ...
installing: zlib-1.2.8-3 ...
installing: conda-4.2.12-py35_0 ...
installing: pycrypto-2.6.1-py35_4 ...
installing: pip-8.1.2-py35_0 ...
installing: wheel-0.29.0-py35_0 ...
installing: setuptools-27.2.0-py35_0 ...
Python 3.5.2 :: Continuum Analytics, Inc.
creating default environment...
using -f (force) option
installation finished.
Using config file /Users/travis/.config/bioconda/conf.yml, which has the following contents:
{'CONDA_ROOT': '/anaconda', 'CONDARC': '/anaconda/condarc'}
          Warnings like "'conda-forge' already in 'channels' list, moving to the top"
          are expected if channels have been added before, and can be safely ignored.
          
Warning: 'defaults' already in 'channels' list, moving to the top
conda config is now:
--add channels 'defaults'   # lowest priority
--add channels 'conda-forge'
--add channels 'bioconda'   # highest priority
Using config file /Users/travis/.config/bioconda/conf.yml, which has the following contents:
{'CONDA_ROOT': '/anaconda', 'CONDARC': '/anaconda/condarc'}
Fetching package metadata ...........
Solving package specifications: ..........
Package plan for installation in environment /anaconda:
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    involucro-1.1.2            |                0         2.2 MB  bioconda
    libffi-3.2.1               |                1          41 KB  bioconda
    mkl-2017.0.3               |                0       110.3 MB
    python-3.5.2               |                5        11.8 MB  conda-forge
    alabaster-0.7.10           |           py35_0          13 KB  conda-forge
    argh-0.26.2                |           py35_1          33 KB  conda-forge
    asn1crypto-0.22.0          |           py35_0         149 KB  conda-forge
    beautifulsoup4-4.4.1       |           py35_0         121 KB
    chardet-3.0.2              |           py35_1         187 KB  conda-forge
    colorlog-2.10.0            |           py35_0          18 KB  conda-forge
    decorator-4.1.2            |           py35_0         459 KB  conda-forge
    docutils-0.12              |           py35_0         666 KB  conda-forge
    filelock-2.0.6             |           py35_0           8 KB  conda-forge
    idna-2.5                   |           py35_0         121 KB  conda-forge
    imagesize-0.7.1            |           py35_0         181 KB  conda-forge
    jsonschema-2.5.1           |           py35_0          58 KB  conda-forge
    markupsafe-1.0             |           py35_0          22 KB  conda-forge
    numpy-1.12.1               |           py35_0         3.5 MB
    pkginfo-1.4.1              |           py35_0          38 KB  conda-forge
    pycparser-2.18             |           py35_0         169 KB  conda-forge
    pygithub-1.29              |           py35_0         2.0 MB  conda-forge
    pyparsing-2.2.0            |           py35_0          95 KB  conda-forge
    pytz-2017.2                |           py35_0         188 KB  conda-forge
    pyyaml-3.12                |           py35_1         157 KB  conda-forge
    requests-2.12.4            |           py35_0         988 KB  conda-forge
    six-1.10.0                 |           py35_1         219 KB  conda-forge
    snowballstemmer-1.2.1      |           py35_0          79 KB  conda-forge
    sphinx_rtd_theme-0.1.9     |           py35_0         645 KB  conda-forge
    whoosh-2.7.4               |           py35_0         668 KB  conda-forge
    babel-2.3.4                |           py35_0         4.8 MB  conda-forge
    cffi-1.10.0                |           py35_0         202 KB  conda-forge
    clyent-1.2.1               |           py35_0          14 KB  conda-forge
    conda-verify-2.0.0         |           py35_0          19 KB  conda-forge
    galaxy-lib-17.5.9          |           py35_1         359 KB  bioconda
    jinja2-2.9.6               |           py35_0         385 KB
    networkx-1.11              |           py35_0         1.7 MB  conda-forge
    pyaml-15.8.2               |           py35_0          22 KB  conda-forge
    pydotplus-2.0.2            |           py35_0          39 KB  conda-forge
    pygments-2.2.0             |           py35_0         1.3 MB  conda-forge
    python-dateutil-2.3        |           py35_0         214 KB  bioconda
    anaconda-client-1.6.3      |           py35_0         130 KB  conda-forge
    cryptography-1.9           |           py35_0         476 KB  conda-forge
    pandas-0.19.2              |      np112py35_1         8.7 MB  conda-forge
    sphinx-1.5.6               |           py35_0         1.5 MB  conda-forge
    pyopenssl-16.2.0           |           py35_0          72 KB  conda-forge
    conda-4.3.21               |           py35_1         511 KB  conda-forge
    conda-build-2.1.16         |           py35_0         281 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       155.6 MB
The following NEW packages will be INSTALLED:
    alabaster:        0.7.10-py35_0      conda-forge
    anaconda-client:  1.6.3-py35_0       conda-forge
    argh:             0.26.2-py35_1      conda-forge
    asn1crypto:       0.22.0-py35_0      conda-forge
    babel:            2.3.4-py35_0       conda-forge
    beautifulsoup4:   4.4.1-py35_0                  
    cffi:             1.10.0-py35_0      conda-forge
    chardet:          3.0.2-py35_1       conda-forge
    clyent:           1.2.1-py35_0       conda-forge
    colorlog:         2.10.0-py35_0      conda-forge
    conda-build:      2.1.16-py35_0      conda-forge
    conda-verify:     2.0.0-py35_0       conda-forge
    cryptography:     1.9-py35_0         conda-forge
    decorator:        4.1.2-py35_0       conda-forge
    docutils:         0.12-py35_0        conda-forge
    filelock:         2.0.6-py35_0       conda-forge
    galaxy-lib:       17.5.9-py35_1      bioconda   
    idna:             2.5-py35_0         conda-forge
    imagesize:        0.7.1-py35_0       conda-forge
    involucro:        1.1.2-0            bioconda   
    jinja2:           2.9.6-py35_0                  
    jsonschema:       2.5.1-py35_0       conda-forge
    libffi:           3.2.1-1            bioconda   
    markupsafe:       1.0-py35_0         conda-forge
    mkl:              2017.0.3-0                    
    networkx:         1.11-py35_0        conda-forge
    numpy:            1.12.1-py35_0                 
    pandas:           0.19.2-np112py35_1 conda-forge
    pkginfo:          1.4.1-py35_0       conda-forge
    pyaml:            15.8.2-py35_0      conda-forge
    pycparser:        2.18-py35_0        conda-forge
    pydotplus:        2.0.2-py35_0       conda-forge
    pygithub:         1.29-py35_0        conda-forge
    pygments:         2.2.0-py35_0       conda-forge
    pyopenssl:        16.2.0-py35_0      conda-forge
    pyparsing:        2.2.0-py35_0       conda-forge
    python-dateutil:  2.3-py35_0         bioconda   
    pytz:             2017.2-py35_0      conda-forge
    pyyaml:           3.12-py35_1        conda-forge
    six:              1.10.0-py35_1      conda-forge
    snowballstemmer:  1.2.1-py35_0       conda-forge
    sphinx:           1.5.6-py35_0       conda-forge
    sphinx_rtd_theme: 0.1.9-py35_0       conda-forge
    whoosh:           2.7.4-py35_0       conda-forge
The following packages will be UPDATED:
    conda:            4.2.12-py35_0                  --> 4.3.21-py35_1 conda-forge
    python:           3.5.2-0                        --> 3.5.2-5       conda-forge
    requests:         2.11.1-py35_0                  --> 2.12.4-py35_0 conda-forge
Fetching packages ...
involucro-1.1. 100% || Time: 0:00:00   5.10 MB/s
libffi-3.2.1-1 100% || Time: 0:00:00   1.23 MB/s
mkl-2017.0.3-0 100% || Time: 0:00:45   2.56 MB/s
python-3.5.2-5 100% || Time: 0:00:07   1.76 MB/s
alabaster-0.7. 100% || Time: 0:00:00 493.65 kB/s
argh-0.26.2-py 100% || Time: 0:00:00 692.23 kB/s
asn1crypto-0.2 100% || Time: 0:00:00 935.75 kB/s
beautifulsoup4 100% || Time: 0:00:00   9.12 MB/s
chardet-3.0.2- 100% || Time: 0:00:00   1.33 MB/s
colorlog-2.10. 100% || Time: 0:00:00   1.12 MB/s
decorator-4.1. 100% || Time: 0:00:00   2.85 MB/s
docutils-0.12- 100% || Time: 0:00:00   2.28 MB/s
filelock-2.0.6 100% || Time: 0:00:00   4.44 MB/s
idna-2.5-py35_ 100% || Time: 0:00:00   1.49 MB/s
imagesize-0.7. 100% || Time: 0:00:00   2.37 MB/s
jsonschema-2.5 100% || Time: 0:00:00   1.11 MB/s
markupsafe-1.0 100% || Time: 0:00:00   1.38 MB/s
numpy-1.12.1-p 100% || Time: 0:00:00   6.62 MB/s
pkginfo-1.4.1- 100% || Time: 0:00:00   1.12 MB/s
pycparser-2.18 100% || Time: 0:00:00   1.82 MB/s
pygithub-1.29- 100% || Time: 0:00:02 766.44 kB/s
pyparsing-2.2. 100% || Time: 0:00:00 234.05 kB/s
pytz-2017.2-py 100% || Time: 0:00:00   2.45 MB/s
pyyaml-3.12-py 100% || Time: 0:00:00   2.52 MB/s
requests-2.12. 100% || Time: 0:00:00   2.73 MB/s
six-1.10.0-py3 100% || Time: 0:00:00   2.29 MB/s
snowballstemme 100% || Time: 0:00:00   1.61 MB/s
sphinx_rtd_the 100% || Time: 0:00:00   4.46 MB/s
whoosh-2.7.4-p 100% || Time: 0:00:00   1.91 MB/s
babel-2.3.4-py 100% || Time: 0:00:02   2.03 MB/s
cffi-1.10.0-py 100% || Time: 0:00:00   2.11 MB/s
clyent-1.2.1-p 100% || Time: 0:00:00 991.50 kB/s
conda-verify-2 100% || Time: 0:00:00   1.24 MB/s
galaxy-lib-17. 100% || Time: 0:00:00   3.75 MB/s
jinja2-2.9.6-p 100% || Time: 0:00:00   7.04 MB/s
networkx-1.11- 100% || Time: 0:00:00   8.10 MB/s
pyaml-15.8.2-p 100% || Time: 0:00:00 971.82 kB/s
pydotplus-2.0. 100% || Time: 0:00:00 756.97 kB/s
pygments-2.2.0 100% || Time: 0:00:00   1.43 MB/s
python-dateuti 100% || Time: 0:00:00 816.61 kB/s
anaconda-clien 100% || Time: 0:00:00   1.26 MB/s
cryptography-1 100% || Time: 0:00:00   2.33 MB/s
pandas-0.19.2- 100% || Time: 0:00:07   1.17 MB/s
sphinx-1.5.6-p 100% || Time: 0:00:00   1.69 MB/s
pyopenssl-16.2 100% || Time: 0:00:00   1.58 MB/s
conda-4.3.21-p 100% || Time: 0:00:00   2.57 MB/s
conda-build-2. 100% || Time: 0:00:00   2.64 MB/s
Extracting packages ...
[      COMPLETE      ]|| 100%
Unlinking packages ...
[      COMPLETE      ]|| 100%
Linking packages ...
[      COMPLETE      ]|| 100%
Collecting git+https://github.com/bioconda/bioconda-utils.git@master
  Cloning https://github.com/bioconda/bioconda-utils.git (to master) to /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-fafmrvjg-build
Installing collected packages: bioconda-utils
  Running setup.py install for bioconda-utils ... done
Successfully installed bioconda-utils-0.10.0
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
        An alternative conda installation is now in /anaconda, channels have been
        set, and requirements for bioconda-utils have been installed there.
        A config file at ~/.config/bioconda/conf.yml has been created to
        store this information, so you can now run `./simulate-travis.py` with
        no additional arguments to use this new conda installation.
        
+/anaconda/bin/conda index /anaconda/conda-bld/linux-64 /anaconda/conda-bld/osx-64
updating index in: /anaconda/conda-bld/linux-64
updating index in: /anaconda/conda-bld/osx-64
+/anaconda/bin/conda config --add channels file://anaconda/conda-bld
10.73s$ scripts/travis-run.sh
+bioconda-utils lint recipes config.yml --git-range 'fb4d4bdcf266^' 583829b3d94f
22:02:39 BIOCONDA ERROR COMMAND FAILED: git diff --relative=recipes --name-only fb4d4bdcf266^...583829b3d94f -- recipes/* recipes/*/*
22:02:39 BIOCONDA ERROR STDOUT+STDERR:
fatal: bad revision 'fb4d4bdcf266^...583829b3d94f'
Traceback (most recent call last):
  File "/anaconda/bin/bioconda-utils", line 11, in <module>
    load_entry_point('bioconda-utils==0.10.0', 'console_scripts', 'bioconda-utils')()
  File "/anaconda/lib/python3.5/site-packages/bioconda_utils/cli.py", line 475, in main
    argh.dispatch_commands([build, dag, dependent, lint, duplicates])
  File "/anaconda/lib/python3.5/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/anaconda/lib/python3.5/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/anaconda/lib/python3.5/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/anaconda/lib/python3.5/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/anaconda/lib/python3.5/site-packages/bioconda_utils/cli.py", line 253, in lint
    _recipes = select_recipes(packages, git_range, recipe_folder, config_filename, config, force)
  File "/anaconda/lib/python3.5/site-packages/bioconda_utils/cli.py", line 51, in select_recipes
    modified = utils.modified_recipes(git_range, recipe_folder, config_filename)
  File "/anaconda/lib/python3.5/site-packages/bioconda_utils/utils.py", line 886, in modified_recipes
    p = run(cmds, shell=shell)
  File "/anaconda/lib/python3.5/site-packages/bioconda_utils/utils.py", line 200, in run
    raise e
  File "/anaconda/lib/python3.5/site-packages/bioconda_utils/utils.py", line 194, in run
    **kwargs)
  File "/anaconda/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'diff', '--relative=recipes', '--name-only', 'fb4d4bdcf266^...583829b3d94f', '--', 'recipes/*', 'recipes/*/*']' returned non-zero exit status 128
```

Has the YAML format changed recently, such that other fields or data are now required?

**Comment by daler** [comment]
@alexpreynolds the error you report here appears to be complaining about git revisions missing. Looking more carefully it seems to be a log from travis from your fork of the repo? Is the branch up-to-date with bioconda master?

But more usefully, in #5502, the error appears to be `clang: error: invalid arch name '-arch 64'`, shown here: https://travis-ci.org/bioconda/bioconda-recipes/jobs/263667915#L2055. I'm afraid I can't help much beyond that though in actually fixing the issue.

**Comment by alexpreynolds** [comment]
Thanks. It looks like the `ARCH` variable gets clobbered somewhere. I applied a hotfix to the Darwin-specific Makefile to make it harder to overwrite. We'll see how it goes.

**Comment by alexpreynolds** [comment]
Okay, looks good. Not sure if `ARCH` gets set somewhere outside of this, but I'll close up this ticket.

**Comment by daler** [comment]
@alexpreynolds yep, it's conda that's doing it: https://conda.io/docs/building/environment-vars.html#environment-variables-set-during-the-build-process

**Comment by alexpreynolds** [comment]
Ah, yeah, that would definitely break things on our end. Up until the last release we've been offering 32- and 64-bit binaries, so that was an important variable for us to set properly.
