### ISSUE TITLE
gatk -T AnalyzeCovariates dies due to missing R dependency

### ISSUE THREAD

**Issue by wkretzsch** [bioconda/bioconda-recipes#5537]
When I run
```
gatk -T AnalyzeCovariates -R reference.fa -before recal_data.table -after post_recal_data.table -plots recal_data.table.pdf -l debug
```
I get the following output:

> ...
> INFO  10:58:49,370 AnalyzeCovariates - Generating plots file 
'recal_data.table.pdf'
> DEBUG 10:58:49,379 RecalUtils - R command line: Rscript (resource)org/broadinstitute/gatk/engine/recalibration/BQSR.R /tmp/AnalyzeCovariates9055981041056846110.csv recal_data.table.pdf
> DEBUG 10:58:49,397 RScriptExecutor - Executing:
> DEBUG 10:58:49,397 RScriptExecutor -   Rscript
> DEBUG 10:58:49,397 RScriptExecutor -   -e
> DEBUG 10:58:49,397 RScriptExecutor -   tempLibDir = '/tmp/Rlib.5991889272801718946';source('/tmp/BQSR.5123964779217121787.R');
> DEBUG 10:58:49,397 RScriptExecutor -   /tmp/AnalyzeCovariates9055981041056846110.csv
> DEBUG 10:58:49,397 RScriptExecutor -   recal_data.table
> DEBUG 10:58:49,397 RScriptExecutor -   recal_data.table.pdf
> Error in library(gplots) : there is no package called ‘gplots’
> Calls: source -> withVisible -> eval -> eval -> library
> Execution halted
> DEBUG 10:58:51,039 RScriptExecutor - Result: 1
> ##### ERROR --
> ##### ERROR stack trace
> org.broadinstitute.gatk.utils.R.RScriptExecutorException: RScript exited with 1
>         at org.broadinstitute.gatk.utils.R.RScriptExecutor.exec(RScriptExecutor.java:176)
>         at org.broadinstitute.gatk.engine.recalibration.RecalUtils.generatePlots(RecalUtils.java:555)
>         at org.broadinstitute.gatk.tools.walkers.bqsr.AnalyzeCovariates.generatePlots(AnalyzeCovariates.java:373)
>         at org.broadinstitute.gatk.tools.walkers.bqsr.AnalyzeCovariates.initialize(AnalyzeCovariates.java:387)
>         at org.broadinstitute.gatk.engine.executive.LinearMicroScheduler.execute(LinearMicroScheduler.java:83)
>         at org.broadinstitute.gatk.engine.GenomeAnalysisEngine.execute(GenomeAnalysisEngine.java:323)
>         at org.broadinstitute.gatk.engine.CommandLineExecutable.execute(CommandLineExecutable.java:123)
>         at org.broadinstitute.gatk.utils.commandline.CommandLineProgram.start(CommandLineProgram.java:256)
>         at org.broadinstitute.gatk.utils.commandline.CommandLineProgram.start(CommandLineProgram.java:158)
>         at org.broadinstitute.gatk.engine.CommandLineGATK.main(CommandLineGATK.java:108)
> ##### ERROR ------------------------------------------------------------------------------------------
> ##### ERROR A GATK RUNTIME ERROR has occurred (version 3.8-0-ge9d806836):
> ##### ERROR
> ##### ERROR This might be a bug. Please check the documentation guide to see if this is a known problem.
> ##### ERROR If not, please post the error message, with stack trace, to the GATK forum.
> ##### ERROR Visit our website and forum for extensive documentation and answers to
> ##### ERROR commonly asked questions https://software.broadinstitute.org/gatk
> ##### ERROR
> ##### ERROR MESSAGE: RScript exited with 1
> ##### ERROR ------------------------------------------------------------------------------------------
> 

It appears that `AnalyzeCovariates` depends on `R` and the `gplots` package.  However, I find no mention of R in the meta.yaml for gatk. 

Should R and the `gplots` R package be added as dependencies for the gatk recipe?

**Comment by wkretzsch** [comment]
According to the [GATK website](https://gatkforums.broadinstitute.org/gatk/discussion/2899/howto-install-all-software-packages-required-to-follow-the-gatk-best-practices) the required R dependencies are:
- gplots
- ggplot2
- gsalib
- reshape
