### ISSUE TITLE
Problem htseq-count on bioconda

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [bioconda/bioconda-recipes#6030]
I have successful instal using bioconda using htseq-count. I have this error.

```
(rna_test2) [riva@ilmn-qm ~]$ htseq-count -h
Traceback (most recent call last):
  File "/home/riva/miniconda2/envs/rna_test2/lib/python3.5/site-packages/HTSeq/StepVector.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/riva/miniconda2/envs/rna_test2/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 903, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: /home/riva/miniconda2/envs/rna_test2/lib/python3.5/site-packages/HTSeq/_StepVector.cpython-35m-x86_64-linux-gnu.so: ELF file OS ABI invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/riva/miniconda2/envs/rna_test2/bin/htseq-count", line 4, in <module>
    __import__('pkg_resources').run_script('HTSeq==0.7.2', 'htseq-count')
  File "/home/riva/miniconda2/envs/rna_test2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/riva/miniconda2/envs/rna_test2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1503, in run_script
    exec(code, namespace, namespace)
  File "/home/riva/miniconda2/envs/rna_test2/lib/python3.5/site-packages/HTSeq-0.7.2-py3.5-linux-x86_64.egg-info/scripts/htseq-count", line 3, in <module>
    import HTSeq.scripts.count
  File "/home/riva/miniconda2/envs/rna_test2/lib/python3.5/site-packages/HTSeq/__init__.py", line 11, in <module>
    from HTSeq._HTSeq import *
  File "python3/src/HTSeq/_HTSeq.pyx", line 17, in init HTSeq._HTSeq (src/_HTSeq.c:41010)
  File "/home/riva/miniconda2/envs/rna_test2/lib/python3.5/site-packages/HTSeq/StepVector.py", line 17, in <module>
    _StepVector = swig_import_helper()
  File "/home/riva/miniconda2/envs/rna_test2/lib/python3.5/site-packages/HTSeq/StepVector.py", line 16, in swig_import_helper
    return importlib.import_module('_StepVector')
  File "/home/riva/miniconda2/envs/rna_test2/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_StepVector'

```
My system is rhed hat 5.5

**Comment by bgruening** [comment]
BioConda only supports >= CentOS/RHEL 6.0 ... This could be a problem. Sorry.

**Comment by bgruening** [comment]
Let us know if we can help in any way.
