### ISSUE TITLE
bioconda deeptools error

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [bioconda/bioconda-recipes#6099]
I use minconda 2 and I have installe depptools. Ihave this error:
```
conda -V
conda 4.3.23

Traceback (most recent call last):
  File "/home/maurizio/miniconda2/envs/rna_test/bin/plotFingerprint", line 4, in <module>
    from deeptools.plotFingerprint import main
  File "/home/maurizio/miniconda2/envs/rna_test/lib/python3.5/site-packages/deeptools/plotFingerprint.py", line 15, in <module>
    import deeptools.countReadsPerBin as countR
  File "/home/maurizio/miniconda2/envs/rna_test/lib/python3.5/site-packages/deeptools/countReadsPerBin.py", line 9, in <module>
    import deeptools.utilities
  File "/home/maurizio/miniconda2/envs/rna_test/lib/python3.5/site-packages/deeptools/utilities.py", line 3, in <module>
    import pysam
  File "/home/maurizio/miniconda2/envs/rna_test/lib/python3.5/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
  File "pysam/libchtslib.pyx", line 1, in init pysam.libchtslib (pysam/libchtslib.c:7429)
ImportError: /home/maurizio/miniconda2/envs/rna_test/lib/python3.5/site-packages/pysam/libcutils.cpython-35m-x86_64-linux-gnu.so: undefined symbol: cram_container_get_landmarks
(rna_test)

what can I do?
```

**Comment by bgruening** [comment]
@bioinfo-dirty-jobs which command of deeptools are you running to produce this error?

**Comment by bgruening** [comment]
Please reopen this issue if you still encounter any problem and let us know how we can reproduce it. Thanks!
