### ISSUE TITLE
RepeatMasker - patch issues with build 

### ISSUE THREAD

**Issue by colindaven** [bioconda/bioconda-recipes#6450]
Dear all, 

I am having issues with the patch while trying to update RepeatMasker to 4.0.7

The program downloads fine but then the patch seems to fail with a download issue.

@pvanheus Maybe you had a similar problem?

```
bioconda-recipes$ ./simulate-travis.py --git-range HEAD --disable-docker
Using config file /home/rcug/.config/bioconda/conf.yml, which has the following contents:
{'CONDA_ROOT': '/mnt/ngsnfs/bioconda_dev/miniconda/', 'CONDARC': '/mnt/ngsnfs/bioconda_dev/miniconda/condarc'}
+ bioconda-utils lint recipes config.yml --git-range HEAD
09:54:28 BIOCONDA INFO Recipes newly unblacklisted:

09:54:28 BIOCONDA INFO Recipes to consider according to git: 
recipes/repeatmasker
09:54:29 BIOCONDA INFO Recipes to lint:
recipes/repeatmasker
+ set +x
+ bioconda-utils build recipes config.yml --loglevel=info --git-range HEAD
09:54:30 BIOCONDA INFO Recipes newly unblacklisted:

09:54:30 BIOCONDA INFO Recipes modified according to git: repeatmasker
09:54:30 BIOCONDA INFO blacklist: abyss, abyss/1.9.0, abyss/2.0.1-k128, blasr_libcpp, blast, blast/2.2.21, cap-mirseq, cgat-scripts-devel, clever-toolkit, denovogear, detonate, frc, kobas, lefse, metaprob, mgkit, mothur/1.36.1, multiqc, perl-font-afm, quast, r-histonehmm, r-pscbs/0.61.0, r-spp, rsem, transcomb, triform2
09:54:30 BIOCONDA INFO Filtering recipes

Filtering 1 of 1 (100.0%) recipes/repeatmasker
09:54:32 BIOCONDA INFO Building and testing 1 recipes in total
09:54:32 BIOCONDA INFO Recipes to build: 
repeatmasker
09:54:32 BIOCONDA INFO Building and testing subdag 1 of 1 (1 recipes)
09:54:32 BIOCONDA INFO BUILD START recipes/repeatmasker, env: CONDA_ALLOW_SOFTLINKS=false;CONDA_BOOST=1.64;CONDA_BZIP2=1.0;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.6;CONDA_NCURSES=5.9;CONDA_NPY=112;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.4.1;CONDA_ROOT=/mnt/ngsnfs/bioconda_dev/miniconda/;CONDA_ZLIB=1.2.8;LANG=en_US.UTF-8;LC_ADDRESS=de_DE.UTF-8;LC_ALL=en_US.UTF-8;LC_IDENTIFICATION=de_DE.UTF-8;LC_MEASUREMENT=de_DE.UTF-8;LC_MONETARY=de_DE.UTF-8;LC_NAME=de_DE.UTF-8;LC_NUMERIC=de_DE.UTF-8;LC_PAPER=de_DE.UTF-8;LC_TELEPHONE=de_DE.UTF-8;LC_TIME=de_DE.UTF-8;MACOSX_DEPLOYMENT_TARGET=10.9;PATH=/anaconda/bin:/mnt/ngsnfs/bioconda_dev/miniconda/bin:/home/rcug/bin:/home/rcug/.local/bin:/mnt/ngsnfs/tools/miniconda2/bin:/bin:/mnt/ngsnfs/tools/TRF:/mnt/ngsnfs/tools/REPET/REPET_linux-x64-2.2:/mnt/ngsnfs/tools/RepeatMasker/RepeatMasker:/mnt/ngsnfs/tools/RepeatModeler/RepeatScout/RepeatScout-1:/mnt/ngsnfs/tools/genometools/bin:/mnt/ngsnfs/tools/RECON/RECON-1.08:/mnt/ngsnfs/tools/RECON/RECON-1.08/scripts:/mnt/ngsnfs/tools/PILER:/mnt/ngsnfs/tools/mpich-3.1.4/mpich-3.1.4/bin:/mnt/ngsnfs/tools/openmpi-1.8.1/bin:/mnt/ngsnfs/tools/gmap/gmap-2016-09-23/bin:/mnt/ngsnfs/tools/parallel/parallel-20141122/bin:/mnt/ngsnfs/tools/STAR/STAR_2_5_1/STAR/bin/Linux_x86_64_static:/mnt/ngsnfs/tools/cufflinks-2.2.1.Linux_x86_64:/mnt/ngsnfs/tools/fastx/bin:/mnt/ngsnfs/tools/trinity/trinityrnaseq-2.0.6:/mnt/ngsnfs/tools/diamond_7.9:/mnt/ngsnfs/tools/meraculous/bin:/mnt/ngsnfs/tools/aragorn1.2.36:/mnt/ngsnfs/tools/tbl2asn:/mnt/ngsnfs/tools/mauve_snapshot_2015-02-13/linux-x64:/mnt/ngsnfs/tools/ngsutils/ngsutils-ngsutils-0.5.7/bin:/mnt/ngsnfs/tools/mugsy_x86-64-v1r2.3:/mnt/ngsnfs/tools/last/last/bin:/mnt/ngsnfs/tools/Lighter:/mnt/ngsnfs/tools/micro:/mnt/ngsnfs/tools/blast-2.2.26/bin:/mnt/ngsnfs/tools/blast/ncbi-blast-2.4.0+/bin:/mnt/ngsnfs/tools/lastz-distrib-1.02.00/bin:/mnt/ngsnfs/tools/MUMmer3.23:/mnt/ngsnfs/tools/trig/trig-1.0/bin/:/mnt/ngsnfs/tools/Metassembler_1.5/bin:/mnt/ngsnfs/tools/allmaps:/mnt/ngsnfs/tools/pindel:/mnt/ngsnfs/tools/trim_galore/TrimGalore:/mnt/ngsnfs/tools/R/R-3.2.2/bin:/mnt/ngsnfs/tools/bcftools-1.2:/mnt/ngsnfs/tools/vcftools/bin:/mnt/ngsnfs/tools/dos2unix-7.3.2:/mnt/ngsnfs/tools/cdhit:/mnt/ngsnfs/tools/clustal_omega:/mnt/ngsnfs/tools/FastUniq/source:/mnt/ngsnfs/tools/bamtools/bin:/mnt/ngsnfs/tools/augustus-3.2.1/bin:/mnt/ngsnfs/tools/BISMARK/Bismark:/mnt/ngsnfs/tools/cutadapt/cutadapt-1.9.1/bin:/mnt/ngsnfs/tools/root/root/bin:/mnt/ngsnfs/tools/aseq/binaries/linux64:/mnt/ngsnfs/tools/vt/vt:/mnt/ngsnfs/tools/snap:/mnt/ngsnfs/tools/bedtools2/bedtools2-2.26.0/bin/:/mnt/ngsnfs/tools/quickmerge/quickmerge/merger:/mnt/ngsnfs/tools/ucsc:/mnt/ngsnfs/tools/sra-tools/sratoolkit.2.6.3-ubuntu64/bin:/mnt/ngsnfs/tools/bedops/bin:/mnt/ngsnfs/tools/smalt-0.7.6/bin:/mnt/scratch/ensembl-vep/htslib:/mnt/ngsnfs/tools/fasta-36.3.8e/bin:/mnt/ngsnfs/tools/fastme-2.1.5/binaries:/mnt/ngsnfs/tools/PASApipeline/bin:/mnt/ngsnfs/tools/cmake-3.7.0-rc1/bin:/mnt/ngsnfs/tools/subread/subread-1.5.1-Linux-x86_64/bin:/mnt/ngsnfs/tools/salmon/build/bin:/home/rcug/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
.09:55:12 BIOCONDA ERROR COMMAND FAILED: /mnt/ngsnfs/bioconda_dev/miniconda/bin/conda build --no-anaconda-upload --channel bioconda --channel conda-forge --channel defaults recipes/repeatmasker/meta.yaml
09:55:12 BIOCONDA ERROR STDOUT+STDERR:
patching file RepeatMasker
Hunk #1 succeeded at 408 (offset 1 line).
Hunk #2 FAILED at 549.
Hunk #3 FAILED at 583.
Hunk #4 succeeded at 628 (offset -33 lines).
2 out of 4 hunks FAILED -- saving rejects to file RepeatMasker.rej

WARNING: conda-build appears to be out of date. You have version 2.1.16 but the
latest version is 3.0.19. Run

conda update -n root conda-build

to get the latest version.

BUILD START: repeatmasker-4.0.7-pl5.22.0_10

The following NEW packages will be INSTALLED:

    blast:   2.2.31-1   bioconda   
    boost:   1.57.0-4              
    bzip2:   1.0.6-1    conda-forge
    icu:     58.1-1     conda-forge
    libgcc:  5.2.0-0               
    perl:    5.22.0.1-0 conda-forge
    rmblast: 2.2.28-1   bioconda   
    zlib:    1.2.11-0   conda-forge

Source cache directory is: /mnt/ngsnfs/bioconda_dev/miniconda/conda-bld/src_cache
Found source in cache: RepeatMasker-open-4-0-7.tar.gz
Extracting download
Applying patch: '/mnt/ngsnfs/bioconda_dev/bioconda-recipes/recipes/repeatmasker/patch1'
Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
Error was: 
Command '['/usr/bin/patch', '-p1', '-i', '/mnt/ngsnfs/bioconda_dev/bioconda-recipes/recipes/repeatmasker/patch1']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/mnt/ngsnfs/bioconda_dev/miniconda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/mnt/ngsnfs/bioconda_dev/miniconda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "/mnt/ngsnfs/bioconda_dev/miniconda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "/mnt/ngsnfs/bioconda_dev/miniconda/lib/python3.5/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/mnt/ngsnfs/bioconda_dev/miniconda/lib/python3.5/site-packages/conda_build/build.py", line 1522, in build_tree
    config=config)
  File "/mnt/ngsnfs/bioconda_dev/miniconda/lib/python3.5/site-packages/conda_build/build.py", line 1062, in build
    assert not need_source_download, "Source download failed.  Please investigate."
AssertionError: Source download failed.  Please investigate.


09:55:32 BIOCONDA ERROR BUILD FAILED recipes/repeatmasker, CONDA_BOOST=1.64;CONDA_BZIP2=1.0;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.6;CONDA_NCURSES=5.9;CONDA_NPY=112;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.4.1;CONDA_ZLIB=1.2.8;MACOSX_DEPLOYMENT_TARGET=10.9
09:55:47 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
09:55:47 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe repeatmasker-4.0.7-pl5.22.0_10.tar.bz2, environment CONDA_HDF5=1.8.17;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_GMP=5.1;CONDA_BZIP2=1.0;CONDA_HTSLIB=1.6;CONDA_GSL=1.16;CONDA_BOOST=1.64;CONDA_NCURSES=5.9;CONDA_R=3.4.1;MACOSX_DEPLOYMENT_TARGET=10.9;CONDA_NPY=112;CONDA_ZLIB=1.2.8
rcug@hpc-vm1:/mnt/ngsnfs/bioconda_dev/bioconda-recipes$ ls repeatmasker-4.0.7-pl5.22.0_10.tar.bz2,
ls: cannot access 'repeatmasker-4.0.7-pl5.22.0_10.tar.bz2,': No such file or directory
rcug@hpc-vm1:/mnt/ngsnfs/bioconda_dev/bioconda-recipes$ ls /mnt/ngsnfs/bioconda_dev/miniconda/conda-bld/src_cache
RepeatMasker-open-4-0-7.tar.gz

```

**Comment by kastman** [comment]
May have been solved by #8225? If so we can close this issue.
