### ISSUE TITLE
travis test&deploy fails

### ISSUE THREAD

**Issue by martin-mann** [bioconda/bioconda-recipes#6623]
Hi @bioconda/core it seems the Travis test&deploy build has a problem. The Travis log of the last pull requests like #6622 #6605  crash with
```[bash]
$ scripts/travis-run.sh

+bioconda-utils lint recipes config.yml --git-range master HEAD --push-comment --pull-request 6622

19:02:00 BIOCONDA INFO Recipes newly unblacklisted:

19:02:00 BIOCONDA INFO Recipes to consider according to git: 

recipes/cmappy

Traceback (most recent call last):

  File "/anaconda/bin/bioconda-utils", line 11, in <module>

    load_entry_point('bioconda-utils==0.10.0', 'console_scripts', 'bioconda-utils')()

  File "/anaconda/lib/python3.5/site-packages/bioconda_utils/cli.py", line 590, in main

    argh.dispatch_commands([build, dag, dependent, lint, duplicates, bioconductor_skeleton, pypi_check])

  File "/anaconda/lib/python3.5/site-packages/argh/dispatching.py", line 328, in dispatch_commands

    dispatch(parser, *args, **kwargs)

  File "/anaconda/lib/python3.5/site-packages/argh/dispatching.py", line 174, in dispatch

    for line in lines:

  File "/anaconda/lib/python3.5/site-packages/argh/dispatching.py", line 277, in _execute_command

    for line in result:

  File "/anaconda/lib/python3.5/site-packages/argh/dispatching.py", line 260, in _call

    result = function(*positional, **keywords)

  File "/anaconda/lib/python3.5/site-packages/bioconda_utils/cli.py", line 258, in lint

    _recipes = select_recipes(packages, git_range, recipe_folder, config_filename, config, force)

  File "/anaconda/lib/python3.5/site-packages/bioconda_utils/cli.py", line 73, in select_recipes

    if recipes in blacklisted_recipes and recipes in changed_recipes:

NameError: name 'recipes' is not defined
```
Thanks for looking into this!
Martin

**Comment by bgruening** [comment]
Already on it: https://github.com/bioconda/bioconda-utils/pull/209

**Comment by martin-mann** [comment]
unbelievable.. @bgruening you are awesome! when do you sleep? *grin* many many thanks!

**Comment by martin-mann** [comment]
thanks, build continues again!
