### ISSUE TITLE
error when launching quiver from the genomicconsensus conda package

### ISSUE THREAD

**Issue by lbouri** [bioconda/bioconda-recipes#6707]
Hi, i tried to run quiver after the installation of the genomicconsensus package via conda (https://bioconda.github.io/recipes/genomicconsensus/README.html).
First, i installed conda with the Miniconda2 install script, then added the conda channel needed and finally installed the genomicconsensus package with "conda install genomicconsensus".
The error appears when i launched the quiver executable in "/root/miniconda2/bin":

Traceback (most recent call last):
  File "/root/miniconda3/bin/variantCaller", line 4, in <module>
    __import__('pkg_resources').run_script('GenomicConsensus==1.1.0', 'variantCaller')
  File "/root/miniconda3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/root/miniconda3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/root/miniconda3/lib/python2.7/site-packages/GenomicConsensus-1.1.0-py2.7.egg-info/scripts/variantCaller", line 5, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python2.7/site-packages/GenomicConsensus/main.py", line 408, in main
    parser=get_parser(),
  File "/root/miniconda3/lib/python2.7/site-packages/GenomicConsensus/options.py", line 141, in get_parser
    add_options_to_argument_parser(p.arg_parser.parser)
  File "/root/miniconda3/lib/python2.7/site-packages/GenomicConsensus/options.py", line 305, in add_options_to_argument_parser
    help="Set the verbosity level.")
  File "/root/miniconda3/lib/python2.7/argparse.py", line 1308, in add_argument
    return self._add_action(action)
  File "/root/miniconda3/lib/python2.7/argparse.py", line 1509, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/root/miniconda3/lib/python2.7/argparse.py", line 1322, in _add_action
    self._check_conflict(action)
  File "/root/miniconda3/lib/python2.7/argparse.py", line 1460, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/root/miniconda3/lib/python2.7/argparse.py", line 1467, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -v/--verbose: conflicting option string(s): --verbose

**Comment by daler** [comment]
@lbouri thanks for reporting. Looks like this is a bug in the original program. There has not been an official release since 2015, despite a lot of changes to the code. Furthermore looking at the recent changes, there has been a lot of activity recently (https://github.com/PacificBiosciences/GenomicConsensus/commits/master) but their tests are currently failing (https://circleci.com/gh/PacificBiosciences/GenomicConsensus).

It might be best to let the upstream code settle down, and possibly ask upstream for another release, before updating this recipe.

That said, maybe we could patch the bug in the recipe just to get something working. @bioconda/core thoughts?

**Comment by daler** [comment]
(also ping @mictadlo since it looks like you added this originally)

**Comment by bgruening** [comment]
No activity here, I will close it.
