### ISSUE TITLE
pacbio_falcon fails on naive test

### ISSUE THREAD

**Issue by ruyjau** [bioconda/bioconda-recipes#6844]
I tried to run pacbio_falcon as per the instructions on the author's tutorial (http://pb-falcon.readthedocs.io/en/latest/tutorial.html)

My config file looks like this:
[General]
job_type = local
input_fofn = files.fofn
input_type = raw
length_cutoff = 6000
length_cutoff_pr = 8000
jobqueue = default
sge_option_da = -pe smp 4 -q %(jobqueue)s
sge_option_la = -pe smp 20 -q %(jobqueue)s
sge_option_pda = -pe smp 6 -q %(jobqueue)s
sge_option_pla = -pe smp 16 -q %(jobqueue)s
sge_option_fc = -pe smp 24 -q %(jobqueue)s
sge_option_cns = -pe smp 8 -q %(jobqueue)s
pa_concurrent_jobs = 22
cns_concurrent_jobs = 22
ovlp_concurrent_jobs = 22
pa_HPCdaligner_option =  -v -dal128 -t16 -e0.75 -M24 -l3200 -k18 -h480 -w8 -s100
ovlp_HPCdaligner_option = -v -dal128 -M24 -k24 -h1024 -e.96 -l2500 -s100
pa_DBsplit_option = -a -x500 -s200
ovlp_DBsplit_option = -s200
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 200 --n_core 8
overlap_filtering_setting = --max_diff 120 --max_cov 120 --min_cov 2 --n_core 12

The command I ran is:
 fc_run fc_run.cfg

The output I got is:
['/home/jaureguir/conda-envs/pacbio_falcon/bin/fc_run', 'fc_run.cfg']
[INFO]fc_run started with configuration fc_run.cfg
[INFO] No target specified, assuming "assembly" as target
/home/jaureguir/conda-envs/pacbio_falcon/lib/python2.7/site-packages/falcon_kit/run_support.py:235: UserWarning: Unexpected keys in input config: set(['jobqueue'])
  warnings.warn("Unexpected keys in input config: %s" %repr(unused))
Traceback (most recent call last):
  File "/home/jaureguir/conda-envs/pacbio_falcon/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit==0.4.0', 'console_scripts', 'fc_run')()
  File "/home/jaureguir/conda-envs/pacbio_falcon/lib/python2.7/site-packages/falcon_kit/mains/run.py", line 614, in main
    main1(*argv)
  File "/home/jaureguir/conda-envs/pacbio_falcon/lib/python2.7/site-packages/falcon_kit/mains/run.py", line 438, in main1
    wf.refreshTargets([fofn_abs_task])
  File "/home/jaureguir/conda-envs/pacbio_falcon/lib/python2.7/site-packages/pypeflow/controller.py", line 528, in refreshTargets
    tSortedURLs = PypeGraph(rdfGraph, connectedPypeNodes).tSort( )
  File "/home/jaureguir/conda-envs/pacbio_falcon/lib/python2.7/site-packages/pypeflow/controller.py", line 110, in __init__
    for row in self._RDFGraph.query('SELECT ?s ?o WHERE {?s pype:prereq ?o . }', initNs=dict(pype=pypeNS)):
  File "/home/jaureguir/conda-envs/pacbio_falcon/lib/python2.7/site-packages/rdflib/graph.py", line 1080, in query
    result = plugin.get(result, query.Result)
  File "/home/jaureguir/conda-envs/pacbio_falcon/lib/python2.7/site-packages/rdflib/plugin.py", line 104, in get
    return p.getClass()
  File "/home/jaureguir/conda-envs/pacbio_falcon/lib/python2.7/site-packages/rdflib/plugin.py", line 66, in getClass
    module = __import__(self.module_path, globals(), locals(), [""])
ImportError: No module named rdfextras.sparql.query

Would you have any idea what is going wrong?

Thanks in advance,

**Comment by daler** [comment]
@ruyjau I just updated the recipe so it includes `rdfextras` as a dependency, can you try installing again and see if it fixes the issue?

**Comment by ruyjau** [comment]
Now, with rdfextras present,  the falcon package produces another error:

 fc_run fc_run.cfg
['/home/jaureguir/conda-envs/pacbio_falcon/bin/fc_run', 'fc_run.cfg']
[INFO]fc_run started with configuration fc_run.cfg
[INFO] No target specified, assuming "assembly" as target
/home/jaureguir/conda-envs/pacbio_falcon/lib/python2.7/site-packages/falcon_kit/run_support.py:235: UserWarning: Unexpected keys in input config: set(['jobqueue'])
  warnings.warn("Unexpected keys in input config: %s" %repr(unused))
Traceback (most recent call last):
  File "/home/jaureguir/conda-envs/pacbio_falcon/bin/fc_run", line 11, in <module>
    load_entry_point('falcon-kit==0.4.0', 'console_scripts', 'fc_run')()
  File "/home/jaureguir/conda-envs/pacbio_falcon/lib/python2.7/site-packages/falcon_kit/mains/run.py", line 614, in main
    main1(*argv)
  File "/home/jaureguir/conda-envs/pacbio_falcon/lib/python2.7/site-packages/falcon_kit/mains/run.py", line 438, in main1
    wf.refreshTargets([fofn_abs_task])
  File "/home/jaureguir/conda-envs/pacbio_falcon/lib/python2.7/site-packages/pypeflow/controller.py", line 528, in refreshTargets
    tSortedURLs = PypeGraph(rdfGraph, connectedPypeNodes).tSort( )
  File "/home/jaureguir/conda-envs/pacbio_falcon/lib/python2.7/site-packages/pypeflow/controller.py", line 110, in __init__
    for row in self._RDFGraph.query('SELECT ?s ?o WHERE {?s pype:prereq ?o . }', initNs=dict(pype=pypeNS)):
  File "/home/jaureguir/conda-envs/pacbio_falcon/lib/python2.7/site-packages/rdflib/graph.py", line 1085, in query
    query_object, initBindings, initNs, **kwargs))
  File "/home/jaureguir/conda-envs/pacbio_falcon/lib/python2.7/site-packages/rdfextras-0.4-py2.7.egg/rdfextras/sparql/processor.py", line 49, in query
    loadContexts=loadContexts)
  File "/home/jaureguir/conda-envs/pacbio_falcon/lib/python2.7/site-packages/rdfextras-0.4-py2.7.egg/rdfextras/sparql/algebra.py", line 388, in TopEvaluate
    top.topLevelExpand(expr.constraints, query.prolog)
  File "/home/jaureguir/conda-envs/pacbio_falcon/lib/python2.7/site-packages/rdfextras-0.4-py2.7.egg/rdfextras/sparql/query.py", line 520, in topLevelExpand
    self.expand(constraints)
  File "/home/jaureguir/conda-envs/pacbio_falcon/lib/python2.7/site-packages/rdfextras-0.4-py2.7.egg/rdfextras/sparql/query.py", line 527, in expand
    if self.tripleStore.graph.store.batch_unification:
AttributeError: 'IOMemory' object has no attribute 'batch_unification'

**Comment by daler** [comment]
This sounds like an upstream problem; I did find https://github.com/PacificBiosciences/SMRT-Analysis/issues/76#issuecomment-33965462 which suggests that downgrading `rdflib` to 3.4 might help, but versions that old don't exist in conda-forge or bioconda. In your conda environment, does `pip install rdflib==3.4` help with the problem?

**Comment by bgruening** [comment]
@ruyjau ping

**Comment by peterjc** [comment]
It seems ``pacbio_falcon`` has been replaced by ``pb-falcon`` instead - see also #8945 - does this fix the problem with the test dataset for you?
