### ISSUE TITLE
Cant seem to build any of the bioconductor-X recipes: fail in 'build.sh'

### ISSUE THREAD

**Issue by xguse** [bioconda/bioconda-recipes#719]
I keep getting the same error:

```
Package: bioconductor-edger-3.12.0-0
source tree in: /home/gus/src/repos/git/conda-package-repo/pkgs/channel/work/edgeR
+ mv DESCRIPTION DESCRIPTION.old
+ grep -v '^Priority: ' DESCRIPTION.old
+ /home/gus/anaconda2/envs/_build/bin/R CMD INSTALL --build .
sh: symbol lookup error: sh: undefined symbol: rl_signal_event_hook
Command failed: /bin/bash -x -e /home/gus/src/repos/git/bioconda-recipes/recipes/bioconductor-edger/build.sh
```

FYI: This is not in the docker container but on my home system.

Any advice/direction?

Gus

**Comment by xguse** [comment]
OK this seems to be related to Arch linux and readline issues.  Still not sure of the best way to proceed though.  I guess I may just need to always use a non-Arch container to build stuff.  Better for shareability, but a little annoying for purely personal stuff... Thoughts?

**Comment by johanneskoester** [comment]
You can build with our docker container on your local machine.

**Comment by xguse** [comment]
I can build some.  bioconda-limma doesn't build but I think that is because of a new version of limma being hosted and for some reason the old one not being at the same url anymore.  I dont think its bioconda's issue.

I am writing a recipe for vsn (bioconductor) but I cant get it to download in the build container.  It complains its getting a 404 error even though I can wget the url just fine locally.

__However, this is not the same issue.__  The readline stuff works just fine.

The output of the build failing by 404 error for the sake of completeness.

```

gus at jupiter in ~/src/repos/git/bioconda-recipes (f/nanostring-pipeline●●)
$ docker run -v `pwd`:/bioconda-recipes bioconda/bioconda-builder --packages bioconductor-vsn
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ldd (GNU libc) 2.5
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
Reading recipe /bioconda-recipes/recipes/bioconductor-vsn
['/bioconda-recipes/recipes/bioconductor-vsn']
F
======================================================================
FAIL: __main__.test_recipes('/bioconda-recipes/recipes/bioconductor-vsn',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/anaconda/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/bioconda-recipes/scripts/build-packages.py", line 91, in build_recipe
    assert False, "At least one build of recipe {} failed.".format(recipe)
AssertionError: At least one build of recipe /bioconda-recipes/recipes/bioconductor-vsn failed.
-------------------- >> begin captured stdout << ---------------------
Fetching package metadata: ............
Removing old build environment
Removing old work directory
BUILD START: bioconductor-vsn-3.38.0-0
Fetching package metadata: ............
Solving package specifications: ..........
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    jbig-2.1                   |                0          29 KB
    jpeg-8d                    |                0         699 KB
    libffi-3.0.13              |                0          33 KB
    libgcc-4.8.5               |                1         922 KB
    libpng-1.6.17              |                0         214 KB
    ncurses-5.9                |                4         676 KB
    pcre-8.31                  |                0         534 KB
    pixman-0.32.6              |                0         2.4 MB
    freetype-2.5.5             |                0         2.2 MB
    glib-2.43.0                |                2         7.4 MB
    libtiff-4.0.6              |                1         1.5 MB
    libxml2-2.9.3              |                0         5.2 MB
    fontconfig-2.11.1          |                5         402 KB
    cairo-1.12.18              |                6         594 KB
    harfbuzz-0.9.35            |                6         1.1 MB
    pango-1.36.8               |                3         796 KB
    r-base-3.2.2               |                0        20.6 MB
    r-3.2.2                    |                0           2 KB
    r-boot-1.3_17              |         r3.2.2_0         575 KB
    r-cluster-2.0.3            |         r3.2.2_0         466 KB
    r-codetools-0.2_14         |         r3.2.2_0          45 KB
    r-foreign-0.8_66           |         r3.2.2_0         220 KB
    r-kernsmooth-2.23_15       |         r3.2.2_0          84 KB
    r-lattice-0.20_33          |         r3.2.2_0         698 KB
    r-mass-7.3_45              |         r3.2.2_0         1.0 MB
    r-nnet-7.3_11              |         r3.2.2_0          99 KB
    r-rpart-4.1_10             |         r3.2.2_0         861 KB
    r-spatial-7.3_11           |         r3.2.2_0         122 KB
    r-survival-2.38_3          |         r3.2.2_0         4.4 MB
    r-class-7.3_14             |         r3.2.2_0          82 KB
    r-matrix-1.2_2             |         r3.2.2_0         3.1 MB
    r-nlme-3.1_122             |         r3.2.2_0         2.0 MB
    r-mgcv-1.8_9               |         r3.2.2_0         1.8 MB
    r-recommended-3.2.2        |         r3.2.2_0          707 B
    ------------------------------------------------------------
                                           Total:        60.6 MB

The following NEW packages will be INSTALLED:

    cairo:         1.12.18-6
    fontconfig:    2.11.1-5
    freetype:      2.5.5-0
    glib:          2.43.0-2
    harfbuzz:      0.9.35-6
    jbig:          2.1-0
    jpeg:          8d-0
    libffi:        3.0.13-0
    libgcc:        4.8.5-1
    libpng:        1.6.17-0
    libtiff:       4.0.6-1
    libxml2:       2.9.3-0
    ncurses:       5.9-4
    pango:         1.36.8-3
    pcre:          8.31-0
    pixman:        0.32.6-0
    r:             3.2.2-0
    r-base:        3.2.2-0
    r-boot:        1.3_17-r3.2.2_0
    r-class:       7.3_14-r3.2.2_0
    r-cluster:     2.0.3-r3.2.2_0
    r-codetools:   0.2_14-r3.2.2_0
    r-foreign:     0.8_66-r3.2.2_0
    r-kernsmooth:  2.23_15-r3.2.2_0
    r-lattice:     0.20_33-r3.2.2_0
    r-mass:        7.3_45-r3.2.2_0
    r-matrix:      1.2_2-r3.2.2_0
    r-mgcv:        1.8_9-r3.2.2_0
    r-nlme:        3.1_122-r3.2.2_0
    r-nnet:        7.3_11-r3.2.2_0
    r-recommended: 3.2.2-r3.2.2_0
    r-rpart:       4.1_10-r3.2.2_0
    r-spatial:     7.3_11-r3.2.2_0
    r-survival:    2.38_3-r3.2.2_0
    readline:      6.2-2
    tk:            8.5.18-0
    xz:            5.0.5-0
    zlib:          1.2.8-0

Removing old work directory
Source cache directory is: /anaconda/conda-bld/src_cache
Downloading source to cache: vsn_3.38.0.tar.gz
Downloading http://bioconductor.org/packages/release/bioc/src/contrib/vsn_3.38.0.tar.gz


WARNING: conda-build appears to be out of date. You have version 1.18.2 but the
latest version is 1.19.0. Run

conda update -n root conda-build

to get the latest version.

Error: HTTPError: 404 Client Error: Not Found for url: http://bioconductor.org/packages/release/bioc/src/contrib/vsn_3.38.0.tar.gz: http://bioconductor.org/packages/release/bioc/src/contrib/vsn_3.38.0.tar.gz
Error: Could not download vsn_3.38.0.tar.gz


--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 1 test in 49.210s

FAILED (failures=1)
```

**Comment by johanneskoester** [comment]
@daler, any idea? Is this related to the version storage on bioconductor?

**Comment by daler** [comment]
If it the bioconductor version was updated, then the URL wouldn't be accessible locally.

Is this a network-access-in-container issue? Can you wget the URL from inside the container?

**Comment by xguse** [comment]
So I may have confused things a bit by mentioning LIMMA.  

Let me try to clarify. LIMMA most likely will work fine once I update the recipe to to point to the new version.  I can `wget` the new version of LIMMA from my local system but not the old version. I learned of the issue with LIMMA while I was trying a few "positive controls" to make sure that I had the docker container working.  A couple other random bioconductor bioconda recipes work fine. Of the few positive control recipes I selected only LIMMA was a problem, and I am confident I understand the problem.

VSN is the recipe that I am writing.  Its my test case. It is VSN that I am talking about not being able to access from the container script but being able to `wget` in my home system.  I am afraid that I am having issues getting "into" the container myself to try `wget` manually.  The container seems to REALLY REALLY want to run the build-script even when I try to enter it via `exec` etc.  I guess I need to alter the buildfile and build another image with custom bits at the end that don't expect to be running the build-script.

Thoughts/advice are appreciated.  

I am admittedly a novice docker-er.  I have written/built and run my own images but with pretty basic logic.

**Comment by daler** [comment]
For testing in the container interactively, the following is helpful. The trick is overriding `--entrypoint`:

```
docker run --entrypoint /bin/bash -it -v `pwd`:/bioconda-recipes bioconda/bioconda-builder
```

**Comment by xguse** [comment]
First: holy crap thanks for that tip!

Second: I ****ing hate proxies.

I think that the issue is Boston Children's Hospital's proxy BS. I just tried both VSN and AFFY. It chokes if I use https (can't establish SSL connection) and http yields the 404 error which is similar to errors I was getting before I sorted out proxy settings on my host system. 

I am going to confirm this and probably just have to build a new image from y'all's that includes logic to bake in the correct proxy settings.

I also RE-ran some of the tests that I interpreted as successful before (because if it is the proxy stuff those should NOT have succeeded).  It turns out that they did NOT succeed.  They just didn't fail loudly. They skipped the recipes and end wih reporting `OK`.  Of course they also told me that they skipped my recipes, I just didn't read close enough after I saw 'OK' and had no errors raised.

Thanks for the help.  I will report more after I can confirm success with correct proxy settings.


```
gus at jupiter in ~/src/repos/git/bioconda-recipes (f/nanostring-pipeline●●)
$ docker run --rm -v `pwd`:/bioconda-recipes bioconda/bioconda-builder --packages bioconductor-affy
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ldd (GNU libc) 2.5
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
Skipping recipe /bioconda-recipes/recipes/bioconductor-affy
[]

----------------------------------------------------------------------
Ran 0 tests in 7.280s

OK
(nanostring)
gus at jupiter in ~/src/repos/git/bioconda-recipes (f/nanostring-pipeline●●)
$ docker run --rm -v `pwd`:/bioconda-recipes bioconda/bioconda-builder --packages bioconductor-annotate
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ldd (GNU libc) 2.5
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
Skipping recipe /bioconda-recipes/recipes/bioconductor-annotate
[]

----------------------------------------------------------------------
Ran 0 tests in 8.865s

OK
(nanostring)
gus at jupiter in ~/src/repos/git/bioconda-recipes (f/nanostring-pipeline●●)
$ docker run --rm -v `pwd`:/bioconda-recipes bioconda/bioconda-builder --packages bioawk
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ldd (GNU libc) 2.5
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
Skipping recipe /bioconda-recipes/recipes/bioawk
[]

----------------------------------------------------------------------
Ran 0 tests in 7.524s

OK
(nanostring)
```

**Comment by xguse** [comment]
Yes it is the proxy settings.  I can wget using http (but not https) once I `export http_proxy=http://i.hate.this.crap:ports` etc.

Thanks for your time and help as always!

**Comment by xguse** [comment]
Just as a final point on this issue:

```
gus at jupiter in ~/src/repos/git/bioconda-recipes (f/nanostring-pipeline●●)
$ docker run -e http_proxy=http://proxy.tch.harvard.edu:3128/ --rm -v `pwd`:/bioconda-recipes bioconda/bioconda-builder --packages bioconductor-vsn
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ldd (GNU libc) 2.5
Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
Reading recipe /bioconda-recipes/recipes/bioconductor-vsn
['/bioconda-recipes/recipes/bioconductor-vsn']
.
----------------------------------------------------------------------
Ran 1 test in 93.396s

OK
(nanostring)
```

**Comment by daler** [comment]
Ah, that's nice you can provide the proxy on the command line without having to build/modify a container. Success!
