### ISSUE TITLE
Contributing has some issues

### ISSUE THREAD

**Issue by apeltzer** [bioconda/bioconda-recipes#8157]
Hey folks,

I'm trying to contribute some recipes and have several issues setting things up. I followed the instructions [here](https://bioconda.github.io/contribute-a-recipe.html) and was unable to test anything locally

- neither with the `circleci build` setp
- nor with the `conda build recipe/yourrecipe` 

I'm trying to check what fails in my recipe: https://github.com/apeltzer/bioconda-recipes/tree/adapterremoval

On CircleCI it fails with this error message, and I wanted to test locally what went wrong.

``` 
Downloading source to cache: v2.2.2.tar.gz
Downloading https://github.com/MikkelSchubert/adapterremoval/archive/v2.2.2.tar.gz
Success
Extracting download
BUILD START (revised): adapterremoval-2.2.2-2
Package: adapterremoval-2.2.2-2
source tree in: /opt/conda/conda-bld/adapterremoval_1520262678857/work/adapterremoval-2.2.2
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1524, in build_tree
    config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1147, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 628, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 624, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/opt/conda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/opt/conda/conda-bld/adapterremoval_1520262678857/work/adapterremoval-2.2.2/conda_build.sh']' returned non-zero exit status 2.


15:13:16 BIOCONDA ERROR BUILD FAILED recipes/adapterremoval, CONDA_ALLOW_SOFTLINKS=false;CONDA_BAMTOOLS=2.4.1;CONDA_BOOST=1.64;CONDA_BZIP2=1.0;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.7;CONDA_NCURSES=5.9;CONDA_NPY=112;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.4.1;CONDA_ROOT=/home/circleci/project/miniconda;CONDA_XZ=5.2;CONDA_ZLIB=1.2.11;LANG=en_US.UTF-8;MACOSX_DEPLOYMENT_TARGET=10.9
15:13:18 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
15:13:18 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe adapterremoval-2.2.2-2.tar.bz2, environment CONDA_PY=27;CONDA_HTSLIB=1.7;CONDA_BOOST=1.64;CONDA_R=3.4.1;CONDA_PERL=5.22.0;CONDA_NPY=112;CONDA_NCURSES=5.9;CONDA_GSL=1.16;CONDA_GMP=5.1;CONDA_HDF5=1.8.17;MACOSX_DEPLOYMENT_TARGET=10.9;CONDA_ZLIB=1.2.11;CONDA_BZIP2=1.0;CONDA_XZ=5.2;CONDA_BAMTOOLS=2.4.1
Exited with code 1
```

**Comment by daler** [comment]
Hi @apeltzer - 

Check farther up in the log: after merging in the bioconda-recipes master branch and running `circleci build`, I get the following by testing locally:

```
====>> Testing
  #!/bin/bash -eo pipefail
bioconda-utils build recipes config.yml --git-range upstream/master
20:52:53 BIOCONDA INFO Recipes newly unblacklisted:

20:52:53 BIOCONDA INFO Recipes modified according to git: adapterremoval
20:52:53 BIOCONDA INFO blacklist: angsd, blast/2.2.21, breakdancer, cap-mirseq, cgat-scripts, clever-toolkit, dcmtk, denovogear, fermikit, frc, metaprob, mgkit, mothur/1.36.1, nanopolish/0.4.0, ngless, openslide, osra/2.1.0, perl-compress-raw-zlib, perl-font-afm, p
erl-io-compress, plastid, preseq, prosic, pysamstats, r-pscbs/0.61.0, rust-overlaps, samtools/1.1, shorah, slang, smalt, soapec, somatic-sniper, transcomb, transrate-tools, trinity/2.1.1
20:52:53 BIOCONDA INFO Filtering recipes

Filtering 1 of 1 (100.0%) recipes/adapterremoval
20:52:55 BIOCONDA INFO Building and testing 1 recipes in total
20:52:55 BIOCONDA INFO Recipes to build:
adapterremoval
20:52:55 BIOCONDA INFO Building and testing subdag 1 of 1 (1 recipes)
20:52:55 BIOCONDA INFO BUILD START recipes/adapterremoval, env: CONDA_ALLOW_SOFTLINKS=false;CONDA_BAMTOOLS=2.4.1;CONDA_BOOST=1.64;CONDA_BZIP2=1.0;CONDA_DEFAULT_ENV=root;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.7;CONDA_NCURSES=5.9;CONDA_NPY=112;
CONDA_PATH_BACKUP=/opt/rh/devtoolset-2/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin;CONDA_PERL=5.22.0;CONDA_PS1_BACKUP=;CONDA_PY=27;CONDA_R=3.4.1;CONDA_ROOT=/opt/conda;CONDA_XZ=5.2;CONDA_ZLIB=1.2.11;LANG=en_US.UTF-8;MACOSX_DEPLOYMENT_TA
RGET=10.9;PATH=/root/project/miniconda/bin:/opt/conda/bin:/opt/rh/devtoolset-2/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
..20:54:42 BIOCONDA ERROR COMMAND FAILED: /opt/conda/bin/conda build --no-anaconda-upload --channel bioconda --channel conda-forge --channel defaults recipes/adapterremoval/meta.yaml
20:54:42 BIOCONDA ERROR STDOUT+STDERR:
+ source /opt/conda/bin/activate /opt/conda/conda-bld/adapterremoval_1520455976443/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
hold_placehold_placehol
+ make
Building AdapterRemoval with coverage instrumentation: no
Building AdapterRemoval with debug information: no
which: no wget in (/opt/conda/conda-bld/adapterremoval_1520455976443/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
_placehol/bin:/opt/conda/conda-bld/adapterremoval_1520455976443/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac
ehol:/opt/conda/conda-bld/adapterremoval_1520455976443/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin:
/root/project/miniconda/bin:/opt/conda/bin:/opt/rh/devtoolset-2/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
\033[0;36mBuilding build/main/adapterset.o from src/adapterset.cpp\033[0m
\033[0;36mBuilding build/main/alignment.o from src/alignment.cpp\033[0m
\033[0;36mBuilding build/main/argparse.o from src/argparse.cpp\033[0m
\033[0;36mBuilding build/main/debug.o from src/debug.cpp\033[0m
\033[0;36mBuilding build/main/demultiplex.o from src/demultiplex.cpp\033[0m
\033[0;36mBuilding build/main/fastq.o from src/fastq.cpp\033[0m
\033[0;36mBuilding build/main/fastq_enc.o from src/fastq_enc.cpp\033[0m
\033[0;36mBuilding build/main/fastq_io.o from src/fastq_io.cpp\033[0m
\033[0;36mBuilding build/main/linereader.o from src/linereader.cpp\033[0m
\033[0;36mBuilding build/main/linereader_joined.o from src/linereader_joined.cpp\033[0m
\033[0;36mBuilding build/main/main_adapter_id.o from src/main_adapter_id.cpp\033[0m
\033[0;36mBuilding build/main/main_adapter_rm.o from src/main_adapter_rm.cpp\033[0m
\033[0;36mBuilding build/main/main_demultiplex.o from src/main_demultiplex.cpp\033[0m
\033[0;36mBuilding build/main/scheduler.o from src/scheduler.cpp\033[0m
\033[0;36mBuilding build/main/strutils.o from src/strutils.cpp\033[0m
\033[0;36mBuilding build/main/threads.o from src/threads.cpp\033[0m
\033[0;36mBuilding build/main/timer.o from src/timer.cpp\033[0m
\033[0;36mBuilding build/main/trimmed_reads.o from src/trimmed_reads.cpp\033[0m
\033[0;36mBuilding build/main/userconfig.o from src/userconfig.cpp\033[0m
\033[0;36mBuilding build/main/main.o from src/main.cpp\033[0m
\033[0;32mLinking executable build/AdapterRemoval\033[0m
\033[0;32mConstructing man-page build/AdapterRemoval.1 from AdapterRemoval.pod\033[0m
/bin/sh: pod2man: command not found
make: *** [build/AdapterRemoval.1] Error 127
```

After that comes the log you pasted.

Looks like two issues here: it can't find `wget` (seems to use it for running `make test`?) and can't find `pod2man`. Try adding `wget` and `perl` to the build deps. That fixed it for me locally.

**Comment by apeltzer** [comment]
Should have read it more carefully - it works now and I submitted a pull request :+1:  Thanks to point that out for me - still learning
