### ISSUE TITLE
Error with Plastid build py27_1

### ISSUE THREAD

**Issue by StevenVerbruggen** [bioconda/bioconda-recipes#8219]
I had an error with Plastid (bioconda-recipes/recipes/plastid) build py27_1.
For example:
```> metagene generate -h
Traceback (most recent call last):
  File "/data/steven/.conda/envs/test_mqc/bin/metagene", line 11, in <module>
    load_entry_point('plastid==0.4.7', 'console_scripts', 'metagene')()
  File "/data/steven/.conda/envs/test_mqc/lib/python2.7/site-packages/pkg_resources/__init__.py", line 587, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/data/steven/.conda/envs/test_mqc/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2800, in load_entry_point
    return ep.load()
  File "/data/steven/.conda/envs/test_mqc/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2431, in load
    return self.resolve()
  File "/data/steven/.conda/envs/test_mqc/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2437, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/data/steven/.conda/envs/test_mqc/lib/python2.7/site-packages/plastid/__init__.py", line 44, in <module>
    from plastid.genomics.genome_array import (BAMGenomeArray,
  File "/data/steven/.conda/envs/test_mqc/lib/python2.7/site-packages/plastid/genomics/genome_array.py", line 215, in <module>
    from plastid.genomics.map_factories import *
  File "libcfaidx.pxd", line 52, in init plastid.genomics.map_factories
AttributeError: 'module' object has no attribute 'FastxRecord'
```

This error did not occur with build py27_0. So I suppose there is still a bug in the new build of Plastid. Just wanted to let you know this.

**Comment by bgruening** [comment]
There are now multiple new version, I hope the new ones are working.
