### ISSUE TITLE
circleci build fails

### ISSUE THREAD

**Issue by dturaev** [bioconda/bioconda-recipes#8319]
Ok, I'm stuck with the recipe for the latest seqmagick version (0.7.0). The build works fine with "conda build" (even though it was necessary to add "nose" as a dependency after running "conda skeleton"...), but fails with "circleci build" in the testing section. What's going on there? Does the container try to execute setup.py before setting up the environment with all dependencies?
```
...
14:34:05 BIOCONDA INFO Building and testing subdag 1 of 1 (1 recipes)
14:34:05 BIOCONDA INFO BUILD START recipes/seqmagick, env: CONDA_ALLOW_SOFTLINKS=false;CONDA_BAMTOOLS=2.4.1;CONDA_BOOST=1.64;CONDA_BZIP2=1.0;CONDA_DEFAULT_ENV=root;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_HDF5=1.8.17;CONDA_HTSLIB=1.7;CONDA_NCURSES=5.9;CONDA_NPY=112;CONDA_PATH_BACKUP=/opt/rh/devtoolset-2/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin;CONDA_PERL=5.22.0;CONDA_PS1_BACKUP=;CONDA_PY=35;CONDA_R=3.4.1;CONDA_ROOT=/opt/conda;CONDA_XZ=5.2;CONDA_ZLIB=1.2.11;LANG=en_US.UTF-8;MACOSX_DEPLOYMENT_TARGET=10.9;PATH=/root/project/miniconda/bin:/opt/conda/bin:/opt/rh/devtoolset-2/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
.14:34:09 BIOCONDA ERROR COMMAND FAILED: /opt/conda/bin/conda build --no-anaconda-upload --channel bioconda --channel conda-forge --channel defaults recipes/seqmagick/meta.yaml
14:34:09 BIOCONDA ERROR STDOUT+STDERR:
INFO:fetch.start:('seqmagick-0.7.', 42006)
INFO:fetch.update:16384
INFO:fetch.update:32768
INFO:fetch.update:42006
INFO:fetch.stop:None
+ source /opt/conda/bin/activate /opt/conda/conda-bld/seqmagick_1521556446896/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
+ python setup.py install --single-version-externally-managed --record=record.txt
Traceback (most recent call last):
  File "setup.py", line 47, in <module>
    license="GPL V3")
  File "/opt/conda/lib/python3.6/site-packages/setuptools/__init__.py", line 128, in setup
    _install_setup_requires(attrs)
  File "/opt/conda/lib/python3.6/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/opt/conda/lib/python3.6/site-packages/setuptools/dist.py", line 461, in fetch_build_eggs
    replace_conflicting=True,
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 866, in resolve
    replace_conflicting=replace_conflicting
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1146, in best_match
    return self.obtain(req, installer)
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1158, in obtain
    return installer(requirement)
  File "/opt/conda/lib/python3.6/site-packages/setuptools/dist.py", line 528, in fetch_build_egg
    return cmd.easy_install(req)
  File "/opt/conda/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 661, in easy_install
    not self.always_copy, self.local_index
  File "/opt/conda/lib/python3.6/site-packages/setuptools/package_index.py", line 660, in fetch_distribution
    self.find_packages(requirement)
  File "/opt/conda/lib/python3.6/site-packages/setuptools/package_index.py", line 493, in find_packages
    self.scan_url(self.index_url + requirement.unsafe_name + '/')
  File "/opt/conda/lib/python3.6/site-packages/setuptools/package_index.py", line 833, in scan_url
    self.process_url(url, True)
  File "/opt/conda/lib/python3.6/site-packages/setuptools/package_index.py", line 328, in process_url
    "Be sure to add all dependencies in the meta.yaml  url=%s" % url)
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/nose/
...
```

**Comment by dturaev** [comment]
Ok never mind, seems that there was a "build.sh" file lying around that the container picked up, and that somehow destroyed the building process... My fault. Build is running now.

**Comment by daler** [comment]
@dturaev do you have a pull request with the recipe so we could take a look?

**Comment by dturaev** [comment]
Thanks, here it is: https://github.com/bioconda/bioconda-recipes/pull/8351
