### ISSUE TITLE
First Bioconda package: Problems trying to run tests

### ISSUE THREAD

**Issue by ignaciot** [bioconda/bioconda-recipes#9534]
Hi guys, this is my first attempt at submitting a package to Bioconda, so I apologize in advance if I'm missing something really obvious. I have a proper PyPI package that I'd like to include in Bioconda as well, I followed the instructions up to forking this repository and when trying to run the local tests, I'm running into errors with both the "Circle CI" and "bootstrap" methods.

With the first one, I get an exception regarding conda.version (I can import conda but don't seem to have a conda.version package, is this part of something else?):

```
$ circleci build

====>> Spin up Environment
Build-agent version 0.0.5895-01cdb92 (2018-05-29T20:07:10+0000)
Starting container bioconda/bioconda-utils-build-env
  using image bioconda/bioconda-utils-build-env@sha256:969aad03c0b5661ed55d2eadb938295706a4cf45191dc47e2dfe4c57f4d2d436

Using build environment variables:
  BASH_ENV=/tmp/.bash_env-localbuild-1529630969
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=dastk
  CIRCLE_BUILD_NUM=
  CIRCLE_JOB=build
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_REPOSITORY_URL=https://github.com/ignaciot/bioconda-recipes.git
  CIRCLE_SHA1=671f6dbc52adca025f10fa000b2566ff2908d9d1
  CIRCLE_SHELL_ENV=/tmp/.bash_env-localbuild-1529630969
  CIRCLE_WORKING_DIRECTORY=~/project

====>> Checkout code
  #!/bin/sh
mkdir -p /root/project && cp -r /tmp/_circleci_local_build_repo/. /root/project
====>> Setup ssh
  #!/bin/bash -eo pipefail
mkdir -p ~/.ssh
ssh-keyscan -H github.com >> ~/.ssh/known_hosts

# github.com SSH-2.0-libssh_0.7.0
====>> Setup base system
  #!/bin/bash -eo pipefail
cat >> $BASH_ENV <<EOF
if [[ \$- == *u* ]] ; then
    set +u ; . /tmp/repo/docker-entrypoint-source ; set -u
else
    . /tmp/repo/docker-entrypoint-source
fi
EOF

====>> Download common definitions
  #!/bin/bash -eo pipefail
curl -s https://raw.githubusercontent.com/bioconda/bioconda-common/master/common.sh > .circleci/common.sh
# TODO remove this temporal override before merging the PR into master
echo -e 'MINICONDA_VER=4.4.10\nBIOCONDA_UTILS_TAG=cb3-migration' > .circleci/common.sh

====>> Setup bioconda-utils
  #!/bin/bash -eo pipefail
.circleci/setup.sh
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /opt/conda:

The following NEW packages will be INSTALLED:

    intel-openmp:   2018.0.3-0                    defaults
    libgcc-ng:      7.2.0-hdf63c60_3              defaults
    libgfortran-ng: 7.2.0-hdf63c60_3              defaults
    mkl:            2018.0.3-1                    defaults
    mkl_fft:        1.0.2-py36_0                  conda-forge
    mkl_random:     1.0.1-py36_0                  conda-forge
    numpy-base:     1.14.5-py36hdbf6ddf_0         defaults

The following packages will be UPDATED:

    conda:          4.3.33-py36_0                 conda-forge --> 4.5.4-py36_0          conda-forge
    conda-build:    2.1.18-py36_0                 conda-forge --> 3.10.6-py36_0         conda-forge
    git:            2.14.2-3                      conda-forge --> 2.17.1-0              conda-forge
    numpy:          1.14.3-py36_blas_openblas_200 conda-forge [blas_openblas] --> 1.14.5-py36hcd700cb_0 defaults
    tini:           0.18.0-0                      conda-forge --> 0.18.0-h470a237_1     conda-forge

The following packages will be DOWNGRADED:

    blas:           1.1-openblas                  conda-forge --> 1.0-mkl               defaults

Proceed ([y]/n)?
blas-1.0-mkl.t 100% || Time: 0:00:00   3.99 MB/ss
intel-openmp-2 100% || Time: 0:00:00   5.12 MB/ss
libgcc-ng-7.2. 100% || Time: 0:00:00  12.43 MB/ss
libgfortran-ng 100% || Time: 0:00:00  20.93 MB/ss
mkl-2018.0.3-1 100% || Time: 0:00:12  16.75 MB/ss
tini-0.18.0-h4 100% || Time: 0:00:00  11.17 MB/ss
git-2.17.1-0.t 100% || Time: 0:00:09   1.97 MB/ss
numpy-base-1.1 100% || Time: 0:00:00  23.04 MB/ss
conda-4.5.4-py 100% || Time: 0:00:00   2.84 MB/ss
conda-build-3. 100% || Time: 0:00:00   1.25 MB/ss
mkl_fft-1.0.2- 100% || Time: 0:00:00   2.55 MB/ss
mkl_random-1.0 100% || Time: 0:00:00   4.58 MB/ss
numpy-1.14.5-p 100% || Time: 0:00:00  25.17 MB/ss
remote: Counting objects: 709, done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 709 (delta 405), reused 441 (delta 404), pack-reused 265
Receiving objects: 100% (709/709), 143.32 KiB | 13.03 MiB/s, done.
Resolving deltas: 100% (405/405), completed with 296 local objects.
From https://github.com/bioconda/bioconda-recipes
 * [new branch]          master     -> __upstream__obeubaimpb/master
====>> Linting
  #!/bin/bash -eo pipefail
bioconda-utils lint --loglevel debug --full-report recipes config.yml --git-range master HEAD
Traceback (most recent call last):
  File "/opt/conda/bin/bioconda-utils", line 11, in <module>
    load_entry_point('bioconda-utils==0+untagged.1.gf35d935', 'console_scripts', 'bioconda-utils')()
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/conda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 15, in <module>
    from . import utils
  File "/opt/conda/lib/python3.6/site-packages/bioconda_utils/utils.py", line 25, in <module>
    from conda.version import VersionOrder
ModuleNotFoundError: No module named 'conda.version'
Error: Exited with code 1
Step failed
Task failed
```

With the bootstrap method, I get an error from the setup.sh script, because it's attempting to execute `common.sh` which isn't present:

```
$ ./bootstrap.py /tmp/miniconda
.circleci/setup.sh: line 13: conda: command not found
Traceback (most recent call last):
  File "./bootstrap.py", line 104, in <module>
    sp.check_call(['.circleci/setup.sh'], env=env)
  File "/Users/ignaciot/miniconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['.circleci/setup.sh']' returned non-zero exit status 127.
```

Any clues would be greatly appreciated! I'm trying to run this on python 3:

```
$ python --version
Python 3.6.5 :: Anaconda, Inc.
```

**Comment by daler** [comment]
@ignaciot as a temporary solution while we're in the middle of the conda-build 3 migration, can you try the following:

```
echo -e 'MINICONDA_VER=4.5.4\nBIOCONDA_UTILS_TAG=cb3-migration' > .circleci/common.sh
./bootstrap.py /tmp/miniconda
```

to see if it solves your issue?

**Comment by daler** [comment]
@ignaciot never mind, more things need to be fixed in bootstrap . . . will push soon.

**Comment by ignaciot** [comment]
Thanks a lot for the update! I'll hang in tight, then.

**Comment by daler** [comment]
@ignaciot please try #9541, but note that the `adjustText` and `DateTime` dependencies specified by DAStk are not currently available as conda packages. As these are general-purpose packages, they should be added conda-forge first.

**Comment by ignaciot** [comment]
Thank you so much for looking into this! I'll give this a try.

**Comment by ignaciot** [comment]
I will have to wait until adding `adjustText` and `DateTime` to conda-forge, so until I have time for that I won't be able to test this. I will close the issue for now. Thanks for your help, and glad this helped uncover an issue with the conda-build 3 migration. Thanks for fixing that so quickly, BTW.
