### ISSUE TITLE
circleci build error

### ISSUE THREAD

**Issue by roblanf** [bioconda/bioconda-recipes#9573]
Hi all,

I am working through making  a recipe for an R script.

recipe:
`https://github.com/roblanf/bioconda-recipes/tree/r-minionqc/recipes/r-minionqc`

script:
`https://github.com/roblanf/minion_qc`

according to the output from `circleci build` below, it seems like the error could be with the build script:

```
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/opt/conda/conda-bld/r-minionqc_1529944999335/work/conda_build.sh']' returned non-zero exit status 1.
```

but there are other errors and warnings to do with R packages before that, so I'm not certain. 

If anyone could lend a hand getting me past this hurdle, I'd be grateful.

Rob

End of `circleci build` output
```
## Package Plan ##

  environment location: /opt/conda/conda-bld/r-minionqc_1529944999335/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl


The following NEW packages will be INSTALLED:

    bzip2:            1.0.6-1              conda-forge
    ca-certificates:  2018.4.16-0          conda-forge
    cairo:            1.14.10-0            conda-forge
    curl:             7.60.0-0             conda-forge
    fontconfig:       2.12.6-0             conda-forge
    freetype:         2.8.1-0              conda-forge
    gettext:          0.19.8.1-0           conda-forge
    glib:             2.55.0-0             conda-forge
    graphite2:        1.3.11-hfc679d8_0    conda-forge
    gsl:              2.1-2                conda-forge
    harfbuzz:         1.7.6-0              conda-forge
    icu:              58.2-hfc679d8_0      conda-forge
    jpeg:             9b-2                 conda-forge
    krb5:             1.14.6-0             conda-forge
    libffi:           3.2.1-3              conda-forge
    libgcc:           7.2.0-h69d50b8_2     defaults   
    libgcc-ng:        7.2.0-hdf63c60_3     defaults   
    libiconv:         1.15-h470a237_1      conda-forge
    libpng:           1.6.34-0             conda-forge
    libssh2:          1.8.0-h5b517e9_2     conda-forge
    libstdcxx-ng:     7.2.0-hdf63c60_3     defaults   
    libtiff:          4.0.9-he6b73bb_0     conda-forge
    libxml2:          2.9.8-0              conda-forge
    ncurses:          5.9-10               conda-forge
    openssl:          1.0.2o-0             conda-forge
    pango:            1.40.14-0            conda-forge
    pcre:             8.39-0               conda-forge
    pixman:           0.34.0-2             conda-forge
    r-assertthat:     0.2.0-r3.4.1_0       conda-forge
    r-base:           3.4.1-4              conda-forge
    r-bh:             1.66.0_1-r3.4.1_0    conda-forge
    r-cli:            1.0.0-r3.4.1_0       conda-forge
    r-colorspace:     1.3_2-r3.4.1_0       conda-forge
    r-crayon:         1.3.4-r3.4.1_0       conda-forge
    r-data.table:     1.10.4-r3.4.1_0      bioconda   
    r-dichromat:      2.0_0-r3.4.1_0       conda-forge
    r-digest:         0.6.15-r3.4.1_0      conda-forge
    r-futile.logger:  1.4.3-r3.4.1_0       conda-forge
    r-futile.options: 1.0.0-r3.4.1_0       conda-forge
    r-getopt:         1.20.2-r3.4.1_0      conda-forge
    r-ggplot2:        2.2.1-r3.4.1_0       conda-forge
    r-glue:           1.2.0-r3.4.1_0       conda-forge
    r-gridextra:      2.3-r3.4.1_0         conda-forge
    r-gtable:         0.2.0-r3.4.1_0       conda-forge
    r-hms:            0.3-r3.4.1_0         conda-forge
    r-labeling:       0.3-r3.4.1_0         conda-forge
    r-lambda.r:       1.2-r3.4.1_0         conda-forge
    r-lazyeval:       0.2.1-r3.4.1_0       conda-forge
    r-magrittr:       1.5-r3.4.1_0         conda-forge
    r-mass:           7.3_48-r3.4.1_0      conda-forge
    r-munsell:        0.5.0-r341_0         conda-forge
    r-optparse:       1.6.0-r341_0         conda-forge
    r-pillar:         1.2.2-r341h6115d3f_1 conda-forge
    r-plyr:           1.8.4-r3.4.1_0       conda-forge
    r-r6:             2.2.2-r3.4.1_0       conda-forge
    r-rcolorbrewer:   1.1_2-r3.4.1_0       conda-forge
    r-rcpp:           0.12.15-r3.4.1_0     conda-forge
    r-readr:          1.1.1-r3.4.1_0       conda-forge
    r-reshape2:       1.4.3-r3.4.1_0       conda-forge
    r-rlang:          0.2.1-r341_0         conda-forge
    r-scales:         0.5.0-r3.4.1_0       conda-forge
    r-stringi:        1.1.7-r3.4.1_1       conda-forge
    r-stringr:        1.3.0-r3.4.1_0       conda-forge
    r-tibble:         1.4.2-r3.4.1_0       conda-forge
    r-utf8:           1.1.3-r3.4.1_0       conda-forge
    r-viridis:        0.5.1-r3.4.1_0       conda-forge
    r-viridislite:    0.3.0-r3.4.1_0       conda-forge
    r-yaml:           2.1.18-r3.4.1_0      conda-forge
    readline:         7.0-0                conda-forge
    tk:               8.6.7-0              conda-forge
    xz:               5.2.3-0              conda-forge
    zlib:             1.2.11-h470a237_3    conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Solving environment: ...working... done
Warning: invalid package ‘.’
Error: ERROR: no packages specified
Source cache directory is: /opt/conda/conda-bld/src_cache
Downloading source to cache: minionqc_28dfec6747.zip
Downloading https://github.com/roblanf/minion_qc/releases/download/v1.3.4/minionqc.zip
Success
Extracting download
source tree in: /opt/conda/conda-bld/r-minionqc_1529944999335/work
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 2164, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1402, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 300, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 280, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/opt/conda/conda-bld/r-minionqc_1529944999335/work/conda_build.sh']' returned non-zero exit status 1.


16:45:42 BIOCONDA ERROR BUILD FAILED recipes/r-minionqc
16:45:45 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
16:45:45 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/r-minionqc
Error: Exited with code 1
Step failed
Task failed
```

**Comment by asmariyaz23** [comment]
I too get a similar error, however I am building a python package.
```
  File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/utils.py", line 280, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/Users/distiller/project/miniconda/conda-bld/freebayes_1529970306383/work/conda_build.sh']' returned non-zero exit status 2.
```

**Comment by roblanf** [comment]
thanks for the reply @dpryan79. You're right, that doesn't work locally. 

Newbie question now: is the aim of `build.sh` to simply install the script somewhere so it can be run from the commandline? In which case I could just use `build.sh` copy it to `/usr/local/bin` right? 

If you happen to know if there's a standard approach to installing scripts (i.e. not packages or binaries) with bioconda, or a recipe that does something like this, I'd be happy to take pointers. Meanwhile, i search through existing recipes to look for ideas...

**Comment by dpryan79** [comment]
You can copy it to `$PREFIX/bin`.
