### ISSUE TITLE
Error on Circel CI sue to build of a different package

### ISSUE THREAD

**Issue by zachcp** [bioconda/bioconda-recipes#9793]
I just submitted a PR for [Antismash4.2](https://github.com/bioconda/bioconda-recipes/pull/9789) and the build runs [but fails](https://circleci.com/gh/bioconda/bioconda-recipes/16801?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) with an error building an unrelated package (mashtree) as seen below:

It appears that I am building/testing a number of other packages as well. Can I force a build of only the package of interest?

Thanks
zach cp

```
source tree in: /opt/conda/conda-bld/mashtree_1530885855294/work
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 2177, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1417, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 310, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 290, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/opt/conda/conda-bld/mashtree_1530885855294/work/conda_build.sh']' returned non-zero exit status 2.


14:06:07 BIOCONDA ERROR BUILD FAILED recipes/mashtree
14:06:08 BIOCONDA ERROR BUILD SUMMARY: of 3 recipes, 3 failed and 0 were skipped. Details of recipes and environments follow.
14:06:08 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/locarna/1.8.9
14:06:08 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/locarna/1.9.0
14:06:08 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/mashtree
Exited with code 1
```

**Comment by zachcp** [comment]
fixed after rebase to master
