### ISSUE TITLE
hmmer tar.bz2 can't be decompressed in Python 2

### ISSUE THREAD

**Issue by hsiaoyi0504** [bioconda/bioconda-recipes#9907]
Here is a minimum example to reproduce

``` python
from six.moves import urllib
from os.path import join
import tarfile
from sys import platform

hmmer_local_file_path = join('.', 'hmmer-3.2-0.tar.bz2')

if platform == 'darwin':
    download_url = ('https://anaconda.org/bioconda/hmmer/'
        '3.2/download/osx-64/hmmer-3.2-0.tar.bz2')
else:  # for linux
    download_url = ('https://anaconda.org/bioconda/hmmer/'
        '3.2/download/linux-64/hmmer-3.2-0.tar.bz2')

urllib.request.urlretrieve(
    download_url,
    hmmer_local_file_path)

tar = tarfile.open(hmmer_local_file_path, 'r:bz2')
tar.extractall()
tar.close()
```

When executing this file, it will complain that 

```
Traceback (most recent call last):
  File "test_download.py", line 20, in <module>
    tar = tarfile.open(hmmer_local_file_path, "r:bz2")
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1693, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1782, in bz2open
    raise ReadError("not a bzip2 file")
tarfile.ReadError: not a bzip2 file
```

**Comment by bgruening** [comment]
Downloading it and open it works for me. Please also not that there are newer packages available for hmmer.

**Comment by hsiaoyi0504** [comment]
I tested the newer version but it still doesn't work.
I noted that it works with shell command, but doesn't work using Python package.
``` python
from six.moves import urllib
from os.path import join
import tarfile
from sys import platform

hmmer_local_file_path = join('.', 'hmmer-3.2-0.tar.bz2')

if platform == 'darwin':
    download_url = ('https://anaconda.org/bioconda/hmmer/3.2/download/osx-64/hmmer-3.2-hfc679d8_3.tar.bz2')
else:  # for linux
    download_url = ('https://anaconda.org/bioconda/hmmer/3.2/download/linux-64/hmmer-3.2-hfc679d8_3.tar.bz2')

urllib.request.urlretrieve(
    download_url,
    hmmer_local_file_path)

tar = tarfile.open(hmmer_local_file_path, 'r:bz2')
tar.extractall()
tar.close()
```

**Comment by hsiaoyi0504** [comment]
I think it's not bioconda problem. I will get urllib.error.HTTPError: HTTP Error 403: Forbidden in Python 3.

**Comment by hsiaoyi0504** [comment]
For people with same problem, try use opener in **urllib**.
https://stackoverflow.com/questions/34692009/download-image-from-url-using-python-urllib-but-receiving-http-error-403-forbid
